"""Custom domains data for navigational suggestions"""

CUSTOM_DOMAINS = [
    {"url": "https://mail.google.com", "categories": ["Technology", "Email", "Productivity"]},
    {"url": "https://go.twitch.tv", "categories": ["Technology", "Entertainment", "Streaming"]},
    {"url": "https://amazon.com", "categories": ["Shopping", "E-commerce"]},
    {"url": "https://amazon.ca", "categories": ["Shopping", "E-commerce"]},
    {"url": "https://amazon.cn", "categories": ["Shopping", "E-commerce"]},
    {"url": "https://amazon.co.jp", "categories": ["Shopping", "E-commerce"]},
    {"url": "https://amazon.co.uk", "categories": ["Shopping", "E-commerce"]},
    {"url": "https://amazon.com.au", "categories": ["Shopping", "E-commerce"]},
    {"url": "https://amazon.com.br", "categories": ["Shopping", "E-commerce"]},
    {"url": "https://amazon.com.mx", "categories": ["Shopping", "E-commerce"]},
    {"url": "https://amazon.de", "categories": ["Shopping", "E-commerce"]},
    {"url": "https://amazon.es", "categories": ["Shopping", "E-commerce"]},
    {"url": "https://amazon.fr", "categories": ["Shopping", "E-commerce"]},
    {"url": "https://amazon.in", "categories": ["Shopping", "E-commerce"]},
    {"url": "https://amazon.it", "categories": ["Shopping", "E-commerce"]},
    {"url": "https://search.yahoo.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://alltheinternet.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://altavistasearchengine.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://andisearch.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://aolsearch.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://ask.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://biznar.com", "categories": ["Technology", "Search Engine", "Business"]},
    {"url": "https://search.brave.com", "categories": ["Technology", "Search Engine", "Privacy"]},
    {"url": "https://carrot2.org", "categories": ["Technology", "Search Engine"]},
    {"url": "https://choositosearchengine.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://dogpile.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://easyseek.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://efind.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://ekoru.org", "categories": ["Technology", "Search Engine", "Environment"]},
    {"url": "https://entireweb.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://etools.ch", "categories": ["Technology", "Search Engine"]},
    {"url": "https://excite.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://findsoftware.com", "categories": ["Technology", "Search Engine", "Software"]},
    {"url": "https://fireball.de", "categories": ["Technology", "Search Engine"]},
    {"url": "https://freespoke.com", "categories": ["Technology", "Search Engine"]},
    {
        "url": "https://ghosterysearch.com",
        "categories": ["Technology", "Search Engine", "Privacy"],
    },
    {"url": "https://gibiru.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://gigablastsearchengine.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://givero.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://gogoprivate.com", "categories": ["Technology", "Search Engine", "Privacy"]},
    {"url": "https://search.goo.ne.jp", "categories": ["Technology", "Search Engine"]},
    {"url": "https://good-search.org", "categories": ["Technology", "Search Engine"]},
    {"url": "https://goodsearch.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://iseek.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://izito.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://askjeevessearch.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://kiddle.co", "categories": ["Technology", "Search Engine", "Education"]},
    {"url": "https://librex.devol.it", "categories": ["Technology", "Search Engine", "Privacy"]},
    {
        "url": "https://search.lilo.org",
        "categories": ["Technology", "Search Engine", "Environment"],
    },
    {"url": "https://lukol.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://search.lycos.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://metacrawler.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://metager.org", "categories": ["Technology", "Search Engine", "Privacy"]},
    {"url": "https://mojeek.co.uk", "categories": ["Technology", "Search Engine"]},
    {"url": "https://monstercrawler.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://naver.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://neevasearchengine.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://openmd.com", "categories": ["Technology", "Search Engine", "Medical"]},
    {"url": "https://openverse.org", "categories": ["Technology", "Search Engine", "Media"]},
    {"url": "https://petalsearchengine.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://policebuddy.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://popularsearchengines.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://presearch.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://qmamu.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://qwant.com", "categories": ["Technology", "Search Engine", "Privacy"]},
    {"url": "https://resulthunter.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://rightdao.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://searchbuddy.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://searchencrypt.com", "categories": ["Technology", "Search Engine", "Privacy"]},
    {"url": "https://searchgeek.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://searchraven.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://searchhaven.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://search-here.net", "categories": ["Technology", "Search Engine"]},
    {"url": "https://searchthing.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://searchtool.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://searchalot.com", "categories": ["Technology", "Search Engine"]},
    {
        "url": "https://searchcode.com",
        "categories": ["Technology", "Search Engine", "Development"],
    },
    {"url": "https://startpage.com", "categories": ["Technology", "Search Engine", "Privacy"]},
    {"url": "https://startsiden.no/sok", "categories": ["Technology", "Search Engine"]},
    {"url": "https://swisscows.com", "categories": ["Technology", "Search Engine", "Privacy"]},
    {"url": "https://torry.io", "categories": ["Technology", "Search Engine"]},
    {"url": "https://wikibuddy.com", "categories": ["Technology", "Search Engine"]},
    {
        "url": "https://wolframalpha.com",
        "categories": ["Technology", "Search Engine", "Education", "Science"],
    },
    {"url": "https://yelliot.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://yippysearchengine.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://youcare.world", "categories": ["Technology", "Search Engine"]},
    {"url": "https://zapmeta.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://4search.com", "categories": ["Technology", "Search Engine"]},
    {"url": "https://99searchengines.com", "categories": ["Technology", "Search Engine"]},
]
