default_language_version:
  python: python3.12
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: "https://github.com/psf/black"
    rev: 22.6.0
    hooks:
      - id: black
  - repo: "https://github.com/pycqa/flake8"
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: "https://github.com/pycqa/isort"
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: "https://github.com/pycqa/bandit"
    rev: 1.7.4
    hooks:
      - id: bandit
        # skips asserts
        #   - https://bandit.readthedocs.io/en/latest/plugins/b101_assert_used.html#
        #   - https://bandit.readthedocs.io/en/latest/plugins/b104_hardcoded_bind_all_interfaces.html
        args:
          - "--skip"
          - "B101,B104"
  - repo: "https://github.com/pycqa/pydocstyle"
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args:
          - "--convention"
          - pep257
          - "--add-select"
          - "D212"
          - "--add-ignore"
          - "D105,D107,D203,D205,D400"
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: v0.971
    hooks:
      - id: mypy
        files: "^merino|^tests"
        args:
          [
            --python-version=3.12,
            --disallow-untyped-calls,
            --follow-imports=normal,
            --ignore-missing-imports,
            --pretty,
            --show-error-codes,
            --strict-optional,
            --warn-no-return,
            --warn-redundant-casts,
            --warn-return-any,
            --warn-unused-ignores,
          ]
        additional_dependencies:
          [
            "pydantic",
            "types-geoip2",
            "types-PyYAML",
            "types-requests",
            "types-redis",
            "types-python-dateutil",
          ]
