# Configurations for production. Configurations defined here will override the
# counterparts in `default.toml`.
#
# Switch to this environment via: MERINO_FLEECE_ENV=production

[production]
dynaconf_merge = true

[production.logging]
level = "INFO"
format = "mozlog"
