# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

"""Module for test configurations for the AdM provider unit test directory."""

import json
from typing import Any

import pytest
from moz_merino_ext.amp import AmpIndexManager
from pytest_mock import MockerFixture

from merino.optimizers.models import EngagementMetrics, ThompsonConfig
from merino.optimizers.thompson import ThompsonSampler
from merino.providers.suggest.adm.backends.protocol import (
    AdmBackend,
    KeywordEngagementData,
    KeywordEntry,
    KeywordMetrics,
    SuggestionContent,
    EngagementData,
)
from merino.providers.suggest.adm.backends.protocol import FormFactor
from merino.providers.suggest.adm.provider import Provider


@pytest.fixture(name="adm_parameters")
def fixture_adm_parameters() -> dict[str, Any]:
    """Define provider parameters for test."""
    return {
        "score": 0.3,
        "name": "adm",
        "resync_interval_sec": 10800,
        "cron_interval_sec": 60,
        "engagement_gcs_bucket": "test-engagement-bucket",
        "engagement_blob_name": "suggest-merino-exports/engagement/latest.json",
        "engagement_resync_interval_sec": 3600,
        "keyword_engagement_blob_name": "suggest-merino-exports/engagement/keyword/latest.json",
    }


@pytest.fixture(name="rs_attachment_raw_us")
def fixture_rs_attachment_raw_us() -> str:
    """Return raw attachment data as generated by the Remote Settings endpoint."""
    return json.dumps(
        [
            {
                "id": 2,
                "advertiser": "Example.org",
                "click_url": "https://example.org/click/mozilla",
                "full_keywords": [
                    ["firefox accounts", 3],
                    ["mozilla firefox accounts", 4],
                ],
                "iab_category": "5 - Education",
                "icon": "01",
                "serp_categories": [],
                "impression_url": "https://example.org/impression/mozilla",
                "keywords": [
                    "firefox",
                    "firefox account",
                    "firefox accounts",
                    "mozilla",
                    "mozilla firefox",
                    "mozilla firefox account",
                    "mozilla firefox accounts",
                ],
                "title": "Mozilla Firefox Accounts",
                "url": "https://example.org/target/mozfirefoxaccounts",
            }
        ]
    )


@pytest.fixture(name="rs_attachment_raw_de")
def fixture_rs_attachment_raw_de() -> str:
    """Return raw attachment data as generated by the Remote Settings endpoint."""
    return json.dumps(
        [
            {
                "id": 2,
                "advertiser": "de.Example.org",
                "click_url": "https://de.example.org/click/mozilla",
                "full_keywords": [
                    ["firefox accounts de", 4],
                    ["mozilla firefox accounts de", 5],
                ],
                "iab_category": "5 - Education",
                "icon": "01",
                "serp_categories": [],
                "impression_url": "https://de.example.org/impression/mozilla",
                "keywords": [
                    "firefox",
                    "firefox account",
                    "firefox accounts",
                    "firefox accounts de",
                    "mozilla",
                    "mozilla firefox",
                    "mozilla firefox account",
                    "mozilla firefox accountsmozilla firefox accounts de",
                ],
                "title": "Mozilla Firefox Accounts",
                "url": "https://de.example.org/target/mozfirefoxaccounts",
            }
        ]
    )


@pytest.fixture(name="rs_attachment_raw_thompson")
def fixture_rs_attachment_raw_thompson() -> str:
    """Return raw attachment data as generated by the Remote Settings endpoint."""
    return json.dumps(
        [
            {
                "id": 2,
                "advertiser": "Example.org",
                "click_url": "https://example.org/click/mozilla",
                "full_keywords": [
                    ["firefox accounts", 3],
                    ["mozilla firefox accounts", 4],
                ],
                "iab_category": "5 - Education",
                "icon": "01",
                "serp_categories": [],
                "impression_url": "https://example.org/impression/mozilla",
                "keywords": [
                    "firefox",
                    "firefox account",
                    "firefox accounts",
                    "mozilla",
                    "mozilla firefox",
                    "mozilla firefox account",
                    "mozilla firefox accounts",
                ],
                "title": "Mozilla Firefox Accounts",
                "url": "https://example.org/target/mozfirefoxaccounts",
            },
            {
                "id": 2,
                "advertiser": "LowEngagement",
                "click_url": "https://example.org/click/lowengagement",
                "full_keywords": [
                    ["low engagement", 1],
                ],
                "iab_category": "5 - Education",
                "icon": "01",
                "serp_categories": [],
                "impression_url": "https://example.org/impression/mozilla",
                "keywords": [
                    "low engagement",
                ],
                "title": "Low Engagement Suggestion",
                "url": "https://example.org/target/lowengagement",
            },
        ]
    )


@pytest.fixture(name="backend_mock")
def fixture_backend_mock(
    mocker: MockerFixture, rs_attachment_raw_us: str, rs_attachment_raw_de: str
) -> Any:
    """Create an AdmBackend mock object for test."""
    backend_mock: Any = mocker.AsyncMock(spec=AdmBackend)
    index_manager = AmpIndexManager()  # type: ignore[no-untyped-call]
    index_manager.build(f"US/({FormFactor.DESKTOP.value},)", rs_attachment_raw_us)
    index_manager.build(f"DE/({FormFactor.PHONE.value},)", rs_attachment_raw_de)
    backend_mock.fetch.return_value = SuggestionContent(
        index_manager=index_manager,
        icons={"01": "attachment-host/main-workspace/quicksuggest/icon-01"},
    )
    return backend_mock


@pytest.fixture(name="thompson_backend_mock")
def fixture_thompson_backend_mock(mocker: MockerFixture, rs_attachment_raw_thompson: str) -> Any:
    """Create an AdmBackend mock object with Thompson Suggestions for test."""
    backend_mock: Any = mocker.AsyncMock(spec=AdmBackend)
    index_manager = AmpIndexManager()  # type: ignore[no-untyped-call]
    index_manager.build(f"US/({FormFactor.DESKTOP.value},)", rs_attachment_raw_thompson)
    backend_mock.fetch.return_value = SuggestionContent(
        index_manager=index_manager,
        icons={"01": "attachment-host/main-workspace/quicksuggest/icon-01"},
    )
    return backend_mock


@pytest.fixture(name="adm")
def fixture_adm(backend_mock: Any, adm_parameters: dict[str, Any], statsd_mock: Any) -> Provider:
    """Create an AdM Provider for test."""
    return Provider(backend=backend_mock, metrics_client=statsd_mock, **adm_parameters)


@pytest.fixture(name="thompson_sampler")
def fixture_thompson_sampler() -> ThompsonSampler:
    """Create a deterministic ThompsonSampler (no dummy) for testing."""
    return ThompsonSampler(config=ThompsonConfig(random_seed=0))


@pytest.fixture(name="thompson_sampler_with_dummy")
def fixture_thompson_sampler_with_dummy() -> ThompsonSampler:
    """Create a deterministic ThompsonSampler with a dominant dummy candidate for testing."""
    return ThompsonSampler(
        config=ThompsonConfig(
            random_seed=0,
            dummy_candidate=EngagementMetrics(engaged=1000, attempted=1001),
        )
    )


@pytest.fixture(name="engagement_data")
def fixture_engagement_data() -> EngagementData:
    """Engagement data for testing."""
    return EngagementData(
        amp={
            "mozilla": {
                "advertiser": "mozilla",
                "impressions": 100,
                "clicks": 5,
            },
            "Example.org": {
                "advertiser": "example.org",
                "impressions": 10001,
                "clicks": 10000,
            },
            "LowEngagement": {
                "advertiser": "lowengagement",
                "impressions": 9999,
                "clicks": 5,
            },
        },
        amp_aggregated={
            "impressions": 300,
            "clicks": 15,
        },
    )


@pytest.fixture(name="keyword_engagement_data")
def fixture_keyword_engagement_data() -> KeywordEngagementData:
    """Keyword engagement data for testing."""
    return KeywordEngagementData(
        amp={
            "mozilla/firefox": KeywordEntry(
                live=KeywordMetrics(impressions=100, clicks=5),
                historical=KeywordMetrics(impressions=200, clicks=10),
            ),
            "example.org/firefox": KeywordEntry(
                live=KeywordMetrics(impressions=10001, clicks=10000),
                historical=KeywordMetrics(impressions=110001, clicks=11000),
            ),
            "lowengagement/low engagement": KeywordEntry(
                live=KeywordMetrics(impressions=9999, clicks=5),
                historical=KeywordMetrics(impressions=19999, clicks=15),
            ),
        },
        amp_aggregated={"impressions": 300, "clicks": 15},
    )


@pytest.fixture(name="adm_with_thompson")
def fixture_adm_with_thompson(
    thompson_backend_mock: Any,
    adm_parameters: dict[str, Any],
    thompson_sampler: ThompsonSampler,
    engagement_data: EngagementData,
    keyword_engagement_data: KeywordEngagementData,
    statsd_mock: Any,
) -> Provider:
    """Create an AdM Provider with Thompson sampling enabled for testing."""
    provider = Provider(
        backend=thompson_backend_mock,
        metrics_client=statsd_mock,
        thompson=thompson_sampler,
        **adm_parameters,
    )
    provider.engagement_data = engagement_data
    provider.keyword_engagement_data = keyword_engagement_data
    return provider


@pytest.fixture(name="adm_with_thompson_dummy")
def fixture_adm_with_thompson_dummy(
    thompson_backend_mock: Any,
    adm_parameters: dict[str, Any],
    thompson_sampler_with_dummy: ThompsonSampler,
    statsd_mock: Any,
) -> Provider:
    """Create an AdM Provider with a dominant dummy Thompson sampler for testing.

    No engagement data is set so candidates fall back to (engaged=1, attempted=1),
    ensuring the dummy always dominates and suppresses suggestions.
    """
    return Provider(
        backend=thompson_backend_mock,
        metrics_client=statsd_mock,
        thompson=thompson_sampler_with_dummy,
        **adm_parameters,
    )


@pytest.fixture(name="adm_with_thompson_dummy_min_attempted_count")
def fixture_adm_with_thompson_dummy_min_attempted_count(
    thompson_backend_mock: Any,
    adm_parameters: dict[str, Any],
    engagement_data: EngagementData,
    keyword_engagement_data: KeywordEngagementData,
    thompson_sampler_with_dummy: ThompsonSampler,
    statsd_mock: Any,
) -> Provider:
    """Create an AdM Provider with a dominant dummy Thompson sampler and minimal
    attempted count for testing.
    """
    provider = Provider(
        backend=thompson_backend_mock,
        metrics_client=statsd_mock,
        min_attempted_count=1000,
        thompson=thompson_sampler_with_dummy,
        **adm_parameters,
    )
    provider.engagement_data = engagement_data
    provider.keyword_engagement_data = keyword_engagement_data
    return provider


@pytest.fixture(name="adm_with_thompson_skip_client_variants_check")
def fixture_adm_with_thompson_skip_client_variants_check(
    backend_mock: Any,
    adm_parameters: dict[str, Any],
    thompson_sampler: ThompsonSampler,
    statsd_mock: Any,
) -> Provider:
    """Create an AdM Provider with Thompson sampling enabled for testing."""
    return Provider(
        backend=backend_mock,
        metrics_client=statsd_mock,
        thompson=thompson_sampler,
        should_check_client_variants=False,
        **adm_parameters,
    )


@pytest.fixture(name="adm_with_thompson_single_candidate_below_threshold")
def fixture_adm_with_thompson_single_candidate_below_threshold(
    backend_mock: Any,
    adm_parameters: dict[str, Any],
    thompson_sampler_with_dummy: ThompsonSampler,
    statsd_mock: Any,
    engagement_data: EngagementData,
) -> Provider:
    """Create an AdM Provider with Thompson sampling and a min_attempted_count threshold."""
    provider = Provider(
        backend=backend_mock,
        metrics_client=statsd_mock,
        min_attempted_count=1000,
        thompson=thompson_sampler_with_dummy,
        **adm_parameters,
    )
    provider.engagement_data = EngagementData(
        amp={
            "example.org": {"click": 10, "impression": 100},
        },
        amp_aggregated={},
    )
    provider.keyword_engagement_data = KeywordEngagementData(
        amp={
            "example.org/firefox": KeywordEntry(
                live=KeywordMetrics(impressions=100, clicks=10),
            )
        }
    )
    return provider
