"""Module containing JSON object with ETF ticker symbol to company name mapping for the top indices."""

DOW_JONES_ETF_COMPANY = {
    "DIA": "SPDR Dow Jones Industrial Average ETF Trust",
    "DJD": "Invesco Dow Jones Industrial Average Dividend ETF",
    "FDM": "First Trust Dow Jones Select MicroCap Index Fund",
    "FDN": "First Trust Dow Jones Internet Index Fund ETF",
    "FDND": "FT Vest Dow Jones Internet & Target Income ETF",
    "FDNI": "First Trust Dow Jones International Internet ETF",
    "FGD": "First Trust Dow Jones Global Select Dividend Index Fund",
    "GYLD": "Arrow Dow Jones Global Yield ETF",
    "IYY": "iShares Dow Jones U.S. ETF",
    "RWO": "SPDR  Dow Jones  Global Real Estate ETF",
    "RWR": "SPDR Dow Jones REIT ETF",
    "RWX": "SPDR Dow Jones  International Real Estate ETF",
    "SPSK": "SP Funds Dow Jones Global Sukuk ETF",
    "SCHD": "Schwab US Dividend Equity ETF",
    "UMMA": "Wahed Dow Jones Islamic World ETF",
    "WEBL": "Direxion Daily Dow Jones Internet Bull 3X Shares",
    "WEBS": "Direxion Daily Dow Jones Internet Bear 3X Shares",
}

NASDAQ_ETF_COMPANY = {
    "BIB": "ProShares Ultra NASDAQ Biotechnology",
    "BIS": "ProShares UltraShort NASDAQ Biotechnology",
    "BLCN": "Siren ETF Trust Siren Nasdaq NexGen Economy ETF",
    "BUFQ": "FT Vest Laddered Nasdaq Buffer ETF",
    "CANQ": "Calamos ETF Trust Calamos Nasdaq Equity & Income ETF",
    "CIBR": "First Trust Exchange-Traded Fund II First Trust NASDAQ Cybersecurity ETF",
    "CPNJ": "Calamos Nasdaq-100 Structured Alt Protection ETF - June",
    "CPNM": "Calamos Nasdaq-100 Structured Alt Protection ETF - March",
    "CPNQ": "Calamos Nasdaq-100 Structured Alt Protection ETF - December",
    "CPNS": "Calamos Nasdaq-100 Structured Alt Protection ETF - September",
    "DRUP": "GraniteShares Nasdaq Select Disruptors ETF",
    "EKG": "First Trust Nasdaq Lux Digital Health Solutions ETF",
    "FTXG": "First Trust Nasdaq Food & Beverage ETF",
    "FTXH": "First Trust Nasdaq Pharmaceuticals ETF",
    "FTXL": "First Trust Nasdaq Semiconductor ETF",
    "FTXN": "First Trust Nasdaq Oil & Gas ETF",
    "FTXO": "First Trust Nasdaq Bank ETF",
    "FTXR": "First Trust Nasdaq Transportation ETF",
    "GLCR": "GlacierShares Nasdaq Iceland ETF",
    "GPIQ": "Goldman Sachs ETF Trust Goldman Sachs Nasdaq-100 Premium Income ETF",
    "GRID": "First Trust NASDAQ Clean Edge Smart Grid Infrastructure Index Fund",
    "HEQQ": "JPMorgan Nasdaq Hedged Equity Laddered Overlay ETF",
    "HNDL": "Strategy Shares Nasdaq 7HANDL Index ETF",
    "IBBQ": "Invesco Nasdaq Biotechnology ETF",
    "IQQQ": "ProShares Nasdaq-100 High Income ETF",
    "JEPQ": "J.P. Morgan Nasdaq Equity Premium Income ETF",
    "NCIQ": "Hashdex Nasdaq Crypto Index US ETF",
    "ONEQ": "Fidelity Nasdaq Composite Index ETF",
    "OOQB": "One One Nasdaq-100 and Bitcoin ETF",
    "PATN": "Pacer Nasdaq International Patent Leaders ETF",
    "PBQQ": "PGIM Laddered Nasdaq-100 Buffer 12 ETF",
    "PNQI": "Invesco NASDAQ Internet ETF",
    "PQAP": "PGIM Nasdaq-100 Buffer 12 ETF - April",
    "PQJA": "PGIM Nasdaq-100 Buffer 12 ETF - January",
    "PQJL": "PGIM Nasdaq-100 Buffer 12 ETF - July",
    "PQOC": "PGIM Nasdaq-100 Buffer 12 ETF - October",
    "QABA": "First Trust NASDAQ ABA Community Bank Index Fund",
    "QB": "ProShares Nasdaq-100 Dynamic Buffer ETF",
    "QBUF": "Innovator Nasdaq-100 10 Buffer ETF Quarterly",
    "QCAP": "FT Vest Nasdaq-100 Conservative Buffer ETF - April",
    "QCJA": "FT Vest Nasdaq-100 Conservative Buffer ETF - January",
    "QCJL": "FT Vest Nasdaq-100 Conservative Buffer ETF - July",
    "QCLN": "First Trust NASDAQ Clean Edge Green Energy Index Fund",
    "QCLR": "Global X NASDAQ 100 Collar 95-110 ETF",
    "QCOC": "FT Vest Nasdaq-100 Conservative Buffer ETF - October",
    "QDTY": "YieldMax Nasdaq 100 0DTE Covered Call Strategy ETF",
    "QGRD": "Horizon Nasdaq-100 Defined Risk ETF",
    "QHDG": "Innovator Hedged Nasdaq-100 ETF",
    "QMAG": "FT Vest Nasdaq-100 Moderate Buffer ETF - August",
    "QMFE": "FT Vest Nasdaq-100 Moderate Buffer ETF - February",
    "QMMY": "FT Vest Nasdaq-100 Moderate Buffer ETF - May",
    "QMNV": "FT Vest Nasdaq-100 Moderate Buffer ETF - November",
    "QNXT": "iShares Nasdaq-100 ex Top 30 ETF",
    "QOWZ": "Invesco Nasdaq Free Cash Flow Achievers ETF",
    "QQEW": "First Trust NASDAQ-100 Equal Weighted Index Fund",
    "QQJG": "Invesco ESG NASDAQ Next Gen 100 ETF",
    "QQMG": "Invesco ESG NASDAQ 100 ETF",
    "QQQ": "Invesco QQQ Trust, Series 1",
    "QQQA": "ProShares Nasdaq-100 Dorsey Wright Momentum ETF",
    "QQQE": "Direxion NASDAQ-100 Equal Weighted Index Shares",
    "QQQG": "Pacer Nasdaq 100 Top 50 Cash Cows Growth Leaders ETF",
    "QQQH": "NEOS Nasdaq-100 Hedged Equity Income ETF",
    "QQQI": "NEOS Nasdaq 100 High Income ETF",
    "QQQJ": "Invesco NASDAQ Next Gen 100 ETF",
    "QQQM": "Invesco NASDAQ 100 ETF",
    "QQQS": "Invesco NASDAQ Future Gen 200 ETF",
    "QQQT": "Defiance Nasdaq 100 Income Target ETF",
    "QQQY": "Tidal Trust II Defiance Nasdaq 100 Enhanced Options & 0DTE Income ETF",
    "QQWZ": "Pacer Cash COWZ 100-Nasdaq 100 Rotator ETF",
    "QQXT": "First Trust NASDAQ - 100 Ex-Technology Sector Index Fund",
    "QRMI": "Global X NASDAQ 100 Risk Managed Income ETF",
    "QSIX": "Pacer Metaurus Nasdaq 100 Dividend Multiplier 600 ETF",
    "QSPT": "FT Vest Nasdaq-100 Buffer ETF - September",
    "QTEC": "First Trust NASDAQ-100 Technology  Index Fund",
    "QTOP": "iShares Nasdaq Top 30 Stocks ETF",
    "QTR": "Global X NASDAQ 100 Tail Risk ETF",
    "QXQ": "SGI Enhanced Nasdaq-100 ETF",
    "QYLD": "Global X Funds Global X NASDAQ-100 Covered Call ETF",
    "QYLG": "Global X Nasdaq 100 Covered Call & Growth ETF",
    "ROBT": "First Trust Nasdaq Artificial Intelligence and Robotics ETF",
    "SKYU": "ProShares Ultra Nasdaq Cloud Computing ETF",
    "TDIV": "First Trust Exchange-Traded Fund VI First Trust NASDAQ Technology Dividend Index Fund",
    "UCYB": "ProShares Ultra Nasdaq Cybersecurity ETF",
}

SP500_ETF_COMPANY = {
    "APRP": "PGIM S&P 500 Buffer 12 ETF - April",
    "AUGP": "PGIM S&P 500 Buffer 12 ETF - August",
    "BUFP": "PGIM Laddered S&P 500 Buffer 12 ETF",
    "CATH": "Global X S&P 500 Catholic Values ETF",
    "CPSA": "Calamos S&P 500 Structured Alt Protection ETF - August",
    "CPSD": "Calamos S&P 500 Structured Alt Protection ETF - December",
    "CPSF": "Calamos S&P 500 Structured Alt Protection ETF - February",
    "CPSJ": "Calamos S&P 500 Structured Alt Protection ETF - July",
    "CPSL": "Calamos Laddered S&P 500 Structured Alt Protection ETF",
    "CPSM": "Calamos S&P 500 Structured Alt Protection ETF - May",
    "CPSN": "Calamos S&P 500 Structured Alt Protection ETF - November",
    "CPSO": "Calamos S&P 500 Structured Alt Protection ETF - October",
    "CPSP": "Calamos S&P 500 Structured Alt Protection ETF - April",
    "CPSR": "Calamos S&P 500 Structured Alt Protection ETF - March",
    "CPST": "Calamos S&P 500 Structured Alt Protection ETF - September",
    "CPSU": "Calamos S&P 500 Structured Alt Protection ETF - June",
    "CPSY": "Calamos S&P 500 Structured Alt Protection ETF - January",
    "DECP": "PGIM S&P 500 Buffer 12 ETF - December",
    "DIVG": "Invesco S&P 500 High Dividend Growers ETF",
    "DSPY": "Tema S&P 500 Historical Weight ETF Strategy",
    "EFIV": "SPDR S&P 500 ESG ETF",
    "EGLE": "Global X S&P 500 U.S. Revenue Leaders ETF",
    "EMOT": "First Trust S&P 500 Economic Moat ETF",
    "FB": "ProShares S&P 500 Dynamic Buffer ETF",
    "FCFY": "First Trust S&P 500 Diversified Free Cash Flow ETF",
    "FEBP": "PGIM S&P 500 Buffer 12 ETF - February",
    "FLAG": "Global X S&P 500 U.S. Market Leaders Top 50 ETF",
    "GPIX": "Goldman Sachs ETF Trust Goldman Sachs S&P 500 Premium Income ETF",
    "HIBL": "Direxion Daily S&P 500 High Beta Bull 3X Shares",
    "HIBS": "Direxion Daily S&P 500 High Beta Bear 3X Shares",
    "ISPY": "ProShares S&P 500 High Income ETF",
    "IVE": "iShares S&P 500 Value ETF",
    "IVV": "iShares Core S&P 500 ETF",
    "IVVW": "iShares S&P 500 BuyWrite ETF",
    "IVW": "iShares S&P 500 Growth ETF",
    "JANP": "PGIM S&P 500 Buffer 12 ETF - January",
    "JULP": "PGIM S&P 500 Buffer 12 ETF - July",
    "JUNP": "PGIM S&P 500 Buffer 12 ETF - June",
    "KNG": "FT Vest S&P 500 Dividend Aristocrats Target Income ETF",
    "KNGZ": "First Trust Exchange-Traded Fund VI First Trust S&P 500 Diversified Dividend Aristocrats ETF",
    "LCOW": "Pacer S&P 500 Quality FCF Aristocrats ETF",
    "MAYP": "PGIM S&P 500 Buffer 12 ETF - May",
    "MRCP": "PGIM S&P 500 Buffer 12 ETF - March",
    "NOBL": "ProShares S&P 500 Dividend Aristocrats ETF",
    "NOVP": "PGIM S&P 500 Buffer 12 ETF - November",
    "OCTP": "PGIM S&P 500 Buffer 12 ETF - October",
    "OOSB": "One One S&P 500 and Bitcoin ETF",
    "PBAP": "PGIM S&P 500 Buffer 20 ETF - April",
    "PBAU": "PGIM S&P 500 Buffer 20 ETF - August",
    "PBDE": "PGIM S&P 500 Buffer 20 ETF - December",
    "PBFB": "PGIM S&P 500 Buffer 20 ETF - February",
    "PBFR": "PGIM Laddered S&P 500 Buffer 20 ETF",
    "PBJA": "PGIM S&P 500 Buffer 20 ETF - January",
    "PBJL": "PGIM S&P 500 Buffer 20 ETF - July",
    "PBJN": "PGIM S&P 500 Buffer 20 ETF - June",
    "PBMR": "PGIM S&P 500 Buffer 20 ETF - March",
    "PBMY": "PGIM S&P 500 Buffer 20 ETF - May",
    "PBNV": "PGIM S&P 500 Buffer 20 ETF - November",
    "PBOC": "PGIM S&P 500 Buffer 20 ETF - October",
    "PBSE": "PGIM S&P 500 Buffer 20 ETF - September",
    "PHDG": "Invesco S&P 500 Downside Hedged ETF",
    "PMAP": "PGIM S&P 500 Max Buffer ETF - April",
    "PMAU": "PGIM S&P 500 Max Buffer ETF - August",
    "PMFB": "PGIM S&P 500 Max Buffer ETF - February",
    "PMJA": "PGIM S&P 500 Max Buffer ETF - January",
    "PMJL": "PGIM S&P 500 Max Buffer ETF - July",
    "PMJN": "PGIM S&P 500 Max Buffer ETF - June",
    "PMMR": "PGIM S&P 500 Max Buffer ETF - March",
    "PMMY": "PGIM S&P 500 Max Buffer ETF - May",
    "PUTD": "Cboe Validus S&P 500 Dynamic PutWrite Index ETF",
    "QDCC": "Global X S&P 500 Quality Dividend Covered Call ETF",
    "QDIV": "Global X S&P 500 Quality Dividend ETF",
    "QVML": "Invesco S&P 500 QVM Multi-factor ETF",
    "RPG": "Invesco S&P 500 Pure Growth ETF",
    "RPV": "Invesco S&P 500 Pure Value ETF",
    "RSP": "Invesco S&P 500 Equal Weight ETF",
    "RSPA": "Invesco S&P 500 Equal Weight Income Advantage ETF",
    "RSPC": "Invesco Exchange-Traded Fund Trust Invesco S&P 500 Equal Weight Communication Services ETF",
    "RSPD": "Invesco S&P 500 Equal Weight Consumer Discretionary ETF",
    "RSPE": "Invesco ESG S&P 500 Equal Weight ETF",
    "RSPF": "Invesco S&P 500 Equal Weight Financials ETF",
    "RSPG": "Invesco S&P 500 Equal Weight Energy ETF",
    "RSPH": "Invesco S&P 500 Equal Weight Health Care ETF",
    "RSPM": "Invesco S&P 500 Equal Weight Materials ETF",
    "RSPN": "Invesco S&P 500 Equal Weight Industrials ETF",
    "RSPR": "Invesco S&P 500 Equal Weight Real Estate ETF",
    "RSPS": "Invesco S&P 500 Equal Weight Consumer Staples ETF",
    "RSPT": "Invesco S&P 500 Equal Weight Technology ETF",
    "RSPU": "Invesco S&P 500 Equal Weight Utilities ETF",
    "RWL": "Invesco S&P 500 Revenue ETF",
    "SDTY": "YieldMax S&P 500 0DTE Covered Call Strategy ETF",
    "SEPP": "PGIM S&P 500 Buffer 12 ETF - September",
    "SNPE": "Xtrackers S&P 500 Scored & Screened ETF",
    "SNPG": "Xtrackers S&P 500 Growth Scored & Screened ETF",
    "SNPV": "Xtrackers S&P 500 Value Scored & Screened ETF",
    "SPDN": "Direxion Daily S&P 500 Bear 1X Shares",
    "SPDV": "AAM S&P 500 High Dividend Value ETF",
    "SPGP": "Invesco S&P 500 GARP ETF",
    "SPHB": "Invesco S&P 500 High Beta ETF",
    "SPHD": "Invesco S&P 500 High Dividend Low Volatility ETF",
    "SPHQ": "Invesco S&P 500 Quality ETF",
    "SPLG": "SPDR Portfolio S&P 500 ETF",
    "SPLV": "Invesco S&P 500 Low Volatility ETF",
    "SPMO": "Invesco S&P 500 Momentum ETF",
    "SPMV": "Invesco S&P 500 Minimum Variance ETF",
    "SPUS": "SP Funds S&P 500 Sharia  ETF",
    "SPUU": "Direxion Daily S&P 500 Bull 2X Shares",
    "SPVM": "Invesco S&P 500 Value with Momentum ETF",
    "SPVU": "Invesco S&P 500 Enhanced Value ETF",
    "SPXD": "Xtrackers S&P 500 Diversified Sector Weight ETF",
    "SPXE": "ProShares S&P 500 Ex-Energy ETF",
    "SPXL": "Direxion Daily S&P 500  Bull 3x Shares",
    "SPXN": "ProShares S&P 500 Ex-Financials ETF",
    "SPXS": "Direxion Daily S&P 500 Bear 3x Shares",
    "SPXT": "ProShares S&P 500 Ex-Technology ETF",
    "SPXU": "ProShares UltraPro Short S&P 500",
    "SPXV": "ProShares S&P 500 Ex-Health Care ETF",
    "SPY": "SPDR S&P 500 ETF Trust",
    "SPYD": "SPDR Portfolio S&P 500 High Dividend ETF",
    "SPYG": "SPDR Portfolio S&P 500 Growth ETF",
    "SPYH": "NEOS S&P 500 Hedged Equity Income ETF",
    "SPYI": "NEOS S&P 500 High Income ETF",
    "SPYT": "Defiance S&P 500 Income Target ETF",
    "SPYV": "SPDR Portfolio S&P 500 Value ETF",
    "SPYX": "SPDR S&P 500 Fossil Fuel Free ETF",
    "TOPC": "iShares S&P 500 3% Capped ETF",
    "UPRO": "ProShares UltraPro S&P 500",
    "VOO": "Vanguard S&P 500 ETF",
    "VOOG": "Vanguard S&P 500 Growth ETF",
    "VOOV": "Vanguard S&P 500 Value ETF",
    "VXX": "iPath Series B S&P 500 VIX Short-Term Futures ETN",
    "VXZ": "iPath Series B S&P 500 VIX Mid-Term Futures ETN",
    "WDTE": "Defiance S&P 500 Enhanced Options & 0DTE Income ETF",
    "XCLR": "Global X S&P 500 Collar 95-110 ETF",
    "XDIV": "Roundhill S&P 500 No Dividend Target ETF",
    "XDTE": "Roundhill S&P 500 0DTE Covered Call Strategy ETF",
    "XLG": "Invesco S&P 500 Top 50 ETF",
    "XOEF": "iShares S&P 500 ex S&P 100 ETF",
    "XPAY": "Roundhill S&P 500 Target 20 Managed Distribution ETF",
    "XRLV": "Invesco S&P 500 ex-Rate Sensitive Low Volatility ETF",
    "XRMI": "Global X S&P 500 Risk Managed Income ETF",
    "XTR": "Global X S&P 500 Tail Risk ETF",
    "XVV": "iShares ESG Select Screened S&P 500 ETF",
    "XYLD": "Global X S&P 500 Covered Call ETF",
    "XYLG": "Global X S&P 500 Covered Call & Growth ETF",
    "ZZZ": "Cyber Hornet S&P 500 and Bitcoin 75/25 Strategy ETF",
}

DOW_JONES_POPULAR_3_ETF_COMPANY = {
    "DIA": "SPDR Dow Jones Industrial Average ETF Trust",
    "DJD": "Invesco Dow Jones Industrial Average Dividend ETF",
    "SCHD": "Schwab US Dividend Equity ETF",
}

NASDAQ_POPULAR_3_ETF_COMPANY = {
    "QQQ": "Invesco QQQ Trust, Series 1",
    "QQQM": "Invesco NASDAQ 100 ETF",
    "ONEQ": "Fidelity Nasdaq Composite Index ETF",
}

SP500_POPULAR_3_ETF_COMPANY = {
    "SPY": "SPDR S&P 500 ETF Trust",
    "VOO": "Vanguard S&P 500 ETF",
    "IVV": "iShares Core S&P 500 ETF",
}

SP100_POPULAR_3_ETF_COMPANY = {
    "EQWL": "Invesco S&P 100 Equal Weight ETF",
    "OEF": "iShares S&P 100 ETF",
    "XOEF": "iShares S&P 500 ex S&P 100 ETF",
}

RUSSELL2000_POPULAR_3_ETF_COMPANY = {
    "IWM": "iShares Russell 2000 ETF",
    "VTWO": "Vanguard Russell 2000 ETF",
    "SMMV": "iShares MSCI USA Small-Cap Min Vol Factor ETF",
}

# NOTE: This index only has 2 ETF tickers listed on the US market and supported by Polygon.
HSI_POPULAR_2_ETF_COMPANY = {
    "EWH": "iShares MSCI Hong Kong ETF",
    "KTEC": "KraneShares Hang Seng TECH Index ETF",
}

NI225_POPULAR_3_ETF_COMPANY = {
    "EWJ": "iShares MSCI Japan ETF",
    "FLJP": "Franklin FTSE Japan ETF",
    "DXJ": "WisdomTree Japan Hedged Equity Fund",
}

ALL_ETF_TICKER_COMPANY_MAPPING = (
    DOW_JONES_ETF_COMPANY
    | DOW_JONES_ETF_COMPANY
    | NASDAQ_ETF_COMPANY
    | NASDAQ_POPULAR_3_ETF_COMPANY
    | SP500_ETF_COMPANY
    | SP500_POPULAR_3_ETF_COMPANY
    | SP100_POPULAR_3_ETF_COMPANY
    | RUSSELL2000_POPULAR_3_ETF_COMPANY
    | HSI_POPULAR_2_ETF_COMPANY
    | NI225_POPULAR_3_ETF_COMPANY
)

DOW_JONES_POPULAR_3_ETF = frozenset(DOW_JONES_POPULAR_3_ETF_COMPANY.keys())
NASDAQ_POPULAR_3_ETF = frozenset(NASDAQ_POPULAR_3_ETF_COMPANY.keys())
SP500_POPULAR_3_ETF = frozenset(SP500_POPULAR_3_ETF_COMPANY.keys())
SP100_POPULAR_3_ETF = frozenset(SP100_POPULAR_3_ETF_COMPANY.keys())
RUSSELL2000_POPULAR_3_ETF = frozenset(RUSSELL2000_POPULAR_3_ETF_COMPANY.keys())
HSI_POPULAR_2_ETF = frozenset(HSI_POPULAR_2_ETF_COMPANY.keys())
NI225_POPULAR_3_ETF = frozenset(NI225_POPULAR_3_ETF_COMPANY.keys())
