"""Module containing keywords for stock and ETF tickers."""

from merino.providers.suggest.finance.backends.polygon.etf_ticker_company_mapping import (
    DOW_JONES_POPULAR_3_ETF,
    NASDAQ_POPULAR_3_ETF,
    SP500_POPULAR_3_ETF,
    SP100_POPULAR_3_ETF,
    RUSSELL2000_POPULAR_3_ETF,
    HSI_POPULAR_2_ETF,
    NI225_POPULAR_3_ETF,
)

# Keyword to stock ticker mapping. Each keyword maps to its corresponding stock ticker.
# NOTE: Treat as read-only at runtime.
KEYWORD_TO_STOCK_TICKER_MAPPING = {
    # "aa stock": "AA",
    # "stock aa": "AA",
    "al stock": "AL",
    "stock al": "AL",
    "am stock": "AM",
    "stock am": "AM",
    "an stock": "AN",
    "stock an": "AN",
    "ar stock": "AR",
    "stock ar": "AR",
    "as stock": "AS",
    "stock as": "AS",
    "au stock": "AU",
    "stock au": "AU",
    "bc stock": "BC",
    "stock bc": "BC",
    "bg stock": "BG",
    "stock bg": "BG",
    "bj stock": "BJ",
    "stock bj": "BJ",
    "bk stock": "BK",
    "stock bk": "BK",
    "br stock": "BR",
    "stock br": "BR",
    "bx stock": "BX",
    "stock bx": "BX",
    "cb stock": "CB",
    "stock cb": "CB",
    "ce stock": "CE",
    "stock ce": "CE",
    "cf stock": "CF",
    "stock cf": "CF",
    "cg stock": "CG",
    "stock cg": "CG",
    "ci stock": "CI",
    "stock ci": "CI",
    "cl stock": "CL",
    "stock cl": "CL",
    "cr stock": "CR",
    "stock cr": "CR",
    "cw stock": "CW",
    "stock cw": "CW",
    "dd stock": "DD",
    "stock dd": "DD",
    "de stock": "DE",
    "stock de": "DE",
    "dg stock": "DG",
    "stock dg": "DG",
    "dt stock": "DT",
    "stock dt": "DT",
    "dv stock": "DV",
    "stock dv": "DV",
    "ea stock": "EA",
    "stock ea": "EA",
    "ed stock": "ED",
    "stock ed": "ED",
    "eg stock": "EG",
    "stock eg": "EG",
    "el stock": "EL",
    "stock el": "EL",
    "es stock": "ES",
    "stock es": "ES",
    "ew stock": "EW",
    "stock ew": "EW",
    "fe stock": "FE",
    "stock fe": "FE",
    "fi stock": "FI",
    "stock fi": "FI",
    "fr stock": "FR",
    "stock fr": "FR",
    "gd stock": "GD",
    "stock gd": "GD",
    "ge stock": "GE",
    "stock ge": "GE",
    "gl stock": "GL",
    "stock gl": "GL",
    "gm stock": "GM",
    "stock gm": "GM",
    "gs stock": "GS",
    "stock gs": "GS",
    "hr stock": "HR",
    "stock hr": "HR",
    "ip stock": "IP",
    "stock ip": "IP",
    "ir stock": "IR",
    "stock ir": "IR",
    "it stock": "IT",
    "stock it": "IT",
    "kd stock": "KD",
    "stock kd": "KD",
    "kr stock": "KR",
    "stock kr": "KR",
    "lh stock": "LH",
    "stock lh": "LH",
    "lw stock": "LW",
    "stock lw": "LW",
    "mo stock": "MO",
    "stock mo": "MO",
    "mp stock": "MP",
    "stock mp": "MP",
    "ms stock": "MS",
    "stock ms": "MS",
    "ni stock": "NI",
    "stock ni": "NI",
    "nu stock": "NU",
    "stock nu": "NU",
    "oc stock": "OC",
    "stock oc": "OC",
    "on stock": "ON",
    "stock on": "ON",
    "pb stock": "PB",
    "stock pb": "PB",
    "ph stock": "PH",
    "stock ph": "PH",
    "pk stock": "PK",
    "stock pk": "PK",
    "pm stock": "PM",
    "stock pm": "PM",
    "pr stock": "PR",
    "stock pr": "PR",
    "qs stock": "QS",
    "stock qs": "QS",
    "rf stock": "RF",
    "stock rf": "RF",
    "rh stock": "RH",
    "stock rh": "RH",
    "rl stock": "RL",
    "stock rl": "RL",
    "rs stock": "RS",
    "stock rs": "RS",
    "sf stock": "SF",
    "stock sf": "SF",
    "sn stock": "SN",
    "stock sn": "SN",
    "so stock": "SO",
    "stock so": "SO",
    "st stock": "ST",
    "stock st": "ST",
    "sw stock": "SW",
    "stock sw": "SW",
    "tt stock": "TT",
    "stock tt": "TT",
    "tw stock": "TW",
    "stock tw": "TW",
    "ua stock": "UA",
    "stock ua": "UA",
    "ui stock": "UI",
    "stock ui": "UI",
    "vz stock": "VZ",
    "stock vz": "VZ",
    "wh stock": "WH",
    "stock wh": "WH",
    "wm stock": "WM",
    "stock wm": "WM",
    "wu stock": "WU",
    "stock wu": "WU",
    "wy stock": "WY",
    "stock wy": "WY",
    "xp stock": "XP",
    "stock xp": "XP",
    "aal stock": "AAL",
    "aapl stock": "AAPL",
    "abbv stock": "ABBV",
    "abbvie stock": "ABBV",
    "adbe stock": "ADBE",
    "adobe stock": "ADBE",
    "advanced micro devices stock": "AMD",
    "alphabet stock": "GOOGL",
    "amazn stock": "AMZN",
    "amazon stock": "AMZN",
    "amd stock": "AMD",
    "american airlines stock": "AAL",
    "apple stock": "AAPL",
    "avgo stock": "AVGO",
    "ba stock": "BA",
    "bac stock": "BAC",
    "bank of america stock": "BAC",
    "berkshire hathaway stock": "BRK.B",
    "boeing stock": "BA",
    "brk.b stock": "BRK.B",
    "broadcom stock": "AVGO",
    "chevron stock": "CVX",
    "coca-cola stock": "KO",
    "coin stock": "COIN",
    "coinbase stock": "COIN",
    "cost stock": "COST",
    "crm stock": "CRM",
    "cvx stock": "CVX",
    "dis stock": "DIS",
    "disney stock": "DIS",
    "eli lilly stock": "LLY",
    "et stock": "ET",
    "exxonmobil stock": "XOM",
    "googl stock": "GOOGL",
    "hd stock": "HD",
    "home depot stock": "HD",
    "intc stock": "INTC",
    "intel stock": "INTC",
    "jnj stock": "JNJ",
    "johnson & johnson stock": "JNJ",
    "jpm stock": "JPM",
    "jpmorgan chase stock": "JPM",
    "ko stock": "KO",
    "lcid stock": "LCID",
    "lly stock": "LLY",
    "lucid group stock": "LCID",
    "ma stock": "MA",
    "mastercard stock": "MA",
    "mcd stock": "MCD",
    "mcdonald's stock": "MCD",
    "meta stock": "META",
    "micron technology stock": "MU",
    "microsoft stock": "MSFT",
    "msft stock": "MSFT",
    "mu stock": "MU",
    "nasdaq qqq": "QQQ",
    "netflix stock": "NFLX",
    "nflx stock": "NFLX",
    "nvda stock": "NVDA",
    "nvidia stock": "NVDA",
    "palantir technologies stock": "PLTR",
    "paypal stock": "PYPL",
    "pep stock": "PEP",
    "pepsico stock": "PEP",
    "pfe stock": "PFE",
    "pfizer stock": "PFE",
    "pg stock": "PG",
    "pltr stock": "PLTR",
    "plug power stock": "PLUG",
    "plug stock": "PLUG",
    "procter & gamble stock": "PG",
    "pypl stock": "PYPL",
    "qcom stock": "QCOM",
    "qqq": "QQQ",
    "qqqm": "QQQ",
    "qualcomm stock": "QCOM",
    "rblx stock": "RBLX",
    "roblox stock": "RBLX",
    "salesforce stock": "CRM",
    "sche": "SCHE",
    "sivr": "SIVR",
    "sofi stock": "SOFI",
    "sofi technologies stock": "SOFI",
    "amzn stock": "AMZN",
    "csco stock": "CSCO",
    "stock csco": "CSCO",
    "dell stock": "DELL",
    "stock dell": "DELL",
    "docu stock": "DOCU",
    "stock docu": "DOCU",
    "ebay stock": "EBAY",
    "stock ebay": "EBAY",
    "goog stock": "GOOG",
    "stock goog": "GOOG",
    "hood stock": "HOOD",
    "stock hood": "HOOD",
    "ibm stock": "IBM",
    "stock ibm": "IBM",
    "lyft stock": "LYFT",
    "stock lyft": "LYFT",
    "orcl stock": "ORCL",
    "stock orcl": "ORCL",
    "pins stock": "PINS",
    "stock pins": "PINS",
    "rddt stock": "RDDT",
    "stock rddt": "RDDT",
    "roku stock": "ROKU",
    "stock roku": "ROKU",
    "snow stock": "SNOW",
    "stock snow": "SNOW",
    "spot stock": "SPOT",
    "stock spot": "SPOT",
    "team stock": "TEAM",
    "stock team": "TEAM",
    "uber stock": "UBER",
    "stock uber": "UBER",
    "stock aal": "AAL",
    "stock aapl": "AAPL",
    "stock abbv": "ABBV",
    "stock abbvie": "ABBV",
    "stock adbe": "ADBE",
    "stock adobe": "ADBE",
    "stock advanced micro devices": "AMD",
    "stock alphabet": "GOOGL",
    "stock amazon": "AMZN",
    "stock amd": "AMD",
    "stock american airlines": "AAL",
    "stock amzn": "AMZN",
    "stock apple": "AAPL",
    "stock avgo": "AVGO",
    "stock ba": "BA",
    "stock bac": "BAC",
    "stock bank of america": "BAC",
    "stock berkshire hathaway": "BRK.B",
    "stock boeing": "BA",
    "stock brk.b": "BRK.B",
    "stock broadcom": "AVGO",
    "stock chevron": "CVX",
    "stock coca-cola": "KO",
    "stock coin": "COIN",
    "stock coinbase": "COIN",
    "stock cost": "COST",
    "stock costco": "COST",
    "stock crm": "CRM",
    "stock cvx": "CVX",
    "stock dis": "DIS",
    "stock disney": "DIS",
    "stock eli lilly": "LLY",
    "stock exxonmobil": "XOM",
    "stock googl": "GOOGL",
    "stock hd": "HD",
    "stock home depot": "HD",
    "stock intc": "INTC",
    "stock intel": "INTC",
    "stock jnj": "JNJ",
    "stock johnson & johnson": "JNJ",
    "stock jpm": "JPM",
    "stock jpmorgan chase": "JPM",
    "stock ko": "KO",
    "stock lcid": "LCID",
    "stock lly": "LLY",
    "stock lucid group": "LCID",
    "stock ma": "MA",
    "stock mastercard": "MA",
    "stock mcd": "MCD",
    "stock mcdonald's": "MCD",
    "stock meta": "META",
    "stock micron technology": "MU",
    "stock microsoft": "MSFT",
    "stock msft": "MSFT",
    "stock mu": "MU",
    "stock netflix": "NFLX",
    "stock nflx": "NFLX",
    "stock nvda": "NVDA",
    "stock nvidia": "NVDA",
    "stock palantir technologies": "PLTR",
    "stock paypal": "PYPL",
    "stock pep": "PEP",
    "stock pepsico": "PEP",
    "stock pfe": "PFE",
    "stock pfizer": "PFE",
    "stock pg": "PG",
    "stock pltr": "PLTR",
    "stock plug": "PLUG",
    "stock plug power": "PLUG",
    "stock procter & gamble": "PG",
    "stock pypl": "PYPL",
    "stock qcom": "QCOM",
    "stock qualcomm": "QCOM",
    "stock rblx": "RBLX",
    "stock roblox": "RBLX",
    "stock salesforce": "CRM",
    "stock sofi": "SOFI",
    "stock sofi technologies": "SOFI",
    "stock tesla": "TSLA",
    "stock texas instruments": "TXN",
    "stock tsla": "TSLA",
    "stock txn": "TXN",
    "stock unh": "UNH",
    "stock unitedhealth group": "UNH",
    "stock v": "V",
    "stock visa": "V",
    "stock walmart": "WMT",
    "stock wmt": "WMT",
    "stock xom": "XOM",
    "tesla stock": "TSLA",
    "texas instruments stock": "TXN",
    "tqqq": "QQQ",
    "tsla stock": "TSLA",
    "txn stock": "TXN",
    "unh stock": "UNH",
    "unitedhealth group stock": "UNH",
    "v stock": "V",
    "visa stock": "V",
    "vti": "VTI",
    "walmart stock": "WMT",
    "wmt stock": "WMT",
    "xom stock": "XOM",
}

# Keyword to ETF ticker mapping. Each keyword maps to its corresponding ETF ticker.
# NOTE: Treat as read-only at runtime.
KEYWORD_TO_ETF_TICKER_MAPPING = {
    "100 nasdaq": NASDAQ_POPULAR_3_ETF,
    "529 account": NASDAQ_POPULAR_3_ETF,
    "american stock market today": NASDAQ_POPULAR_3_ETF,
    "best stocks to buy now": NASDAQ_POPULAR_3_ETF,
    "cnbc markets": NASDAQ_POPULAR_3_ETF,
    "cnbc premarket": NASDAQ_POPULAR_3_ETF,
    "cnbc us markets": NASDAQ_POPULAR_3_ETF,
    "dji index live": DOW_JONES_POPULAR_3_ETF,
    "djia": DOW_JONES_POPULAR_3_ETF,
    "djia futures": DOW_JONES_POPULAR_3_ETF,
    "djia futures now": DOW_JONES_POPULAR_3_ETF,
    "djia index": DOW_JONES_POPULAR_3_ETF,
    "djia live": DOW_JONES_POPULAR_3_ETF,
    "djia today": DOW_JONES_POPULAR_3_ETF,
    "don jones index": DOW_JONES_POPULAR_3_ETF,
    "dow and jones index": DOW_JONES_POPULAR_3_ETF,
    "dow average today": DOW_JONES_POPULAR_3_ETF,
    "dow futures": DOW_JONES_POPULAR_3_ETF,
    "dow futures now": DOW_JONES_POPULAR_3_ETF,
    "dow graph": DOW_JONES_POPULAR_3_ETF,
    "dow index today": DOW_JONES_POPULAR_3_ETF,
    "dow industrial live": DOW_JONES_POPULAR_3_ETF,
    "dow jones": DOW_JONES_POPULAR_3_ETF,
    "dow jones average": DOW_JONES_POPULAR_3_ETF,
    "dow jones chart": DOW_JONES_POPULAR_3_ETF,
    "dow jones futures": DOW_JONES_POPULAR_3_ETF,
    "dow jones index": DOW_JONES_POPULAR_3_ETF,
    "dow jones index chart": DOW_JONES_POPULAR_3_ETF,
    "dow jones index futures": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial average": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial average chart": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial average futures": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial average index": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial average live": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial average today": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial futures": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial index": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial live": DOW_JONES_POPULAR_3_ETF,
    "dow jones live": DOW_JONES_POPULAR_3_ETF,
    "dow jones stock markets": DOW_JONES_POPULAR_3_ETF,
    "dow jones stock markets futures": DOW_JONES_POPULAR_3_ETF,
    "dow jones stocks": DOW_JONES_POPULAR_3_ETF,
    "dow jones today": DOW_JONES_POPULAR_3_ETF,
    "dow today": DOW_JONES_POPULAR_3_ETF,
    "dowjones index live": DOW_JONES_POPULAR_3_ETF,
    "etf": NASDAQ_POPULAR_3_ETF,
    "etf s": NASDAQ_POPULAR_3_ETF,
    "etfs": NASDAQ_POPULAR_3_ETF,
    "financial advisor": NASDAQ_POPULAR_3_ETF,
    "futures cnbc": NASDAQ_POPULAR_3_ETF,
    "hkex index": HSI_POPULAR_2_ETF,
    "index nasdaq 100": NASDAQ_POPULAR_3_ETF,
    "index nasdaq composite": NASDAQ_POPULAR_3_ETF,
    "indexnasdaq ixic": NASDAQ_POPULAR_3_ETF,
    "investing": NASDAQ_POPULAR_3_ETF,
    "nasdaq": NASDAQ_POPULAR_3_ETF,
    "nasdaq 100": NASDAQ_POPULAR_3_ETF,
    "nasdaq 100 companies": NASDAQ_POPULAR_3_ETF,
    "nasdaq comp index": NASDAQ_POPULAR_3_ETF,
    "nasdaq compo": NASDAQ_POPULAR_3_ETF,
    "nasdaq composite": NASDAQ_POPULAR_3_ETF,
    "nasdaq composite ixic": NASDAQ_POPULAR_3_ETF,
    "nasdaq composite stock index": NASDAQ_POPULAR_3_ETF,
    "nasdaq futures": NASDAQ_POPULAR_3_ETF,
    "nasdaq index": NASDAQ_POPULAR_3_ETF,
    "nasdaq ixic": NASDAQ_POPULAR_3_ETF,
    "nasdaq market index": NASDAQ_POPULAR_3_ETF,
    "nasdaq ndaq": NASDAQ_POPULAR_3_ETF,
    "nasdaq stock market today": NASDAQ_POPULAR_3_ETF,
    "nasdaq today": NASDAQ_POPULAR_3_ETF,
    "nikkei 225": NI225_POPULAR_3_ETF,
    "ny stock exchange": NASDAQ_POPULAR_3_ETF,
    "premarket": NASDAQ_POPULAR_3_ETF,
    "reddit stocks": NASDAQ_POPULAR_3_ETF,
    "russell 2000": RUSSELL2000_POPULAR_3_ETF,
    "s and p": SP500_POPULAR_3_ETF,
    "s and p 500": SP500_POPULAR_3_ETF,
    "s and p 500 futures": SP500_POPULAR_3_ETF,
    "s and p 500 index fund": SP500_POPULAR_3_ETF,
    "s and p 500 today": SP500_POPULAR_3_ETF,
    "s and p futures": SP500_POPULAR_3_ETF,
    "s p 100": SP100_POPULAR_3_ETF,
    "s p 500": SP500_POPULAR_3_ETF,
    "s&0 500": SP500_POPULAR_3_ETF,
    "s&5 500": SP500_POPULAR_3_ETF,
    "s&500 index": SP500_POPULAR_3_ETF,
    "s&p": SP500_POPULAR_3_ETF,
    "s&p 100": SP100_POPULAR_3_ETF,
    "s&p 500": SP500_POPULAR_3_ETF,
    "s&p 500 fund": SP500_POPULAR_3_ETF,
    "s&p 500 futures": SP500_POPULAR_3_ETF,
    "s&p 500 index": SP500_POPULAR_3_ETF,
    "s&p 500 index spx": SP500_POPULAR_3_ETF,
    "s&p 500 today": SP500_POPULAR_3_ETF,
    "s&p futures": SP500_POPULAR_3_ETF,
    "s&p stock market today": SP500_POPULAR_3_ETF,
    "s&poors 500": SP500_POPULAR_3_ETF,
    "sand p500": SP500_POPULAR_3_ETF,
    "sandp": SP500_POPULAR_3_ETF,
    "sandp500": SP500_POPULAR_3_ETF,
    "shares": NASDAQ_POPULAR_3_ETF,
    "snp500 futures": SP500_POPULAR_3_ETF,
    "sp 100": SP100_POPULAR_3_ETF,
    "sp 500": SP500_POPULAR_3_ETF,
    "spx": SP500_POPULAR_3_ETF,
    "spx 500 futures": SP500_POPULAR_3_ETF,
    "spx futures": SP500_POPULAR_3_ETF,
    "spx index futures": SP500_POPULAR_3_ETF,
    "spx stock": SP500_POPULAR_3_ETF,
    "standard & poor's 500": SP500_POPULAR_3_ETF,
    "standard & poor's 500 index": SP500_POPULAR_3_ETF,
    "standard and poor's 500 futures": SP500_POPULAR_3_ETF,
    "stock futures": NASDAQ_POPULAR_3_ETF,
    "stock index": NASDAQ_POPULAR_3_ETF,
    "stock indices": NASDAQ_POPULAR_3_ETF,
    "stock market": NASDAQ_POPULAR_3_ETF,
    "stock market futures": NASDAQ_POPULAR_3_ETF,
    "stock market news": NASDAQ_POPULAR_3_ETF,
    "stock market stocks": NASDAQ_POPULAR_3_ETF,
    "stock market today": NASDAQ_POPULAR_3_ETF,
    "stock prices": NASDAQ_POPULAR_3_ETF,
    "stocks": NASDAQ_POPULAR_3_ETF,
    "venture capital": NASDAQ_POPULAR_3_ETF,
    "us stock market": NASDAQ_POPULAR_3_ETF,
    "us stock market today": NASDAQ_POPULAR_3_ETF,
    "bib stock": ["BIB"],
    "stock bib": ["BIB"],
    "ekg stock": ["EKG"],
    "stock ekg": ["EKG"],
    "webl stock": ["WEBL"],
    "stock webl": ["WEBL"],
    "webs stock": ["WEBS"],
    "stock webs": ["WEBS"],
    "grid stock": ["GRID"],
    "stock grid": ["GRID"],
    "flag stock": ["FLAG"],
    "stock flag": ["FLAG"],
    "spy stock": ["SPY"],
    "stock spy": ["SPY"],
    "ispy stock": ["ISPY"],
    "stock ispy": ["ISPY"],
    "rpg stock": ["RPG"],
    "stock rpg": ["RPG"],
    "topc stock": ["TOPC"],
    "stock topc": ["TOPC"],
    "robt stock": ["ROBT"],
    "stock robt": ["ROBT"],
    "rwx stock": ["RWX"],
    "stock rwx": ["RWX"],
    "zzz stock": ["ZZZ"],
    "stock zzz": ["ZZZ"],
    "egle stock": ["EGLE"],
    "stock egle": ["EGLE"],
    "emot stock": ["EMOT"],
    "stock emot": ["EMOT"],
    "kng stock": ["KNG"],
    "stock kng": ["KNG"],
    "kngz stock": ["KNGZ"],
    "stock kngz": ["KNGZ"],
    "hndl stock": ["HNDL"],
    "stock hndl": ["HNDL"],
    "putd stock": ["PUTD"],
    "stock putd": ["PUTD"],
    "xtr stock": ["XTR"],
    "stock xtr": ["XTR"],
    "xlg stock": ["XLG"],
    "stock xlg": ["XLG"],
    "fb stock": ["FB"],
    "stock fb": ["FB"],
    "qb stock": ["QB"],
    "stock qb": ["QB"],
}
