"""Module containing keywords for stock and ETF tickers."""

# Keyword to stock ticker mapping. Each keyword maps to its corresponding stock ticker.
# NOTE: Treat as read-only at runtime.
KEYWORD_TO_STOCK_TICKER = {
    "aal stock": "AAL",
    "aapl stock": "AAPL",
    "abbv stock": "ABBV",
    "abbvie stock": "ABBV",
    "adbe stock": "ADBE",
    "adobe stock": "ADBE",
    "advanced micro devices stock": "AMD",
    "alphabet stock": "GOOGL",
    "amazn stock": "AMZN",
    "amazon stock": "AMZN",
    "amd stock": "AMD",
    "american airlines stock": "AAL",
    "apple stock": "AAPL",
    "avgo stock": "AVGO",
    "ba stock": "BA",
    "bac stock": "BAC",
    "bank of america stock": "BAC",
    "berkshire hathaway stock": "BRK.B",
    "boeing stock": "BA",
    "brk.b stock": "BRK.B",
    "broadcom stock": "AVGO",
    "chevron stock": "CVX",
    "coca-cola stock": "KO",
    "coin stock": "COIN",
    "coinbase stock": "COIN",
    "cost stock": "COST",
    "crm stock": "CRM",
    "cvx stock": "CVX",
    "dis stock": "DIS",
    "disney stock": "DIS",
    "eli lilly stock": "LLY",
    "et stock": "ET",
    "exxonmobil stock": "XOM",
    "googl stock": "GOOGL",
    "hd stock": "HD",
    "home depot stock": "HD",
    "intc stock": "INTC",
    "intel stock": "INTC",
    "jnj stock": "JNJ",
    "johnson & johnson stock": "JNJ",
    "jpm stock": "JPM",
    "jpmorgan chase stock": "JPM",
    "ko stock": "KO",
    "lcid stock": "LCID",
    "lly stock": "LLY",
    "lucid group stock": "LCID",
    "ma stock": "MA",
    "mastercard stock": "MA",
    "mcd stock": "MCD",
    "mcdonald's stock": "MCD",
    "meta stock": "META",
    "micron technology stock": "MU",
    "microsoft stock": "MSFT",
    "msft stock": "MSFT",
    "mu stock": "MU",
    "nasdaq qqq": "QQQ",
    "netflix stock": "NFLX",
    "nflx stock": "NFLX",
    "nvda stock": "NVDA",
    "nvidia stock": "NVDA",
    "palantir technologies stock": "PLTR",
    "paypal stock": "PYPL",
    "pep stock": "PEP",
    "pepsico stock": "PEP",
    "pfe stock": "PFE",
    "pfizer stock": "PFE",
    "pg stock": "PG",
    "pltr stock": "PLTR",
    "plug power stock": "PLUG",
    "plug stock": "PLUG",
    "procter & gamble stock": "PG",
    "pypl stock": "PYPL",
    "qcom stock": "QCOM",
    "qqq": "QQQ",
    "qqqm": "QQQ",
    "qualcomm stock": "QCOM",
    "rblx stock": "RBLX",
    "roblox stock": "RBLX",
    "salesforce stock": "CRM",
    "sche": "SCHE",
    "sivr": "SIVR",
    "sofi stock": "SOFI",
    "sofi technologies stock": "SOFI",
    "stock aal": "AAL",
    "stock aapl": "AAPL",
    "stock abbv": "ABBV",
    "stock abbvie": "ABBV",
    "stock adbe": "ADBE",
    "stock adobe": "ADBE",
    "stock advanced micro devices": "AMD",
    "stock alphabet": "GOOGL",
    "stock amazon": "AMZN",
    "stock amd": "AMD",
    "stock american airlines": "AAL",
    "stock amzn": "AMZN",
    "stock apple": "AAPL",
    "stock avgo": "AVGO",
    "stock ba": "BA",
    "stock bac": "BAC",
    "stock bank of america": "BAC",
    "stock berkshire hathaway": "BRK.B",
    "stock boeing": "BA",
    "stock brk.b": "BRK.B",
    "stock broadcom": "AVGO",
    "stock chevron": "CVX",
    "stock coca-cola": "KO",
    "stock coin": "COIN",
    "stock coinbase": "COIN",
    "stock cost": "COST",
    "stock costco": "COST",
    "stock crm": "CRM",
    "stock cvx": "CVX",
    "stock dis": "DIS",
    "stock disney": "DIS",
    "stock eli lilly": "LLY",
    "stock exxonmobil": "XOM",
    "stock googl": "GOOGL",
    "stock hd": "HD",
    "stock home depot": "HD",
    "stock intc": "INTC",
    "stock intel": "INTC",
    "stock jnj": "JNJ",
    "stock johnson & johnson": "JNJ",
    "stock jpm": "JPM",
    "stock jpmorgan chase": "JPM",
    "stock ko": "KO",
    "stock lcid": "LCID",
    "stock lly": "LLY",
    "stock lucid group": "LCID",
    "stock ma": "MA",
    "stock mastercard": "MA",
    "stock mcd": "MCD",
    "stock mcdonald's": "MCD",
    "stock meta": "META",
    "stock micron technology": "MU",
    "stock microsoft": "MSFT",
    "stock msft": "MSFT",
    "stock mu": "MU",
    "stock netflix": "NFLX",
    "stock nflx": "NFLX",
    "stock nvda": "NVDA",
    "stock nvidia": "NVDA",
    "stock palantir technologies": "PLTR",
    "stock paypal": "PYPL",
    "stock pep": "PEP",
    "stock pepsico": "PEP",
    "stock pfe": "PFE",
    "stock pfizer": "PFE",
    "stock pg": "PG",
    "stock pltr": "PLTR",
    "stock plug": "PLUG",
    "stock plug power": "PLUG",
    "stock procter & gamble": "PG",
    "stock pypl": "PYPL",
    "stock qcom": "QCOM",
    "stock qualcomm": "QCOM",
    "stock rblx": "RBLX",
    "stock roblox": "RBLX",
    "stock salesforce": "CRM",
    "stock sofi": "SOFI",
    "stock sofi technologies": "SOFI",
    "stock tesla": "TSLA",
    "stock texas instruments": "TXN",
    "stock tsla": "TSLA",
    "stock txn": "TXN",
    "stock unh": "UNH",
    "stock unitedhealth group": "UNH",
    "stock v": "V",
    "stock visa": "V",
    "stock walmart": "WMT",
    "stock wmt": "WMT",
    "stock xom": "XOM",
    "tesla stock": "TSLA",
    "texas instruments stock": "TXN",
    "tqqq": "QQQ",
    "tsla stock": "TSLA",
    "txn stock": "TXN",
    "unh stock": "UNH",
    "unitedhealth group stock": "UNH",
    "us stock market": "MA",
    "us stock market today": "MA",
    "v stock": "V",
    "visa stock": "V",
    "vti": "VTI",
    "walmart stock": "WMT",
    "wmt stock": "WMT",
    "xom stock": "XOM",
}

# Keyword to ETF ticker mapping. Each keyword maps to its corresponding ETF ticker.
# NOTE: Treat as read-only at runtime.
KEYWORD_TO_ETF_TICKER = {
    "100 nasdaq": None,
    "529 account": None,
    "american stock market today": None,
    "best stocks to buy now": None,
    "cnbc markets": None,
    "cnbc premarket": None,
    "cnbc us markets": None,
    "dji index live": None,
    "djia": None,
    "djia futures": None,
    "djia futures now": None,
    "djia index": None,
    "djia live": None,
    "djia today": None,
    "don jones index": None,
    "dow and jones index": None,
    "dow average today": None,
    "dow futures": None,
    "dow futures now": None,
    "dow graph": None,
    "dow index today": None,
    "dow industrial live": None,
    "dow jones": None,
    "dow jones average": None,
    "dow jones chart": None,
    "dow jones futures": None,
    "dow jones index": None,
    "dow jones index chart": None,
    "dow jones index futures": None,
    "dow jones industrial": None,
    "dow jones industrial average": None,
    "dow jones industrial average chart": None,
    "dow jones industrial average futures": None,
    "dow jones industrial average index": None,
    "dow jones industrial average live": None,
    "dow jones industrial average today": None,
    "dow jones industrial futures": None,
    "dow jones industrial index": None,
    "dow jones industrial live": None,
    "dow jones live": None,
    "dow jones stock markets": None,
    "dow jones stock markets futures": None,
    "dow jones stocks": None,
    "dow jones today": None,
    "dow today": None,
    "dowjones index live": None,
    "etf": None,
    "etf s": None,
    "etfs": None,
    "financial advisor": None,
    "futures cnbc": None,
    "hkex index": None,
    "index nasdaq 100": None,
    "index nasdaq composite": None,
    "indexnasdaq ixic": None,
    "investing": None,
    "nasdaq": None,
    "nasdaq 100": None,
    "nasdaq 100 companies": None,
    "nasdaq comp index": None,
    "nasdaq compo": None,
    "nasdaq composite": None,
    "nasdaq composite ixic": None,
    "nasdaq composite stock index": None,
    "nasdaq futures": None,
    "nasdaq index": None,
    "nasdaq ixic": None,
    "nasdaq market index": None,
    "nasdaq ndaq": None,
    "nasdaq stock market today": None,
    "nasdaq today": None,
    "nikkei 225": None,
    "ny stock exchange": None,
    "premarket": None,
    "reddit stocks": None,
    "russell 2000": None,
    "s and p": None,
    "s and p 500": None,
    "s and p 500 futures": None,
    "s and p 500 index fund": None,
    "s and p 500 today": None,
    "s and p futures": None,
    "s p 100": None,
    "s p 500": None,
    "s&0 500": None,
    "s&5 500": None,
    "s&500 index": None,
    "s&p": None,
    "s&p 100": None,
    "s&p 500": None,
    "s&p 500 fund": None,
    "s&p 500 futures": None,
    "s&p 500 index": None,
    "s&p 500 index spx": None,
    "s&p 500 today": None,
    "s&p futures": None,
    "s&p stock market today": None,
    "s&poors 500": None,
    "sand p500": None,
    "sandp": None,
    "sandp500": None,
    "shares": None,
    "snp500 futures": None,
    "sp 100": None,
    "sp 500": None,
    "spx": None,
    "spx 500 futures": None,
    "spx futures": None,
    "spx index futures": None,
    "spx stock": None,
    "standard & poor's 500": None,
    "standard & poor's 500 index": None,
    "standard and poor's 500 futures": None,
    "stock futures": None,
    "stock index": None,
    "stock indices": None,
    "stock market": None,
    "stock market futures": None,
    "stock market news": None,
    "stock market stocks": None,
    "stock market today": None,
    "stock prices": None,
    "stocks": None,
    "venture capital": None,
}

STOCK_TICKER_KEYWORDS = frozenset(KEYWORD_TO_STOCK_TICKER.keys())

ETF_TICKER_KEYWORDS = frozenset(KEYWORD_TO_ETF_TICKER.keys())
