"""Module containing JSON object with ticker symbol to company name mapping for RUSSELL1000 tickers."""

# Source of truth for ticker symbol and company name mapping.
# NOTE: Should be treated as read-only and runtime.
ALL_STOCK_TICKER_COMPANY_MAPPING: dict[str, dict[str, str]] = {
    "A": {"company": "Agilent Technologies", "exchange": "NYSE"},
    "AA": {"company": "Alcoa Corp", "exchange": "NYSE"},
    "AAL": {"company": "American Airlines Gp", "exchange": "NASDAQ"},
    "AAON": {"company": "Aaon Inc", "exchange": "NASDAQ"},
    "AAPL": {"company": "Apple Inc", "exchange": "NASDAQ"},
    "ABBV": {"company": "Abbvie Inc", "exchange": "NYSE"},
    "ABNB": {"company": "Airbnb Inc", "exchange": "NASDAQ"},
    "ABT": {"company": "Abbott Laboratories", "exchange": "NYSE"},
    "ACGL": {"company": "Arch Capital Grp Ltd", "exchange": "NASDAQ"},
    "ACHC": {"company": "Acadia Healthcr Company", "exchange": "NASDAQ"},
    "ACI": {"company": "Albertsons Companies Inc", "exchange": "NYSE"},
    "ACM": {"company": "Aecom Technology Corp", "exchange": "NYSE"},
    "ACN": {"company": "Accenture Plc", "exchange": "NYSE"},
    "ADBE": {"company": "Adobe Systems Inc", "exchange": "NASDAQ"},
    "ADC": {"company": "Agree Realty Corp", "exchange": "NYSE"},
    "ADI": {"company": "Analog Devices", "exchange": "NASDAQ"},
    "ADM": {"company": "Archer Daniels Midland", "exchange": "NYSE"},
    "ADP": {"company": "Automatic Data Processing", "exchange": "NASDAQ"},
    "ADSK": {"company": "Autodesk Inc", "exchange": "NASDAQ"},
    "ADT": {"company": "ADT Inc", "exchange": "NYSE"},
    "AEE": {"company": "Ameren Corp", "exchange": "NYSE"},
    "AEP": {"company": "American Electric Power Company", "exchange": "NASDAQ"},
    "AES": {"company": "The Aes Corp", "exchange": "NYSE"},
    "AFG": {"company": "American Financial Group", "exchange": "NYSE"},
    "AFL": {"company": "Aflac Inc", "exchange": "NYSE"},
    "AFRM": {"company": "Affirm Holdings Inc", "exchange": "NASDAQ"},
    "AGCO": {"company": "Agco Corp", "exchange": "NYSE"},
    "AGNC": {"company": "Agnc Investment Corp", "exchange": "NASDAQ"},
    "AGO": {"company": "Assured Guaranty Ltd", "exchange": "NYSE"},
    "AIG": {"company": "American International Group", "exchange": "NYSE"},
    "AIT": {"company": "Applied Industrial Technologies", "exchange": "NYSE"},
    "AIZ": {"company": "Assurant Inc", "exchange": "NYSE"},
    "AJG": {"company": "Arthur J. Gallagher & Company", "exchange": "NYSE"},
    "AKAM": {"company": "Akamai Technologies", "exchange": "NASDAQ"},
    "AL": {"company": "Air Lease Corp", "exchange": "NYSE"},
    "ALAB": {"company": "Astera Labs Inc", "exchange": "NASDAQ"},
    "ALB": {"company": "Albemarle Corp", "exchange": "NYSE"},
    "ALGM": {"company": "Allegro Microsystems Inc", "exchange": "NASDAQ"},
    "ALGN": {"company": "Align Technology", "exchange": "NASDAQ"},
    "ALK": {"company": "Alaska Air Group", "exchange": "NYSE"},
    "ALL": {"company": "Allstate Corp", "exchange": "NYSE"},
    "ALLE": {"company": "Allegion Plc", "exchange": "NYSE"},
    "ALLY": {"company": "Ally Financial", "exchange": "NYSE"},
    "ALNY": {"company": "Alnylam Pharmaceuticals", "exchange": "NASDAQ"},
    "ALSN": {"company": "Allison Transmission Holdings", "exchange": "NYSE"},
    "AM": {"company": "Antero Midstream Corp", "exchange": "NYSE"},
    "AMAT": {"company": "Applied Materials", "exchange": "NASDAQ"},
    "AMCR": {"company": "Amcor Plc", "exchange": "NYSE"},
    "AMD": {"company": "Adv Micro Devices", "exchange": "NASDAQ"},
    "AME": {"company": "Ametek Inc", "exchange": "NYSE"},
    "AMED": {"company": "Amedisys Inc", "exchange": "NASDAQ"},
    "AMG": {"company": "Affiliated Managers Group", "exchange": "NYSE"},
    "AMGN": {"company": "Amgen Inc", "exchange": "NASDAQ"},
    "AMH": {"company": "American Homes 4 Rent", "exchange": "NYSE"},
    "AMKR": {"company": "Amkor Technology", "exchange": "NASDAQ"},
    "AMP": {"company": "Ameriprise Financial Services", "exchange": "NYSE"},
    "AMT": {"company": "American Tower Corp", "exchange": "NYSE"},
    "AMTM": {"company": "Amentum Holdings Inc", "exchange": "NYSE"},
    "AMZN": {"company": "Amazon.com Inc", "exchange": "NASDAQ"},
    "AN": {"company": "Autonation Inc", "exchange": "NYSE"},
    "ANET": {"company": "Arista Networks Inc", "exchange": "NYSE"},
    "AON": {"company": "AON Plc", "exchange": "NYSE"},
    "AOS": {"company": "Smith A.O. Corp", "exchange": "NYSE"},
    "APA": {"company": "Apa Corp", "exchange": "NASDAQ"},
    "APD": {"company": "Air Products and Chemicals", "exchange": "NYSE"},
    "APG": {"company": "Api Group Corp", "exchange": "NYSE"},
    "APH": {"company": "Amphenol Corp", "exchange": "NYSE"},
    "APLS": {"company": "Apellis Pharmaceuticals Inc", "exchange": "NASDAQ"},
    "APO": {"company": "Apollo Asset Management Inc", "exchange": "NYSE"},
    "APP": {"company": "Applovin Corp", "exchange": "NASDAQ"},
    "APPF": {"company": "Appfolio", "exchange": "NASDAQ"},
    "APTV": {"company": "Aptiv Plc", "exchange": "NYSE"},
    "AR": {"company": "Antero Resources Corp", "exchange": "NYSE"},
    "ARE": {"company": "Alexandria Real Estate Equities", "exchange": "NYSE"},
    "ARES": {"company": "Ares Management LP", "exchange": "NYSE"},
    "ARMK": {"company": "Aramark Holdings Corp", "exchange": "NYSE"},
    "ARW": {"company": "Arrow Electronics", "exchange": "NYSE"},
    "AS": {"company": "Amer Sports Inc", "exchange": "NYSE"},
    "ASH": {"company": "Ashland Inc", "exchange": "NYSE"},
    "ASTS": {"company": "Ast Spacemobile Inc", "exchange": "NASDAQ"},
    "ATI": {"company": "Ati Inc", "exchange": "NYSE"},
    "ATO": {"company": "Atmos Energy Corp", "exchange": "NYSE"},
    "ATR": {"company": "Aptargroup", "exchange": "NYSE"},
    "AU": {"company": "Anglogold Ashanti Ltd ADR", "exchange": "NYSE"},
    "AUR": {"company": "Aurora Innovation Inc", "exchange": "NASDAQ"},
    "AVB": {"company": "Avalonbay Communities", "exchange": "NYSE"},
    "AVGO": {"company": "Broadcom Ltd", "exchange": "NASDAQ"},
    "AVT": {"company": "Avnet Inc", "exchange": "NASDAQ"},
    "AVTR": {"company": "Avantor Inc", "exchange": "NYSE"},
    "AVY": {"company": "Avery Dennison Corp", "exchange": "NYSE"},
    "AWI": {"company": "Armstrong World Industries Inc", "exchange": "NYSE"},
    "AWK": {"company": "American Water Works", "exchange": "NYSE"},
    "AXON": {"company": "Axon Enterprise Inc", "exchange": "NASDAQ"},
    "AXP": {"company": "American Express Company", "exchange": "NYSE"},
    "AXS": {"company": "Axis Capital Holdings", "exchange": "NYSE"},
    "AXTA": {"company": "Axalta Coating Systems Ltd", "exchange": "NYSE"},
    "AYI": {"company": "Acuity Inc", "exchange": "NYSE"},
    "AZO": {"company": "Autozone", "exchange": "NYSE"},
    "BA": {"company": "Boeing Company", "exchange": "NYSE"},
    "BAC": {"company": "Bank of America Corp", "exchange": "NYSE"},
    "BAH": {"company": "Booz Allen Hamilton Holding Corp", "exchange": "NYSE"},
    "BALL": {"company": "Ball Corporation", "exchange": "NYSE"},
    "BAM": {"company": "Brookfield Asset Management Ltd", "exchange": "NYSE"},
    "BAX": {"company": "Baxter International Inc", "exchange": "NYSE"},
    "BBWI": {"company": "Bath & Body Works Inc", "exchange": "NYSE"},
    "BBY": {"company": "Best Buy Company", "exchange": "NYSE"},
    "BC": {"company": "Brunswick Corp", "exchange": "NYSE"},
    "BDX": {"company": "Becton Dickinson and Company", "exchange": "NYSE"},
    "BEN": {"company": "Franklin Resources", "exchange": "NYSE"},
    "BEPC": {"company": "Brookfield Renewable Corp", "exchange": "NYSE"},
    "BF.A": {"company": "Brown Forman Inc", "exchange": "NYSE"},
    "BF.B": {"company": "Brown Forman Inc Cl B", "exchange": "NYSE"},
    "BFAM": {"company": "Bright Horizons Family Solutions Inc", "exchange": "NYSE"},
    "BG": {"company": "Bunge Ltd", "exchange": "NYSE"},
    "BHF": {"company": "Brighthouse Financial Inc", "exchange": "NASDAQ"},
    "BIIB": {"company": "Biogen Inc", "exchange": "NASDAQ"},
    "BILL": {"company": "Bill Holdings Inc", "exchange": "NYSE"},
    "BIO": {"company": "Bio-Rad Laboratories", "exchange": "NYSE"},
    "BIRK": {"company": "Birkenstock Holding Plc", "exchange": "NYSE"},
    "BJ": {"company": "Bj's Wholesale Club Holdings Inc", "exchange": "NYSE"},
    "BK": {"company": "Bank of New York Mellon Corp", "exchange": "NYSE"},
    "BKNG": {"company": "Booking Holdings Inc", "exchange": "NASDAQ"},
    "BKR": {"company": "Baker Hughes Company", "exchange": "NASDAQ"},
    "BLD": {"company": "Topbuild Corp", "exchange": "NYSE"},
    "BLDR": {"company": "Builders Firstsource", "exchange": "NYSE"},
    "BLK": {"company": "Blackrock Inc", "exchange": "NYSE"},
    "BMRN": {"company": "Biomarin Pharmaceuticals", "exchange": "NASDAQ"},
    "BMY": {"company": "Bristol-Myers Squibb Company", "exchange": "NYSE"},
    "BOKF": {"company": "Bok Financial Corp", "exchange": "NASDAQ"},
    "BPOP": {"company": "Popular Inc", "exchange": "NASDAQ"},
    "BR": {"company": "Broadridge Financial Solutions Llc", "exchange": "NYSE"},
    "BRBR": {"company": "Bellring Brands Inc", "exchange": "NYSE"},
    "BRK.B": {"company": "Berkshire Hathaway Cl B", "exchange": "NYSE"},
    "BRKR": {"company": "Bruker Corp", "exchange": "NASDAQ"},
    "BRO": {"company": "Brown & Brown", "exchange": "NYSE"},
    "BROS": {"company": "Dutch Bros Inc", "exchange": "NYSE"},
    "BRX": {"company": "Brixmor Property Group Inc", "exchange": "NYSE"},
    "BSX": {"company": "Boston Scientific Corp", "exchange": "NYSE"},
    "BSY": {"company": "Bentley Systems Inc Cl B", "exchange": "NASDAQ"},
    "BURL": {"company": "Burlington Stores Inc", "exchange": "NYSE"},
    "BWA": {"company": "Borgwarner Inc", "exchange": "NYSE"},
    "BWXT": {"company": "Bwx Technologies Inc", "exchange": "NYSE"},
    "BX": {"company": "Blackstone Inc", "exchange": "NYSE"},
    "BXP": {"company": "Bxp Inc", "exchange": "NYSE"},
    "BYD": {"company": "Boyd Gaming Corp", "exchange": "NYSE"},
    "C": {"company": "Citigroup Inc", "exchange": "NYSE"},
    "CACC": {"company": "Credit Acceptance", "exchange": "NASDAQ"},
    "CACI": {"company": "Caci International", "exchange": "NYSE"},
    "CAG": {"company": "Conagra Brands Inc", "exchange": "NYSE"},
    "CAH": {"company": "Cardinal Health", "exchange": "NYSE"},
    "CAR": {"company": "Avis Budget Group", "exchange": "NASDAQ"},
    "CARR": {"company": "Carrier Global Corp", "exchange": "NYSE"},
    "CART": {"company": "Maplebear Inc [Instacart]", "exchange": "NASDAQ"},
    "CASY": {"company": "Casey's General Stor", "exchange": "NASDAQ"},
    "CAT": {"company": "Caterpillar Inc", "exchange": "NYSE"},
    "CAVA": {"company": "Cava Group Inc", "exchange": "NYSE"},
    "CB": {"company": "Chubb Ltd", "exchange": "NYSE"},
    "CBOE": {"company": "CBOE Global Markets Inc", "exchange": "BATS"},
    "CBRE": {"company": "CBRE Group Inc", "exchange": "NYSE"},
    "CBSH": {"company": "Commerce Bancshares", "exchange": "NASDAQ"},
    "CCCS": {"company": "CCC Intelligent Solutions Hldgs Inc", "exchange": "NASDAQ"},
    "CCI": {"company": "Crown Castle Inc", "exchange": "NYSE"},
    "CCK": {"company": "Crown Cork & Seal Company", "exchange": "NYSE"},
    "CCL": {"company": "Carnival Corp", "exchange": "NYSE"},
    "CDNS": {"company": "Cadence Design Sys", "exchange": "NASDAQ"},
    "CDW": {"company": "CDW Corp", "exchange": "NASDAQ"},
    "CE": {"company": "Celanese Corp", "exchange": "NYSE"},
    "CEG": {"company": "Constellation Energy Corp", "exchange": "NASDAQ"},
    "CELH": {"company": "Celsius Holdings Inc", "exchange": "NASDAQ"},
    "CERT": {"company": "Certara Inc", "exchange": "NASDAQ"},
    "CF": {"company": "Cf Industries Holdings", "exchange": "NYSE"},
    "CFG": {"company": "Citizens Financial Group Inc/Ri", "exchange": "NYSE"},
    "CFLT": {"company": "Confluent Inc", "exchange": "NASDAQ"},
    "CFR": {"company": "Cullen/Frost Bankers", "exchange": "NYSE"},
    "CG": {"company": "The Carlyle Group", "exchange": "NASDAQ"},
    "CGNX": {"company": "Cognex Corp", "exchange": "NASDAQ"},
    "CHD": {"company": "Church & Dwight Company", "exchange": "NYSE"},
    "CHDN": {"company": "Churchill Downs IN", "exchange": "NASDAQ"},
    "CHE": {"company": "Chemed Inc", "exchange": "NYSE"},
    "CHH": {"company": "Choice Hotels International", "exchange": "NYSE"},
    "CHRD": {"company": "Chord Energy Corp", "exchange": "NASDAQ"},
    "CHRW": {"company": "C.H. Robinson Ww", "exchange": "NASDAQ"},
    "CHTR": {"company": "Charter Communications Inc", "exchange": "NASDAQ"},
    "CHWY": {"company": "Chewy Inc", "exchange": "NYSE"},
    "CI": {"company": "The Cigna Group", "exchange": "NYSE"},
    "CIEN": {"company": "Ciena Corp", "exchange": "NYSE"},
    "CINF": {"company": "Cincinnati Financial", "exchange": "NASDAQ"},
    "CIVI": {"company": "Civitas Resources Inc", "exchange": "NYSE"},
    "CL": {"company": "Colgate-Palmolive Company", "exchange": "NYSE"},
    "CLF": {"company": "Cleveland-Cliffs Inc", "exchange": "NYSE"},
    "CLH": {"company": "Clean Harbors", "exchange": "NYSE"},
    "CLVT": {"company": "Clarivate Analytics Plc", "exchange": "NYSE"},
    "CLX": {"company": "Clorox Company", "exchange": "NYSE"},
    "CMA": {"company": "Comerica Inc", "exchange": "NYSE"},
    "CMCSA": {"company": "Comcast Corp A", "exchange": "NASDAQ"},
    "CME": {"company": "CME Group Inc", "exchange": "NASDAQ"},
    "CMG": {"company": "Chipotle Mexican Grill", "exchange": "NYSE"},
    "CMI": {"company": "Cummins Inc", "exchange": "NYSE"},
    "CMS": {"company": "Cms Energy Corp", "exchange": "NYSE"},
    "CNA": {"company": "CNA Financial Corp", "exchange": "NYSE"},
    "CNC": {"company": "Centene Corp", "exchange": "NYSE"},
    "CNH": {"company": "CNH Industrial N.V.", "exchange": "NYSE"},
    "CNM": {"company": "Core & Main Inc", "exchange": "NYSE"},
    "CNP": {"company": "Centerpoint Energy Inc", "exchange": "NYSE"},
    "CNXC": {"company": "Concentrix Corp", "exchange": "NASDAQ"},
    "COF": {"company": "Capital One Financial Corp", "exchange": "NYSE"},
    "COHR": {"company": "Coherent Corp", "exchange": "NYSE"},
    "COIN": {"company": "Coinbase Global Inc", "exchange": "NASDAQ"},
    "COKE": {"company": "Coca-Cola Consolidated Inc", "exchange": "NASDAQ"},
    "COLB": {"company": "Columbia Banking Sys", "exchange": "NASDAQ"},
    "COLD": {"company": "Americold Realty Trust", "exchange": "NYSE"},
    "COLM": {"company": "Columbia Sprtswr", "exchange": "NASDAQ"},
    "COO": {"company": "Cooper Companies", "exchange": "NASDAQ"},
    "COOP": {"company": "Mr.Cooper Group Inc", "exchange": "NASDAQ"},
    "COP": {"company": "Conocophillips", "exchange": "NYSE"},
    "COR": {"company": "Cencora Inc", "exchange": "NYSE"},
    "CORT": {"company": "Corcept Therapeutics", "exchange": "NASDAQ"},
    "COST": {"company": "Costco Wholesale", "exchange": "NASDAQ"},
    "COTY": {"company": "Coty Inc", "exchange": "NYSE"},
    "CPAY": {"company": "Corpay Inc", "exchange": "NYSE"},
    "CPB": {"company": "The Campbell's Company", "exchange": "NASDAQ"},
    "CPNG": {"company": "Coupang Inc", "exchange": "NYSE"},
    "CPRT": {"company": "Copart Inc", "exchange": "NASDAQ"},
    "CPT": {"company": "Camden Property Trust", "exchange": "NYSE"},
    "CR": {"company": "Crane Company", "exchange": "NYSE"},
    "CRH": {"company": "CRH Plc ADR", "exchange": "NYSE"},
    "CRL": {"company": "Charles River Laboratories Intl", "exchange": "NYSE"},
    "CRM": {"company": "Salesforce Inc", "exchange": "NYSE"},
    "CROX": {"company": "Crocs Inc", "exchange": "NASDAQ"},
    "CRS": {"company": "Carpenter Technology Corp", "exchange": "NYSE"},
    "CRUS": {"company": "Cirrus Logic Inc", "exchange": "NASDAQ"},
    "CRWD": {"company": "Crowdstrike Holdings Inc", "exchange": "NASDAQ"},
    "CSCO": {"company": "Cisco Systems Inc", "exchange": "NASDAQ"},
    "CSGP": {"company": "Costar Group Inc", "exchange": "NASDAQ"},
    "CSL": {"company": "Carlisle Companies Inc", "exchange": "NYSE"},
    "CSX": {"company": "CSX Corp", "exchange": "NASDAQ"},
    "CTAS": {"company": "Cintas Corp", "exchange": "NASDAQ"},
    "CTRA": {"company": "Coterra Energy Inc", "exchange": "NYSE"},
    "CTSH": {"company": "Cognizant Tech Sol", "exchange": "NASDAQ"},
    "CTVA": {"company": "Corteva Inc", "exchange": "NYSE"},
    "CUBE": {"company": "Cubesmart", "exchange": "NYSE"},
    "CUZ": {"company": "Cousins Properties Inc", "exchange": "NYSE"},
    "CVNA": {"company": "Carvana Company", "exchange": "NYSE"},
    "CVS": {"company": "CVS Corp", "exchange": "NYSE"},
    "CVX": {"company": "Chevron Corp", "exchange": "NYSE"},
    "CW": {"company": "Curtiss-Wright Corp", "exchange": "NYSE"},
    "CWE.A": {"company": "Clearway Energy Inc [Cwen.A]", "exchange": "NYSE"},
    "CWEN": {"company": "Clearway Energy Inc Cl C", "exchange": "NYSE"},
    "CXT": {"company": "Crane Nxt CO", "exchange": "NYSE"},
    "CZR": {"company": "Caesars Entertainment Inc", "exchange": "NASDAQ"},
    "D": {"company": "Dominion Energy Inc", "exchange": "NYSE"},
    "DAL": {"company": "Delta Air Lines Inc", "exchange": "NYSE"},
    "DAR": {"company": "Darling International Inc", "exchange": "NYSE"},
    "DASH": {"company": "Doordash Inc", "exchange": "NASDAQ"},
    "DAY": {"company": "Dayforce Inc", "exchange": "NYSE"},
    "DBX": {"company": "Dropbox Inc", "exchange": "NASDAQ"},
    "DCI": {"company": "Donaldson Company", "exchange": "NYSE"},
    "DD": {"company": "Dupont Denemours Inc", "exchange": "NYSE"},
    "DDOG": {"company": "Datadog Inc", "exchange": "NASDAQ"},
    "DDS": {"company": "Dillard's", "exchange": "NYSE"},
    "DE": {"company": "Deere & Company", "exchange": "NYSE"},
    "DECK": {"company": "Deckers Outdoor Corp", "exchange": "NYSE"},
    "DELL": {"company": "Dell Technologies Inc", "exchange": "NYSE"},
    "DG": {"company": "Dollar General Corp", "exchange": "NYSE"},
    "DGX": {"company": "Quest Diagnostics Inc", "exchange": "NYSE"},
    "DHI": {"company": "D.R. Horton", "exchange": "NYSE"},
    "DHR": {"company": "Danaher Corp", "exchange": "NYSE"},
    "DINO": {"company": "HF Sinclair Corp", "exchange": "NYSE"},
    "DIS": {"company": "Walt Disney Company", "exchange": "NYSE"},
    "DJT": {"company": "Trump Media & Technology Group Corp", "exchange": "NASDAQ"},
    "DKNG": {"company": "Draftkings Inc", "exchange": "NASDAQ"},
    "DKS": {"company": "Dick's Sporting Goods Inc", "exchange": "NYSE"},
    "DLB": {"company": "Dolby Laboratories", "exchange": "NYSE"},
    "DLR": {"company": "Digital Realty Trust", "exchange": "NYSE"},
    "DLTR": {"company": "Dollar Tree Inc", "exchange": "NASDAQ"},
    "DNB": {"company": "Dun & Bradstreet Holdings Inc", "exchange": "NYSE"},
    "DOC": {"company": "Healthpeak Properties Inc", "exchange": "NYSE"},
    "DOCS": {"company": "Doximity Inc", "exchange": "NYSE"},
    "DOCU": {"company": "Docusign Inc", "exchange": "NASDAQ"},
    "DOV": {"company": "Dover Corp", "exchange": "NYSE"},
    "DOW": {"company": "Dow Inc", "exchange": "NYSE"},
    "DOX": {"company": "Amdocs Ltd Ord", "exchange": "NASDAQ"},
    "DPZ": {"company": "Domino's Pizza Inc", "exchange": "NASDAQ"},
    "DRI": {"company": "Darden Restaurants", "exchange": "NYSE"},
    "DRS": {"company": "Leonardo Drs Inc", "exchange": "NASDAQ"},
    "DT": {"company": "Dynatrace Inc", "exchange": "NYSE"},
    "DTE": {"company": "Dte Energy Company", "exchange": "NYSE"},
    "DTM": {"company": "Dt Midstream Inc", "exchange": "NYSE"},
    "DUK": {"company": "Duke Energy Corp", "exchange": "NYSE"},
    "DUOL": {"company": "Duolingo Inc", "exchange": "NASDAQ"},
    "DV": {"company": "Doubleverify Holdings Inc", "exchange": "NYSE"},
    "DVA": {"company": "Davita Healthcare Partners Inc", "exchange": "NYSE"},
    "DVN": {"company": "Devon Energy Corp", "exchange": "NYSE"},
    "DXC": {"company": "Dxc Technology Company", "exchange": "NYSE"},
    "DXCM": {"company": "Dexcom Inc", "exchange": "NASDAQ"},
    "EA": {"company": "Electronic Arts Inc", "exchange": "NASDAQ"},
    "EBAY": {"company": "Ebay Inc", "exchange": "NASDAQ"},
    "ECG": {"company": "Everus Construction Group Inc", "exchange": "NYSE"},
    "ECL": {"company": "Ecolab Inc", "exchange": "NYSE"},
    "ED": {"company": "Consolidated Edison Company", "exchange": "NYSE"},
    "EEFT": {"company": "Euronet Worldwide", "exchange": "NASDAQ"},
    "EFX": {"company": "Equifax Inc", "exchange": "NYSE"},
    "EG": {"company": "Everest Re Group", "exchange": "NYSE"},
    "EGP": {"company": "Eastgroup Properties", "exchange": "NYSE"},
    "EHC": {"company": "Encompass Health Corp", "exchange": "NYSE"},
    "EIX": {"company": "Edison International", "exchange": "NYSE"},
    "EL": {"company": "Estee Lauder Companies", "exchange": "NYSE"},
    "ELAN": {"company": "Elanco Animal Health Inc", "exchange": "NYSE"},
    "ELF": {"company": "E.L.F. Beauty Inc", "exchange": "NYSE"},
    "ELS": {"company": "Equity Lifestyle Properties", "exchange": "NYSE"},
    "ELV": {"company": "Elevance Health Inc", "exchange": "NYSE"},
    "EME": {"company": "Emcor Group", "exchange": "NYSE"},
    "EMN": {"company": "Eastman Chemical Company", "exchange": "NYSE"},
    "EMR": {"company": "Emerson Electric Company", "exchange": "NYSE"},
    "ENPH": {"company": "Enphase Energy Inc", "exchange": "NASDAQ"},
    "ENTG": {"company": "Entegris Inc", "exchange": "NASDAQ"},
    "EOG": {"company": "Eog Resources", "exchange": "NYSE"},
    "EPAM": {"company": "Epam Systems Inc", "exchange": "NYSE"},
    "EPR": {"company": "Entertainment Properties Trust", "exchange": "NYSE"},
    "EQH": {"company": "Axa Equitable Holdings Inc", "exchange": "NYSE"},
    "EQIX": {"company": "Equinix Inc", "exchange": "NASDAQ"},
    "EQR": {"company": "Equity Residential", "exchange": "NYSE"},
    "EQT": {"company": "Eqt Corp", "exchange": "NYSE"},
    "ES": {"company": "Eversource Energy", "exchange": "NYSE"},
    "ESAB": {"company": "Esab Corp", "exchange": "NYSE"},
    "ESI": {"company": "Element Solutions Inc", "exchange": "NYSE"},
    "ESS": {"company": "Essex Property Trust", "exchange": "NYSE"},
    "ESTC": {"company": "Elastic N.V.", "exchange": "NYSE"},
    "ETN": {"company": "Eaton Corp", "exchange": "NYSE"},
    "ETR": {"company": "Entergy Corp", "exchange": "NYSE"},
    "ETSY": {"company": "Etsy Inc", "exchange": "NASDAQ"},
    "EVR": {"company": "Evercore Partners Inc", "exchange": "NYSE"},
    "EVRG": {"company": "Evergy Inc", "exchange": "NASDAQ"},
    "EW": {"company": "Edwards Lifesciences Corp", "exchange": "NYSE"},
    "EWBC": {"company": "East West Bancorp", "exchange": "NASDAQ"},
    "EXAS": {"company": "Exact Sciences Cor", "exchange": "NASDAQ"},
    "EXC": {"company": "Exelon Corp", "exchange": "NASDAQ"},
    "EXE": {"company": "Expand Energy Corporation", "exchange": "NASDAQ"},
    "EXEL": {"company": "Exelixis Inc", "exchange": "NASDAQ"},
    "EXLS": {"company": "Exlservice Holdings", "exchange": "NASDAQ"},
    "EXP": {"company": "Eagle Materials Inc", "exchange": "NYSE"},
    "EXPD": {"company": "Expeditors Intl", "exchange": "NYSE"},
    "EXPE": {"company": "Expedia Group Inc", "exchange": "NASDAQ"},
    "EXR": {"company": "Extra Space Storage Inc", "exchange": "NYSE"},
    "F": {"company": "Ford Motor Company", "exchange": "NYSE"},
    "FAF": {"company": "First American Corp", "exchange": "NYSE"},
    "FANG": {"company": "Diamondback Energy", "exchange": "NASDAQ"},
    "FAST": {"company": "Fastenal Company", "exchange": "NASDAQ"},
    "FBIN": {"company": "Fortune Brands Innovations Inc", "exchange": "NYSE"},
    "FCN": {"company": "Fti Consulting", "exchange": "NYSE"},
    "FCNCA": {"company": "First Citizens Bancs", "exchange": "NASDAQ"},
    "FCX": {"company": "Freeport-Mcmoran Inc", "exchange": "NYSE"},
    "FDS": {"company": "Factset Research Systems Inc", "exchange": "NYSE"},
    "FDX": {"company": "Fedex Corp", "exchange": "NYSE"},
    "FE": {"company": "Firstenergy Corp", "exchange": "NYSE"},
    "FERG": {"company": "Ferguson Enterprises Inc", "exchange": "NYSE"},
    "FFIV": {"company": "F5 Inc", "exchange": "NASDAQ"},
    "FHB": {"company": "First Hawaiian Inc", "exchange": "NASDAQ"},
    "FHN": {"company": "First Horizon Corp", "exchange": "NYSE"},
    "FI": {"company": "Fiserv Inc", "exchange": "NYSE"},
    "FICO": {"company": "Fair Isaac and Company", "exchange": "NYSE"},
    "FIS": {"company": "Fidelity National Information Services", "exchange": "NYSE"},
    "FITB": {"company": "Fifth Third Bancorp", "exchange": "NASDAQ"},
    "FIVE": {"company": "Five Below Inc", "exchange": "NASDAQ"},
    "FIX": {"company": "Comfort Systems USA", "exchange": "NYSE"},
    "FLEX": {"company": "Flextronics Intl Ltd", "exchange": "NASDAQ"},
    "FLO": {"company": "Flowers Foods", "exchange": "NYSE"},
    "FLS": {"company": "Flowserve Corp", "exchange": "NYSE"},
    "FLUT": {"company": "Flutter Entertainment Plc", "exchange": "NYSE"},
    "FMC": {"company": "FMC Corp", "exchange": "NYSE"},
    "FNB": {"company": "F.N.B. Corp", "exchange": "NYSE"},
    "FND": {"company": "Floor & Decor Holdings Inc", "exchange": "NYSE"},
    "FNF": {"company": "Fidelity National Financial", "exchange": "NYSE"},
    "FOUR": {"company": "Shift4 Payments Inc", "exchange": "NYSE"},
    "FOX": {"company": "Fox Corp Cl B", "exchange": "NASDAQ"},
    "FOXA": {"company": "Fox Corp", "exchange": "NASDAQ"},
    "FR": {"company": "First Industrial Realty Trust", "exchange": "NYSE"},
    "FRHC": {"company": "Freedom Holding Corp", "exchange": "NASDAQ"},
    "FRPT": {"company": "Freshpet Inc CS", "exchange": "NASDAQ"},
    "FRT": {"company": "Federal Realty Investment Trust", "exchange": "NYSE"},
    "FSLR": {"company": "First Solar Inc", "exchange": "NASDAQ"},
    "FTAI": {"company": "Ftai Aviation Ltd", "exchange": "NASDAQ"},
    "FTI": {"company": "Technipfmc Plc", "exchange": "NYSE"},
    "FTNT": {"company": "Fortinet Inc", "exchange": "NASDAQ"},
    "FTV": {"company": "Fortive Corp", "exchange": "NYSE"},
    "FWONA": {"company": "Liberty Media Formula One Sr A", "exchange": "NASDAQ"},
    "FWONK": {"company": "Liberty Media Formula One Sr C", "exchange": "NASDAQ"},
    "FYBR": {"company": "Frontier Communications Parent Inc", "exchange": "NASDAQ"},
    "G": {"company": "Genpact Ltd", "exchange": "NYSE"},
    "GAP": {"company": "Gap Inc", "exchange": "NYSE"},
    "GD": {"company": "General Dynamics Corp", "exchange": "NYSE"},
    "GDDY": {"company": "Godaddy Inc", "exchange": "NYSE"},
    "GE": {"company": "GE Aerospace", "exchange": "NYSE"},
    "GEHC": {"company": "GE Healthcare Technologies Inc", "exchange": "NASDAQ"},
    "GEN": {"company": "Gen Digital Inc", "exchange": "NASDAQ"},
    "GEV": {"company": "GE Vernova Inc", "exchange": "NYSE"},
    "GFS": {"company": "Globalfoundries Inc", "exchange": "NASDAQ"},
    "GGG": {"company": "Graco Inc", "exchange": "NYSE"},
    "GILD": {"company": "Gilead Sciences Inc", "exchange": "NASDAQ"},
    "GIS": {"company": "General Mills", "exchange": "NYSE"},
    "GL": {"company": "Globe Life Inc", "exchange": "NYSE"},
    "GLIBA": {"company": "Gci Liberty Inc Series A Gci", "exchange": "NASDAQ"},
    "GLIBK": {"company": "Gci Liberty Inc Series C Gci", "exchange": "NASDAQ"},
    "GLOB": {"company": "Globant S.A.", "exchange": "NYSE"},
    "GLPI": {"company": "Gaming & Leisure", "exchange": "NASDAQ"},
    "GLW": {"company": "Corning Inc", "exchange": "NYSE"},
    "GM": {"company": "General Motors Company", "exchange": "NYSE"},
    "GME": {"company": "Gamestop Corp", "exchange": "NYSE"},
    "GMED": {"company": "Globus Medical Inc", "exchange": "NYSE"},
    "GNRC": {"company": "Generac Holdings Inc", "exchange": "NYSE"},
    "GNTX": {"company": "Gentex Corp", "exchange": "NASDAQ"},
    "GOOG": {"company": "Alphabet Cl C", "exchange": "NASDAQ"},
    "GOOGL": {"company": "Alphabet", "exchange": "NASDAQ"},
    "GPC": {"company": "Genuine Parts Company", "exchange": "NYSE"},
    "GPK": {"company": "Graphic Packaging Holding Company", "exchange": "NYSE"},
    "GPN": {"company": "Global Payments Inc", "exchange": "NYSE"},
    "GRMN": {"company": "Garmin Ltd", "exchange": "NYSE"},
    "GS": {"company": "Goldman Sachs Group", "exchange": "NYSE"},
    "GTES": {"company": "Gates Industrial Corp Plc", "exchange": "NYSE"},
    "GTLB": {"company": "Gitlab Inc", "exchange": "NASDAQ"},
    "GTM": {"company": "Zoominfo Technologies Inc", "exchange": "NASDAQ"},
    "GWRE": {"company": "Guidewire Software Inc", "exchange": "NYSE"},
    "GWW": {"company": "W.W. Grainger", "exchange": "NYSE"},
    "GXO": {"company": "Gxo Logistics Inc", "exchange": "NYSE"},
    "H": {"company": "Hyatt Hotels Corp", "exchange": "NYSE"},
    "HAL": {"company": "Halliburton Company", "exchange": "NYSE"},
    "HALO": {"company": "Halozyme Therapeutic", "exchange": "NASDAQ"},
    "HAS": {"company": "Hasbro Inc", "exchange": "NASDAQ"},
    "HAYW": {"company": "Hayward Holdings Inc", "exchange": "NYSE"},
    "HBAN": {"company": "Huntington Bancshares Inc", "exchange": "NASDAQ"},
    "HCA": {"company": "Hca Holdings Inc", "exchange": "NYSE"},
    "HD": {"company": "Home Depot", "exchange": "NYSE"},
    "HEI": {"company": "Heico Corp", "exchange": "NYSE"},
    "HEI.A": {"company": "Heico Corp", "exchange": "NYSE"},
    "HHH": {"company": "Howard Hughes Holdings Inc", "exchange": "NYSE"},
    "HIG": {"company": "The Hartford Insurance Group Inc", "exchange": "NYSE"},
    "HII": {"company": "Huntington Ingalls Industries", "exchange": "NYSE"},
    "HIW": {"company": "Highwoods Properties", "exchange": "NYSE"},
    "HLI": {"company": "Houlihan Lokey", "exchange": "NYSE"},
    "HLNE": {"company": "Hamilton Lane Inc", "exchange": "NASDAQ"},
    "HLT": {"company": "Hilton Inc", "exchange": "NYSE"},
    "HOG": {"company": "Harley-Davidson Inc", "exchange": "NYSE"},
    "HOLX": {"company": "Hologic Inc", "exchange": "NASDAQ"},
    "HON": {"company": "Honeywell International Inc", "exchange": "NASDAQ"},
    "HOOD": {"company": "Robinhood Markets Inc", "exchange": "NASDAQ"},
    "HPE": {"company": "Hewlett Packard Enterprise Comp", "exchange": "NYSE"},
    "HPQ": {"company": "HP Inc", "exchange": "NYSE"},
    "HR": {"company": "Healthcare Realty Trust Inc.", "exchange": "NYSE"},
    "HRB": {"company": "H&R Block", "exchange": "NYSE"},
    "HRL": {"company": "Hormel Foods Corp", "exchange": "NYSE"},
    "HSIC": {"company": "Henry Schein Inc", "exchange": "NASDAQ"},
    "HST": {"company": "Host Marriott Financial Trust", "exchange": "NASDAQ"},
    "HSY": {"company": "Hershey Foods Corp", "exchange": "NYSE"},
    "HUBB": {"company": "Hubbell Inc B", "exchange": "NYSE"},
    "HUBS": {"company": "Hubspot Inc", "exchange": "NYSE"},
    "HUM": {"company": "Humana Inc", "exchange": "NYSE"},
    "HUN": {"company": "Huntsman Corp", "exchange": "NYSE"},
    "HWM": {"company": "Howmet Aerospace Inc", "exchange": "NYSE"},
    "HXL": {"company": "Hexcel Corp", "exchange": "NYSE"},
    "IAC": {"company": "Iac Inc", "exchange": "NASDAQ"},
    "IBKR": {"company": "Interactive Brokers", "exchange": "NASDAQ"},
    "IBM": {"company": "Intl Business Machines", "exchange": "NYSE"},
    "ICE": {"company": "Intercontinental Exchange", "exchange": "NYSE"},
    "IDA": {"company": "Idacorp Inc", "exchange": "NYSE"},
    "IDXX": {"company": "Idexx Laboratories", "exchange": "NASDAQ"},
    "IEX": {"company": "Idex Corp", "exchange": "NYSE"},
    "IFF": {"company": "International Flavors & Fragrances", "exchange": "NYSE"},
    "ILMN": {"company": "Illumina Inc", "exchange": "NASDAQ"},
    "INCY": {"company": "Incyte Corp", "exchange": "NASDAQ"},
    "INFA": {"company": "Informatica Inc", "exchange": "NYSE"},
    "INGM": {"company": "Ingram Micro Holding Corp", "exchange": "NYSE"},
    "INGR": {"company": "Ingredion Inc", "exchange": "NYSE"},
    "INSM": {"company": "Insmed Inc", "exchange": "NASDAQ"},
    "INSP": {"company": "Inspire Medical Systems Inc", "exchange": "NYSE"},
    "INTC": {"company": "Intel Corp", "exchange": "NASDAQ"},
    "INTU": {"company": "Intuit Inc", "exchange": "NASDAQ"},
    "INVH": {"company": "Invitation Homes Inc", "exchange": "NYSE"},
    "IONS": {"company": "Ionis Pharmaceuticals", "exchange": "NASDAQ"},
    "IOT": {"company": "Samsara Inc", "exchange": "NYSE"},
    "IP": {"company": "International Paper Company", "exchange": "NYSE"},
    "IPG": {"company": "Interpublic Group of Companies", "exchange": "NYSE"},
    "IPGP": {"company": "Ipg Photonics Corp", "exchange": "NASDAQ"},
    "IQV": {"company": "Iqvia Holdings Inc", "exchange": "NYSE"},
    "IR": {"company": "Ingersoll Rand Inc", "exchange": "NYSE"},
    "IRDM": {"company": "Iridium Comm Inc", "exchange": "NASDAQ"},
    "IRM": {"company": "Iron Mountain Inc", "exchange": "NYSE"},
    "ISRG": {"company": "Intuitive Surg Inc", "exchange": "NASDAQ"},
    "IT": {"company": "Gartner Inc", "exchange": "NYSE"},
    "ITT": {"company": "ITT Inc", "exchange": "NYSE"},
    "ITW": {"company": "Illinois Tool Works Inc", "exchange": "NYSE"},
    "IVZ": {"company": "Invesco Plc", "exchange": "NYSE"},
    "J": {"company": "Jacobs Engineering Group Inc", "exchange": "NYSE"},
    "JAZZ": {"company": "Jazz Pharma Plc", "exchange": "NASDAQ"},
    "JBHT": {"company": "J B Hunt Transport", "exchange": "NASDAQ"},
    "JBL": {"company": "Jabil Circuit", "exchange": "NYSE"},
    "JCI": {"company": "Johnson Controls Intl", "exchange": "NYSE"},
    "JEF": {"company": "Jefferies Financial Group Inc", "exchange": "NYSE"},
    "JHG": {"company": "Janus Henderson Group Plc", "exchange": "NYSE"},
    "JHX": {"company": "James Hardie Industries Se ADR", "exchange": "NYSE"},
    "JKHY": {"company": "Jack Henry & Assoc", "exchange": "NASDAQ"},
    "JLL": {"company": "Jones Lang Lasalle Inc", "exchange": "NYSE"},
    "JNJ": {"company": "Johnson & Johnson", "exchange": "NYSE"},
    "JPM": {"company": "JP Morgan Chase & Company", "exchange": "NYSE"},
    "K": {"company": "Kellanova", "exchange": "NYSE"},
    "KBR": {"company": "KBR Inc", "exchange": "NYSE"},
    "KD": {"company": "Kyndryl Hldgs Inc", "exchange": "NYSE"},
    "KDP": {"company": "Keurig Dr Pepper Inc", "exchange": "NASDAQ"},
    "KEX": {"company": "Kirby Corp", "exchange": "NYSE"},
    "KEY": {"company": "Keycorp", "exchange": "NYSE"},
    "KEYS": {"company": "Keysight Technologies Inc", "exchange": "NYSE"},
    "KHC": {"company": "Kraft Heinz Company", "exchange": "NASDAQ"},
    "KIM": {"company": "Kimco Realty Corp", "exchange": "NYSE"},
    "KKR": {"company": "KKR & Company LP", "exchange": "NYSE"},
    "KLAC": {"company": "K L A-Tencor Corp", "exchange": "NASDAQ"},
    "KMB": {"company": "Kimberly-Clark Corp", "exchange": "NASDAQ"},
    "KMI": {"company": "Kinder Morgan Inc", "exchange": "NYSE"},
    "KMPR": {"company": "Kemper Corp", "exchange": "NYSE"},
    "KMX": {"company": "Carmax Inc", "exchange": "NYSE"},
    "KNSL": {"company": "Kinsale Capital Group Inc", "exchange": "NYSE"},
    "KNX": {"company": "Knight-Swift Transporation Inc", "exchange": "NYSE"},
    "KO": {"company": "Coca-Cola Company", "exchange": "NYSE"},
    "KR": {"company": "Kroger Company", "exchange": "NYSE"},
    "KRC": {"company": "Kilroy Realty Corp", "exchange": "NYSE"},
    "KRMN": {"company": "Karman Holdings Inc", "exchange": "NYSE"},
    "KVUE": {"company": "Kenvue Inc", "exchange": "NYSE"},
    "L": {"company": "Loews Corp", "exchange": "NYSE"},
    "LAD": {"company": "Lithia Motors", "exchange": "NYSE"},
    "LAMR": {"company": "Lamar Advertis A", "exchange": "NASDAQ"},
    "LAZ": {"company": "Lazard Inc", "exchange": "NYSE"},
    "LBRDA": {"company": "Liberty Broadband Corp Sr A", "exchange": "NASDAQ"},
    "LBRDK": {"company": "Liberty Broadband Corp Sr C", "exchange": "NASDAQ"},
    "LBTYA": {"company": "Liberty Global Ltd Ord A", "exchange": "NASDAQ"},
    "LBTYK": {"company": "Liberty Global Ltd Ord C", "exchange": "NASDAQ"},
    "LCID": {"company": "Lucid Group Inc", "exchange": "NASDAQ"},
    "LDOS": {"company": "Leidos Holdings Inc", "exchange": "NYSE"},
    "LEA": {"company": "Lear Corp", "exchange": "NYSE"},
    "LECO": {"company": "Lincoln Elec Holdings", "exchange": "NASDAQ"},
    "LEN": {"company": "Lennar Corp", "exchange": "NYSE"},
    "LEN.B": {"company": "Lennar Corp Cl B", "exchange": "NYSE"},
    "LFUS": {"company": "Littelfuse Inc", "exchange": "NASDAQ"},
    "LH": {"company": "Laboratory Corp of America Holdings", "exchange": "NYSE"},
    "LHX": {"company": "L3Harris Technologies Inc", "exchange": "NYSE"},
    "LII": {"company": "Lennox International", "exchange": "NYSE"},
    "LIN": {"company": "Linde Plc", "exchange": "NASDAQ"},
    "LINE": {"company": "Lineage Inc", "exchange": "NASDAQ"},
    "LITE": {"company": "Lumentum Holdings", "exchange": "NASDAQ"},
    "LKQ": {"company": "LKQ Corp", "exchange": "NASDAQ"},
    "LLY": {"company": "Eli Lilly and Company", "exchange": "NYSE"},
    "LLYVA": {"company": "Liberty Live Series A", "exchange": "NASDAQ"},
    "LLYVK": {"company": "Liberty Live Series C", "exchange": "NASDAQ"},
    "LMT": {"company": "Lockheed Martin Corp", "exchange": "NYSE"},
    "LNC": {"company": "Lincoln National Corp", "exchange": "NYSE"},
    "LNG": {"company": "Cheniere Energy", "exchange": "NYSE"},
    "LNT": {"company": "Alliant Energy Corp", "exchange": "NASDAQ"},
    "LNW": {"company": "Light & Wonder Inc", "exchange": "NASDAQ"},
    "LOAR": {"company": "Loar Holdings Inc", "exchange": "NYSE"},
    "LOPE": {"company": "Grand Canyon Educati", "exchange": "NASDAQ"},
    "LOW": {"company": "Lowe's Companies", "exchange": "NYSE"},
    "LPLA": {"company": "Lpl Financial Holdings", "exchange": "NASDAQ"},
    "LPX": {"company": "Louisiana-Pacific Corp", "exchange": "NYSE"},
    "LRCX": {"company": "Lam Research Corp", "exchange": "NASDAQ"},
    "LSCC": {"company": "Lattice Semicond", "exchange": "NASDAQ"},
    "LSTR": {"company": "Landstar System", "exchange": "NASDAQ"},
    "LULU": {"company": "Lululemon Athletica", "exchange": "NASDAQ"},
    "LUV": {"company": "Southwest Airlines Company", "exchange": "NYSE"},
    "LVS": {"company": "Las Vegas Sands", "exchange": "NYSE"},
    "LW": {"company": "Lamb Weston Holdings Inc", "exchange": "NYSE"},
    "LYB": {"company": "Lyondellbasell Industries NV", "exchange": "NYSE"},
    "LYFT": {"company": "Lyft Inc", "exchange": "NASDAQ"},
    "LYV": {"company": "Live Nation Entertainment", "exchange": "NYSE"},
    "M": {"company": "Macy's Inc", "exchange": "NYSE"},
    "MA": {"company": "Mastercard Inc", "exchange": "NYSE"},
    "MAA": {"company": "Mid-America Apartment Communities", "exchange": "NYSE"},
    "MAN": {"company": "Manpower Inc", "exchange": "NYSE"},
    "MANH": {"company": "Manhattan Assoc", "exchange": "NASDAQ"},
    "MAR": {"company": "Marriot Int", "exchange": "NASDAQ"},
    "MAS": {"company": "Masco Corp", "exchange": "NYSE"},
    "MASI": {"company": "Masimo Corp", "exchange": "NASDAQ"},
    "MAT": {"company": "Mattel Inc", "exchange": "NASDAQ"},
    "MCD": {"company": "McDonald's Corp", "exchange": "NYSE"},
    "MCHP": {"company": "Microchip Technology", "exchange": "NASDAQ"},
    "MCK": {"company": "Mckesson Corp", "exchange": "NYSE"},
    "MCO": {"company": "Moody's Corp", "exchange": "NYSE"},
    "MDB": {"company": "Mongodb Inc", "exchange": "NASDAQ"},
    "MDLZ": {"company": "Mondelez Intl Inc", "exchange": "NASDAQ"},
    "MDT": {"company": "Medtronic Inc", "exchange": "NYSE"},
    "MDU": {"company": "Mdu Res Group Inc", "exchange": "NYSE"},
    "MEDP": {"company": "Medpace Holdings Inc", "exchange": "NASDAQ"},
    "MET": {"company": "Metlife Inc", "exchange": "NYSE"},
    "META": {"company": "Meta Platforms Inc", "exchange": "NASDAQ"},
    "MGM": {"company": "MGM Resorts International", "exchange": "NYSE"},
    "MHK": {"company": "Mohawk Industries", "exchange": "NYSE"},
    "MIDD": {"company": "Middleby Corp", "exchange": "NASDAQ"},
    "MKC": {"company": "Mccormick & Company", "exchange": "NYSE"},
    "MKL": {"company": "Markel Corp", "exchange": "NYSE"},
    "MKSI": {"company": "Mks Inc", "exchange": "NASDAQ"},
    "MKTX": {"company": "Marketaxess Holdings", "exchange": "NASDAQ"},
    "MLI": {"company": "Mueller Industries", "exchange": "NYSE"},
    "MLM": {"company": "Martin Marietta Materials", "exchange": "NYSE"},
    "MMC": {"company": "Marsh & Mclennan Companies", "exchange": "NYSE"},
    "MMM": {"company": "3M Company", "exchange": "NYSE"},
    "MNST": {"company": "Monster Beverage Corp", "exchange": "NASDAQ"},
    "MO": {"company": "Altria Group", "exchange": "NYSE"},
    "MOH": {"company": "Molina Healthcare Inc", "exchange": "NYSE"},
    "MORN": {"company": "Morningstar Inc", "exchange": "NASDAQ"},
    "MOS": {"company": "Mosaic Company", "exchange": "NYSE"},
    "MP": {"company": "MP Materials Corp", "exchange": "NYSE"},
    "MPC": {"company": "Marathon Petroleum Corp", "exchange": "NYSE"},
    "MPW": {"company": "Medical Properties Trust", "exchange": "NYSE"},
    "MPWR": {"company": "Monolithic Power Sys", "exchange": "NASDAQ"},
    "MRK": {"company": "Merck & Company", "exchange": "NYSE"},
    "MRNA": {"company": "Moderna Inc", "exchange": "NASDAQ"},
    "MRP": {"company": "Millrose Properties Inc", "exchange": "NYSE"},
    "MRVL": {"company": "Marvell Technology Inc", "exchange": "NASDAQ"},
    "MS": {"company": "Morgan Stanley", "exchange": "NYSE"},
    "MSA": {"company": "Msa Safety Inc", "exchange": "NYSE"},
    "MSCI": {"company": "MSCI Inc", "exchange": "NYSE"},
    "MSFT": {"company": "Microsoft Corp", "exchange": "NASDAQ"},
    "MSGS": {"company": "Madison Square Garden Sports Corp", "exchange": "NYSE"},
    "MSI": {"company": "Motorola Solutions", "exchange": "NYSE"},
    "MSM": {"company": "Msc Industrial Direct Company", "exchange": "NYSE"},
    "MSTR": {"company": "Strategy Inc", "exchange": "NASDAQ"},
    "MTB": {"company": "M&T Bank Corp", "exchange": "NYSE"},
    "MTCH": {"company": "Match Group Inc", "exchange": "NASDAQ"},
    "MTD": {"company": "Mettler-Toledo International", "exchange": "NYSE"},
    "MTDR": {"company": "Matador Resources Company", "exchange": "NYSE"},
    "MTG": {"company": "Mgic Investment Corp", "exchange": "NYSE"},
    "MTN": {"company": "Vail Resorts", "exchange": "NYSE"},
    "MTSI": {"company": "Macom Technology S", "exchange": "NASDAQ"},
    "MTZ": {"company": "Mastec Inc", "exchange": "NYSE"},
    "MU": {"company": "Micron Technology", "exchange": "NASDAQ"},
    "MUSA": {"company": "Murphy USA Inc", "exchange": "NYSE"},
    "NBIX": {"company": "Neurocrine Bioscienc", "exchange": "NASDAQ"},
    "NCLH": {"company": "Norwegian Cruise Ord", "exchange": "NYSE"},
    "NCNO": {"company": "Ncino Inc", "exchange": "NASDAQ"},
    "NDAQ": {"company": "Nasdaq Inc", "exchange": "NASDAQ"},
    "NDSN": {"company": "Nordson Corp", "exchange": "NASDAQ"},
    "NEE": {"company": "Nextera Energy", "exchange": "NYSE"},
    "NEM": {"company": "Newmont Mining Corp", "exchange": "NYSE"},
    "NET": {"company": "Cloudflare Inc", "exchange": "NYSE"},
    "NEU": {"company": "Newmarket Corp", "exchange": "NYSE"},
    "NFG": {"company": "National Fuel Gas Company", "exchange": "NYSE"},
    "NFLX": {"company": "Netflix Inc", "exchange": "NASDAQ"},
    "NI": {"company": "NiSource Inc", "exchange": "NYSE"},
    "NKE": {"company": "Nike Inc", "exchange": "NYSE"},
    "NLY": {"company": "Annaly Capital Management Inc", "exchange": "NYSE"},
    "NNN": {"company": "NNN REIT Inc", "exchange": "NYSE"},
    "NOC": {"company": "Northrop Grumman Corp", "exchange": "NYSE"},
    "NOV": {"company": "Nov Inc", "exchange": "NYSE"},
    "NOW": {"company": "Servicenow Inc", "exchange": "NYSE"},
    "NRG": {"company": "NRG Energy", "exchange": "NYSE"},
    "NSA": {"company": "National Storage Affiliates Tru", "exchange": "NYSE"},
    "NSC": {"company": "Norfolk Southern Corp", "exchange": "NYSE"},
    "NTAP": {"company": "Netapp Inc", "exchange": "NASDAQ"},
    "NTNX": {"company": "Nutanix Inc", "exchange": "NASDAQ"},
    "NTRA": {"company": "Natera Inc", "exchange": "NASDAQ"},
    "NTRS": {"company": "Northern Trust Corp", "exchange": "NASDAQ"},
    "NU": {"company": "Nu Holdings Ltd", "exchange": "NYSE"},
    "NUE": {"company": "Nucor Corp", "exchange": "NYSE"},
    "NVDA": {"company": "Nvidia Corp", "exchange": "NASDAQ"},
    "NVR": {"company": "NVR Inc", "exchange": "NYSE"},
    "NVST": {"company": "Envista Holdings Corp", "exchange": "NYSE"},
    "NVT": {"company": "Nvent Electric Plc", "exchange": "NYSE"},
    "NWL": {"company": "Newell Rubbermaid Inc", "exchange": "NASDAQ"},
    "NWS": {"company": "News Corp Cl B", "exchange": "NASDAQ"},
    "NWSA": {"company": "News Corp", "exchange": "NASDAQ"},
    "NXST": {"company": "Nexstar Media Group Inc", "exchange": "NASDAQ"},
    "NYT": {"company": "New York Times Company", "exchange": "NYSE"},
    "O": {"company": "Realty Income Corp", "exchange": "NYSE"},
    "OC": {"company": "Owens Corning Inc", "exchange": "NYSE"},
    "ODFL": {"company": "Old Dominion Freight Line Inc", "exchange": "NASDAQ"},
    "OGE": {"company": "Oge Energy Corp", "exchange": "NYSE"},
    "OGN": {"company": "Organon & Co.", "exchange": "NYSE"},
    "OHI": {"company": "Omega Healthcare Investors", "exchange": "NYSE"},
    "OKE": {"company": "Oneok Inc", "exchange": "NYSE"},
    "OKTA": {"company": "Okta Inc", "exchange": "NASDAQ"},
    "OLED": {"company": "Universal Display", "exchange": "NASDAQ"},
    "OLLI": {"company": "Ollies Bargain CS", "exchange": "NASDAQ"},
    "OLN": {"company": "Olin Corp", "exchange": "NYSE"},
    "OMC": {"company": "Omnicom Group Inc", "exchange": "NYSE"},
    "OMF": {"company": "Onemain Holdings Inc", "exchange": "NYSE"},
    "ON": {"company": "On Semiconductor", "exchange": "NASDAQ"},
    "ONON": {"company": "On Holding Ag", "exchange": "NYSE"},
    "ONTO": {"company": "Onto Innovation Inc", "exchange": "NYSE"},
    "ORCL": {"company": "Oracle Corp", "exchange": "NYSE"},
    "ORI": {"company": "Old Republic International Corp", "exchange": "NYSE"},
    "ORLY": {"company": "O'Reilly Automotive", "exchange": "NASDAQ"},
    "OSK": {"company": "Oshkosh Truck Corp", "exchange": "NYSE"},
    "OTIS": {"company": "Otis Worldwide Corp", "exchange": "NYSE"},
    "OVV": {"company": "Ovintiv Inc", "exchange": "NYSE"},
    "OWL": {"company": "Blue Owl Capital Inc", "exchange": "NYSE"},
    "OXY": {"company": "Occidental Petroleum Corp", "exchange": "NYSE"},
    "OZK": {"company": "Bank Ozk", "exchange": "NASDAQ"},
    "PAG": {"company": "Penske Automotive Group", "exchange": "NYSE"},
    "PANW": {"company": "Palo Alto Networks Inc", "exchange": "NASDAQ"},
    "PATH": {"company": "Uipath Inc", "exchange": "NYSE"},
    "PAYC": {"company": "Paycom Software Inc", "exchange": "NYSE"},
    "PAYX": {"company": "Paychex Inc", "exchange": "NASDAQ"},
    "PB": {"company": "Prosperity Bancshares", "exchange": "NYSE"},
    "PCAR": {"company": "Paccar Inc", "exchange": "NASDAQ"},
    "PCG": {"company": "Pacific Gas & Electric Company", "exchange": "NYSE"},
    "PCOR": {"company": "Procore Technologies Inc", "exchange": "NYSE"},
    "PCTY": {"company": "Paylocity Holdings Corp", "exchange": "NASDAQ"},
    "PEG": {"company": "Public Service Enterprise Group Inc", "exchange": "NYSE"},
    "PEGA": {"company": "Pegasystems Inc", "exchange": "NASDAQ"},
    "PEN": {"company": "Penumbra Inc", "exchange": "NYSE"},
    "PENN": {"company": "Penn Entertainment Inc", "exchange": "NASDAQ"},
    "PEP": {"company": "Pepsico Inc", "exchange": "NASDAQ"},
    "PFE": {"company": "Pfizer Inc", "exchange": "NYSE"},
    "PFG": {"company": "Principal Financial Group Inc", "exchange": "NASDAQ"},
    "PFGC": {"company": "Performance Food Group Company", "exchange": "NYSE"},
    "PG": {"company": "Procter & Gamble Company", "exchange": "NYSE"},
    "PGR": {"company": "Progressive Corp", "exchange": "NYSE"},
    "PH": {"company": "Parker-Hannifin Corp", "exchange": "NYSE"},
    "PHM": {"company": "Pultegroup", "exchange": "NYSE"},
    "PINS": {"company": "Pinterest Inc", "exchange": "NYSE"},
    "PK": {"company": "Park Hotels & Resorts Inc", "exchange": "NYSE"},
    "PKG": {"company": "Packaging Corp of America", "exchange": "NYSE"},
    "PLD": {"company": "Prologis Inc", "exchange": "NYSE"},
    "PLNT": {"company": "Planet Fitness", "exchange": "NYSE"},
    "PLTR": {"company": "Palantir Technologies Inc", "exchange": "NASDAQ"},
    "PLUG": {"company": "Plug Power Inc", "exchange": "NASDAQ"},
    "PM": {"company": "Philip Morris International Inc", "exchange": "NYSE"},
    "PNC": {"company": "PNC Bank", "exchange": "NYSE"},
    "PNFP": {"company": "Pinnacle Finl Ptnrs", "exchange": "NASDAQ"},
    "PNR": {"company": "Pentair Ltd", "exchange": "NYSE"},
    "PNW": {"company": "Pinnacle West Capital Corp", "exchange": "NYSE"},
    "PODD": {"company": "Insulet Corp", "exchange": "NASDAQ"},
    "POOL": {"company": "Pool Corp", "exchange": "NASDAQ"},
    "POST": {"company": "Post Holdings Inc", "exchange": "NYSE"},
    "PPC": {"company": "Pilgrim's Pride", "exchange": "NASDAQ"},
    "PPG": {"company": "PPG Industries", "exchange": "NYSE"},
    "PPL": {"company": "PPL Corp", "exchange": "NYSE"},
    "PR": {"company": "Permian Resources Corp", "exchange": "NYSE"},
    "PRGO": {"company": "Perrigo Company", "exchange": "NYSE"},
    "PRI": {"company": "Primerica Inc", "exchange": "NYSE"},
    "PRMB": {"company": "Primo Water Corp", "exchange": "NYSE"},
    "PRU": {"company": "Prudential Financial Inc", "exchange": "NYSE"},
    "PSA": {"company": "Public Storage", "exchange": "NYSE"},
    "PSKY": {"company": "Paramount Global", "exchange": "NASDAQ"},
    "PSN": {"company": "Parsons Corp", "exchange": "NYSE"},
    "PSTG": {"company": "Pure Storage Inc", "exchange": "NYSE"},
    "PSX": {"company": "Phillips 66", "exchange": "NYSE"},
    "PTC": {"company": "Ptc Inc", "exchange": "NASDAQ"},
    "PVH": {"company": "Phillips-Van Heusen Corp", "exchange": "NYSE"},
    "PWR": {"company": "Quanta Services", "exchange": "NYSE"},
    "PYPL": {"company": "Paypal Holdings", "exchange": "NASDAQ"},
    "QCOM": {"company": "Qualcomm Inc", "exchange": "NASDAQ"},
    "QGEN": {"company": "Qiagen N.V.", "exchange": "NYSE"},
    "QRVO": {"company": "Qorvo Inc", "exchange": "NASDAQ"},
    "QS": {"company": "Quantumscape Corp", "exchange": "NYSE"},
    "QSR": {"company": "Restaurant Brands International", "exchange": "NYSE"},
    "QXO": {"company": "Qxo Inc", "exchange": "NYSE"},
    "R": {"company": "Ryder System", "exchange": "NYSE"},
    "RAL": {"company": "Ralliant Corporation", "exchange": "NYSE"},
    "RARE": {"company": "Ultragenyx Pharmaceu", "exchange": "NASDAQ"},
    "RBA": {"company": "Rb Global Inc", "exchange": "NYSE"},
    "RBC": {"company": "RBC Bearings Inc", "exchange": "NYSE"},
    "RBLX": {"company": "Roblox Corp", "exchange": "NYSE"},
    "RBRK": {"company": "Rubrik Inc", "exchange": "NYSE"},
    "RCL": {"company": "Royal Caribbean Cruises Ltd", "exchange": "NYSE"},
    "RDDT": {"company": "Reddit Inc", "exchange": "NYSE"},
    "REG": {"company": "Regency Centers Corp", "exchange": "NASDAQ"},
    "REGN": {"company": "Regeneron Pharmaceuticals", "exchange": "NASDAQ"},
    "REXR": {"company": "Rexford Industrial Realty Inc", "exchange": "NYSE"},
    "REYN": {"company": "Reynolds Consumer Products Inc", "exchange": "NASDAQ"},
    "RF": {"company": "Regions Financial Corp", "exchange": "NYSE"},
    "RGA": {"company": "Reinsurance Group of America Inc", "exchange": "NYSE"},
    "RGEN": {"company": "Repligen Corp", "exchange": "NASDAQ"},
    "RGLD": {"company": "Royal Gold Inc", "exchange": "NASDAQ"},
    "RH": {"company": "Rh Common Stock", "exchange": "NYSE"},
    "RHI": {"company": "Robert Half Inc", "exchange": "NYSE"},
    "RITM": {"company": "Rithm Capital Corp", "exchange": "NYSE"},
    "RIVN": {"company": "Rivian Automotive Inc", "exchange": "NASDAQ"},
    "RJF": {"company": "Raymond James Financial", "exchange": "NYSE"},
    "RKLB": {"company": "Rocket Lab Corporation", "exchange": "NASDAQ"},
    "RKT": {"company": "Rocket Companies Inc", "exchange": "NYSE"},
    "RL": {"company": "Ralph Lauren Corp", "exchange": "NYSE"},
    "RLI": {"company": "Rli Corp", "exchange": "NYSE"},
    "RMD": {"company": "Resmed Inc", "exchange": "NYSE"},
    "RNG": {"company": "Ringcentral Inc", "exchange": "NYSE"},
    "RNR": {"company": "Renaissancere Holdings Ltd", "exchange": "NYSE"},
    "ROIV": {"company": "Roivant Sciences Ltd", "exchange": "NASDAQ"},
    "ROK": {"company": "Rockwell Automation Inc", "exchange": "NYSE"},
    "ROKU": {"company": "Roku Inc", "exchange": "NASDAQ"},
    "ROL": {"company": "Rollins Inc", "exchange": "NYSE"},
    "ROP": {"company": "Roper Industries", "exchange": "NASDAQ"},
    "ROST": {"company": "Ross Stores Inc", "exchange": "NASDAQ"},
    "RPM": {"company": "RPM International Inc", "exchange": "NYSE"},
    "RPRX": {"company": "Royalty Pharma Plc", "exchange": "NASDAQ"},
    "RRC": {"company": "Range Resources Corp", "exchange": "NYSE"},
    "RRX": {"company": "Regal Rexnord Corp", "exchange": "NYSE"},
    "RS": {"company": "Reliance Inc", "exchange": "NYSE"},
    "RSG": {"company": "Republic Services", "exchange": "NYSE"},
    "RTX": {"company": "Rtx Corp", "exchange": "NYSE"},
    "RVMD": {"company": "Revolution Medicines Inc", "exchange": "NASDAQ"},
    "RVTY": {"company": "Revvity Inc", "exchange": "NYSE"},
    "RYAN": {"company": "Ryan Specialty Hldgs Inc", "exchange": "NYSE"},
    "RYN": {"company": "Rayonier Inc REIT", "exchange": "NYSE"},
    "S": {"company": "Sentinelone Inc", "exchange": "NYSE"},
    "SAIA": {"company": "Saia Inc", "exchange": "NASDAQ"},
    "SAIC": {"company": "Science Applications International", "exchange": "NASDAQ"},
    "SAIL": {"company": "Sailpoint Inc", "exchange": "NASDAQ"},
    "SAM": {"company": "Boston Beer Company", "exchange": "NYSE"},
    "SARO": {"company": "Standardaero Inc", "exchange": "NYSE"},
    "SBAC": {"company": "SBA Communications", "exchange": "NASDAQ"},
    "SBUX": {"company": "Starbucks Corp", "exchange": "NASDAQ"},
    "SCCO": {"company": "Southern Copper Corp", "exchange": "NYSE"},
    "SCHW": {"company": "The Charles Schwab Corp", "exchange": "NYSE"},
    "SCI": {"company": "Service Corp International", "exchange": "NYSE"},
    "SEB": {"company": "Seaboard Corp", "exchange": "AMEX"},
    "SEE": {"company": "Sealed Air Corp", "exchange": "NYSE"},
    "SEIC": {"company": "Sei Investments Company", "exchange": "NASDAQ"},
    "SF": {"company": "Stifel Financial Corp", "exchange": "NYSE"},
    "SFD": {"company": "Smithfield Foods Inc", "exchange": "NASDAQ"},
    "SFM": {"company": "Sprouts Farmers Market", "exchange": "NASDAQ"},
    "SGI": {"company": "Somnigroup International Inc", "exchange": "NYSE"},
    "SHC": {"company": "Sotera Health Company", "exchange": "NASDAQ"},
    "SHW": {"company": "Sherwin-Williams Company", "exchange": "NYSE"},
    "SIRI": {"company": "Siriusxm Holdings Inc", "exchange": "NASDAQ"},
    "SITE": {"company": "Siteone Landscape Supply", "exchange": "NYSE"},
    "SJM": {"company": "J.M. Smucker Company", "exchange": "NYSE"},
    "SKX": {"company": "Skechers U.S.A.", "exchange": "NYSE"},
    "SLB": {"company": "Schlumberger N.V.", "exchange": "NYSE"},
    "SLGN": {"company": "Silgan Holdings", "exchange": "NYSE"},
    "SLM": {"company": "SLM Corp", "exchange": "NASDAQ"},
    "SMCI": {"company": "Super Micro Computer", "exchange": "NASDAQ"},
    "SMG": {"company": "Scotts Miracle-Gro Company", "exchange": "NYSE"},
    "SMMT": {"company": "Summit Therapeu ADR", "exchange": "NASDAQ"},
    "SN": {"company": "Sharkninja Inc", "exchange": "NYSE"},
    "SNA": {"company": "Snap-On Inc", "exchange": "NYSE"},
    "SNDK": {"company": "Sandisk Corp", "exchange": "NASDAQ"},
    "SNDR": {"company": "Schneider National Inc", "exchange": "NYSE"},
    "SNOW": {"company": "Snowflake Inc", "exchange": "NYSE"},
    "SNPS": {"company": "Synopsys Inc", "exchange": "NASDAQ"},
    "SNV": {"company": "Synovus Financial Corp", "exchange": "NYSE"},
    "SNX": {"company": "Synnex Corp", "exchange": "NYSE"},
    "SO": {"company": "Southern Company", "exchange": "NYSE"},
    "SOFI": {"company": "Sofi Technologies Inc", "exchange": "NASDAQ"},
    "SOLV": {"company": "Solventum Corporation", "exchange": "NYSE"},
    "SON": {"company": "Sonoco Products", "exchange": "NYSE"},
    "SPG": {"company": "Simon Property Group", "exchange": "NYSE"},
    "SPGI": {"company": "S&P Global Inc", "exchange": "NYSE"},
    "SPOT": {"company": "Spotify Technology S.A.", "exchange": "NYSE"},
    "SPR": {"company": "Spirit Aerosystems Holdings", "exchange": "NYSE"},
    "SRE": {"company": "Sempra", "exchange": "NYSE"},
    "SRPT": {"company": "Sarepta Therapeutics", "exchange": "NASDAQ"},
    "SSB": {"company": "Southstate Corp", "exchange": "NYSE"},
    "SSD": {"company": "Simpson Manufacturing Company", "exchange": "NYSE"},
    "SSNC": {"company": "SS&C Technologies", "exchange": "NASDAQ"},
    "ST": {"company": "Sensata Technologies Holding N.V.", "exchange": "NYSE"},
    "STAG": {"company": "Stag Industrial Inc", "exchange": "NYSE"},
    "STE": {"company": "Steris Corp", "exchange": "NYSE"},
    "STLD": {"company": "Steel Dynamics Inc", "exchange": "NASDAQ"},
    "STT": {"company": "State Street Corp", "exchange": "NYSE"},
    "STWD": {"company": "Starwood Property Trust", "exchange": "NYSE"},
    "STZ": {"company": "Constellation Brands Inc", "exchange": "NYSE"},
    "SUI": {"company": "Sun Communities", "exchange": "NYSE"},
    "SW": {"company": "Smurfit Westrock Plc", "exchange": "NYSE"},
    "SWK": {"company": "Stanley Black & Decker Inc", "exchange": "NYSE"},
    "SWKS": {"company": "Skyworks Solutions", "exchange": "NASDAQ"},
    "SYF": {"company": "Synchrony Financial", "exchange": "NYSE"},
    "SYK": {"company": "Stryker Corp", "exchange": "NYSE"},
    "SYY": {"company": "Sysco Corp", "exchange": "NYSE"},
    "T": {"company": "AT&T Inc", "exchange": "NYSE"},
    "TAP": {"company": "Molson Coors Brewing Company", "exchange": "NYSE"},
    "TDC": {"company": "Teradata Corp", "exchange": "NYSE"},
    "TDG": {"company": "Transdigm Group Inc", "exchange": "NYSE"},
    "TDY": {"company": "Teledyne Technologies Inc", "exchange": "NYSE"},
    "TEAM": {"company": "Atlassian Corp", "exchange": "NASDAQ"},
    "TECH": {"company": "Bio-Techne Corp", "exchange": "NASDAQ"},
    "TEM": {"company": "Tempus Ai", "exchange": "NASDAQ"},
    "TER": {"company": "Teradyne Inc", "exchange": "NASDAQ"},
    "TFC": {"company": "Truist Financial Corp", "exchange": "NYSE"},
    "TFSL": {"company": "Tfs Financial Corp", "exchange": "NASDAQ"},
    "TFX": {"company": "Teleflex Inc", "exchange": "NYSE"},
    "TGT": {"company": "Target Corp", "exchange": "NYSE"},
    "THC": {"company": "Tenet Healthcare Corp", "exchange": "NYSE"},
    "THG": {"company": "The Hanover Insurance Group", "exchange": "NYSE"},
    "THO": {"company": "Thor Industries", "exchange": "NYSE"},
    "TIGO": {"company": "Millicom International Cellular S.A.", "exchange": "NASDAQ"},
    "TJX": {"company": "TJX Companies", "exchange": "NYSE"},
    "TKO": {"company": "Tko Group Holdings Inc", "exchange": "NYSE"},
    "TKR": {"company": "Timken Company", "exchange": "NYSE"},
    "TLN": {"company": "Talen Energy Corporation", "exchange": "NASDAQ"},
    "TMO": {"company": "Thermo Fisher Scientific Inc", "exchange": "NYSE"},
    "TMUS": {"company": "T-Mobile US", "exchange": "NASDAQ"},
    "TNL": {"company": "Travel + Leisure Co.", "exchange": "NYSE"},
    "TOL": {"company": "Toll Brothers Inc", "exchange": "NYSE"},
    "TOST": {"company": "Toast Inc", "exchange": "NYSE"},
    "TPG": {"company": "Tpg Inc", "exchange": "NASDAQ"},
    "TPL": {"company": "Texas Pacific Land Trust", "exchange": "NYSE"},
    "TPR": {"company": "Tapestry Inc", "exchange": "NYSE"},
    "TREX": {"company": "Trex Company", "exchange": "NYSE"},
    "TRGP": {"company": "Targa Resources", "exchange": "NYSE"},
    "TRMB": {"company": "Trimble Navigation", "exchange": "NASDAQ"},
    "TROW": {"company": "T Rowe Price Group", "exchange": "NASDAQ"},
    "TRU": {"company": "Transunion", "exchange": "NYSE"},
    "TRV": {"company": "The Travelers Companies Inc", "exchange": "NYSE"},
    "TSCO": {"company": "Tractor Supply Company", "exchange": "NASDAQ"},
    "TSLA": {"company": "Tesla Inc", "exchange": "NASDAQ"},
    "TSN": {"company": "Tyson Foods", "exchange": "NYSE"},
    "TT": {"company": "Trane Technologies Plc", "exchange": "NYSE"},
    "TTC": {"company": "Toro Company", "exchange": "NYSE"},
    "TTD": {"company": "Trade Desk Inc", "exchange": "NASDAQ"},
    "TTEK": {"company": "Tetra Tech Inc", "exchange": "NASDAQ"},
    "TTWO": {"company": "Take-Two Interactive", "exchange": "NASDAQ"},
    "TW": {"company": "Tradeweb Markets Inc", "exchange": "NASDAQ"},
    "TWLO": {"company": "Twilio", "exchange": "NYSE"},
    "TXN": {"company": "Texas Instruments", "exchange": "NASDAQ"},
    "TXRH": {"company": "Texas Roadhouse Inc", "exchange": "NASDAQ"},
    "TXT": {"company": "Textron Inc", "exchange": "NYSE"},
    "TYL": {"company": "Tyler Technologies", "exchange": "NYSE"},
    "U": {"company": "Unity Software Inc", "exchange": "NYSE"},
    "UA": {"company": "Under Armour Inc Cl C", "exchange": "NYSE"},
    "UAA": {"company": "Under Armour", "exchange": "NYSE"},
    "UAL": {"company": "United Airlines Holdings Inc", "exchange": "NASDAQ"},
    "UBER": {"company": "Uber Technologies Inc", "exchange": "NYSE"},
    "UDR": {"company": "United Dominion Realty Trust", "exchange": "NYSE"},
    "UGI": {"company": "Ugi Corp", "exchange": "NYSE"},
    "UHA.B": {"company": "U-Haul Holding Series N Non-Voting", "exchange": "NYSE"},
    "UHAL": {"company": "U-Haul Holding Company", "exchange": "NYSE"},
    "UHS": {"company": "Universal Health Services", "exchange": "NYSE"},
    "UI": {"company": "Ubiquiti Networks", "exchange": "NYSE"},
    "ULTA": {"company": "Ulta Beauty Inc", "exchange": "NASDAQ"},
    "UNH": {"company": "Unitedhealth Group Inc", "exchange": "NYSE"},
    "UNM": {"company": "Unumprovident Corp", "exchange": "NYSE"},
    "UNP": {"company": "Union Pacific Corp", "exchange": "NYSE"},
    "UPS": {"company": "United Parcel Service", "exchange": "NYSE"},
    "URI": {"company": "United Rentals", "exchange": "NYSE"},
    "USB": {"company": "U.S. Bancorp", "exchange": "NYSE"},
    "USFD": {"company": "US Foods Holding", "exchange": "NYSE"},
    "UTHR": {"company": "United Therapeutic", "exchange": "NASDAQ"},
    "UWMC": {"company": "Uwm Hldg Corp", "exchange": "NYSE"},
    "V": {"company": "Visa Inc", "exchange": "NYSE"},
    "VEEV": {"company": "Veeva Systems Inc", "exchange": "NYSE"},
    "VFC": {"company": "V.F. Corp", "exchange": "NYSE"},
    "VICI": {"company": "Vici Properties Inc", "exchange": "NYSE"},
    "VIK": {"company": "Viking Holdings Ltd", "exchange": "NYSE"},
    "VIRT": {"company": "Virtu Financial Cm A", "exchange": "NYSE"},
    "VKTX": {"company": "Viking Thera", "exchange": "NASDAQ"},
    "VLO": {"company": "Valero Energy Corp", "exchange": "NYSE"},
    "VLTO": {"company": "Veralto Corporation", "exchange": "NYSE"},
    "VMC": {"company": "Vulcan Materials Company", "exchange": "NYSE"},
    "VMI": {"company": "Valmont Industries", "exchange": "NYSE"},
    "VNO": {"company": "Vornado Realty Trust", "exchange": "NYSE"},
    "VNOM": {"company": "Viper Energy Inc", "exchange": "NASDAQ"},
    "VNT": {"company": "Vontier Corp", "exchange": "NYSE"},
    "VOYA": {"company": "VOYA Financial Inc", "exchange": "NYSE"},
    "VRSK": {"company": "Verisk Analytics Inc", "exchange": "NASDAQ"},
    "VRSN": {"company": "Verisign Inc", "exchange": "NASDAQ"},
    "VRT": {"company": "Vertiv Holdings Llc.", "exchange": "NYSE"},
    "VRTX": {"company": "Vertex Pharmaceutic", "exchange": "NASDAQ"},
    "VST": {"company": "Vistra Energy Corp", "exchange": "NYSE"},
    "VTR": {"company": "Ventas Inc", "exchange": "NYSE"},
    "VTRS": {"company": "Viatris Inc", "exchange": "NASDAQ"},
    "VVV": {"company": "Valvoline Inc", "exchange": "NYSE"},
    "VZ": {"company": "Verizon Communications Inc", "exchange": "NYSE"},
    "W": {"company": "Wayfair Inc", "exchange": "NYSE"},
    "WAB": {"company": "Wabtec Corp", "exchange": "NYSE"},
    "WAL": {"company": "Western Alliance Bancorp", "exchange": "NYSE"},
    "WAT": {"company": "Waters Corp", "exchange": "NYSE"},
    "WBA": {"company": "Walgreens Boots Alliance", "exchange": "NASDAQ"},
    "WBD": {"company": "Discovery Inc Series A", "exchange": "NASDAQ"},
    "WBS": {"company": "Webster Financial Corp", "exchange": "NYSE"},
    "WCC": {"company": "Wesco International", "exchange": "NYSE"},
    "WDAY": {"company": "Workday Inc", "exchange": "NASDAQ"},
    "WDC": {"company": "Western Digital Corp", "exchange": "NASDAQ"},
    "WEC": {"company": "Wisconsin Energy Corp", "exchange": "NYSE"},
    "WELL": {"company": "Welltower Inc", "exchange": "NYSE"},
    "WEN": {"company": "Wendys Company", "exchange": "NASDAQ"},
    "WEX": {"company": "Wex Inc", "exchange": "NYSE"},
    "WFC": {"company": "Wells Fargo & Company", "exchange": "NYSE"},
    "WFRD": {"company": "Weatherford International Plc", "exchange": "NASDAQ"},
    "WH": {"company": "Wyndham Hotels & Resorts Inc", "exchange": "NYSE"},
    "WHR": {"company": "Whirlpool Corp", "exchange": "NYSE"},
    "WING": {"company": "Wingstop Inc", "exchange": "NASDAQ"},
    "WLK": {"company": "Westlake Corp", "exchange": "NYSE"},
    "WM": {"company": "Waste Management", "exchange": "NYSE"},
    "WMB": {"company": "Williams Companies", "exchange": "NYSE"},
    "WMS": {"company": "Advanced Drainage Systems Inc", "exchange": "NYSE"},
    "WMT": {"company": "Walmart Inc", "exchange": "NYSE"},
    "WPC": {"company": "W.P. Carey & Company Llc", "exchange": "NYSE"},
    "WRB": {"company": "W.R. Berkley Corp", "exchange": "NYSE"},
    "WSC": {"company": "Willscot Holdings Corp", "exchange": "NASDAQ"},
    "WSM": {"company": "Williams-Sonoma", "exchange": "NYSE"},
    "WSO": {"company": "Watsco Inc", "exchange": "NYSE"},
    "WST": {"company": "West Pharmaceutical Services", "exchange": "NYSE"},
    "WTFC": {"company": "Wintrust Financial Corp", "exchange": "NASDAQ"},
    "WTM": {"company": "White Mountains Insurance Group", "exchange": "NYSE"},
    "WTRG": {"company": "Essential Utilities Inc", "exchange": "NYSE"},
    "WTW": {"company": "Willis Towers Watson Public Ltd", "exchange": "NASDAQ"},
    "WU": {"company": "Western Union Company", "exchange": "NYSE"},
    "WWD": {"company": "Woodward Inc", "exchange": "NASDAQ"},
    "WY": {"company": "Weyerhaeuser Company", "exchange": "NYSE"},
    "WYNN": {"company": "Wynn Resorts Ltd", "exchange": "NASDAQ"},
    "XEL": {"company": "XCEL Energy Inc", "exchange": "NASDAQ"},
    "XOM": {"company": "Exxon Mobil Corp", "exchange": "NYSE"},
    "XP": {"company": "XP Inc", "exchange": "NASDAQ"},
    "XPO": {"company": "Xpo Inc", "exchange": "NYSE"},
}  # noqa

# Tickers prone to eager matches (short symbols or company name-like); used to avoid
# aggressive matches on partial queries.
STOCK_TICKER_EAGER_MATCH_BLOCKLIST = [
    "AA",
    "AL",
    "AM",
    "AN",
    "AR",
    "AS",
    "AU",
    "BA",
    "BC",
    "BG",
    "BJ",
    "BK",
    "BR",
    "BX",
    "CB",
    "CE",
    "CF",
    "CG",
    "CI",
    "CL",
    "CR",
    "CW",
    "DD",
    "DE",
    "DG",
    "DT",
    "DV",
    "EA",
    "ED",
    "EG",
    "EL",
    "ES",
    "EW",
    "FE",
    "FI",
    "FR",
    "GD",
    "GE",
    "GL",
    "GM",
    "GS",
    "HD",
    "HR",
    "IP",
    "IR",
    "IT",
    "KD",
    "KO",
    "KR",
    "LH",
    "LW",
    "MA",
    "MO",
    "MP",
    "MS",
    "MU",
    "NI",
    "NU",
    "OC",
    "ON",
    "PB",
    "PG",
    "PH",
    "PK",
    "PM",
    "PR",
    "QS",
    "RF",
    "RH",
    "RL",
    "RS",
    "SF",
    "SN",
    "SO",
    "ST",
    "SW",
    "TT",
    "TW",
    "UA",
    "UI",
    "VZ",
    "WH",
    "WM",
    "WU",
    "WY",
    "XP",
    "ACI",
    "ALL",
    "ALLY",
    "APP",
    "ARE",
    "ASH",
    "AUR",
    "BALL",
    "BILL",
    "BIO",
    "BRO",
    "BROS",
    "BURL",
    "CAR",
    "CART",
    "CAT",
    "CAVA",
    "CERT",
    "COLD",
    "COIN",
    "COKE",
    "COST",
    "CUBE",
    "CVS",
    "DASH",
    "DAY",
    "DECK",
    "DELL",
    "DINO",
    "DIS",
    "DOC",
    "DOCS",
    "DOCU",
    "DOW",
    "EBAY",
    "ELF",
    "FANG",
    "FAST",
    "FIVE",
    "FLEX",
    "FLO",
    "FOUR",
    "FOX",
    "GAP",
    "GEN",
    "GLOB",
    "GOOG",
    "GOOGL",
    "HALO",
    "HAS",
    "HOOD",
    "HUM",
    "HUN",
    "IBM",
    "ICE",
    "JAZZ",
    "KEY",
    "KEYS",
    "LINE",
    "LITE",
    "LOW",
    "LYFT",
    "MAN",
    "META",
    "MORN",
    "MOS",
    "NET",
    "NOW",
    "OKTA",
    "ON",
    "ONTO",
    "OWL",
    "PATH",
    "PEN",
    "PENN",
    "PEP",
    "PINS",
    "PLUG",
    "POOL",
    "POST",
    "RARE",
    "ROL",
    "ROKU",
    "SAIL",
    "SAM",
    "SEE",
    "SITE",
    "SNOW",
    "SOLV",
    "SON",
    "SPOT",
    "STAG",
    "TEAM",
    "TECH",
    "TOST",
    "TOL",
    "UBER",
    "VICI",
    "WELL",
    "WING",
]
