"""Module containing JSON object with ticker symbol to company name mapping for RUSSELL1000 tickers."""

# Source of truth for ticker symbol and company name mapping.
# NOTE: Should be treated as read-only and runtime.
_TICKER_COMPANY = {
    "A": "Agilent Technologies",
    "AA": "Alcoa Corp",
    "AAL": "American Airlines Gp",
    "AAON": "Aaon Inc",
    "AAPL": "Apple Inc",
    "ABBV": "Abbvie Inc",
    "ABNB": "Airbnb Inc",
    "ABT": "Abbott Laboratories",
    "ACGL": "Arch Capital Grp Ltd",
    "ACHC": "Acadia Healthcr Company",
    "ACI": "Albertsons Companies Inc",
    "ACM": "Aecom Technology Corp",
    "ACN": "Accenture Plc",
    "ADBE": "Adobe Systems Inc",
    "ADC": "Agree Realty Corp",
    "ADI": "Analog Devices",
    "ADM": "Archer Daniels Midland",
    "ADP": "Automatic Data Processing",
    "ADSK": "Autodesk Inc",
    "ADT": "ADT Inc",
    "AEE": "Ameren Corp",
    "AEP": "American Electric Power Company",
    "AES": "The Aes Corp",
    "AFG": "American Financial Group",
    "AFL": "Aflac Inc",
    "AFRM": "Affirm Holdings Inc",
    "AGCO": "Agco Corp",
    "AGNC": "Agnc Investment Corp",
    "AGO": "Assured Guaranty Ltd",
    "AIG": "American International Group",
    "AIT": "Applied Industrial Technologies",
    "AIZ": "Assurant Inc",
    "AJG": "Arthur J. Gallagher & Company",
    "AKAM": "Akamai Technologies",
    "AL": "Air Lease Corp",
    "ALAB": "Astera Labs Inc",
    "ALB": "Albemarle Corp",
    "ALGM": "Allegro Microsystems Inc",
    "ALGN": "Align Technology",
    "ALK": "Alaska Air Group",
    "ALL": "Allstate Corp",
    "ALLE": "Allegion Plc",
    "ALLY": "Ally Financial",
    "ALNY": "Alnylam Pharmaceuticals",
    "ALSN": "Allison Transmission Holdings",
    "AM": "Antero Midstream Corp",
    "AMAT": "Applied Materials",
    "AMCR": "Amcor Plc",
    "AMD": "Adv Micro Devices",
    "AME": "Ametek Inc",
    "AMED": "Amedisys Inc",
    "AMG": "Affiliated Managers Group",
    "AMGN": "Amgen Inc",
    "AMH": "American Homes 4 Rent",
    "AMKR": "Amkor Technology",
    "AMP": "Ameriprise Financial Services",
    "AMT": "American Tower Corp",
    "AMTM": "Amentum Holdings Inc",
    "AMZN": "Amazon.com Inc",
    "AN": "Autonation Inc",
    "ANET": "Arista Networks Inc",
    "AON": "AON Plc",
    "AOS": "Smith A.O. Corp",
    "APA": "Apa Corp",
    "APD": "Air Products and Chemicals",
    "APG": "Api Group Corp",
    "APH": "Amphenol Corp",
    "APLS": "Apellis Pharmaceuticals Inc",
    "APO": "Apollo Asset Management Inc",
    "APP": "Applovin Corp",
    "APPF": "Appfolio",
    "APTV": "Aptiv Plc",
    "AR": "Antero Resources Corp",
    "ARE": "Alexandria Real Estate Equities",
    "ARES": "Ares Management LP",
    "ARMK": "Aramark Holdings Corp",
    "ARW": "Arrow Electronics",
    "AS": "Amer Sports Inc",
    "ASH": "Ashland Inc",
    "ASTS": "Ast Spacemobile Inc",
    "ATI": "Ati Inc",
    "ATO": "Atmos Energy Corp",
    "ATR": "Aptargroup",
    "AU": "Anglogold Ashanti Ltd ADR",
    "AUR": "Aurora Innovation Inc",
    "AVB": "Avalonbay Communities",
    "AVGO": "Broadcom Ltd",
    "AVT": "Avnet Inc",
    "AVTR": "Avantor Inc",
    "AVY": "Avery Dennison Corp",
    "AWI": "Armstrong World Industries Inc",
    "AWK": "American Water Works",
    "AXON": "Axon Enterprise Inc",
    "AXP": "American Express Company",
    "AXS": "Axis Capital Holdings",
    "AXTA": "Axalta Coating Systems Ltd",
    "AYI": "Acuity Inc",
    "AZO": "Autozone",
    "BA": "Boeing Company",
    "BAC": "Bank of America Corp",
    "BAH": "Booz Allen Hamilton Holding Corp",
    "BALL": "Ball Corporation",
    "BAM": "Brookfield Asset Management Ltd",
    "BAX": "Baxter International Inc",
    "BBWI": "Bath & Body Works Inc",
    "BBY": "Best Buy Company",
    "BC": "Brunswick Corp",
    "BDX": "Becton Dickinson and Company",
    "BEN": "Franklin Resources",
    "BEPC": "Brookfield Renewable Corp",
    "BF.A": "Brown Forman Inc",
    "BFAM": "Bright Horizons Family Solutions Inc",
    "BF.B": "Brown Forman Inc Cl B",
    "BG": "Bunge Ltd",
    "BHF": "Brighthouse Financial Inc",
    "BIIB": "Biogen Inc",
    "BILL": "Bill Holdings Inc",
    "BIO": "Bio-Rad Laboratories",
    "BIRK": "Birkenstock Holding Plc",
    "BJ": "Bj's Wholesale Club Holdings Inc",
    "BK": "Bank of New York Mellon Corp",
    "BKNG": "Booking Holdings Inc",
    "BKR": "Baker Hughes Company",
    "BLD": "Topbuild Corp",
    "BLDR": "Builders Firstsource",
    "BLK": "Blackrock Inc",
    "BMRN": "Biomarin Pharmaceuticals",
    "BMY": "Bristol-Myers Squibb Company",
    "BOKF": "Bok Financial Corp",
    "BPOP": "Popular Inc",
    "BR": "Broadridge Financial Solutions Llc",
    "BRBR": "Bellring Brands Inc",
    "BRK.B": "Berkshire Hathaway Cl B",
    "BRKR": "Bruker Corp",
    "BRO": "Brown & Brown",
    "BROS": "Dutch Bros Inc",
    "BRX": "Brixmor Property Group Inc",
    "BSX": "Boston Scientific Corp",
    "BSY": "Bentley Systems Inc Cl B",
    "BURL": "Burlington Stores Inc",
    "BWA": "Borgwarner Inc",
    "BWXT": "Bwx Technologies Inc",
    "BX": "Blackstone Inc",
    "BXP": "Bxp Inc",
    "BYD": "Boyd Gaming Corp",
    "C": "Citigroup Inc",
    "CACC": "Credit Acceptance",
    "CACI": "Caci International",
    "CAG": "Conagra Brands Inc",
    "CAH": "Cardinal Health",
    "CAR": "Avis Budget Group",
    "CARR": "Carrier Global Corp",
    "CART": "Maplebear Inc [Instacart]",
    "CASY": "Casey's General Stor",
    "CAT": "Caterpillar Inc",
    "CAVA": "Cava Group Inc",
    "CB": "Chubb Ltd",
    "CBOE": "CBOE Global Markets Inc",
    "CBRE": "CBRE Group Inc",
    "CBSH": "Commerce Bancshares",
    "CCCS": "CCC Intelligent Solutions Hldgs Inc",
    "CCI": "Crown Castle Inc",
    "CCK": "Crown Cork & Seal Company",
    "CCL": "Carnival Corp",
    "CDNS": "Cadence Design Sys",
    "CDW": "CDW Corp",
    "CE": "Celanese Corp",
    "CEG": "Constellation Energy Corp",
    "CELH": "Celsius Holdings Inc",
    "CERT": "Certara Inc",
    "CF": "Cf Industries Holdings",
    "CFG": "Citizens Financial Group Inc/Ri",
    "CFLT": "Confluent Inc",
    "CFR": "Cullen/Frost Bankers",
    "CG": "The Carlyle Group",
    "CGNX": "Cognex Corp",
    "CHD": "Church & Dwight Company",
    "CHDN": "Churchill Downs IN",
    "CHE": "Chemed Inc",
    "CHH": "Choice Hotels International",
    "CHRD": "Chord Energy Corp",
    "CHRW": "C.H. Robinson Ww",
    "CHTR": "Charter Communications Inc",
    "CHWY": "Chewy Inc",
    "CI": "The Cigna Group",
    "CIEN": "Ciena Corp",
    "CINF": "Cincinnati Financial",
    "CIVI": "Civitas Resources Inc",
    "CL": "Colgate-Palmolive Company",
    "CLF": "Cleveland-Cliffs Inc",
    "CLH": "Clean Harbors",
    "CLVT": "Clarivate Analytics Plc",
    "CLX": "Clorox Company",
    "CMA": "Comerica Inc",
    "CMCSA": "Comcast Corp A",
    "CME": "CME Group Inc",
    "CMG": "Chipotle Mexican Grill",
    "CMI": "Cummins Inc",
    "CMS": "Cms Energy Corp",
    "CNA": "CNA Financial Corp",
    "CNC": "Centene Corp",
    "CNH": "CNH Industrial N.V.",
    "CNM": "Core & Main Inc",
    "CNP": "Centerpoint Energy Inc",
    "CNXC": "Concentrix Corp",
    "COF": "Capital One Financial Corp",
    "COHR": "Coherent Corp",
    "COIN": "Coinbase Global Inc",
    "COKE": "Coca-Cola Consolidated Inc",
    "COLB": "Columbia Banking Sys",
    "COLD": "Americold Realty Trust",
    "COLM": "Columbia Sprtswr",
    "COO": "Cooper Companies",
    "COOP": "Mr.Cooper Group Inc",
    "COP": "Conocophillips",
    "COR": "Cencora Inc",
    "CORT": "Corcept Therapeutics",
    "COST": "Costco Wholesale",
    "COTY": "Coty Inc",
    "CPAY": "Corpay Inc",
    "CPB": "The Campbell's Company",
    "CPNG": "Coupang Inc",
    "CPRT": "Copart Inc",
    "CPT": "Camden Property Trust",
    "CR": "Crane Company",
    "CRH": "CRH Plc ADR",
    "CRL": "Charles River Laboratories Intl",
    "CRM": "Salesforce Inc",
    "CROX": "Crocs Inc",
    "CRS": "Carpenter Technology Corp",
    "CRUS": "Cirrus Logic Inc",
    "CRWD": "Crowdstrike Holdings Inc",
    "CSCO": "Cisco Systems Inc",
    "CSGP": "Costar Group Inc",
    "CSL": "Carlisle Companies Inc",
    "CSX": "CSX Corp",
    "CTAS": "Cintas Corp",
    "CTRA": "Coterra Energy Inc",
    "CTSH": "Cognizant Tech Sol",
    "CTVA": "Corteva Inc",
    "CUBE": "Cubesmart",
    "CUZ": "Cousins Properties Inc",
    "CVNA": "Carvana Company",
    "CVS": "CVS Corp",
    "CVX": "Chevron Corp",
    "CW": "Curtiss-Wright Corp",
    "CWEN": "Clearway Energy Inc Cl C",
    "CWE.A": "Clearway Energy Inc [Cwen.A]",
    "CXT": "Crane Nxt CO",
    "CZR": "Caesars Entertainment Inc",
    "D": "Dominion Energy Inc",
    "DAL": "Delta Air Lines Inc",
    "DAR": "Darling International Inc",
    "DASH": "Doordash Inc",
    "DAY": "Dayforce Inc",
    "DBX": "Dropbox Inc",
    "DCI": "Donaldson Company",
    "DD": "Dupont Denemours Inc",
    "DDOG": "Datadog Inc",
    "DDS": "Dillard's",
    "DE": "Deere & Company",
    "DECK": "Deckers Outdoor Corp",
    "DELL": "Dell Technologies Inc",
    "DG": "Dollar General Corp",
    "DGX": "Quest Diagnostics Inc",
    "DHI": "D.R. Horton",
    "DHR": "Danaher Corp",
    "DINO": "HF Sinclair Corp",
    "DIS": "Walt Disney Company",
    "DJT": "Trump Media & Technology Group Corp",
    "DKNG": "Draftkings Inc",
    "DKS": "Dick's Sporting Goods Inc",
    "DLB": "Dolby Laboratories",
    "DLR": "Digital Realty Trust",
    "DLTR": "Dollar Tree Inc",
    "DNB": "Dun & Bradstreet Holdings Inc",
    "DOC": "Healthpeak Properties Inc",
    "DOCS": "Doximity Inc",
    "DOCU": "Docusign Inc",
    "DOV": "Dover Corp",
    "DOW": "Dow Inc",
    "DOX": "Amdocs Ltd Ord",
    "DPZ": "Domino's Pizza Inc",
    "DRI": "Darden Restaurants",
    "DRS": "Leonardo Drs Inc",
    "DT": "Dynatrace Inc",
    "DTE": "Dte Energy Company",
    "DTM": "Dt Midstream Inc",
    "DUK": "Duke Energy Corp",
    "DUOL": "Duolingo Inc",
    "DV": "Doubleverify Holdings Inc",
    "DVA": "Davita Healthcare Partners Inc",
    "DVN": "Devon Energy Corp",
    "DXC": "Dxc Technology Company",
    "DXCM": "Dexcom Inc",
    "EA": "Electronic Arts Inc",
    "EBAY": "Ebay Inc",
    "ECG": "Everus Construction Group Inc",
    "ECL": "Ecolab Inc",
    "ED": "Consolidated Edison Company",
    "EEFT": "Euronet Worldwide",
    "EFX": "Equifax Inc",
    "EG": "Everest Re Group",
    "EGP": "Eastgroup Properties",
    "EHC": "Encompass Health Corp",
    "EIX": "Edison International",
    "EL": "Estee Lauder Companies",
    "ELAN": "Elanco Animal Health Inc",
    "ELF": "E.L.F. Beauty Inc",
    "ELS": "Equity Lifestyle Properties",
    "ELV": "Elevance Health Inc",
    "EME": "Emcor Group",
    "EMN": "Eastman Chemical Company",
    "EMR": "Emerson Electric Company",
    "ENPH": "Enphase Energy Inc",
    "ENTG": "Entegris Inc",
    "EOG": "Eog Resources",
    "EPAM": "Epam Systems Inc",
    "EPR": "Entertainment Properties Trust",
    "EQH": "Axa Equitable Holdings Inc",
    "EQIX": "Equinix Inc",
    "EQR": "Equity Residential",
    "EQT": "Eqt Corp",
    "ES": "Eversource Energy",
    "ESAB": "Esab Corp",
    "ESI": "Element Solutions Inc",
    "ESS": "Essex Property Trust",
    "ESTC": "Elastic N.V.",
    "ETN": "Eaton Corp",
    "ETR": "Entergy Corp",
    "ETSY": "Etsy Inc",
    "EVR": "Evercore Partners Inc",
    "EVRG": "Evergy Inc",
    "EW": "Edwards Lifesciences Corp",
    "EWBC": "East West Bancorp",
    "EXAS": "Exact Sciences Cor",
    "EXC": "Exelon Corp",
    "EXE": "Expand Energy Corporation",
    "EXEL": "Exelixis Inc",
    "EXLS": "Exlservice Holdings",
    "EXP": "Eagle Materials Inc",
    "EXPD": "Expeditors Intl",
    "EXPE": "Expedia Group Inc",
    "EXR": "Extra Space Storage Inc",
    "F": "Ford Motor Company",
    "FAF": "First American Corp",
    "FANG": "Diamondback Energy",
    "FAST": "Fastenal Company",
    "FBIN": "Fortune Brands Innovations Inc",
    "FCN": "Fti Consulting",
    "FCNCA": "First Citizens Bancs",
    "FCX": "Freeport-Mcmoran Inc",
    "FDS": "Factset Research Systems Inc",
    "FDX": "Fedex Corp",
    "FE": "Firstenergy Corp",
    "FERG": "Ferguson Enterprises Inc",
    "FFIV": "F5 Inc",
    "FHB": "First Hawaiian Inc",
    "FHN": "First Horizon Corp",
    "FI": "Fiserv Inc",
    "FICO": "Fair Isaac and Company",
    "FIS": "Fidelity National Information Services",
    "FITB": "Fifth Third Bancorp",
    "FIVE": "Five Below Inc",
    "FIX": "Comfort Systems USA",
    "FLEX": "Flextronics Intl Ltd",
    "FLO": "Flowers Foods",
    "FLS": "Flowserve Corp",
    "FLUT": "Flutter Entertainment Plc",
    "FMC": "FMC Corp",
    "FNB": "F.N.B. Corp",
    "FND": "Floor & Decor Holdings Inc",
    "FNF": "Fidelity National Financial",
    "FOUR": "Shift4 Payments Inc",
    "FOX": "Fox Corp Cl B",
    "FOXA": "Fox Corp",
    "FR": "First Industrial Realty Trust",
    "FRHC": "Freedom Holding Corp",
    "FRPT": "Freshpet Inc CS",
    "FRT": "Federal Realty Investment Trust",
    "FSLR": "First Solar Inc",
    "FTAI": "Ftai Aviation Ltd",
    "FTI": "Technipfmc Plc",
    "FTNT": "Fortinet Inc",
    "FTV": "Fortive Corp",
    "FWONA": "Liberty Media Formula One Sr A",
    "FWONK": "Liberty Media Formula One Sr C",
    "FYBR": "Frontier Communications Parent Inc",
    "G": "Genpact Ltd",
    "GAP": "Gap Inc",
    "GD": "General Dynamics Corp",
    "GDDY": "Godaddy Inc",
    "GE": "GE Aerospace",
    "GEHC": "GE Healthcare Technologies Inc",
    "GEN": "Gen Digital Inc",
    "GEV": "GE Vernova Inc",
    "GFS": "Globalfoundries Inc",
    "GGG": "Graco Inc",
    "GILD": "Gilead Sciences Inc",
    "GIS": "General Mills",
    "GL": "Globe Life Inc",
    "GLIBA": "Gci Liberty Inc Series A Gci",
    "GLIBK": "Gci Liberty Inc Series C Gci",
    "GLOB": "Globant S.A.",
    "GLPI": "Gaming & Leisure",
    "GLW": "Corning Inc",
    "GM": "General Motors Company",
    "GME": "Gamestop Corp",
    "GMED": "Globus Medical Inc",
    "GNRC": "Generac Holdings Inc",
    "GNTX": "Gentex Corp",
    "GOOG": "Alphabet Cl C",
    "GOOGL": "Alphabet",
    "GPC": "Genuine Parts Company",
    "GPK": "Graphic Packaging Holding Company",
    "GPN": "Global Payments Inc",
    "GRMN": "Garmin Ltd",
    "GS": "Goldman Sachs Group",
    "GTES": "Gates Industrial Corp Plc",
    "GTLB": "Gitlab Inc",
    "GTM": "Zoominfo Technologies Inc",
    "GWRE": "Guidewire Software Inc",
    "GWW": "W.W. Grainger",
    "GXO": "Gxo Logistics Inc",
    "H": "Hyatt Hotels Corp",
    "HAL": "Halliburton Company",
    "HALO": "Halozyme Therapeutic",
    "HAS": "Hasbro Inc",
    "HAYW": "Hayward Holdings Inc",
    "HBAN": "Huntington Bancshares Inc",
    "HCA": "Hca Holdings Inc",
    "HD": "Home Depot",
    "HEI": "Heico Corp",
    "HEI.A": "Heico Corp",
    "HHH": "Howard Hughes Holdings Inc",
    "HIG": "The Hartford Insurance Group Inc",
    "HII": "Huntington Ingalls Industries",
    "HIW": "Highwoods Properties",
    "HLI": "Houlihan Lokey",
    "HLNE": "Hamilton Lane Inc",
    "HLT": "Hilton Inc",
    "HOG": "Harley-Davidson Inc",
    "HOLX": "Hologic Inc",
    "HON": "Honeywell International Inc",
    "HOOD": "Robinhood Markets Inc",
    "HPE": "Hewlett Packard Enterprise Comp",
    "HPQ": "HP Inc",
    "HR": "Healthcare Realty Trust Inc.",
    "HRB": "H&R Block",
    "HRL": "Hormel Foods Corp",
    "HSIC": "Henry Schein Inc",
    "HST": "Host Marriott Financial Trust",
    "HSY": "Hershey Foods Corp",
    "HUBB": "Hubbell Inc B",
    "HUBS": "Hubspot Inc",
    "HUM": "Humana Inc",
    "HUN": "Huntsman Corp",
    "HWM": "Howmet Aerospace Inc",
    "HXL": "Hexcel Corp",
    "IAC": "Iac Inc",
    "IBKR": "Interactive Brokers",
    "IBM": "Intl Business Machines",
    "ICE": "Intercontinental Exchange",
    "IDA": "Idacorp Inc",
    "IDXX": "Idexx Laboratories",
    "IEX": "Idex Corp",
    "IFF": "International Flavors & Fragrances",
    "ILMN": "Illumina Inc",
    "INCY": "Incyte Corp",
    "INFA": "Informatica Inc",
    "INGM": "Ingram Micro Holding Corp",
    "INGR": "Ingredion Inc",
    "INSM": "Insmed Inc",
    "INSP": "Inspire Medical Systems Inc",
    "INTC": "Intel Corp",
    "INTU": "Intuit Inc",
    "INVH": "Invitation Homes Inc",
    "IONS": "Ionis Pharmaceuticals",
    "IOT": "Samsara Inc",
    "IP": "International Paper Company",
    "IPG": "Interpublic Group of Companies",
    "IPGP": "Ipg Photonics Corp",
    "IQV": "Iqvia Holdings Inc",
    "IR": "Ingersoll Rand Inc",
    "IRDM": "Iridium Comm Inc",
    "IRM": "Iron Mountain Inc",
    "ISRG": "Intuitive Surg Inc",
    "IT": "Gartner Inc",
    "ITT": "ITT Inc",
    "ITW": "Illinois Tool Works Inc",
    "IVZ": "Invesco Plc",
    "J": "Jacobs Engineering Group Inc",
    "JAZZ": "Jazz Pharma Plc",
    "JBHT": "J B Hunt Transport",
    "JBL": "Jabil Circuit",
    "JCI": "Johnson Controls Intl",
    "JEF": "Jefferies Financial Group Inc",
    "JHG": "Janus Henderson Group Plc",
    "JHX": "James Hardie Industries Se ADR",
    "JKHY": "Jack Henry & Assoc",
    "JLL": "Jones Lang Lasalle Inc",
    "JNJ": "Johnson & Johnson",
    "JPM": "JP Morgan Chase & Company",
    "K": "Kellanova",
    "KBR": "KBR Inc",
    "KD": "Kyndryl Hldgs Inc",
    "KDP": "Keurig Dr Pepper Inc",
    "KEX": "Kirby Corp",
    "KEY": "Keycorp",
    "KEYS": "Keysight Technologies Inc",
    "KHC": "Kraft Heinz Company",
    "KIM": "Kimco Realty Corp",
    "KKR": "KKR & Company LP",
    "KLAC": "K L A-Tencor Corp",
    "KMB": "Kimberly-Clark Corp",
    "KMI": "Kinder Morgan Inc",
    "KMPR": "Kemper Corp",
    "KMX": "Carmax Inc",
    "KNSL": "Kinsale Capital Group Inc",
    "KNX": "Knight-Swift Transporation Inc",
    "KO": "Coca-Cola Company",
    "KR": "Kroger Company",
    "KRC": "Kilroy Realty Corp",
    "KRMN": "Karman Holdings Inc",
    "KVUE": "Kenvue Inc",
    "L": "Loews Corp",
    "LAD": "Lithia Motors",
    "LAMR": "Lamar Advertis A",
    "LAZ": "Lazard Inc",
    "LBRDA": "Liberty Broadband Corp Sr A",
    "LBRDK": "Liberty Broadband Corp Sr C",
    "LBTYA": "Liberty Global Ltd Ord A",
    "LBTYK": "Liberty Global Ltd Ord C",
    "LCID": "Lucid Group Inc",
    "LDOS": "Leidos Holdings Inc",
    "LEA": "Lear Corp",
    "LECO": "Lincoln Elec Holdings",
    "LEN": "Lennar Corp",
    "LEN.B": "Lennar Corp Cl B",
    "LFUS": "Littelfuse Inc",
    "LH": "Laboratory Corp of America Holdings",
    "LHX": "L3Harris Technologies Inc",
    "LII": "Lennox International",
    "LIN": "Linde Plc",
    "LINE": "Lineage Inc",
    "LITE": "Lumentum Holdings",
    "LKQ": "LKQ Corp",
    "LLY": "Eli Lilly and Company",
    "LLYVA": "Liberty Live Series A",
    "LLYVK": "Liberty Live Series C",
    "LMT": "Lockheed Martin Corp",
    "LNC": "Lincoln National Corp",
    "LNG": "Cheniere Energy",
    "LNT": "Alliant Energy Corp",
    "LNW": "Light & Wonder Inc",
    "LOAR": "Loar Holdings Inc",
    "LOPE": "Grand Canyon Educati",
    "LOW": "Lowe's Companies",
    "LPLA": "Lpl Financial Holdings",
    "LPX": "Louisiana-Pacific Corp",
    "LRCX": "Lam Research Corp",
    "LSCC": "Lattice Semicond",
    "LSTR": "Landstar System",
    "LULU": "Lululemon Athletica",
    "LUV": "Southwest Airlines Company",
    "LVS": "Las Vegas Sands",
    "LW": "Lamb Weston Holdings Inc",
    "LYB": "Lyondellbasell Industries NV",
    "LYFT": "Lyft Inc",
    "LYV": "Live Nation Entertainment",
    "M": "Macy's Inc",
    "MA": "Mastercard Inc",
    "MAA": "Mid-America Apartment Communities",
    "MAN": "Manpower Inc",
    "MANH": "Manhattan Assoc",
    "MAR": "Marriot Int",
    "MAS": "Masco Corp",
    "MASI": "Masimo Corp",
    "MAT": "Mattel Inc",
    "MCD": "McDonald's Corp",
    "MCHP": "Microchip Technology",
    "MCK": "Mckesson Corp",
    "MCO": "Moody's Corp",
    "MDB": "Mongodb Inc",
    "MDLZ": "Mondelez Intl Inc",
    "MDT": "Medtronic Inc",
    "MDU": "Mdu Res Group Inc",
    "MEDP": "Medpace Holdings Inc",
    "MET": "Metlife Inc",
    "META": "Meta Platforms Inc",
    "MGM": "MGM Resorts International",
    "MHK": "Mohawk Industries",
    "MIDD": "Middleby Corp",
    "MKC": "Mccormick & Company",
    "MKL": "Markel Corp",
    "MKSI": "Mks Inc",
    "MKTX": "Marketaxess Holdings",
    "MLI": "Mueller Industries",
    "MLM": "Martin Marietta Materials",
    "MMC": "Marsh & Mclennan Companies",
    "MMM": "3M Company",
    "MNST": "Monster Beverage Corp",
    "MO": "Altria Group",
    "MOH": "Molina Healthcare Inc",
    "MORN": "Morningstar Inc",
    "MOS": "Mosaic Company",
    "MP": "MP Materials Corp",
    "MPC": "Marathon Petroleum Corp",
    "MPW": "Medical Properties Trust",
    "MPWR": "Monolithic Power Sys",
    "MRK": "Merck & Company",
    "MRNA": "Moderna Inc",
    "MRP": "Millrose Properties Inc",
    "MRVL": "Marvell Technology Inc",
    "MS": "Morgan Stanley",
    "MSA": "Msa Safety Inc",
    "MSCI": "MSCI Inc",
    "MSFT": "Microsoft Corp",
    "MSGS": "Madison Square Garden Sports Corp",
    "MSI": "Motorola Solutions",
    "MSM": "Msc Industrial Direct Company",
    "MSTR": "Strategy Inc",
    "MTB": "M&T Bank Corp",
    "MTCH": "Match Group Inc",
    "MTD": "Mettler-Toledo International",
    "MTDR": "Matador Resources Company",
    "MTG": "Mgic Investment Corp",
    "MTN": "Vail Resorts",
    "MTSI": "Macom Technology S",
    "MTZ": "Mastec Inc",
    "MU": "Micron Technology",
    "MUSA": "Murphy USA Inc",
    "NBIX": "Neurocrine Bioscienc",
    "NCLH": "Norwegian Cruise Ord",
    "NCNO": "Ncino Inc",
    "NDAQ": "Nasdaq Inc",
    "NDSN": "Nordson Corp",
    "NEE": "Nextera Energy",
    "NEM": "Newmont Mining Corp",
    "NET": "Cloudflare Inc",
    "NEU": "Newmarket Corp",
    "NFG": "National Fuel Gas Company",
    "NFLX": "Netflix Inc",
    "NI": "NiSource Inc",
    "NKE": "Nike Inc",
    "NLY": "Annaly Capital Management Inc",
    "NNN": "NNN REIT Inc",
    "NOC": "Northrop Grumman Corp",
    "NOV": "Nov Inc",
    "NOW": "Servicenow Inc",
    "NRG": "NRG Energy",
    "NSA": "National Storage Affiliates Tru",
    "NSC": "Norfolk Southern Corp",
    "NTAP": "Netapp Inc",
    "NTNX": "Nutanix Inc",
    "NTRA": "Natera Inc",
    "NTRS": "Northern Trust Corp",
    "NU": "Nu Holdings Ltd",
    "NUE": "Nucor Corp",
    "NVDA": "Nvidia Corp",
    "NVR": "NVR Inc",
    "NVST": "Envista Holdings Corp",
    "NVT": "Nvent Electric Plc",
    "NWL": "Newell Rubbermaid Inc",
    "NWS": "News Corp Cl B",
    "NWSA": "News Corp",
    "NXST": "Nexstar Media Group Inc",
    "NYT": "New York Times Company",
    "O": "Realty Income Corp",
    "OC": "Owens Corning Inc",
    "ODFL": "Old Dominion Freight Line Inc",
    "OGE": "Oge Energy Corp",
    "OGN": "Organon & Co.",
    "OHI": "Omega Healthcare Investors",
    "OKE": "Oneok Inc",
    "OKTA": "Okta Inc",
    "OLED": "Universal Display",
    "OLLI": "Ollies Bargain CS",
    "OLN": "Olin Corp",
    "OMC": "Omnicom Group Inc",
    "OMF": "Onemain Holdings Inc",
    "ON": "On Semiconductor",
    "ONON": "On Holding Ag",
    "ONTO": "Onto Innovation Inc",
    "ORCL": "Oracle Corp",
    "ORI": "Old Republic International Corp",
    "ORLY": "O'Reilly Automotive",
    "OSK": "Oshkosh Truck Corp",
    "OTIS": "Otis Worldwide Corp",
    "OVV": "Ovintiv Inc",
    "OWL": "Blue Owl Capital Inc",
    "OXY": "Occidental Petroleum Corp",
    "OZK": "Bank Ozk",
    "PAG": "Penske Automotive Group",
    "PANW": "Palo Alto Networks Inc",
    "PARA": "Paramount Global Cl B",
    "PARAA": "Paramount Global",
    "PATH": "Uipath Inc",
    "PAYC": "Paycom Software Inc",
    "PAYX": "Paychex Inc",
    "PB": "Prosperity Bancshares",
    "PCAR": "Paccar Inc",
    "PCG": "Pacific Gas & Electric Company",
    "PCOR": "Procore Technologies Inc",
    "PCTY": "Paylocity Holdings Corp",
    "PEG": "Public Service Enterprise Group Inc",
    "PEGA": "Pegasystems Inc",
    "PEN": "Penumbra Inc",
    "PENN": "Penn Entertainment Inc",
    "PEP": "Pepsico Inc",
    "PFE": "Pfizer Inc",
    "PFG": "Principal Financial Group Inc",
    "PFGC": "Performance Food Group Company",
    "PG": "Procter & Gamble Company",
    "PGR": "Progressive Corp",
    "PH": "Parker-Hannifin Corp",
    "PHM": "Pultegroup",
    "PINS": "Pinterest Inc",
    "PK": "Park Hotels & Resorts Inc",
    "PKG": "Packaging Corp of America",
    "PLD": "Prologis Inc",
    "PLNT": "Planet Fitness",
    "PLTR": "Palantir Technologies Inc",
    "PM": "Philip Morris International Inc",
    "PNC": "PNC Bank",
    "PNFP": "Pinnacle Finl Ptnrs",
    "PNR": "Pentair Ltd",
    "PNW": "Pinnacle West Capital Corp",
    "PODD": "Insulet Corp",
    "POOL": "Pool Corp",
    "POST": "Post Holdings Inc",
    "PPC": "Pilgrim's Pride",
    "PPG": "PPG Industries",
    "PPL": "PPL Corp",
    "PR": "Permian Resources Corp",
    "PRGO": "Perrigo Company",
    "PRI": "Primerica Inc",
    "PRMB": "Primo Water Corp",
    "PRU": "Prudential Financial Inc",
    "PSA": "Public Storage",
    "PSN": "Parsons Corp",
    "PSTG": "Pure Storage Inc",
    "PSX": "Phillips 66",
    "PTC": "Ptc Inc",
    "PVH": "Phillips-Van Heusen Corp",
    "PWR": "Quanta Services",
    "PYPL": "Paypal Holdings",
    "QCOM": "Qualcomm Inc",
    "QGEN": "Qiagen N.V.",
    "QRVO": "Qorvo Inc",
    "QS": "Quantumscape Corp",
    "QSR": "Restaurant Brands International",
    "QXO": "Qxo Inc",
    "R": "Ryder System",
    "RAL": "Ralliant Corporation",
    "RARE": "Ultragenyx Pharmaceu",
    "RBA": "Rb Global Inc",
    "RBC": "RBC Bearings Inc",
    "RBLX": "Roblox Corp",
    "RBRK": "Rubrik Inc",
    "RCL": "Royal Caribbean Cruises Ltd",
    "RDDT": "Reddit Inc",
    "REG": "Regency Centers Corp",
    "REGN": "Regeneron Pharmaceuticals",
    "REXR": "Rexford Industrial Realty Inc",
    "REYN": "Reynolds Consumer Products Inc",
    "RF": "Regions Financial Corp",
    "RGA": "Reinsurance Group of America Inc",
    "RGEN": "Repligen Corp",
    "RGLD": "Royal Gold Inc",
    "RH": "Rh Common Stock",
    "RHI": "Robert Half Inc",
    "RITM": "Rithm Capital Corp",
    "RIVN": "Rivian Automotive Inc",
    "RJF": "Raymond James Financial",
    "RKLB": "Rocket Lab Corporation",
    "RKT": "Rocket Companies Inc",
    "RL": "Ralph Lauren Corp",
    "RLI": "Rli Corp",
    "RMD": "Resmed Inc",
    "RNG": "Ringcentral Inc",
    "RNR": "Renaissancere Holdings Ltd",
    "ROIV": "Roivant Sciences Ltd",
    "ROK": "Rockwell Automation Inc",
    "ROKU": "Roku Inc",
    "ROL": "Rollins Inc",
    "ROP": "Roper Industries",
    "ROST": "Ross Stores Inc",
    "RPM": "RPM International Inc",
    "RPRX": "Royalty Pharma Plc",
    "RRC": "Range Resources Corp",
    "RRX": "Regal Rexnord Corp",
    "RS": "Reliance Inc",
    "RSG": "Republic Services",
    "RTX": "Rtx Corp",
    "RVMD": "Revolution Medicines Inc",
    "RVTY": "Revvity Inc",
    "RYAN": "Ryan Specialty Hldgs Inc",
    "RYN": "Rayonier Inc REIT",
    "S": "Sentinelone Inc",
    "SAIA": "Saia Inc",
    "SAIC": "Science Applications International",
    "SAIL": "Sailpoint Inc",
    "SAM": "Boston Beer Company",
    "SARO": "Standardaero Inc",
    "SBAC": "SBA Communications",
    "SBUX": "Starbucks Corp",
    "SCCO": "Southern Copper Corp",
    "SCHW": "The Charles Schwab Corp",
    "SCI": "Service Corp International",
    "SEB": "Seaboard Corp",
    "SEE": "Sealed Air Corp",
    "SEIC": "Sei Investments Company",
    "SF": "Stifel Financial Corp",
    "SFD": "Smithfield Foods Inc",
    "SFM": "Sprouts Farmers Market",
    "SGI": "Somnigroup International Inc",
    "SHC": "Sotera Health Company",
    "SHW": "Sherwin-Williams Company",
    "SIRI": "Siriusxm Holdings Inc",
    "SITE": "Siteone Landscape Supply",
    "SJM": "J.M. Smucker Company",
    "SKX": "Skechers U.S.A.",
    "SLB": "Schlumberger N.V.",
    "SLGN": "Silgan Holdings",
    "SLM": "SLM Corp",
    "SMCI": "Super Micro Computer",
    "SMG": "Scotts Miracle-Gro Company",
    "SMMT": "Summit Therapeu ADR",
    "SN": "Sharkninja Inc",
    "SNA": "Snap-On Inc",
    "SNDK": "Sandisk Corp",
    "SNDR": "Schneider National Inc",
    "SNOW": "Snowflake Inc",
    "SNPS": "Synopsys Inc",
    "SNV": "Synovus Financial Corp",
    "SNX": "Synnex Corp",
    "SO": "Southern Company",
    "SOFI": "Sofi Technologies Inc",
    "SOLV": "Solventum Corporation",
    "SON": "Sonoco Products",
    "SPG": "Simon Property Group",
    "SPGI": "S&P Global Inc",
    "SPOT": "Spotify Technology S.A.",
    "SPR": "Spirit Aerosystems Holdings",
    "SRE": "Sempra",
    "SRPT": "Sarepta Therapeutics",
    "SSB": "Southstate Corp",
    "SSD": "Simpson Manufacturing Company",
    "SSNC": "SS&C Technologies",
    "ST": "Sensata Technologies Holding N.V.",
    "STAG": "Stag Industrial Inc",
    "STE": "Steris Corp",
    "STLD": "Steel Dynamics Inc",
    "STT": "State Street Corp",
    "STWD": "Starwood Property Trust",
    "STZ": "Constellation Brands Inc",
    "SUI": "Sun Communities",
    "SW": "Smurfit Westrock Plc",
    "SWK": "Stanley Black & Decker Inc",
    "SWKS": "Skyworks Solutions",
    "SYF": "Synchrony Financial",
    "SYK": "Stryker Corp",
    "SYY": "Sysco Corp",
    "T": "AT&T Inc",
    "TAP": "Molson Coors Brewing Company",
    "TDC": "Teradata Corp",
    "TDG": "Transdigm Group Inc",
    "TDY": "Teledyne Technologies Inc",
    "TEAM": "Atlassian Corp",
    "TECH": "Bio-Techne Corp",
    "TEM": "Tempus Ai",
    "TER": "Teradyne Inc",
    "TFC": "Truist Financial Corp",
    "TFSL": "Tfs Financial Corp",
    "TFX": "Teleflex Inc",
    "TGT": "Target Corp",
    "THC": "Tenet Healthcare Corp",
    "THG": "The Hanover Insurance Group",
    "THO": "Thor Industries",
    "TIGO": "Millicom International Cellular S.A.",
    "TJX": "TJX Companies",
    "TKO": "Tko Group Holdings Inc",
    "TKR": "Timken Company",
    "TLN": "Talen Energy Corporation",
    "TMO": "Thermo Fisher Scientific Inc",
    "TMUS": "T-Mobile US",
    "TNL": "Travel + Leisure Co.",
    "TOL": "Toll Brothers Inc",
    "TOST": "Toast Inc",
    "TPG": "Tpg Inc",
    "TPL": "Texas Pacific Land Trust",
    "TPR": "Tapestry Inc",
    "TREX": "Trex Company",
    "TRGP": "Targa Resources",
    "TRMB": "Trimble Navigation",
    "TROW": "T Rowe Price Group",
    "TRU": "Transunion",
    "TRV": "The Travelers Companies Inc",
    "TSCO": "Tractor Supply Company",
    "TSLA": "Tesla Inc",
    "TSN": "Tyson Foods",
    "TT": "Trane Technologies Plc",
    "TTC": "Toro Company",
    "TTD": "Trade Desk Inc",
    "TTEK": "Tetra Tech Inc",
    "TTWO": "Take-Two Interactive",
    "TW": "Tradeweb Markets Inc",
    "TWLO": "Twilio",
    "TXN": "Texas Instruments",
    "TXRH": "Texas Roadhouse Inc",
    "TXT": "Textron Inc",
    "TYL": "Tyler Technologies",
    "U": "Unity Software Inc",
    "UA": "Under Armour Inc Cl C",
    "UAA": "Under Armour",
    "UAL": "United Airlines Holdings Inc",
    "UBER": "Uber Technologies Inc",
    "UDR": "United Dominion Realty Trust",
    "UGI": "Ugi Corp",
    "UHAL": "U-Haul Holding Company",
    "UHA.B": "U-Haul Holding Series N Non-Voting",
    "UHS": "Universal Health Services",
    "UI": "Ubiquiti Networks",
    "ULTA": "Ulta Beauty Inc",
    "UNH": "Unitedhealth Group Inc",
    "UNM": "Unumprovident Corp",
    "UNP": "Union Pacific Corp",
    "UPS": "United Parcel Service",
    "URI": "United Rentals",
    "USB": "U.S. Bancorp",
    "USFD": "US Foods Holding",
    "UTHR": "United Therapeutic",
    "UWMC": "Uwm Hldg Corp",
    "V": "Visa Inc",
    "VEEV": "Veeva Systems Inc",
    "VFC": "V.F. Corp",
    "VICI": "Vici Properties Inc",
    "VIK": "Viking Holdings Ltd",
    "VIRT": "Virtu Financial Cm A",
    "VKTX": "Viking Thera",
    "VLO": "Valero Energy Corp",
    "VLTO": "Veralto Corporation",
    "VMC": "Vulcan Materials Company",
    "VMI": "Valmont Industries",
    "VNO": "Vornado Realty Trust",
    "VNOM": "Viper Energy Inc",
    "VNT": "Vontier Corp",
    "VOYA": "VOYA Financial Inc",
    "VRSK": "Verisk Analytics Inc",
    "VRSN": "Verisign Inc",
    "VRT": "Vertiv Holdings Llc.",
    "VRTX": "Vertex Pharmaceutic",
    "VST": "Vistra Energy Corp",
    "VTR": "Ventas Inc",
    "VTRS": "Viatris Inc",
    "VVV": "Valvoline Inc",
    "VZ": "Verizon Communications Inc",
    "W": "Wayfair Inc",
    "WAB": "Wabtec Corp",
    "WAL": "Western Alliance Bancorp",
    "WAT": "Waters Corp",
    "WBA": "Walgreens Boots Alliance",
    "WBD": "Discovery Inc Series A",
    "WBS": "Webster Financial Corp",
    "WCC": "Wesco International",
    "WDAY": "Workday Inc",
    "WDC": "Western Digital Corp",
    "WEC": "Wisconsin Energy Corp",
    "WELL": "Welltower Inc",
    "WEN": "Wendys Company",
    "WEX": "Wex Inc",
    "WFC": "Wells Fargo & Company",
    "WFRD": "Weatherford International Plc",
    "WH": "Wyndham Hotels & Resorts Inc",
    "WHR": "Whirlpool Corp",
    "WING": "Wingstop Inc",
    "WLK": "Westlake Corp",
    "WM": "Waste Management",
    "WMB": "Williams Companies",
    "WMS": "Advanced Drainage Systems Inc",
    "WMT": "Walmart Inc",
    "WPC": "W.P. Carey & Company Llc",
    "WRB": "W.R. Berkley Corp",
    "WSC": "Willscot Holdings Corp",
    "WSM": "Williams-Sonoma",
    "WSO": "Watsco Inc",
    "WST": "West Pharmaceutical Services",
    "WTFC": "Wintrust Financial Corp",
    "WTM": "White Mountains Insurance Group",
    "WTRG": "Essential Utilities Inc",
    "WTW": "Willis Towers Watson Public Ltd",
    "WU": "Western Union Company",
    "WWD": "Woodward Inc",
    "WY": "Weyerhaeuser Company",
    "WYNN": "Wynn Resorts Ltd",
    "XEL": "XCEL Energy Inc",
    "XOM": "Exxon Mobil Corp",
    "XP": "XP Inc",
    "XPO": "Xpo Inc",
}  # noqa
