version: "3"
services:
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
