services:
  redis-primary:
    image: redis:7.2
    container_name: redis-primary
    restart: always
    volumes:
      - redis_primary:/data
    ports:
      - 6379:6379

  redis-replica:
    image: redis:7.2
    container_name: redis-replica
    restart: always
    volumes:
      - redis_replica:/data
    ports:
      - 6380:6379
    command: redis-server --replicaof redis-primary 6379

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis-primary:6379
    ports:
      - 8081:8081
  fake-gcs:
    image: fsouza/fake-gcs-server
    container_name: fake-gcs-server
    restart: always
    ports:
      - 4443:4443
    volumes:
      - ./local_data/gcs_emulator:/data
    command: -port=4443 -public-host=localhost:4443 -scheme=http

volumes:
  redis_primary:
  redis_replica:
