"""Module containing static airline name-code data"""

# Name : IATA mapping with ICAO as backup
name_mapping = {
    "1Time Airline": "1T",
    "40-Mile Air": "Q5",
    "Ansett Australia": "AN",
    "Abacus International": "1B",
    "Aigle Azur": "ZI",
    "Aloha Airlines": "AQ",
    "American Airlines": "AA",
    "Asiana Airlines": "OZ",
    "Askari Aviation": "4K",
    "Afriqiyah Airways": "8U",
    "Allegiant Air": "G4",
    "ABSA - Aerolinhas Brasileiras": "M3",
    "Astral Aviation": "8V",
    "Air Tindi": "8T",
    "Ada Air": "ZY",
    "Adria Airways": "JP",
    "Air Europa": "UX",
    "Aero Benin": "EM",
    "Aegean Airlines": "A3",
    "Air Europe": "PE",
    "Alaska Central Express": "KO",
    "ACES Colombia": "AES",
    "Astraeus": "5W",
    "Aerosvit Airlines": "VV",
    "Air Italy": "I9",
    "Alliance Airlines": "QQ",
    "Ariana Afghan Airlines": "FG",
    "Aeroflot Russian Airlines": "SU",
    "Air Bosna": "JA",
    "Air France": "AF",
    "Air Caledonie International": "SB",
    "Air Salone": "20",
    "Air Cargo Carriers": "2Q",
    "Air Namibia": "SW",
    "Aerolitoral": "5D",
    "Air Glaciers": "7T",
    "Aviogenex": "AGX",
    "Aeroper": "PL",
    "Atlas Blue": "8A",
    "Azerbaijan Airlines": "J2",
    "Avies": "U3",
    "Airblue": "ED",
    "Airlift International": "AIR",
    "Air Berlin": "AB",
    "Air India Limited": "AI",
    "Air Bourbon": "ZB",
    "Air Atlanta Icelandic": "CC",
    "Air Tahiti Nui": "TN",
    "Arkia Israel Airlines": "IZ",
    "Air Jamaica": "JM",
    "Air One": "AP",
    "Air Sahara": "S2",
    "Air Malta": "KM",
    "Air Japan": "NQ",
    "Air Korea Co. Ltd.": "AKA",
    "Air Kiribati": "4A",
    "America West Airlines": "HP",
    "Air Wisconsin": "ZW",
    "Tatarstan Airlines": "U9",
    "Allegheny Commuter Airlines": "ALO",
    "Air Sunshine": "RSI",
    "Air Libert": "VD",
    "Air Malawi": "QM",
    "Air Sicilia": "BM",
    "ATA Airlines": "AMT",
    "Air Macau": "NX",
    "AMC Airlines": "AMV",
    "Air Seychelles": "HM",
    "AeroMéxico": "AM",
    "All Nippon Airways": "NH",
    "ANA All Nippon Airways": "NH",
    "Air Nostrum": "YW",
    "Air Niugini": "PX",
    "Air Arabia": "G9",
    "Air Canada": "AC",
    "Air Baltic": "BT",
    "Air Nippon": "EL",
    "Airnorth": "TL",
    "Air North Charter - Canada": "4N",
    "Air New Zealand": "NZ",
    "Alitalia Express": "XM",
    "Aero Flight": "GV",
    "Arrow Air": "JW",
    "Aerocondor": "2B",
    "Aires": "4C",
    "Aerolineas Argentinas": "AR",
    "Alaska Airlines": "AS",
    "Air Sinai": "4D",
    "Atlantic Southeast Airlines": "EV",
    "Astrakhan Airlines": "OB",
    "Air Tanzania": "TC",
    "Air Burkina": "2J",
    "Airlines Of Tasmania": "FO",
    "Air Saint Pierre": "PJ",
    "Austrian Airlines": "OS",
    "Air Southwest": "WOW",
    "Augsburg Airways": "IQ",
    "ATUR": "TUR",
    "Abu Dhabi Amiri Flight": "MO",
    "Aeroflot-Nord": "5N",
    "Aurigny Air Services": "GR",
    "Austral Lineas Aereas": "AU",
    "Avianca - Aerovias Nacionales de Colombia": "AV",
    "Air Vanuatu": "NF",
    "Air Bangladesh": "B9",
    "Air Mediterranee": "DR",
    "Air Moorea": "TAH",
    "Aeroline GmbH": "7E",
    "Air Wales": "6G",
    "Air Caraïbes": "TX",
    "Air India Express": "IX",
    "Air Exel": "XT",
    "AirAsia": "AK",
    "Air Asia": "AK",
    "Atlant-Soyuz Airlines": "3G",
    "Alitalia": "AZ",
    "Amaszonas": "Z8",
    "Air Zimbabwe": "UM",
    "Aserca Airlines": "R7",
    "Rossiya-Russian Airlines": "FV",
    "Pulkovo Aviation Enterprise": "FV",
    "American Eagle Airlines": "MQ",
    "AD Aviation": "VUE",
    "Air Ivoire": "VU",
    "Air Botswana": "BP",
    "Air Foyle": "GS",
    "Air Tahiti": "VT",
    "Air VIA": "VL",
    "Africa West": "FK",
    "ATRAN Cargo Airlines": "V8",
    "Air China": "CA",
    "Aero Condor Peru": "Q6",
    "Air Chathams": "CV",
    "Air Marshall Islands": "CW",
    "Access Air": "ZA",
    "Air Algerie": "AH",
    "Adam Air": "KI",
    "Air Dolomiti": "EN",
    "Aeroflot-Don": "D9",
    "Air Madrid": "NM",
    "Aer Lingus": "EI",
    "Air Finland": "OF",
    "Airfix Aviation": "FIX",
    "Air Pacific": "FJ",
    "Atlantic Airways": "RC",
    "Air Florida": "QH",
    "Air Iceland": "NY",
    "Air Philippines": "2P",
    "Air Guinee Express": "2U",
    "Air Greenland": "GL",
    "Atlas Air": "5Y",
    "Air Guyane": "GG",
    "Air Bagan": "W9",
    "Air Canada Jazz": "QK",
    "Atlasjet": "KK",
    "Air Koryo": "JS",
    "Air Astana": "KC",
    "Albanian Airlines": "LV",
    "Air Alfa": "LFA",
    "Aerolane": "XL",
    "Atlantis European Airways": "TD",
    "Air Luxor": "LK",
    "Air Mauritius": "MK",
    "Air Madagascar": "MD",
    "Air Moldova": "9U",
    "Alsie Express": "6I",
    "Air Alsie": "6I",
    "Air Plus Comet": "A7",
    "Astair": "8D",
    "Aero Contractors": "AJ",
    "Aeropelican Air Services": "OT",
    "Aer Arann": "RE",
    "Air Austral": "UU",
    "Asian Spirit": "6K",
    "Air Afrique": "RK",
    "Airlinair": "A5",
    "Aero Lanka": "QL",
    "Armavia": "U8",
    "AeroRep": "P5",
    "Aero-Service": "BF",
    "Aerosur": "5L",
    "Aeronorte": "RTE",
    "Avient Aviation": "Z3",
    "Aircompany Yakutia": "R3",
    "Aeromar": "VW",
    "Arkefly": "OR",
    "Airlines PNG": "CG",
    "AirTran Airways": "FL",
    "Air Transat": "TS",
    "Avialeasing Aviation Company": "EC",
    "Tyrolean Airways": "TYR",
    "Aerolineas Galapagos (Aerogal)": "2K",
    "Alrosa Mirny Air Enterprise": "6R",
    "British Airways": "BA",
    "Biman Bangladesh Airlines": "BG",
    "Belair Airlines": "4T",
    "Bahamasair": "UP",
    "Balkan Bulgarian Airlines": "LZ",
    "British International Helicopters": "BS",
    "BF-Lento OY": "BKF",
    "Bangkok Airways": "PG",
    "Blue1": "KF",
    "Baltic Airlines": "BLL",
    "Bearskin Lake Air Service": "JV",
    "Bellview Airlines": "B3",
    "bmi": "BD",
    "bmi British Midland": "BD",
    "bmibaby": "WW",
    "Bemidji Airlines": "CH",
    "British Midland Regional": "BMR",
    "Blue Panorama Airlines": "BV",
    "Budapest Aircraft Services/Manx2": "BPS",
    "Bering Air": "8E",
    "Brazilian Air Force": "BRS",
    "Belavia Belarusian Airlines": "B2",
    "Metro Batavia": "7P",
    "Berjaya Air": "J8",
    "Blue Wings": "QW",
    "Brit Air": "DB",
    "Brussels Airlines": "SN",
    "SN Brussels Airlines": "SN",
    "Binter Canarias": "NT",
    "Blue Air": "0B",
    "British Mediterranean Airways": "KJ",
    "Bulgaria Air": "FB",
    "Barents AirLink": "8N",
    "CAL Cargo Air Lines": "5C",
    "Calima Aviacion": "XG",
    "Canadian Airlines": "CP",
    "Canadian North": "5T",
    "Cape Air": "9K",
    "Caribbean Airlines": "BW",
    "Carpatair": "V3",
    "Caspian Airlines": "RV",
    "Cathay Pacific": "CX",
    "Cayman Airways": "KX",
    "Cebu Pacific": "5J",
    "Central Connect Airlines": "CCG",
    "Centralwings": "C0",
    "Charter Air": "CHW",
    "Chautauqua Airlines": "RP",
    "China Airlines": "CI",
    "China Eastern Airlines": "MU",
    "China Southern Airlines": "CZ",
    "China United Airlines": "HR",
    "Yunnan Airlines": "3Q",
    "Cimber Air": "QI",
    "Cirrus Airlines": "C9",
    "City Airline": "CF",
    "City Connexion Airlines": "G3",
    "CityJet": "WX",
    "BA CityFlyer": "CJ",
    "Click Airways": "CGK",
    "Coastal Air": "DQ",
    "Colgan Air": "9L",
    "Comair": "MN",
    "CommutAir": "C5",
    "Comores Airlines": "KR",
    "Compass Airlines": "CP",
    "Condor Flugdienst": "DE",
    "Consorcio Aviaxsa": "6A",
    "Contact Air": "C3",
    "Contactair": "C3",
    "Continental Airlines": "CO",
    "Continental Express": "CO",
    "Continental Micronesia": "CS",
    "Conviasa": "V0",
    "Copa Airlines": "CM",
    "Copterline": "AAQ",
    "Corendon Airlines": "CAI",
    "Corsairfly": "SS",
    "Corse-Mediterranee": "XK",
    "Crest Aviation": "CAN",
    "Croatia Airlines": "OU",
    "Crown Airways": "CRO",
    "Cubana de Aviación": "CU",
    "Cyprus Airways": "CY",
    "Cyprus Turkish Airlines": "YK",
    "Czech Airlines": "OK",
    "CSA Czech Airlines": "OK",
    "DAT Danish Air Transport": "DX",
    "Daallo Airlines": "D3",
    "Dalavia": "H8",
    "Darwin Airline": "0D",
    "Delta Aerotaxi": "DEA",
    "Delta Air Lines": "DL",
    "Denim Air": "DNM",
    "Deutsche Bahn": "2A",
    "Djibouti Airlines": "D8",
    "Dniproavia": "UDN",
    "Dominicana de Aviaci": "DO",
    "Domodedovo Airlines": "E3",
    "DonbassAero": "5D",
    "Dragonair": "KA",
    "Druk Air": "KB",
    "Dubrovnik Air": "DBK",
    "Dutch Antilles Express": "DNL",
    "dba": "DI",
    "EVA Air": "BR",
    "Eagle Air": "H7",
    "East African": "QU",
    "Eastern Airways": "T3",
    "Eastland Air": "DK",
    "Ecuavia": "ECU",
    "Edelweiss Air": "WK",
    "Egyptair": "MS",
    "El Al Israel Airlines": "LY",
    "El-Buraq Air Transport": "UZ",
    "Emirates": "EK",
    "Emirates Airlines": "EK",
    "Empresa Ecuatoriana De Aviacion": "EU",
    "Eritrean Airlines": "B8",
    "Estonian Air": "OV",
    "Ethiopian Airlines": "ET",
    "Etihad Airways": "EY",
    "Euro Exec Express": "RZ",
    "Eurocypria Airlines": "UI",
    "Eurofly Service": "GJ",
    "Eurolot": "K2",
    "European Air Express": "EA",
    "Eurowings": "EW",
    "Evergreen International Airlines": "EZ",
    "Excel Airways": "JN",
    "Excel Charter": "XEL",
    "Express One International": "EO",
    "ExpressJet": "XE",
    "easyJet": "U2",
    "EasyJet Airline": "U2",
    "Far Eastern Air Transport": "EF",
    "Finnair": "AY",
    "Finncomm Airlines": "FC",
    "Firefly": "FY",
    "First Air": "7F",
    "First Choice Airways": "DP",
    "Flightline": "B5",
    "Florida West International Airways": "RF",
    "AirAsia X": "D7",
    "FlyAsianXpress": "D7",
    "FlyLal": "TE",
    "FlyNordic": "LF",
    "Flybaboo": "F7",
    "Flybe": "BE",
    "Flyglobespan": "B4",
    "Flyhy Cargo Airlines": "FYH",
    "Formosa Airlines": "VY",
    "Freedom Air": "FP",
    "Freedom Airlines": "FRL",
    "Frontier Airlines": "F9",
    "Frontier Flying Service": "2F",
    "GB Airways": "GT",
    "Garuda Indonesia": "GA",
    "Gazpromavia": "4G",
    "Georgian Airways": "A9",
    "Georgian National Airlines": "QB",
    "Germania": "ST",
    "Germanwings": "4U",
    "Ghana International Airlines": "G0",
    "Go Air": "G8",
    "GoJet Airlines": "G7",
    "Gol Transportes Aéreos": "G3",
    "Golden Air": "DC",
    "Great Lakes Airlines": "ZK",
    "Grupo TACA": "TA",
    "TACA": "TA",
    "Gulf Air": "GFA",
    "Gulf Air Bahrain": "GF",
    "Gulfstream International Airlines": "GFT",
    "Hageland Aviation Services": "H6",
    "Hainan Airlines": "HU",
    "Haiti Ambassador Airlines": "2T",
    "Hamburg International": "4R",
    "TUIfly": "X3",
    "Hapagfly": "HF",
    "Hawaiian Airlines": "HA",
    "Hawkair": "BH",
    "Heli France": "8H",
    "Helijet": "JB",
    "Hellas Jet": "T4",
    "Hello": "HW",
    "Helvetic Airways": "2L",
    "Hex'Air": "UD",
    "Highland Airways": "HWY",
    "Hokkaido International Airlines": "HD",
    "Hong Kong Airlines": "HX",
    "Hong Kong Express Airways": "UO",
    "Horizon Air": "QX",
    "Horizon Airlines": "BN",
    "Iberia Airlines": "IB",
    "Iberworld": "TY",
    "Ibex Airlines": "FW",
    "Icar Air": "RAC",
    "Icelandair": "FI",
    "Imair Airlines": "IK",
    "IndiGo Airlines": "6E",
    "Indian Airlines": "IC",
    "Indigo": "I9",
    "Indonesia AirAsia": "QZ",
    "Indonesian Airlines": "IO",
    "Interair South Africa": "D6",
    "Interavia Airlines": "ZA",
    "Interlink Airlines": "ID",
    "Intersky": "3L",
    "Iran Air": "IR",
    "Iran Aseman Airlines": "EP",
    "Iraqi Airways": "IA",
    "Island Airlines": "IS",
    "Cargo Plus Aviation": "8L",
    "Islas Airways": "IF",
    "Islena De Inversiones": "WC",
    "Israir": "6H",
    "Itek Air": "GI",
    "JAL Express": "JC",
    "JALways": "JO",
    "Japan Airlines": "JL",
    "JAL Japan Airlines": "JL",
    "Japan Asia Airways": "EG",
    "Japan Transocean Air": "NU",
    "Jat Airways": "JU",
    "Jazeera Airways": "J9",
    "Jeju Air": "7C",
    "Jet Airways": "QJ",
    "Jetstar Asia Airways": "3K",
    "Jet2.com": "LS",
    "Jet4You": "8J",
    "JetBlue Airways": "B6",
    "Jetairfly": "JF",
    "Jetflite": "JEF",
    "Jetstar Airways": "JQ",
    "Juneyao Airlines": "HO",
    "KD Avia": "KD",
    "KLM Cityhopper": "WA",
    "KLM Royal Dutch Airlines": "KL",
    "Kam Air": "RQ",
    "Kavminvodyavia": "KV",
    "Kendell Airlines": "KDA",
    "Kenmore Air": "M5",
    "Kenya Airways": "KQ",
    "Kingfisher Airlines": "IT",
    "Kish Air": "Y9",
    "Kogalymavia Air Company": "7K",
    "Korean Air": "KE",
    "Kosmos": "KSM",
    "Krasnojarsky Airlines": "7B",
    "Kuban Airlines": "GW",
    "Kuwait Airways": "KU",
    "Kuzu Airlines Cargo": "GO",
    "LACSA": "LR",
    "LAN Airlines": "LA",
    "LAN Argentina": "4M",
    "LAN Express": "LU",
    "LAN Peru": "LP",
    "LOT Polish Airlines": "LO",
    "LTE International Airways": "XO",
    "LTU Austria": "L3",
    "LTU International": "LT",
    "Lao Airlines": "QV",
    "LatCharter": "LTC",
    "Lauda Air": "NG",
    "Leeward Islands Air Transport": "LI",
    "Libyan Arab Airlines": "LN",
    "Linhas A": "LM",
    "Lion Mentari Airlines": "JT",
    "Luftfahrtgesellschaft Walter": "HE",
    "Lufthansa": "LH",
    "Lufthansa Cargo": "LH",
    "Lufthansa CityLine": "CL",
    "Lufttransport": "L5",
    "Luxair": "LG",
    "L": "MJ",
    "MasAir": "M7",
    "MAT Macedonian Airlines": "IN",
    "MIAT Mongolian Airlines": "OM",
    "MNG Airlines": "MB",
    "Macair Airlines": "CC",
    "Maersk": "DM",
    "Mahan Air": "W5",
    "Malaysia Airlines": "MH",
    "Malta Air Charter": "R5",
    "Malév": "MA",
    "Mandala Airlines": "RI",
    "Mandarin Airlines": "AE",
    "Mango": "JE",
    "Martinair": "MP",
    "Maxair": "8M",
    "Maya Island Air": "MW",
    "Meridiana": "IG",
    "Merpati Nusantara Airlines": "MZ",
    "Mesa Airlines": "YV",
    "Mesaba Airlines": "XJ",
    "Mexicana de Aviaci": "MX",
    "Middle East Airlines": "ME",
    "Midway Airlines": "JI",
    "Midwest Airlines": "YX",
    "Midwest Airlines (Egypt)": "MY",
    "Moldavian Airlines": "2M",
    "Monarch Airlines": "ZB",
    "Myway Airlines": "8I",
    "Montenegro Airlines": "YM",
    "Morningstar Air Express": "MAL",
    "Moskovia Airlines": "3R",
    "Motor Sich": "M9",
    "MyTravel Airways": "VZ",
    "Myanma Airways": "UB",
    "Myanmar Airways International": "8M",
    "Myflug": "MYA",
    "Nasair": "UE",
    "National Jet Systems": "NC",
    "Nationwide Airlines": "CE",
    "Nauru Air Corporation": "ON",
    "Nepal Airlines": "RA",
    "NetJets": "1I",
    "New England Airlines": "EJ",
    "NextJet": "2N",
    "Niki": "HG",
    "Nok Air": "DD",
    "Norfolk County Flight College": "NCF",
    "North American Airlines": "NTM",
    "North American Charters": "HMR",
    "Northern Dene Airways": "U7",
    "Northwest Airlines": "NW",
    "Northwestern Air": "J3",
    "Norwegian Air Shuttle": "DY",
    "Norwegian Aviation College": "TFN",
    "Nouvel Air Tunisie": "BJ",
    "Novair": "1I",
    "Nas Air": "XY",
    "Oasis Hong Kong Airlines": "O8",
    "Ocean Air": "BCN",
    "Oceanair": "O6",
    "Oceanic Airlines": "O2",
    "Olympic Airlines": "OA",
    "Oman Air": "WY",
    "Omni Air International": "OY",
    "One Two Go Airlines": "OTG",
    "Onur Air": "8Q",
    "Orenburg Airlines": "R2",
    "Orient Thai Airlines": "OX",
    "Origin Pacific Airways": "QO",
    "Ostfriesische Lufttransport": "OL",
    "Overland Airways": "OJ",
    "Ozjet Airlines": "O7",
    "PAN Air": "PV",
    "PB Air": "9Q",
    "PLUNA": "PU",
    "PMTair": "U4",
    "Jetstar Pacific": "BL",
    "Pacific Airlines": "BL",
    "Pacific Coastal Airline": "8P",
    "Pacific East Asia Cargo Airlines": "Q8",
    "Pacific Island Aviation": "PSA",
    "Pacific Wings": "LW",
    "Pakistan International Airlines": "PK",
    "PIA Pakistan International": "PK",
    "Paramount Airways": "I7",
    "Passaredo Transportes Aereos": "PTB",
    "Pegasus Airlines": "PC",
    "Peninsula Airways": "KS",
    "Philippine Airlines": "PR",
    "Piedmont Airlines (1948-1989)": "PI",
    "Pinnacle Airlines": "9E",
    "Polet": "POT",
    "Polynesian Airlines": "PH",
    "Porter Airlines": "PD",
    "Portugalia": "NI",
    "Potomac Air": "BK",
    "Precision Air": "PW",
    "Privatair": "PTI",
    "Proflight Commuter Services": "P0",
    "Qantas": "QF",
    "Qantas Airways": "QF",
    "Qatar Airways": "QR",
    "RACSA": "R6",
    "Kinloss Flying Training Unit": "KIN",
    "Regional Airlines": "FN",
    "Regional Express": "ZL",
    "Republic Airlines": "RW",
    "Republic Express Airlines": "RH",
    "Rossiya": "R4",
    "Air Rarotonga": "GZ",
    "Royal Air Maroc": "AT",
    "Royal Brunei Airlines": "BI",
    "Royal Jordanian": "RJ",
    "Royal Phnom Penh Airways": "PPW",
    "Rusline": "RLU",
    "Rwandair Express": "WB",
    "Ryan Air Services": "RYA",
    "Ryan International Airlines": "RD",
    "Ryanair": "FR",
    "Régional": "YS",
    "SATA International": "S4",
    "South African Airways": "SA",
    "SAA South African Airways": "SA",
    "Shaheen Air International": "NL",
    "Scandinavian Airlines System": "SK",
    "SAS Scandinavian Airlines": "SK",
    "ScotAirways": "SAY",
    "S7 Airlines": "S7",
    "Sibir Airlines": "S7",
    "Seaborne Airlines": "BB",
    "Scenic Airlines": "SCE",
    "SriLankan Airlines": "UL",
    "Sun Country Airlines": "SY",
    "Southeast Air": "SEA",
    "Sky Express": "XW",
    "Spicejet": "SG",
    "Star Flyer": "7G",
    "Skagway Air Service": "N5",
    "Sahara Airlines": "SHD",
    "SATA Air Acores": "SP",
    "Singapore Airlines": "SQ",
    "Sibaviatrans": "5M",
    "Skynet Airlines": "SI",
    "Sriwijaya Air": "SJ",
    "Sama Airlines": "ZS",
    "Singapore Airlines Cargo": "SQ",
    "Siem Reap Airways": "FT",
    "South East Asian Airlines": "DG",
    "Skyservice Airlines": "5G",
    "Servicios de Transportes A": "FS",
    "Sudan Airways": "SD",
    "Saudi Arabian Airlines": "SV",
    "Southwest Airlines": "WN",
    "Southern Winds Airlines": "A4",
    "Swiss International Air Lines": "LX",
    "Swiss Airlines": "LX",
    "Swiss European Air Lines": "SWU",
    "Swiss European": "",
    "Swe Fly": "WV",
    "SunExpress": "XQ",
    "Syrian Arab Airlines": "RB",
    "Skywalk Airlines": "AL",
    "Shandong Airlines": "SC",
    "SAS Braathens": "CNO",
    "Spring Airlines": "9S",
    "Sichuan Airlines": "3U",
    "Shanghai Airlines": "FM",
    "Shenzhen Airlines": "ZH",
    "Sun D'Or": "7L",
    "SkyEurope": "NE",
    "Sky Europe Airlines": "HSK",
    "Spanair": "JK",
    "Spirit Airlines": "NK",
    "SATENA": "9R",
    "Skywest Airlines": "OZW",
    "Santa Barbara Airlines": "S3",
    "Sky Airline": "H2",
    "SkyWest": "OO",
    "Skyways Express": "JZ",
    "Skymark Airlines": "BC",
    "SilkAir": "MI",
    "Surinam Airways": "PY",
    "Sterling Airlines": "NB",
    "Skynet Asia Airways": "6J",
    "Solomon Airlines": "IE",
    "Southern Airways": "SOU",
    "Saratov Aviation Division": "6W",
    "Sat Airlines": "HZ",
    "South Pacific Island Airways": "SPI",
    "Shuttle America": "S5",
    "Scat Air": "DV",
    "TAME": "EQ",
    "TAM Brazilian Airlines": "JJ",
    "TAP Portugal": "TP",
    "TAP Air Portugal": "TP",
    "Tunisair": "TU",
    "Thai Air Cargo": "T2",
    "Thomas Cook Airlines": "MT",
    "Trigana Air Service": "TGN",
    "Tiger Airways": "TR",
    "Tigerair Australia": "TT",
    "Thai Airways International": "TG",
    "Turk Hava Kurumu Hava Taksi Isletmesi": "THK",
    "Thai AirAsia": "FD",
    "Thai Air Asia": "FD",
    "Turkish Airlines": "TK",
    "Tajikistan International Airlines": "TIL",
    "Twin Jet": "T7",
    "Translift Airways": "TLA",
    "Trans Mediterranean Airlines": "TL",
    "Tiara Air": "3P",
    "Thomsonfly": "BY",
    "Tropic Air": "PM",
    "TAMPA": "QT",
    "TransAsia Airways": "GE",
    "Transavia Holland": "HV",
    "TACV": "VR",
    "Transwest Air": "9T",
    "Transaero Airlines": "UN",
    "Turkmenistan Airlines": "T5",
    "Turkmenhovayollary": "T5",
    "Tuninter": "UG",
    "Travel Service": "QS",
    "TUIfly Nordic": "6B",
    "TAAG Angola Airlines": "DT",
    "Turkish Air Force": "HVK",
    "TAM Mercosur": "PZ",
    "Trans States Airlines": "AX",
    "Tarom": "RO",
    "Turan Air": "3T",
    "TRIP Linhas A": "8R",
    "USA3000 Airlines": "U5",
    "United Airlines": "UA",
    "United Air Charters": "UAC",
    "Ural Airlines": "U6",
    "UM Airlines": "UF",
    "US Airways": "US",
    "US Helicopter": "USH",
    "UTair Aviation": "UT",
    "United States Air Force": "AIO",
    "Uzbekistan Airways": "HY",
    "Ukraine International Airlines": "PS",
    "US Helicopter Corporation": "UH",
    "Valuair": "VF",
    "Vasco Air": "VFC",
    "Vietnam Airlines": "VN",
    "VIM Airlines": "NN",
    "Volaris": "Y4",
    "Volga-Dnepr Airlines": "VI",
    "Virgin America": "VX",
    "Virgin Express": "TV",
    "Virgin Nigeria Airways": "VK",
    "Virgin Atlantic Airways": "VS",
    "Viva Macau": "ZG",
    "Volare Airlines": "VE",
    "Vueling Airlines": "VY",
    "Vladivostok Air": "XF",
    "Varig Log": "LC",
    "Virgin Australia": "VA",
    "VRG Linhas Aereas": "RG",
    "Varig": "RG",
    "VASP": "VP",
    "VLM Airlines": "VG",
    "Wayraper": "7W",
    "WebJet Linhas A": "WJ",
    "Welcome Air": "2W",
    "West Coast Air": "8O",
    "WestJet": "WS",
    "Western Airlines": "WA",
    "Widerøe": "WF",
    "Wind Jet": "IV",
    "Wings Air": "IW",
    "Wizz Air": "W6",
    "Wizz Air Hungary": "8Z",
    "World Airways": "WO",
    "XL Airways France": "SE",
    "Xiamen Airlines": "MF",
    "Yamal Airlines": "YL",
    "Yemenia": "IY",
    "Yuzhmashavia": "UMK",
    "Zanair": "TAN",
    "Zoom Airlines": "Z4",
    "Maldivian Air Taxi": "8Q",
    "Royal Air Cambodge": "VJ",
    "Air Mandalay": "6T",
    "Air Busan": "BX",
    "SkyExpress": "XW",
    "Globus": "GH",
    "Air Kazakhstan": "9Y",
    "Japan Air System": "JD",
    "EasyJet (DS)": "DS",
    "Star Peru (2I)": "2I",
    "Carnival Air Lines": "KW",
    "United Airways": "4H",
    "Fly540": "5H",
    "Transavia France": "TO",
    "Island Air (WP)": "WP",
    "Uni Air": "B7",
    "Gomelavia": "YD",
    "Red Wings": "WZ",
    "Avialinii 400": "WZ",
    "TUIfly (X3)": "11",
    "Felix Airways": "FU",
    "Kostromskie avialinii": "K1",
    "Greenfly": "XX",
    "Tajik Air": "7J",
    "Air Mozambique": "TM",
    "ELK Airways": "ELK",
    "Gabon Airlines": "GY",
    "MCA Airlines": "MCA",
    "Maldivo Airlines": "ML",
    "Virgin Pacific": "VH",
    "Zest Air": "Z2",
    "Yangon Airways": "HK",
    "Eastar Jet": "ZE",
    "Jin Air": "LJ",
    "Air Arabia Maroc": "3O",
    "Baltic Air lines": "B1",
    "Ciel Canadien": "YC",
    "Canadian National Airways": "CN",
    "Epic Holiday": "FA",
    "Epic Holidays": "FA",
    "Indochina Airlines": "AXC",
    "Air Comet Chile": "3I",
    "German Air Force - FLB": "FLB",
    "Line Blue": "L8",
    "FlyLAL Charters": "LLC",
    "Salzburg arrows": "SZ",
    "SZA": "SZ",
    "Texas Wings": "TQ",
    "Dennis Sky": "DH",
    "Dennis Sky Holding": "DH",
    "Zz": "ZZ",
    "Atifly": "A1",
    "Aerolineas heredas santa maria": "SZB",
    "Ciao Air": "99",
    "Jc royal.britannica": "JRB",
    "Pal airlines": "5P",
    "CanXpress": "C1",
    "Danube Wings (V5)": "V5",
    "Sharp Airlines": "SH",
    "CanXplorer": "C2",
    "Click (Mexicana)": "QA",
    "World Experience Airline": "W1",
    "WEA": "W1",
    "ALAK": "J4",
    "Air Choice One": "3E",
    "Tianjin Airlines": "GCR",
    "China United": "KN",
    "Locair": "ZQ",
    "Safi Airlines": "4Q",
    "SeaPort Airlines": "K5",
    "Salmon Air": "S6",
    "Bobb Air Freight": "01",
    "Star1 Airlines": "V9",
    "Pelita": "6D",
    "Alaska Seaplane Service": "J5",
    "Enerjet": "ENJ",
    "MexicanaLink": "I6",
    "Island Spirit": "IP",
    "TACA Peru": "T0",
    "Orbest": "OBS",
    "Southern Air Charter": "SOA",
    "SVG Air": "SVG",
    "Air Century": "CEY",
    "Pan Am World Airways Dominicana": "7Q",
    "PAWA Dominicana": "7Q",
    "Primera Air": "PF",
    "Air Antilles Express": "3S",
    "Sol Lineas Aereas": "OLS",
    "Regional Paraguaya": "P7",
    "VIP Ecuador": "V6",
    "Transportes Aereos Cielos Andinos": "NDN",
    "Peruvian Airlines": "P9",
    "EasyFly": "EFY",
    "Polar Airlines": "ЯП",
    "Catovair": "OC",
    "Andalus Lineas Aereas": "ANU",
    "Air 26": "DCD",
    "Mauritania Airways": "MTW",
    "CEIBA Intercontinental": "CEL",
    "Halcyonair": "7Z",
    "Business Aviation": "4P",
    "Compagnie Africaine d\\\\'Aviation": "E9",
    "Zambia Skyways": "K8",
    "AlMasria Universal Airlines": "UJ",
    "EgyptAir Express": "MSE",
    "SmartLynx Airlines": "6Y",
    "Air Italy Egypt": "EUD",
    "KoralBlue Airlines": "K7",
    "Wind Rose Aviation": "WRC",
    "Elysian Airlines": "E4",
    "Sevenair": "SEN",
    "Hellenic Imperial Airways": "HT",
    "Amsterdam Airlines": "WD",
    "Arik Niger": "Q9",
    "Dana Air": "DA",
    "STP Airways": "8F",
    "Med Airways": "7Y",
    "Skyjet Airlines": "UQ",
    "Air Volga": "G6",
    "Transavia Denmark": "TDK",
    "Royal Falcon": "RL",
    "Euroline": "4L",
    "Turkuaz Airlines": "TRK",
    "Athens Airways": "ZF",
    "Viking Hellas": "VQ",
    "Norlandair": "FNA",
    "Flugfelag Vestmannaeyja": "FVM",
    "Starline.kz": "DZ",
    "Lugansk Airlines": "L7",
    "Gryphon Airlines": "6P",
    "Gadair European Airlines": "GP",
    "Spirit of Manila Airlines": "SM",
    "Chongqing Airlines": "OQ",
    "Grand China Air": "GDC",
    "West Air China": "PN",
    "QatXpress": "C3",
    "qatXpress": "C3",
    "OneChina": "1C",
    "NordStar Airlines": "Y7",
    "Joy Air": "JR",
    "Air India Regional": "CD",
    "MDLR Airlines": "9H",
    "Jagson Airlines": "JGN",
    "Maldivian": "Q2",
    "Xpressair": "XN",
    "Strategic Airlines": "VC",
    "Fars Air Qeshm": "QFZ",
    "Eastok Avia": "EAA",
    "Jupiter Airlines": "JPU",
    "Vision Air International": "VIS",
    "Al-Naser Airlines": "NA",
    "Fuji Dream Airlines": "JH",
    "Korea Express Air": "KEA",
    "Eznis Airways": "EZA",
    "Pacific Flier": "PFL",
    "Syrian Pearl Airlines": "PSB",
    "SGA Airlines": "5E",
    "Air2there": "F8",
    "Avianova (Russia)": "AO",
    "Parmiss Airlines (IPV)": "PA",
    "EuropeSky": "ES",
    "BRAZIL AIR": "GB",
    "Homer Air": "MR",
    "Homer Sky": "MR",
    "PanAm World Airways": "WQ",
    "Virginwings": "YY",
    "KSY": "KY",
    "Kreta Sky": "KY",
    "Buquebus Líneas Aéreas": "BQ",
    "SOCHI AIR": "CQ",
    "SOCHI": "CQ",
    "Wizz Air Ukraine": "WU",
    "88": "47",
    "LCM AIRLINES": "LQ",
    "Cambodia Angkor Air (K6)": "K6",
    "Royal European Airlines": "69",
    "Azul": "AD",
    "Azul Linhas Aéreas Brasileiras": "AD",
    "LSM Airlines": "PQ",
    "slowbird": "PQ",
    "Zapolyarie Airlines": "PZY",
    "Zapolyarye Airlines": "",
    "LionXpress": "C4",
    "lionXpress": "C4",
    "Genesis": "GK",
    "Congo Express": "XZ",
    "Fly Dubai": "FZ",
    "Domenican Airlines": "D1",
    "Domenican": "D1",
    "Aereonautica militare": "JY",
    "Kal Star Aviation": "KLS",
    "LSM AIRLINES ": "YZ",
    "Russian. Yours Air Lines ": "YZ",
    "UTair-Express": "UR",
    "Huaxia": "G5",
    "HUAXIA": "G5",
    "Zabaykalskii Airlines": "ZP",
    "Baikal Airlines": "ZP",
    "CBM America": "XBM",
    "Marysya Airlines": "M4",
    "MARYSYA AIRLINES": "M4",
    "N1": "N1",
    "Airlink (SAA)": "4Z",
    "Westfalia Express VA": "WFX",
    "JobAir": "3B",
    "Black Stallion Airways": "BZ",
    "German International Air Lines": "GM",
    "Germanair": "GM",
    "TrasBrasil": "TB",
    "TransBrasil Airlines": "TH",
    "China SSS": "9C",
    "Chunqiu Airlines": "9C",
    "AIR INDOCHINE": "IIA",
    "Happy Air": "HPY",
    "Solar Air": "SRB",
    "Air Mekong": "P8",
    "Harbour Air (Priv)": "H3",
    "Air Hamburg (AHO)": "HH",
    "ZABAIKAL AIRLINES": "Z6",
    "ZABAIKAL ": "Z6",
    "TransHolding": "TI",
    "Trans": "TI",
    "SUR Lineas Aereas": "SZZ",
    "Yeti Airways": "YT",
    "Yellowstone Club Private Shuttle": "Y1",
    "Caucasus Airlines": "NS",
    "Serbian Airlines": "S1",
    "Windward Islands Airways": "WM",
    "TransHolding System": "YO",
    "CCML Airlines": "CB",
    "Small Planet Airlines": "ELC",
    "Fly Brasil": "F1",
    "CB Airways UK ( Interliging Flights )": "1F",
    "Fly Colombia ( Interliging Flights )": "3F",
    "Trans Pas Air": "T6",
    "KMV": "МИ",
    "Himalayan Airlines": "HC",
    "Himalaya": "HC",
    "Indya Airline Group": "G1",
    "Indya1": "G1",
    "Sunwing": "WG",
    "Turkish Wings Domestic": "TWD",
    "Japan Regio": "ZX",
    "OCEAN AIR CARGO": "IXO",
    "Norte Lineas Aereas": "N0",
    "NORTE": "N0",
    "Austral Brasil": "W7",
    "Austral Brasil lineas aereas": "W7",
    "PEGASUS AIRLINES-": "H9",
    "Camair-co": "QC",
    "Sky Regional": "RS",
    "Air Canada Express": "RS",
    "LSM International ": "II",
    "Moskva-air": "II",
    "Baikotovitchestrian Airlines ": "BU",
    "Luchsh Airlines ": "L4",
    "Air luch": "L4",
    "ENTERair": "QQQ",
    "Air Cargo Germany": "6U",
    "Mongolian International Air Lines ": "7M",
    "Mongol Air ": "7M",
    "Tway Airlines": "TW",
    "Papillon Grand Canyon Helicopters": "HI",
    "Jusur airways": "JX",
    "NEXT Brasil": "XB",
    "NEXT": "XB",
    "AeroWorld ": "W4",
    "Sovet Air ": "W4",
    "GNB Linhas Aereas": "GN",
    "Usa Sky Cargo": "E1",
    "USky": "E1",
    "Hankook Airline": "HN",
    "REDjet": "Z7",
    "Red Jet Andes": "PT",
    "Red Jet Canada": "QY",
    "Sprintair": "0G",
    "Red Jet Mexico": "4X",
    "Marusya Airways": "Y8",
    "Marusya Air": "Y8",
    "Era Alaska": "7H",
    "AirRussia": "R8",
    "RussianConector": "R8",
    "Hankook Air US": "H1",
    "Carpatair Flight Training": "SMW",
    "I-Fly": "H5",
    "Whitejets": "WTJ",
    "VickJet": "KT",
    "BVI Airways": "XV",
    "Hamburg Airways": "HAY",
    "Salsa d\\\\'Haiti": "SO",
    "Zambezi Airlines (ZMA)": "ZJ",
    "Kan Air": "KND",
    "Air Cudlua": "CUD",
    "Polet Airlines (Priv)": "YQ",
    "Air Explore": "AXE",
    "12 North": "12",
    "Holidays Czech Airlines": "HCC",
    "Comtel Air": "COE",
    "Mint Airways": "MIC",
    "Orbit Airlines": "OBT",
    "Orbit": "",
    "Air Bucharest": "BUR",
    "AlbaStar": "LAV",
    "Mauritania Airlines International": "L6",
    "MAT Airways": "6F",
    "Asian Wings Airways": "AW",
    "Air Arabia Egypt": "E5",
    "Eagles Airlines": "EGS",
    "YES Airways": "YEP",
    "Alitalia Cityliner": "CT",
    "Direct Aero Services": "DSV",
    "Medallion Air": "MDP",
    "Orchid Airlines": "OI",
    "Asia Wings": "Y5",
    "Georgian International Airlines": "GNN",
    "Air Batumi": "BTM",
    "Skywest Australia": "XR",
    "Nile Air": "NP",
    "Feeder Airlines": "FDD",
    "Senegal Airlines": "DN",
    "Starbow Airlines": "S9",
    "Copenhagen Express": "0X",
    "BusinessAir": "8B",
    "SENIC AIRLINES": "YR",
    "XOJET": "XOJ",
    "Sky Wing Pacific": "C7",
    "Bateleur Air": "BEU",
    "Air Indus": "PP",
    "Indus Airlines Pak": "PP",
    "Orbit International Airlines": "OAI",
    "Orbit Regional Airlines": "OAR",
    "Orbit Atlantic Airways": "OAN",
    "Volotea": "VOO",
    "Peach Aviation": "MM",
    "Helitt Líneas Aéreas": "HTH",
    "Russia State Transport": "RSD",
    "Federal State Budget Inst": "",
    "Malaysia Wings": "MWI",
    "Aviabus": "U1",
    "Michael Airlines": "DF",
    "Javi": "DF",
    "Korongo Airlines": "ZC",
    "Indonesia Sky": "I5",
    "Aws express": "B0",
    "Southjet": "76",
    "Southjet connect": "77",
    "Southjet cargo": "78",
    "Iberia Express": "I2",
    "Interjet (ABC Aerolineas)": "4O",
    "AirOnix": "OG",
    "Nordic Global Airlines": "NJ",
    "Scoot": "TR",
    "Hi Fly (5K)": "5K",
    "China Northwest Airlines (WH)": "WH",
    "Zenith International Airline": "ZN",
    "Zenith": "ZN",
    "Orbit Airlines Azerbaijan": "O1",
    "Orbit Azerbaijan": "O1",
    "Air Alps Aviation (A6)": "A6",
    "Flying kangaroo Airline": "FKA",
    "Skippy": "",
    "RusJet": "RSJ",
    "VietJet Air": "VJC",
    "VietJet": "",
    "Patriot Airways": "P4",
    "Vision Airlines (V2)": "V2",
    "BQB Lineas Aereas": "5Q",
    "Buquebus": "5Q",
    "AirAsia Japan": "WAJ",
    "Yellowtail": "YE",
    "Royal Airways": "KG",
    "Royal Inc.": "KG",
    "FlyHigh Airlines Ireland (FH)": "FH",
    "Executive AirShare": "XSR",
    "Hebei Airlines": "HBH",
    "Air KBZ": "KBZ",
    "Aero VIP (2D)": "2D",
    "Yangon Airways Ltd.": "YH",
    "T.J. Air": "TJ",
    "SkyWork Airlines ": "SX",
    "Maastricht Airlines": "W2",
    "Euro Jet": "24",
    "Ukraine Atlantic": "UAT",
    "Nesma Airlines": "NMA",
    "East Horizon": "EHN",
    "Air Majoro": "MJP",
    "Rotana Jet": "RJD",
    "SOCHI AIR CHATER": "Q3",
    "Sochi Air ": "Q3",
    "Denim Air ": "J7",
    "FlyNonstop": "J7",
    "Malindo Air": "OD",
    "Hermes Airlines": "HRM",
    "Flightlink Tanzania": "Z9",
    "Flightlink": "Z9",
    "IzAvia": "I8",
    "Катэкавиа": "КТК",
    "Псковавиа": "PKV",
    "Псков Авиа": "",
    "Maryland Air": "M1",
    "Maryland": "M1",
    "Insel Air (7I/INC) (Priv)": "7I",
    "VivaColombia": "5Z",
    "Flybe Finland Oy": "FCM",
    "Bingo Airways": "BGY",
    "Bingo": "",
    "Bluebird Airways (BZ)": "BBG",
    "Apache Air": "ZM",
    "Apache": "ZM",
    "MHS Aviation GmbH": "M2",
    "Jettor Airlines": "NR",
    "Jettor": "NR",
    "Flyme (VP)": "VQI",
    "Thai Lion Air": "SL",
    "Golden Myanmar Airlines": "GMR",
    "Canaryfly": "CNF",
    "Sunrise Airways": "KSZ",
    "National Air Cargo": "N8",
    "Eastern Atlantic Virtual Airlines": "13",
    "Citilink Indonesia": "QG",
    "Transair": "TTZ",
    "Comfort Express Virtual Charters Albany": "EVC",
    "Comfort Express Virtual Charters": "CEO",
    "FLYJET": "FYJ",
    "Snowbird Airlines": "S8",
    "Russkie Krylya": "KRY",
    "Kharkiv Airlines": "KH",
    "XAIR USA": "XA",
    "Air Costa": "LB",
    "Simrik Airlines": "RMK",
    "XPTO": "XP",
    "XPTO  ": "XP",
    "Royal Flight": "DME",
    "BBN-Airways": "EGH",
    "BlackBurn": "",
    "Tomsk-Avia": "TKS",
    "Malawian Airlines": "3W",
    "Yeti Airlines ": "NYT",
    "Skyline Ulasim Ticaret A.S.": "KCU",
    "Envoy Air": "ENY",
    "CARICOM AIRWAYS (BARBADOS) INC.": "CCB",
    "CARICOM AIRWAYS": "",
    "Rainbow Air (RAI)": "RN",
    "Rainbow Air Canada": "RY",
    "Rainbow Air CAN": "RY",
    "Rainbow Air Polynesia": "RX",
    "Rainbow Air POL": "RX",
    "Rainbow Air Euro": "RU",
    "Rainbow Air EU": "RU",
    "Rainbow Air US": "RM",
    "Transilvania": "TNS",
    "Dobrolet": "QD",
    "Добролёт": "QD",
    "Spike Airlines": "S0",
    "Aero Spike": "S0",
    "Grand Cru Airlines": "GCA",
    "Go2Sky": "RLX",
    "All Argentina": "L1",
    "All America": "A2",
    "All Asia": "L9",
    "All Africa": "9A",
    "Regionalia México": "N4",
    "All Europe": "N9",
    "All Spain": "N7",
    "Regional Air Iceland": "9N",
    "Voestar": "8K",
    "Voestar Brasil": "8K",
    "All Colombia": "7O",
    "Regionalia Uruguay": "2X",
    "Regionalia Venezuela": "9X",
    "Regionalia Chile": "9J",
    "Vuela Cuba": "6C",
    "All Australia": "88",
    "Fly Europa": "ER",
    "FlyPortugal": "PO",
    "Vistara": "UK",
    "Urumqi Air": "UQ",
    "Guangxi Beibu Gulf Airlines": "UQ",
    "My Indo Airlines": "2Y",
    "Government of Morocco": "FRV",
    "Hong Kong Air Cargo": "RH",
    "US-Bangla Airlines": "BS",
    "NetJets Europe": "1I",
    "Bhutan Airlines": "B3",
    "Iran Airtour": "B9",
    "Avcon Jet": "AOJ",
    "Indonesia AirAsia X": "XT",
    "Qatar Executive": "QE",
    "SF Airlines": "O3",
    "Regent Airways": "RX",
    "AsiaCargo Express": "3G",
}

# IATA : Name and ICAO : Name mapping
code_mapping = {
    "1T": "1Time Airline",
    "RNX": "1Time Airline",
    "Q5": "40-Mile Air",
    "MLA": "40-Mile Air",
    "AN": "Ansett Australia",
    "AAA": "Ansett Australia",
    "1B": "Abacus International",
    "ZI": "Aigle Azur",
    "AAF": "Aigle Azur",
    "AQ": "Aloha Airlines",
    "AAH": "Aloha Airlines",
    "AA": "American Airlines",
    "AAL": "American Airlines",
    "OZ": "Asiana Airlines",
    "AAR": "Asiana Airlines",
    "4K": "Askari Aviation",
    "AAS": "Askari Aviation",
    "8U": "Afriqiyah Airways",
    "AAW": "Afriqiyah Airways",
    "G4": "Allegiant Air",
    "AAY": "Allegiant Air",
    "M3": "ABSA - Aerolinhas Brasileiras",
    "TUS": "ABSA - Aerolinhas Brasileiras",
    "8V": "Astral Aviation",
    "ACP": "Astral Aviation",
    "8T": "Air Tindi",
    "ZY": "Ada Air",
    "ADE": "Ada Air",
    "JP": "Adria Airways",
    "ADR": "Adria Airways",
    "UX": "Air Europa",
    "AEA": "Air Europa",
    "EM": "Aero Benin",
    "AEB": "Aero Benin",
    "A3": "Aegean Airlines",
    "AEE": "Aegean Airlines",
    "PE": "Air Europe",
    "AEL": "Air Europe",
    "KO": "Alaska Central Express",
    "AER": "Alaska Central Express",
    "AES": "ACES Colombia",
    "5W": "Astraeus",
    "AEU": "Astraeus",
    "VV": "Aerosvit Airlines",
    "AEW": "Aerosvit Airlines",
    "I9": "Indigo",
    "AEY": "Air Italy",
    "QQ": "Alliance Airlines",
    "UTY": "Alliance Airlines",
    "FG": "Ariana Afghan Airlines",
    "AFG": "Ariana Afghan Airlines",
    "SU": "Aeroflot Russian Airlines",
    "AFL": "Aeroflot Russian Airlines",
    "JA": "Air Bosna",
    "BON": "Air Bosna",
    "AF": "Air France",
    "AFR": "Air France",
    "SB": "Air Caledonie International",
    "ACI": "Air Caledonie International",
    "2O": "Air Salone",
    "2Q": "Air Cargo Carriers",
    "SNC": "Air Cargo Carriers",
    "SW": "Air Namibia",
    "NMB": "Air Namibia",
    "5D": "DonbassAero",
    "SLI": "Aerolitoral",
    "7T": "Air Glaciers",
    "AGV": "Air Glaciers",
    "AGX": "Aviogenex",
    "PL": "Aeroper",
    "PLI": "Aeroper",
    "8A": "Atlas Blue",
    "BMM": "Atlas Blue",
    "J2": "Azerbaijan Airlines",
    "AHY": "Azerbaijan Airlines",
    "U3": "Avies",
    "AIA": "Avies",
    "ED": "Airblue",
    "ABQ": "Airblue",
    "AIR": "Airlift International",
    "AB": "Air Berlin",
    "BER": "Air Berlin",
    "AI": "Air India Limited",
    "AIC": "Air India Limited",
    "ZB": "Monarch Airlines",
    "BUB": "Air Bourbon",
    "CC": "Macair Airlines",
    "ABD": "Air Atlanta Icelandic",
    "TN": "Air Tahiti Nui",
    "THT": "Air Tahiti Nui",
    "IZ": "Arkia Israel Airlines",
    "AIZ": "Arkia Israel Airlines",
    "JM": "Air Jamaica",
    "AJM": "Air Jamaica",
    "AP": "Air One",
    "ADH": "Air One",
    "S2": "Air Sahara",
    "RSH": "Air Sahara",
    "KM": "Air Malta",
    "AMC": "Air Malta",
    "NQ": "Air Japan",
    "AJX": "Air Japan",
    "AKA": "Air Korea Co. Ltd.",
    "4A": "Air Kiribati",
    "AKL": "Air Kiribati",
    "HP": "America West Airlines",
    "AWE": "America West Airlines",
    "ZW": "Air Wisconsin",
    "AWI": "Air Wisconsin",
    "U9": "Tatarstan Airlines",
    "TAK": "Tatarstan Airlines",
    "ALO": "Allegheny Commuter Airlines",
    "RSI": "Air Sunshine",
    "VD": "Air Libert",
    "QM": "Air Malawi",
    "AML": "Air Malawi",
    "BM": "Air Sicilia",
    "AMT": "ATA Airlines",
    "NX": "Air Macau",
    "AMU": "Air Macau",
    "AMV": "AMC Airlines",
    "HM": "Air Seychelles",
    "SEY": "Air Seychelles",
    "AM": "AeroMéxico",
    "AMX": "AeroMéxico",
    "NH": "All Nippon Airways",
    "ANA": "All Nippon Airways",
    "YW": "Air Nostrum",
    "ANE": "Air Nostrum",
    "PX": "Air Niugini",
    "ANG": "Air Niugini",
    "G9": "Air Arabia",
    "ABY": "Air Arabia",
    "AC": "Air Canada",
    "ACA": "Air Canada",
    "BT": "Air Baltic",
    "BTI": "Air Baltic",
    "EL": "Air Nippon",
    "ANK": "Air Nippon",
    "TL": "Trans Mediterranean Airlines",
    "ANO": "Airnorth",
    "4N": "Air North Charter - Canada",
    "ANT": "Air North Charter - Canada",
    "NZ": "Air New Zealand",
    "ANZ": "Air New Zealand",
    "XM": "Alitalia Express",
    "SMX": "Alitalia Express",
    "GV": "Aero Flight",
    "ARF": "Aero Flight",
    "JW": "Arrow Air",
    "APW": "Arrow Air",
    "2B": "Aerocondor",
    "ARD": "Aerocondor",
    "4C": "Aires",
    "ARE": "Aires",
    "AR": "Aerolineas Argentinas",
    "ARG": "Aerolineas Argentinas",
    "AS": "Alaska Airlines",
    "ASA": "Alaska Airlines",
    "4D": "Air Sinai",
    "ASD": "Air Sinai",
    "EV": "Atlantic Southeast Airlines",
    "ASQ": "Atlantic Southeast Airlines",
    "OB": "Astrakhan Airlines",
    "ASZ": "Astrakhan Airlines",
    "TC": "Air Tanzania",
    "ATC": "Air Tanzania",
    "2J": "Air Burkina",
    "VBW": "Air Burkina",
    "FO": "Airlines Of Tasmania",
    "ATM": "Airlines Of Tasmania",
    "PJ": "Air Saint Pierre",
    "SPM": "Air Saint Pierre",
    "OS": "Austrian Airlines",
    "AUA": "Austrian Airlines",
    "WOW": "Air Southwest",
    "IQ": "Augsburg Airways",
    "AUB": "Augsburg Airways",
    "TUR": "ATUR",
    "MO": "Abu Dhabi Amiri Flight",
    "AUH": "Abu Dhabi Amiri Flight",
    "5N": "Aeroflot-Nord",
    "AUL": "Aeroflot-Nord",
    "GR": "Aurigny Air Services",
    "AUR": "Aurigny Air Services",
    "AU": "Austral Lineas Aereas",
    "AUT": "Austral Lineas Aereas",
    "AV": "Avianca - Aerovias Nacionales de Colombia",
    "AVA": "Avianca - Aerovias Nacionales de Colombia",
    "NF": "Air Vanuatu",
    "AVN": "Air Vanuatu",
    "B9": "Iran Airtour",
    "BGD": "Air Bangladesh",
    "DR": "Air Mediterranee",
    "BIE": "Air Mediterranee",
    "TAH": "Air Moorea",
    "7E": "Aeroline GmbH",
    "AWU": "Aeroline GmbH",
    "6G": "Air Wales",
    "AWW": "Air Wales",
    "TX": "Air Caraïbes",
    "FWI": "Air Caraïbes",
    "IX": "Air India Express",
    "AXB": "Air India Express",
    "XT": "Indonesia AirAsia X",
    "AXL": "Air Exel",
    "AK": "AirAsia",
    "AXM": "AirAsia",
    "3G": "AsiaCargo Express",
    "AYZ": "Atlant-Soyuz Airlines",
    "AZ": "Alitalia",
    "AZA": "Alitalia",
    "Z8": "Amaszonas",
    "AZN": "Amaszonas",
    "UM": "Air Zimbabwe",
    "AZW": "Air Zimbabwe",
    "R7": "Aserca Airlines",
    "OCA": "Aserca Airlines",
    "FV": "Rossiya-Russian Airlines",
    "SDM": "Rossiya-Russian Airlines",
    "MQ": "American Eagle Airlines",
    "EGF": "American Eagle Airlines",
    "VUE": "AD Aviation",
    "VU": "Air Ivoire",
    "VUN": "Air Ivoire",
    "BP": "Air Botswana",
    "BOT": "Air Botswana",
    "GS": "Air Foyle",
    "UPA": "Air Foyle",
    "VT": "Air Tahiti",
    "VTA": "Air Tahiti",
    "VL": "Air VIA",
    "VIM": "Air VIA",
    "FK": "Africa West",
    "WTA": "Africa West",
    "V8": "ATRAN Cargo Airlines",
    "VAS": "ATRAN Cargo Airlines",
    "CA": "Air China",
    "CCA": "Air China",
    "Q6": "Aero Condor Peru",
    "CDP": "Aero Condor Peru",
    "CV": "Air Chathams",
    "CVA": "Air Chathams",
    "CW": "Air Marshall Islands",
    "CWM": "Air Marshall Islands",
    "ZA": "Interavia Airlines",
    "CYD": "Access Air",
    "AH": "Air Algerie",
    "DAH": "Air Algerie",
    "KI": "Adam Air",
    "DHI": "Adam Air",
    "EN": "Air Dolomiti",
    "DLA": "Air Dolomiti",
    "D9": "Aeroflot-Don",
    "DNV": "Aeroflot-Don",
    "NM": "Air Madrid",
    "DRD": "Air Madrid",
    "EI": "Aer Lingus",
    "EIN": "Aer Lingus",
    "OF": "Air Finland",
    "FIF": "Air Finland",
    "FIX": "Airfix Aviation",
    "FJ": "Air Pacific",
    "FJI": "Air Pacific",
    "RC": "Atlantic Airways",
    "FLI": "Atlantic Airways",
    "QH": "Air Florida",
    "FLZ": "Air Florida",
    "NY": "Air Iceland",
    "FXI": "Air Iceland",
    "2P": "Air Philippines",
    "GAP": "Air Philippines",
    "2U": "Air Guinee Express",
    "GIP": "Air Guinee Express",
    "GL": "Air Greenland",
    "GRL": "Air Greenland",
    "5Y": "Atlas Air",
    "GTI": "Atlas Air",
    "GG": "Air Guyane",
    "GUY": "Air Guyane",
    "W9": "Air Bagan",
    "JAB": "Air Bagan",
    "QK": "Air Canada Jazz",
    "JZA": "Air Canada Jazz",
    "KK": "Atlasjet",
    "KKK": "Atlasjet",
    "JS": "Air Koryo",
    "KOR": "Air Koryo",
    "KC": "Air Astana",
    "KZR": "Air Astana",
    "LV": "Albanian Airlines",
    "LBC": "Albanian Airlines",
    "LFA": "Air Alfa",
    "XL": "Aerolane",
    "LNE": "Aerolane",
    "TD": "Atlantis European Airways",
    "LUR": "Atlantis European Airways",
    "LK": "Air Luxor",
    "LXR": "Air Luxor",
    "MK": "Air Mauritius",
    "MAU": "Air Mauritius",
    "MD": "Air Madagascar",
    "MDG": "Air Madagascar",
    "9U": "Air Moldova",
    "MLD": "Air Moldova",
    "6I": "Alsie Express",
    "MMD": "Alsie Express",
    "A7": "Air Plus Comet",
    "MPD": "Air Plus Comet",
    "8D": "Astair",
    "AJ": "Aero Contractors",
    "NIG": "Aero Contractors",
    "OT": "Aeropelican Air Services",
    "PEL": "Aeropelican Air Services",
    "RE": "Aer Arann",
    "REA": "Aer Arann",
    "UU": "Air Austral",
    "REU": "Air Austral",
    "6K": "Asian Spirit",
    "RIT": "Asian Spirit",
    "RK": "Air Afrique",
    "RKA": "Air Afrique",
    "A5": "Airlinair",
    "RLA": "Airlinair",
    "QL": "Aero Lanka",
    "RLN": "Aero Lanka",
    "20": "Air Salone",
    "RNE": "Air Salone",
    "U8": "Armavia",
    "RNV": "Armavia",
    "P5": "AeroRep",
    "RPB": "AeroRep",
    "BF": "Aero-Service",
    "RSR": "Aero-Service",
    "5L": "Aerosur",
    "RSU": "Aerosur",
    "RTE": "Aeronorte",
    "Z3": "Avient Aviation",
    "SMJ": "Avient Aviation",
    "R3": "Aircompany Yakutia",
    "SYL": "Aircompany Yakutia",
    "VW": "Aeromar",
    "TAO": "Aeromar",
    "OR": "Arkefly",
    "TFL": "Arkefly",
    "CG": "Airlines PNG",
    "TOK": "Airlines PNG",
    "FL": "AirTran Airways",
    "TRS": "AirTran Airways",
    "TS": "Air Transat",
    "TSC": "Air Transat",
    "EC": "Avialeasing Aviation Company",
    "TWN": "Avialeasing Aviation Company",
    "VO": "Tyrolean Airways",
    "TYR": "Tyrolean Airways",
    "2K": "Aerolineas Galapagos (Aerogal)",
    "GLG": "Aerolineas Galapagos (Aerogal)",
    "6R": "Alrosa Mirny Air Enterprise",
    "DRU": "Alrosa Mirny Air Enterprise",
    "BA": "British Airways",
    "BAW": "British Airways",
    "BG": "Biman Bangladesh Airlines",
    "BBC": "Biman Bangladesh Airlines",
    "4T": "Belair Airlines",
    "BHP": "Belair Airlines",
    "UP": "Bahamasair",
    "BHS": "Bahamasair",
    "LZ": "Balkan Bulgarian Airlines",
    "BS": "US-Bangla Airlines",
    "BIH": "British International Helicopters",
    "BKF": "BF-Lento OY",
    "PG": "Bangkok Airways",
    "BKP": "Bangkok Airways",
    "KF": "Blue1",
    "BLF": "Blue1",
    "BLL": "Baltic Airlines",
    "JV": "Bearskin Lake Air Service",
    "BLS": "Bearskin Lake Air Service",
    "B3": "Bhutan Airlines",
    "BLV": "Bellview Airlines",
    "BD": "bmi",
    "BMA": "bmi",
    "WW": "bmibaby",
    "BMI": "bmibaby",
    "CH": "Bemidji Airlines",
    "BMJ": "Bemidji Airlines",
    "BMR": "British Midland Regional",
    "BV": "Blue Panorama Airlines",
    "BPA": "Blue Panorama Airlines",
    "BPS": "Budapest Aircraft Services/Manx2",
    "8E": "Bering Air",
    "BRG": "Bering Air",
    "BRS": "Brazilian Air Force",
    "B2": "Belavia Belarusian Airlines",
    "BRU": "Belavia Belarusian Airlines",
    "7P": "Metro Batavia",
    "BTV": "Metro Batavia",
    "J8": "Berjaya Air",
    "BVT": "Berjaya Air",
    "QW": "Blue Wings",
    "BWG": "Blue Wings",
    "DB": "Brit Air",
    "BZH": "Brit Air",
    "SN": "Brussels Airlines",
    "DAT": "Brussels Airlines",
    "NT": "Binter Canarias",
    "IBB": "Binter Canarias",
    "0B": "Blue Air",
    "JOR": "Blue Air",
    "KJ": "British Mediterranean Airways",
    "LAJ": "British Mediterranean Airways",
    "FB": "Bulgaria Air",
    "LZB": "Bulgaria Air",
    "8N": "Barents AirLink",
    "NKF": "Barents AirLink",
    "5C": "CAL Cargo Air Lines",
    "ICL": "CAL Cargo Air Lines",
    "XG": "Calima Aviacion",
    "CLI": "Calima Aviacion",
    "CP": "Compass Airlines",
    "CDN": "Canadian Airlines",
    "5T": "Canadian North",
    "MPE": "Canadian North",
    "9K": "Cape Air",
    "KAP": "Cape Air",
    "BW": "Caribbean Airlines",
    "BWA": "Caribbean Airlines",
    "V3": "Carpatair",
    "KRP": "Carpatair",
    "RV": "Caspian Airlines",
    "CPN": "Caspian Airlines",
    "CX": "Cathay Pacific",
    "CPA": "Cathay Pacific",
    "KX": "Cayman Airways",
    "CAY": "Cayman Airways",
    "5J": "Cebu Pacific",
    "CEB": "Cebu Pacific",
    "CCG": "Central Connect Airlines",
    "C0": "Centralwings",
    "CLW": "Centralwings",
    "CHW": "Charter Air",
    "RP": "Chautauqua Airlines",
    "CHQ": "Chautauqua Airlines",
    "CI": "China Airlines",
    "CAL": "China Airlines",
    "MU": "China Eastern Airlines",
    "CES": "China Eastern Airlines",
    "CZ": "China Southern Airlines",
    "CSN": "China Southern Airlines",
    "HR": "China United Airlines",
    "CUA": "China United Airlines",
    "3Q": "Yunnan Airlines",
    "CYH": "Yunnan Airlines",
    "QI": "Cimber Air",
    "CIM": "Cimber Air",
    "C9": "Cirrus Airlines",
    "RUS": "Cirrus Airlines",
    "CF": "City Airline",
    "SDR": "City Airline",
    "G3": "Sky Express",
    "CIX": "City Connexion Airlines",
    "WX": "CityJet",
    "BCY": "CityJet",
    "CJ": "BA CityFlyer",
    "CFE": "BA CityFlyer",
    "CGK": "Click Airways",
    "DQ": "Coastal Air",
    "9L": "Colgan Air",
    "CJC": "Colgan Air",
    "OH": "Comair",
    "COM": "Comair",
    "MN": "Comair",
    "CAW": "Comair",
    "C5": "CommutAir",
    "UCA": "CommutAir",
    "KR": "Comores Airlines",
    "CWK": "Comores Airlines",
    "CPZ": "Compass Airlines",
    "DE": "Condor Flugdienst",
    "CFG": "Condor Flugdienst",
    "6A": "Consorcio Aviaxsa",
    "CHP": "Consorcio Aviaxsa",
    "C3": "QatXpress",
    "KIS": "Contact Air",
    "CO": "Continental Express",
    "COA": "Continental Airlines",
    "CS": "Continental Micronesia",
    "CMI": "Continental Micronesia",
    "V0": "Conviasa",
    "VCV": "Conviasa",
    "CM": "Copa Airlines",
    "CMP": "Copa Airlines",
    "AAQ": "Copterline",
    "CAI": "Corendon Airlines",
    "SS": "Corsairfly",
    "CRL": "Corsairfly",
    "XK": "Corse-Mediterranee",
    "CCM": "Corse-Mediterranee",
    "CAN": "Crest Aviation",
    "OU": "Croatia Airlines",
    "CTN": "Croatia Airlines",
    "CRO": "Crown Airways",
    "CU": "Cubana de Aviación",
    "CUB": "Cubana de Aviación",
    "CY": "Cyprus Airways",
    "CYP": "Cyprus Airways",
    "YK": "Cyprus Turkish Airlines",
    "OK": "Czech Airlines",
    "CSA": "Czech Airlines",
    "DX": "DAT Danish Air Transport",
    "DTR": "DAT Danish Air Transport",
    "D3": "Daallo Airlines",
    "DAO": "Daallo Airlines",
    "H8": "Dalavia",
    "KHB": "Dalavia",
    "0D": "Darwin Airline",
    "DWT": "Darwin Airline",
    "DEA": "Delta Aerotaxi",
    "DL": "Delta Air Lines",
    "DAL": "Delta Air Lines",
    "DNM": "Denim Air",
    "2A": "Deutsche Bahn",
    "D8": "Djibouti Airlines",
    "DJB": "Djibouti Airlines",
    "UDN": "Dniproavia",
    "DO": "Dominicana de Aviaci",
    "DOA": "Dominicana de Aviaci",
    "E3": "Domodedovo Airlines",
    "DMO": "Domodedovo Airlines",
    "UDC": "DonbassAero",
    "KA": "Dragonair",
    "HDA": "Dragonair",
    "KB": "Druk Air",
    "DRK": "Druk Air",
    "DBK": "Dubrovnik Air",
    "DNL": "Dutch Antilles Express",
    "DI": "dba",
    "BAG": "dba",
    "BR": "EVA Air",
    "EVA": "EVA Air",
    "H7": "Eagle Air",
    "QU": "East African",
    "UGX": "East African",
    "T3": "Eastern Airways",
    "EZE": "Eastern Airways",
    "DK": "Eastland Air",
    "ELA": "Eastland Air",
    "ECU": "Ecuavia",
    "WK": "Edelweiss Air",
    "EDW": "Edelweiss Air",
    "MS": "Egyptair",
    "MSR": "Egyptair",
    "LY": "El Al Israel Airlines",
    "ELY": "El Al Israel Airlines",
    "UZ": "El-Buraq Air Transport",
    "BRQ": "El-Buraq Air Transport",
    "EK": "Emirates",
    "UAE": "Emirates",
    "EU": "Empresa Ecuatoriana De Aviacion",
    "EEA": "Empresa Ecuatoriana De Aviacion",
    "B8": "Eritrean Airlines",
    "ERT": "Eritrean Airlines",
    "OV": "Estonian Air",
    "ELL": "Estonian Air",
    "ET": "Ethiopian Airlines",
    "ETH": "Ethiopian Airlines",
    "EY": "Etihad Airways",
    "ETD": "Etihad Airways",
    "RZ": "Euro Exec Express",
    "UI": "Eurocypria Airlines",
    "ECA": "Eurocypria Airlines",
    "GJ": "Eurofly Service",
    "EEU": "Eurofly Service",
    "K2": "Eurolot",
    "ELO": "Eurolot",
    "EA": "European Air Express",
    "EAL": "European Air Express",
    "EW": "Eurowings",
    "EWG": "Eurowings",
    "EZ": "Evergreen International Airlines",
    "EIA": "Evergreen International Airlines",
    "JN": "Excel Airways",
    "XLA": "Excel Airways",
    "XEL": "Excel Charter",
    "EO": "Express One International",
    "LHN": "Express One International",
    "XE": "ExpressJet",
    "BTA": "ExpressJet",
    "U2": "easyJet",
    "EZY": "easyJet",
    "EF": "Far Eastern Air Transport",
    "EFA": "Far Eastern Air Transport",
    "AY": "Finnair",
    "FIN": "Finnair",
    "FC": "Finncomm Airlines",
    "WBA": "Finncomm Airlines",
    "FY": "Firefly",
    "FFM": "Firefly",
    "7F": "First Air",
    "FAB": "First Air",
    "DP": "First Choice Airways",
    "FCA": "First Choice Airways",
    "B5": "Flightline",
    "FLT": "Flightline",
    "RF": "Florida West International Airways",
    "FWL": "Florida West International Airways",
    "D7": "AirAsia X",
    "XAX": "AirAsia X",
    "TE": "FlyLal",
    "LIL": "FlyLal",
    "LF": "FlyNordic",
    "NDC": "FlyNordic",
    "F7": "Flybaboo",
    "BBO": "Flybaboo",
    "BE": "Flybe",
    "BEE": "Flybe",
    "B4": "Flyglobespan",
    "GSM": "Flyglobespan",
    "FYH": "Flyhy Cargo Airlines",
    "VY": "Vueling Airlines",
    "FOS": "Formosa Airlines",
    "FP": "Freedom Air",
    "FRE": "Freedom Air",
    "FRL": "Freedom Airlines",
    "F9": "Frontier Airlines",
    "FFT": "Frontier Airlines",
    "2F": "Frontier Flying Service",
    "FTA": "Frontier Flying Service",
    "GT": "GB Airways",
    "GBL": "GB Airways",
    "GA": "Garuda Indonesia",
    "GIA": "Garuda Indonesia",
    "4G": "Gazpromavia",
    "GZP": "Gazpromavia",
    "A9": "Georgian Airways",
    "TGZ": "Georgian Airways",
    "QB": "Georgian National Airlines",
    "GFG": "Georgian National Airlines",
    "ST": "Germania",
    "GMI": "Germania",
    "4U": "Germanwings",
    "GWI": "Germanwings",
    "G0": "Ghana International Airlines",
    "GHB": "Ghana International Airlines",
    "G8": "Go Air",
    "GOW": "Go Air",
    "G7": "GoJet Airlines",
    "GJS": "GoJet Airlines",
    "GLO": "Gol Transportes Aéreos",
    "DC": "Golden Air",
    "GAO": "Golden Air",
    "ZK": "Great Lakes Airlines",
    "GLA": "Great Lakes Airlines",
    "TA": "Grupo TACA",
    "TAT": "Grupo TACA",
    "GFA": "Gulf Air",
    "GF": "Gulf Air Bahrain",
    "GBA": "Gulf Air Bahrain",
    "GFT": "Gulfstream International Airlines",
    "H6": "Hageland Aviation Services",
    "HAG": "Hageland Aviation Services",
    "HU": "Hainan Airlines",
    "CHH": "Hainan Airlines",
    "2T": "Haiti Ambassador Airlines",
    "HAM": "Haiti Ambassador Airlines",
    "4R": "Hamburg International",
    "HHI": "Hamburg International",
    "X3": "TUIfly",
    "HLX": "TUIfly",
    "HF": "Hapagfly",
    "HLF": "Hapagfly",
    "HA": "Hawaiian Airlines",
    "HAL": "Hawaiian Airlines",
    "BH": "Hawkair",
    "8H": "Heli France",
    "HFR": "Heli France",
    "JB": "Helijet",
    "JBA": "Helijet",
    "T4": "Hellas Jet",
    "HEJ": "Hellas Jet",
    "HW": "Hello",
    "FHE": "Hello",
    "2L": "Helvetic Airways",
    "OAW": "Helvetic Airways",
    "UD": "Hex'Air",
    "HER": "Hex'Air",
    "HWY": "Highland Airways",
    "HD": "Hokkaido International Airlines",
    "ADO": "Hokkaido International Airlines",
    "HX": "Hong Kong Airlines",
    "CRK": "Hong Kong Airlines",
    "UO": "Hong Kong Express Airways",
    "HKE": "Hong Kong Express Airways",
    "QX": "Horizon Air",
    "QXE": "Horizon Air",
    "BN": "Horizon Airlines",
    "HZA": "Horizon Airlines",
    "IB": "Iberia Airlines",
    "IBE": "Iberia Airlines",
    "TY": "Iberworld",
    "IWD": "Iberworld",
    "FW": "Ibex Airlines",
    "IBX": "Ibex Airlines",
    "RAC": "Royal Air Cambodge",
    "FI": "Icelandair",
    "ICE": "Icelandair",
    "IK": "Imair Airlines",
    "ITX": "Imair Airlines",
    "6E": "IndiGo Airlines",
    "IGO": "IndiGo Airlines",
    "IC": "Indian Airlines",
    "IAC": "Indian Airlines",
    "IBU": "Indigo",
    "QZ": "Indonesia AirAsia",
    "AWQ": "Indonesia AirAsia",
    "IO": "Indonesian Airlines",
    "IAA": "Indonesian Airlines",
    "D6": "Interair South Africa",
    "ILN": "Interair South Africa",
    "SUW": "Interavia Airlines",
    "ID": "Interlink Airlines",
    "ITK": "Interlink Airlines",
    "3L": "Intersky",
    "ISK": "Intersky",
    "IR": "Iran Air",
    "IRA": "Iran Air",
    "EP": "Iran Aseman Airlines",
    "IRC": "Iran Aseman Airlines",
    "IA": "Iraqi Airways",
    "IAW": "Iraqi Airways",
    "IS": "Island Airlines",
    "8L": "Cargo Plus Aviation",
    "CGP": "Cargo Plus Aviation",
    "IF": "Islas Airways",
    "ISW": "Islas Airways",
    "WC": "Islena De Inversiones",
    "ISV": "Islena De Inversiones",
    "6H": "Israir",
    "ISR": "Israir",
    "GI": "Itek Air",
    "IKA": "Itek Air",
    "JC": "JAL Express",
    "JEX": "JAL Express",
    "JO": "JALways",
    "JAZ": "JALways",
    "JL": "Japan Airlines",
    "JAL": "Japan Airlines",
    "EG": "Japan Asia Airways",
    "JAA": "Japan Asia Airways",
    "NU": "Japan Transocean Air",
    "JTA": "Japan Transocean Air",
    "JU": "Jat Airways",
    "JAT": "Jat Airways",
    "J9": "Jazeera Airways",
    "JZR": "Jazeera Airways",
    "7C": "Jeju Air",
    "JJA": "Jeju Air",
    "9W": "Jet Airways",
    "JAI": "Jet Airways",
    "QJ": "Jet Airways",
    "3K": "Jetstar Asia Airways",
    "JSA": "Jetstar Asia Airways",
    "LS": "Jet2.com",
    "EXS": "Jet2.com",
    "8J": "Jet4You",
    "JFU": "Jet4You",
    "B6": "JetBlue Airways",
    "JBU": "JetBlue Airways",
    "JF": "Jetairfly",
    "JAF": "Jetairfly",
    "JEF": "Jetflite",
    "JQ": "Jetstar Airways",
    "JST": "Jetstar Airways",
    "HO": "Juneyao Airlines",
    "DKH": "Juneyao Airlines",
    "KD": "KD Avia",
    "KNI": "KD Avia",
    "WA": "Western Airlines",
    "KLC": "KLM Cityhopper",
    "KL": "KLM Royal Dutch Airlines",
    "KLM": "KLM Royal Dutch Airlines",
    "RQ": "Kam Air",
    "KMF": "Kam Air",
    "KV": "Kavminvodyavia",
    "MVD": "Kavminvodyavia",
    "KDA": "Kendell Airlines",
    "M5": "Kenmore Air",
    "KEN": "Kenmore Air",
    "KQ": "Kenya Airways",
    "KQA": "Kenya Airways",
    "IT": "Kingfisher Airlines",
    "KFR": "Kingfisher Airlines",
    "Y9": "Kish Air",
    "IRK": "Kish Air",
    "7K": "Kogalymavia Air Company",
    "KGL": "Kogalymavia Air Company",
    "KE": "Korean Air",
    "KAL": "Korean Air",
    "KSM": "Kosmos",
    "7B": "Krasnojarsky Airlines",
    "KJC": "Krasnojarsky Airlines",
    "GW": "Kuban Airlines",
    "KIL": "Kuban Airlines",
    "KU": "Kuwait Airways",
    "KAC": "Kuwait Airways",
    "GO": "Kuzu Airlines Cargo",
    "KZU": "Kuzu Airlines Cargo",
    "LR": "LACSA",
    "LRC": "LACSA",
    "LA": "LAN Airlines",
    "LAN": "LAN Airlines",
    "4M": "LAN Argentina",
    "DSM": "LAN Argentina",
    "LU": "LAN Express",
    "LXP": "LAN Express",
    "LP": "LAN Peru",
    "LPE": "LAN Peru",
    "LO": "LOT Polish Airlines",
    "LOT": "LOT Polish Airlines",
    "XO": "LTE International Airways",
    "LTE": "LTE International Airways",
    "L3": "LTU Austria",
    "LTO": "LTU Austria",
    "LT": "LTU International",
    "LTU": "LTU International",
    "QV": "Lao Airlines",
    "LAO": "Lao Airlines",
    "LTC": "LatCharter",
    "NG": "Lauda Air",
    "LDA": "Lauda Air",
    "LI": "Leeward Islands Air Transport",
    "LIA": "Leeward Islands Air Transport",
    "LN": "Libyan Arab Airlines",
    "LAA": "Libyan Arab Airlines",
    "LM": "Linhas A",
    "LAM": "Linhas A",
    "JT": "Lion Mentari Airlines",
    "LNI": "Lion Mentari Airlines",
    "HE": "Luftfahrtgesellschaft Walter",
    "LGW": "Luftfahrtgesellschaft Walter",
    "LH": "Lufthansa Cargo",
    "DLH": "Lufthansa",
    "GEC": "Lufthansa Cargo",
    "CL": "Lufthansa CityLine",
    "CLH": "Lufthansa CityLine",
    "L5": "Lufttransport",
    "LTR": "Lufttransport",
    "LG": "Luxair",
    "LGL": "Luxair",
    "MJ": "L",
    "LPR": "L",
    "M7": "MasAir",
    "MAA": "MasAir",
    "IN": "MAT Macedonian Airlines",
    "MAK": "MAT Macedonian Airlines",
    "OM": "MIAT Mongolian Airlines",
    "MGL": "MIAT Mongolian Airlines",
    "MB": "MNG Airlines",
    "MNB": "MNG Airlines",
    "MCK": "Macair Airlines",
    "DM": "Maersk",
    "W5": "Mahan Air",
    "IRM": "Mahan Air",
    "MH": "Malaysia Airlines",
    "MAS": "Malaysia Airlines",
    "R5": "Malta Air Charter",
    "MAC": "Malta Air Charter",
    "MA": "Malév",
    "MAH": "Malév",
    "RI": "Mandala Airlines",
    "MDL": "Mandala Airlines",
    "AE": "Mandarin Airlines",
    "MDA": "Mandarin Airlines",
    "JE": "Mango",
    "MNO": "Mango",
    "MP": "Martinair",
    "MPH": "Martinair",
    "8M": "Myanmar Airways International",
    "MXL": "Maxair",
    "MW": "Maya Island Air",
    "MYD": "Maya Island Air",
    "IG": "Meridiana",
    "ISS": "Meridiana",
    "MZ": "Merpati Nusantara Airlines",
    "MNA": "Merpati Nusantara Airlines",
    "YV": "Mesa Airlines",
    "ASH": "Mesa Airlines",
    "XJ": "Mesaba Airlines",
    "MES": "Mesaba Airlines",
    "MX": "Mexicana de Aviaci",
    "MXA": "Mexicana de Aviaci",
    "ME": "Middle East Airlines",
    "MEA": "Middle East Airlines",
    "JI": "Midway Airlines",
    "MDW": "Midway Airlines",
    "YX": "Midwest Airlines",
    "MEP": "Midwest Airlines",
    "MY": "Midwest Airlines (Egypt)",
    "MWA": "Midwest Airlines (Egypt)",
    "2M": "Moldavian Airlines",
    "MDV": "Moldavian Airlines",
    "MON": "Monarch Airlines",
    "8I": "Myway Airlines",
    "YM": "Montenegro Airlines",
    "MGX": "Montenegro Airlines",
    "MAL": "Morningstar Air Express",
    "3R": "Moskovia Airlines",
    "GAI": "Moskovia Airlines",
    "M9": "Motor Sich",
    "MSI": "Motor Sich",
    "VZ": "MyTravel Airways",
    "MYT": "MyTravel Airways",
    "UB": "Myanma Airways",
    "UBA": "Myanma Airways",
    "MMM": "Myanmar Airways International",
    "MYA": "Myflug",
    "UE": "Nasair",
    "NAS": "Nasair",
    "NC": "National Jet Systems",
    "NJS": "National Jet Systems",
    "CE": "Nationwide Airlines",
    "NTW": "Nationwide Airlines",
    "ON": "Nauru Air Corporation",
    "RON": "Nauru Air Corporation",
    "RA": "Nepal Airlines",
    "RNA": "Nepal Airlines",
    "1I": "NetJets Europe",
    "EJA": "NetJets",
    "EJ": "New England Airlines",
    "NEA": "New England Airlines",
    "2N": "NextJet",
    "NTJ": "NextJet",
    "HG": "Niki",
    "NLY": "Niki",
    "DD": "Nok Air",
    "NOK": "Nok Air",
    "NCF": "Norfolk County Flight College",
    "NTM": "North American Airlines",
    "HMR": "North American Charters",
    "U7": "Northern Dene Airways",
    "NW": "Northwest Airlines",
    "NWA": "Northwest Airlines",
    "J3": "Northwestern Air",
    "PLR": "Northwestern Air",
    "DY": "Norwegian Air Shuttle",
    "NAX": "Norwegian Air Shuttle",
    "TFN": "Norwegian Aviation College",
    "BJ": "Nouvel Air Tunisie",
    "LBT": "Nouvel Air Tunisie",
    "NVR": "Novair",
    "XY": "Nas Air",
    "KNE": "Nas Air",
    "O8": "Oasis Hong Kong Airlines",
    "OHK": "Oasis Hong Kong Airlines",
    "BCN": "Ocean Air",
    "O6": "Oceanair",
    "ONE": "Oceanair",
    "O2": "Oceanic Airlines",
    "OA": "Olympic Airlines",
    "OAL": "Olympic Airlines",
    "WY": "Oman Air",
    "OMA": "Oman Air",
    "OY": "Omni Air International",
    "OAE": "Omni Air International",
    "OTG": "One Two Go Airlines",
    "8Q": "Maldivian Air Taxi",
    "OHY": "Onur Air",
    "R2": "Orenburg Airlines",
    "ORB": "Orenburg Airlines",
    "OX": "Orient Thai Airlines",
    "OEA": "Orient Thai Airlines",
    "QO": "Origin Pacific Airways",
    "OGN": "Origin Pacific Airways",
    "OL": "Ostfriesische Lufttransport",
    "OLT": "Ostfriesische Lufttransport",
    "OJ": "Overland Airways",
    "OLA": "Overland Airways",
    "O7": "Ozjet Airlines",
    "OZJ": "Ozjet Airlines",
    "PV": "PAN Air",
    "PNR": "PAN Air",
    "9Q": "PB Air",
    "PBA": "PB Air",
    "PU": "PLUNA",
    "PUA": "PLUNA",
    "U4": "PMTair",
    "PMT": "PMTair",
    "BL": "Jetstar Pacific",
    "PIC": "Jetstar Pacific",
    "8P": "Pacific Coastal Airline",
    "PCO": "Pacific Coastal Airline",
    "Q8": "Pacific East Asia Cargo Airlines",
    "PEC": "Pacific East Asia Cargo Airlines",
    "PSA": "Pacific Island Aviation",
    "LW": "Pacific Wings",
    "NMI": "Pacific Wings",
    "PK": "Pakistan International Airlines",
    "PIA": "Pakistan International Airlines",
    "I7": "Paramount Airways",
    "PMW": "Paramount Airways",
    "PTB": "Passaredo Transportes Aereos",
    "PC": "Pegasus Airlines",
    "PGT": "Pegasus Airlines",
    "KS": "Peninsula Airways",
    "PEN": "Peninsula Airways",
    "PR": "Philippine Airlines",
    "PAL": "Philippine Airlines",
    "PI": "Piedmont Airlines (1948-1989)",
    "PDT": "Piedmont Airlines (1948-1989)",
    "9E": "Pinnacle Airlines",
    "FLG": "Pinnacle Airlines",
    "POT": "Polet",
    "PH": "Polynesian Airlines",
    "PAO": "Polynesian Airlines",
    "PD": "Porter Airlines",
    "POE": "Porter Airlines",
    "NI": "Portugalia",
    "PGA": "Portugalia",
    "BK": "Potomac Air",
    "PDC": "Potomac Air",
    "PW": "Precision Air",
    "PRF": "Precision Air",
    "PTI": "Privatair",
    "P0": "Proflight Commuter Services",
    "QF": "Qantas",
    "QFA": "Qantas",
    "QR": "Qatar Airways",
    "QTR": "Qatar Airways",
    "R6": "RACSA",
    "KIN": "Kinloss Flying Training Unit",
    "FN": "Regional Airlines",
    "ZL": "Regional Express",
    "RXA": "Regional Express",
    "RW": "Republic Airlines",
    "RPA": "Republic Airlines",
    "RH": "Hong Kong Air Cargo",
    "RPH": "Republic Express Airlines",
    "R4": "Rossiya",
    "GZ": "Air Rarotonga",
    "RAR": "Air Rarotonga",
    "AT": "Royal Air Maroc",
    "RAM": "Royal Air Maroc",
    "BI": "Royal Brunei Airlines",
    "RBA": "Royal Brunei Airlines",
    "RJ": "Royal Jordanian",
    "RJA": "Royal Jordanian",
    "PPW": "Royal Phnom Penh Airways",
    "RLU": "Rusline",
    "WB": "Rwandair Express",
    "RWD": "Rwandair Express",
    "RYA": "Ryan Air Services",
    "RD": "Ryan International Airlines",
    "RYN": "Ryan International Airlines",
    "FR": "Ryanair",
    "RYR": "Ryanair",
    "YS": "Régional",
    "RAE": "Régional",
    "S4": "SATA International",
    "RZO": "SATA International",
    "SA": "South African Airways",
    "SAA": "South African Airways",
    "NL": "Shaheen Air International",
    "SAI": "Shaheen Air International",
    "SK": "Scandinavian Airlines System",
    "SAS": "Scandinavian Airlines System",
    "SAY": "ScotAirways",
    "S7": "S7 Airlines",
    "SBI": "S7 Airlines",
    "BB": "Seaborne Airlines",
    "SBS": "Seaborne Airlines",
    "SCE": "Scenic Airlines",
    "UL": "SriLankan Airlines",
    "ALK": "SriLankan Airlines",
    "SY": "Sun Country Airlines",
    "SCX": "Sun Country Airlines",
    "SEA": "Southeast Air",
    "SEH": "Sky Express",
    "SG": "Spicejet",
    "SEJ": "Spicejet",
    "7G": "Star Flyer",
    "SFJ": "Star Flyer",
    "N5": "Skagway Air Service",
    "SGY": "Skagway Air Service",
    "SHD": "Sahara Airlines",
    "SP": "SATA Air Acores",
    "SAT": "SATA Air Acores",
    "SQ": "Singapore Airlines Cargo",
    "SIA": "Singapore Airlines",
    "5M": "Sibaviatrans",
    "SIB": "Sibaviatrans",
    "SI": "Skynet Airlines",
    "SIH": "Skynet Airlines",
    "SJ": "Sriwijaya Air",
    "SJY": "Sriwijaya Air",
    "ZS": "Sama Airlines",
    "SMY": "Sama Airlines",
    "SQC": "Singapore Airlines Cargo",
    "FT": "Siem Reap Airways",
    "SRH": "Siem Reap Airways",
    "DG": "South East Asian Airlines",
    "SRQ": "South East Asian Airlines",
    "5G": "Skyservice Airlines",
    "SSV": "Skyservice Airlines",
    "FS": "Servicios de Transportes A",
    "STU": "Servicios de Transportes A",
    "SD": "Sudan Airways",
    "SUD": "Sudan Airways",
    "SV": "Saudi Arabian Airlines",
    "SVA": "Saudi Arabian Airlines",
    "WN": "Southwest Airlines",
    "SWA": "Southwest Airlines",
    "A4": "Southern Winds Airlines",
    "SWD": "Southern Winds Airlines",
    "LX": "Swiss International Air Lines",
    "SWR": "Swiss International Air Lines",
    "SWU": "Swiss European Air Lines",
    "WV": "Swe Fly",
    "SWV": "Swe Fly",
    "XQ": "SunExpress",
    "SXS": "SunExpress",
    "RB": "Syrian Arab Airlines",
    "SYR": "Syrian Arab Airlines",
    "AL": "Skywalk Airlines",
    "SYX": "Skywalk Airlines",
    "SC": "Shandong Airlines",
    "CDG": "Shandong Airlines",
    "CNO": "SAS Braathens",
    "9S": "Spring Airlines",
    "CQH": "Spring Airlines",
    "3U": "Sichuan Airlines",
    "CSC": "Sichuan Airlines",
    "FM": "Shanghai Airlines",
    "CSH": "Shanghai Airlines",
    "ZH": "Shenzhen Airlines",
    "CSZ": "Shenzhen Airlines",
    "7L": "Sun D'Or",
    "ERO": "Sun D'Or",
    "NE": "SkyEurope",
    "ESK": "SkyEurope",
    "HSK": "Sky Europe Airlines",
    "JK": "Spanair",
    "JKK": "Spanair",
    "NK": "Spirit Airlines",
    "NKS": "Spirit Airlines",
    "9R": "SATENA",
    "NSE": "SATENA",
    "OZW": "Skywest Airlines",
    "S3": "Santa Barbara Airlines",
    "BBR": "Santa Barbara Airlines",
    "H2": "Sky Airline",
    "SKU": "Sky Airline",
    "OO": "SkyWest",
    "SKW": "SkyWest",
    "JZ": "Skyways Express",
    "SKX": "Skyways Express",
    "BC": "Skymark Airlines",
    "SKY": "Skymark Airlines",
    "MI": "SilkAir",
    "SLK": "SilkAir",
    "PY": "Surinam Airways",
    "SLM": "Surinam Airways",
    "NB": "Sterling Airlines",
    "SNB": "Sterling Airlines",
    "6J": "Skynet Asia Airways",
    "SNJ": "Skynet Asia Airways",
    "IE": "Solomon Airlines",
    "SOL": "Solomon Airlines",
    "SOU": "Southern Airways",
    "6W": "Saratov Aviation Division",
    "SOV": "Saratov Aviation Division",
    "HZ": "Sat Airlines",
    "SOZ": "Sat Airlines",
    "SPI": "South Pacific Island Airways",
    "S5": "Shuttle America",
    "TCF": "Shuttle America",
    "DV": "Scat Air",
    "VSV": "Scat Air",
    "EQ": "TAME",
    "TAE": "TAME",
    "JJ": "TAM Brazilian Airlines",
    "TAM": "TAM Brazilian Airlines",
    "TP": "TAP Portugal",
    "TAP": "TAP Portugal",
    "TU": "Tunisair",
    "TAR": "Tunisair",
    "T2": "Thai Air Cargo",
    "TCG": "Thai Air Cargo",
    "FQ": "Thomas Cook Airlines",
    "TCW": "Thomas Cook Airlines",
    "MT": "Thomas Cook Airlines",
    "TCX": "Thomas Cook Airlines",
    "TGN": "Trigana Air Service",
    "TR": "Scoot",
    "TGW": "Tiger Airways",
    "TT": "Tigerair Australia",
    "TGG": "Tigerair Australia",
    "TG": "Thai Airways International",
    "THA": "Thai Airways International",
    "THK": "Turk Hava Kurumu Hava Taksi Isletmesi",
    "FD": "Thai AirAsia",
    "AIQ": "Thai AirAsia",
    "TK": "Turkish Airlines",
    "THY": "Turkish Airlines",
    "TIL": "Tajikistan International Airlines",
    "T7": "Twin Jet",
    "TJT": "Twin Jet",
    "TLA": "Translift Airways",
    "TMA": "Trans Mediterranean Airlines",
    "3P": "Tiara Air",
    "TNM": "Tiara Air",
    "BY": "Thomsonfly",
    "TOM": "Thomsonfly",
    "PM": "Tropic Air",
    "TOS": "Tropic Air",
    "QT": "TAMPA",
    "TPA": "TAMPA",
    "GE": "TransAsia Airways",
    "TNA": "TransAsia Airways",
    "HV": "Transavia Holland",
    "TRA": "Transavia Holland",
    "VR": "TACV",
    "TCV": "TACV",
    "9T": "Transwest Air",
    "ABS": "Transwest Air",
    "UN": "Transaero Airlines",
    "TSO": "Transaero Airlines",
    "T5": "Turkmenistan Airlines",
    "TUA": "Turkmenistan Airlines",
    "UG": "Tuninter",
    "TUI": "Tuninter",
    "QS": "Travel Service",
    "TVS": "Travel Service",
    "6B": "TUIfly Nordic",
    "BLX": "TUIfly Nordic",
    "DT": "TAAG Angola Airlines",
    "DTA": "TAAG Angola Airlines",
    "HVK": "Turkish Air Force",
    "PZ": "TAM Mercosur",
    "LAP": "TAM Mercosur",
    "AX": "Trans States Airlines",
    "LOF": "Trans States Airlines",
    "RO": "Tarom",
    "ROT": "Tarom",
    "3T": "Turan Air",
    "URN": "Turan Air",
    "8R": "TRIP Linhas A",
    "TIB": "TRIP Linhas A",
    "U5": "USA3000 Airlines",
    "GWY": "USA3000 Airlines",
    "UA": "United Airlines",
    "UAL": "United Airlines",
    "UAC": "United Air Charters",
    "U6": "Ural Airlines",
    "SVR": "Ural Airlines",
    "UF": "UM Airlines",
    "UKM": "UM Airlines",
    "US": "US Airways",
    "USA": "US Airways",
    "USH": "US Helicopter",
    "UT": "UTair Aviation",
    "UTA": "UTair Aviation",
    "AIO": "United States Air Force",
    "HY": "Uzbekistan Airways",
    "UZB": "Uzbekistan Airways",
    "PS": "Ukraine International Airlines",
    "AUI": "Ukraine International Airlines",
    "UH": "US Helicopter Corporation",
    "VF": "Valuair",
    "VLU": "Valuair",
    "VFC": "Vasco Air",
    "VN": "Vietnam Airlines",
    "HVN": "Vietnam Airlines",
    "NN": "VIM Airlines",
    "MOV": "VIM Airlines",
    "Y4": "Volaris",
    "VOI": "Volaris",
    "VI": "Volga-Dnepr Airlines",
    "VDA": "Volga-Dnepr Airlines",
    "VX": "Virgin America",
    "VRD": "Virgin America",
    "TV": "Virgin Express",
    "VEX": "Virgin Express",
    "VK": "Virgin Nigeria Airways",
    "VGN": "Virgin Nigeria Airways",
    "VS": "Virgin Atlantic Airways",
    "VIR": "Virgin Atlantic Airways",
    "ZG": "Viva Macau",
    "VVM": "Viva Macau",
    "VE": "Volare Airlines",
    "VLE": "Volare Airlines",
    "VLG": "Vueling Airlines",
    "XF": "Vladivostok Air",
    "VLK": "Vladivostok Air",
    "LC": "Varig Log",
    "VLO": "Varig Log",
    "VA": "Virgin Australia",
    "VOZ": "Virgin Australia",
    "RG": "VRG Linhas Aereas",
    "VRN": "VRG Linhas Aereas",
    "VP": "VASP",
    "VSP": "VASP",
    "VG": "VLM Airlines",
    "VLM": "VLM Airlines",
    "7W": "Wayraper",
    "WJ": "WebJet Linhas A",
    "WEB": "WebJet Linhas A",
    "2W": "Welcome Air",
    "WLC": "Welcome Air",
    "8O": "West Coast Air",
    "WS": "WestJet",
    "WJA": "WestJet",
    "WAL": "Western Airlines",
    "WF": "Widerøe",
    "WIF": "Widerøe",
    "IV": "Wind Jet",
    "JET": "Wind Jet",
    "IW": "Wings Air",
    "WON": "Wings Air",
    "W6": "Wizz Air",
    "WZZ": "Wizz Air",
    "8Z": "Wizz Air Hungary",
    "WVL": "Wizz Air Hungary",
    "WO": "World Airways",
    "WOA": "World Airways",
    "SE": "XL Airways France",
    "SEU": "XL Airways France",
    "MF": "Xiamen Airlines",
    "CXA": "Xiamen Airlines",
    "YL": "Yamal Airlines",
    "LLM": "Yamal Airlines",
    "IY": "Yemenia",
    "IYE": "Yemenia",
    "UMK": "Yuzhmashavia",
    "TAN": "Zanair",
    "Z4": "Zoom Airlines",
    "OOM": "Zoom Airlines",
    "VJ": "Royal Air Cambodge",
    "6T": "Air Mandalay",
    "BX": "Air Busan",
    "ABL": "Air Busan",
    "XW": "Sky Express",
    "SXR": "Sky Express",
    "GH": "Globus",
    "GLP": "Globus",
    "9Y": "Air Kazakhstan",
    "KZK": "Air Kazakhstan",
    "JD": "Japan Air System",
    "JAS": "Japan Air System",
    "DS": "EasyJet (DS)",
    "2I": "Star Peru (2I)",
    "KW": "Carnival Air Lines",
    "4H": "United Airways",
    "UBD": "United Airways",
    "5H": "Fly540",
    "FFV": "Fly540",
    "TO": "Transavia France",
    "TVF": "Transavia France",
    "WP": "Island Air (WP)",
    "MKU": "Island Air (WP)",
    "B7": "Uni Air",
    "UIA": "Uni Air",
    "YD": "Gomelavia",
    "WZ": "Red Wings",
    "RWZ": "Red Wings",
    "11": "TUIfly (X3)",
    "FU": "Felix Airways",
    "FXX": "Felix Airways",
    "K1": "Kostromskie avialinii",
    "KOQ": "Kostromskie avialinii",
    "XX": "Greenfly",
    "GFY": "Greenfly",
    "7J": "Tajik Air",
    "TM": "Air Mozambique",
    "ELK": "ELK Airways",
    "GY": "Gabon Airlines",
    "GBK": "Gabon Airlines",
    "MCA": "MCA Airlines",
    "ML": "Maldivo Airlines",
    "MAV": "Maldivo Airlines",
    "VH": "Virgin Pacific",
    "VNP": "Virgin Pacific",
    "Z2": "Zest Air",
    "HK": "Yangon Airways",
    "ZE": "Eastar Jet",
    "ESR": "Eastar Jet",
    "LJ": "Jin Air",
    "JNA": "Jin Air",
    "3O": "Air Arabia Maroc",
    "B1": "Baltic Air lines",
    "YC": "Ciel Canadien",
    "YCC": "Ciel Canadien",
    "CN": "Canadian National Airways",
    "YCP": "Canadian National Airways",
    "FA": "Epic Holiday",
    "AXC": "Indochina Airlines",
    "3I": "Air Comet Chile",
    "FLB": "German Air Force - FLB",
    "L8": "Line Blue",
    "LBL": "Line Blue",
    "LLC": "FlyLAL Charters",
    "SZ": "Salzburg arrows",
    "TQ": "Texas Wings",
    "TXW": "Texas Wings",
    "DH": "Dennis Sky",
    "DSY": "Dennis Sky",
    "ZZ": "Zz",
    "A1": "Atifly",
    "SZB": "Aerolineas heredas santa maria",
    "99": "Ciao Air",
    "JRB": "Jc royal.britannica",
    "5P": "Pal airlines",
    "C1": "CanXpress",
    "V5": "Danube Wings (V5)",
    "SH": "Sharp Airlines",
    "SHA": "Sharp Airlines",
    "C2": "CanXplorer",
    "CAP": "CanXplorer",
    "QA": "Click (Mexicana)",
    "W1": "World Experience Airline",
    "J4": "ALAK",
    "3E": "Air Choice One",
    "GCR": "Tianjin Airlines",
    "KN": "China United",
    "ZQ": "Locair",
    "LOC": "Locair",
    "4Q": "Safi Airlines",
    "K5": "SeaPort Airlines",
    "SQH": "SeaPort Airlines",
    "S6": "Salmon Air",
    "01": "Bobb Air Freight",
    "V9": "Star1 Airlines",
    "HCW": "Star1 Airlines",
    "6D": "Pelita",
    "J5": "Alaska Seaplane Service",
    "ENJ": "Enerjet",
    "I6": "MexicanaLink",
    "MXI": "MexicanaLink",
    "IP": "Island Spirit",
    "ISX": "Island Spirit",
    "T0": "TACA Peru",
    "OBS": "Orbest",
    "SOA": "Southern Air Charter",
    "SVG": "SVG Air",
    "CEY": "Air Century",
    "7Q": "Pan Am World Airways Dominicana",
    "PF": "Primera Air",
    "3S": "Air Antilles Express",
    "OLS": "Sol Lineas Aereas",
    "P7": "Regional Paraguaya",
    "REP": "Regional Paraguaya",
    "V6": "VIP Ecuador",
    "NDN": "Transportes Aereos Cielos Andinos",
    "P9": "Peruvian Airlines",
    "EFY": "EasyFly",
    "ЯП": "Polar Airlines",
    "OC": "Catovair",
    "ANU": "Andalus Lineas Aereas",
    "DCD": "Air 26",
    "MTW": "Mauritania Airways",
    "CEL": "CEIBA Intercontinental",
    "7Z": "Halcyonair",
    "4P": "Business Aviation",
    "E9": "Compagnie Africaine d\\\\'Aviation",
    "K8": "Zambia Skyways",
    "UJ": "AlMasria Universal Airlines",
    "LMU": "AlMasria Universal Airlines",
    "MSE": "EgyptAir Express",
    "6Y": "SmartLynx Airlines",
    "EUD": "Air Italy Egypt",
    "K7": "KoralBlue Airlines",
    "KBR": "KoralBlue Airlines",
    "WRC": "Wind Rose Aviation",
    "E4": "Elysian Airlines",
    "GIE": "Elysian Airlines",
    "SEN": "Sevenair",
    "HT": "Hellenic Imperial Airways",
    "IMP": "Hellenic Imperial Airways",
    "WD": "Amsterdam Airlines",
    "AAN": "Amsterdam Airlines",
    "Q9": "Arik Niger",
    "NAK": "Arik Niger",
    "DA": "Dana Air",
    "8F": "STP Airways",
    "STP": "STP Airways",
    "7Y": "Med Airways",
    "UQ": "Guangxi Beibu Gulf Airlines",
    "SJU": "Skyjet Airlines",
    "G6": "Air Volga",
    "TDK": "Transavia Denmark",
    "RL": "Royal Falcon",
    "RFJ": "Royal Falcon",
    "4L": "Euroline",
    "MJX": "Euroline",
    "TRK": "Turkuaz Airlines",
    "ZF": "Athens Airways",
    "VQ": "Viking Hellas",
    "VKH": "Viking Hellas",
    "FNA": "Norlandair",
    "FVM": "Flugfelag Vestmannaeyja",
    "DZ": "Starline.kz",
    "L7": "Lugansk Airlines",
    "6P": "Gryphon Airlines",
    "GP": "Gadair European Airlines",
    "GDR": "Gadair European Airlines",
    "SM": "Spirit of Manila Airlines",
    "MNP": "Spirit of Manila Airlines",
    "OQ": "Chongqing Airlines",
    "CQN": "Chongqing Airlines",
    "GDC": "Grand China Air",
    "PN": "West Air China",
    "CHB": "West Air China",
    "QAX": "QatXpress",
    "1C": "OneChina",
    "Y7": "NordStar Airlines",
    "JR": "Joy Air",
    "JOY": "Joy Air",
    "CD": "Air India Regional",
    "9H": "MDLR Airlines",
    "JGN": "Jagson Airlines",
    "Q2": "Maldivian",
    "XN": "Xpressair",
    "VC": "Strategic Airlines",
    "QFZ": "Fars Air Qeshm",
    "EAA": "Eastok Avia",
    "JPU": "Jupiter Airlines",
    "VIS": "Vision Air International",
    "NA": "Al-Naser Airlines",
    "JH": "Fuji Dream Airlines",
    "KEA": "Korea Express Air",
    "EZA": "Eznis Airways",
    "PFL": "Pacific Flier",
    "PSB": "Syrian Pearl Airlines",
    "5E": "SGA Airlines",
    "F8": "Air2there",
    "AO": "Avianova (Russia)",
    "PA": "Parmiss Airlines (IPV)",
    "IPV": "Parmiss Airlines (IPV)",
    "ES": "EuropeSky",
    "EUV": "EuropeSky",
    "GB": "BRAZIL AIR",
    "BZE": "BRAZIL AIR",
    "MR": "Homer Air",
    "OME": "Homer Air",
    "WQ": "PanAm World Airways",
    "PQW": "PanAm World Airways",
    "YY": "Virginwings",
    "VWA": "Virginwings",
    "KY": "KSY",
    "KSY": "KSY",
    "BQ": "Buquebus Líneas Aéreas",
    "BQB": "Buquebus Líneas Aéreas",
    "CQ": "SOCHI AIR",
    "KOL": "SOCHI AIR",
    "WU": "Wizz Air Ukraine",
    "WAU": "Wizz Air Ukraine",
    "47": "88",
    "VVN": "88",
    "LQ": "LCM AIRLINES",
    "LMM": "LCM AIRLINES",
    "K6": "Cambodia Angkor Air (K6)",
    "69": "Royal European Airlines",
    "AD": "Azul",
    "AZU": "Azul",
    "PQ": "LSM Airlines",
    "LOO": "LSM Airlines",
    "PZY": "Zapolyarie Airlines",
    "C4": "LionXpress",
    "LIX": "LionXpress",
    "GK": "Genesis",
    "XZ": "Congo Express",
    "FZ": "Fly Dubai",
    "FDB": "Fly Dubai",
    "D1": "Domenican Airlines",
    "MDO": "Domenican Airlines",
    "JY": "Aereonautica militare",
    "AXZ": "Aereonautica militare",
    "KLS": "Kal Star Aviation",
    "YZ": "LSM AIRLINES ",
    "YZZ": "LSM AIRLINES ",
    "UR": "UTair-Express",
    "G5": "Huaxia",
    "ZP": "Zabaykalskii Airlines",
    "ZZZ": "Zabaykalskii Airlines",
    "XBM": "CBM America",
    "M4": "Marysya Airlines",
    "N1": "N1",
    "4Z": "Airlink (SAA)",
    "WFX": "Westfalia Express VA",
    "3B": "JobAir",
    "BZ": "Black Stallion Airways",
    "BSA": "Black Stallion Airways",
    "GM": "German International Air Lines",
    "GER": "German International Air Lines",
    "TB": "TrasBrasil",
    "TBZ": "TrasBrasil",
    "TH": "TransBrasil Airlines",
    "THS": "TransBrasil Airlines",
    "9C": "China SSS",
    "IIA": "AIR INDOCHINE",
    "HPY": "Happy Air",
    "SRB": "Solar Air",
    "P8": "Air Mekong",
    "MKG": "Air Mekong",
    "H3": "Harbour Air (Priv)",
    "HH": "Air Hamburg (AHO)",
    "AHO": "Air Hamburg (AHO)",
    "Z6": "ZABAIKAL AIRLINES",
    "ZTT": "ZABAIKAL AIRLINES",
    "TI": "TransHolding",
    "THI": "TransHolding",
    "SZZ": "SUR Lineas Aereas",
    "YT": "Yeti Airways",
    "Y1": "Yellowstone Club Private Shuttle",
    "NS": "Caucasus Airlines",
    "S1": "Serbian Airlines",
    "WM": "Windward Islands Airways",
    "YO": "TransHolding System",
    "TYS": "TransHolding System",
    "CB": "CCML Airlines",
    "CCC": "CCML Airlines",
    "ELC": "Small Planet Airlines",
    "F1": "Fly Brasil",
    "FBL": "Fly Brasil",
    "1F": "CB Airways UK ( Interliging Flights )",
    "CIF": "CB Airways UK ( Interliging Flights )",
    "3F": "Fly Colombia ( Interliging Flights )",
    "T6": "Trans Pas Air",
    "МИ": "KMV",
    "HC": "Himalayan Airlines",
    "HYM": "Himalayan Airlines",
    "G1": "Indya Airline Group",
    "WG": "Sunwing",
    "TWD": "Turkish Wings Domestic",
    "ZX": "Japan Regio",
    "ZXY": "Japan Regio",
    "IXO": "OCEAN AIR CARGO",
    "N0": "Norte Lineas Aereas",
    "W7": "Austral Brasil",
    "H9": "PEGASUS AIRLINES-",
    "QC": "Camair-co",
    "RS": "Sky Regional",
    "II": "LSM International ",
    "UWW": "LSM International ",
    "BU": "Baikotovitchestrian Airlines ",
    "BUU": "Baikotovitchestrian Airlines ",
    "L4": "Luchsh Airlines ",
    "LJJ": "Luchsh Airlines ",
    "QQQ": "ENTERair",
    "6U": "Air Cargo Germany",
    "7M": "Mongolian International Air Lines ",
    "ZTF": "Mongolian International Air Lines ",
    "TW": "Tway Airlines",
    "TWB": "Tway Airlines",
    "HI": "Papillon Grand Canyon Helicopters",
    "JX": "Jusur airways",
    "JSR": "Jusur airways",
    "XB": "NEXT Brasil",
    "NXB": "NEXT Brasil",
    "W4": "AeroWorld ",
    "WER": "AeroWorld ",
    "GN": "GNB Linhas Aereas",
    "E1": "Usa Sky Cargo",
    "HN": "Hankook Airline",
    "HNX": "Hankook Airline",
    "Z7": "REDjet",
    "PT": "Red Jet Andes",
    "QY": "Red Jet Canada",
    "0G": "Sprintair",
    "SAR": "Sprintair",
    "4X": "Red Jet Mexico",
    "Y8": "Marusya Airways",
    "MRS": "Marusya Airways",
    "7H": "Era Alaska",
    "ERR": "Era Alaska",
    "R8": "AirRussia",
    "RRJ": "AirRussia",
    "H1": "Hankook Air US",
    "SMW": "Carpatair Flight Training",
    "H5": "I-Fly",
    "RSY": "I-Fly",
    "WTJ": "Whitejets",
    "KT": "VickJet",
    "VKJ": "VickJet",
    "XV": "BVI Airways",
    "HAY": "Hamburg Airways",
    "SO": "Salsa d\\\\'Haiti",
    "SLC": "Salsa d\\\\'Haiti",
    "ZJ": "Zambezi Airlines (ZMA)",
    "KND": "Kan Air",
    "CUD": "Air Cudlua",
    "YQ": "Polet Airlines (Priv)",
    "AXE": "Air Explore",
    "12": "12 North",
    "HCC": "Holidays Czech Airlines",
    "COE": "Comtel Air",
    "MIC": "Mint Airways",
    "OBT": "Orbit Airlines",
    "BUR": "Air Bucharest",
    "LAV": "AlbaStar",
    "L6": "Mauritania Airlines International",
    "MAI": "Mauritania Airlines International",
    "6F": "MAT Airways",
    "MKD": "MAT Airways",
    "AW": "Asian Wings Airways",
    "AWM": "Asian Wings Airways",
    "E5": "Air Arabia Egypt",
    "RBG": "Air Arabia Egypt",
    "EGS": "Eagles Airlines",
    "YEP": "YES Airways",
    "CT": "Alitalia Cityliner",
    "DSV": "Direct Aero Services",
    "MDP": "Medallion Air",
    "OI": "Orchid Airlines",
    "ORC": "Orchid Airlines",
    "Y5": "Asia Wings",
    "AWA": "Asia Wings",
    "GNN": "Georgian International Airlines",
    "BTM": "Air Batumi",
    "XR": "Skywest Australia",
    "NP": "Nile Air",
    "NIA": "Nile Air",
    "FDD": "Feeder Airlines",
    "DN": "Senegal Airlines",
    "SGG": "Senegal Airlines",
    "S9": "Starbow Airlines",
    "0X": "Copenhagen Express",
    "8B": "BusinessAir",
    "BCC": "BusinessAir",
    "YR": "SENIC AIRLINES",
    "XOJ": "XOJET",
    "C7": "Sky Wing Pacific",
    "BEU": "Bateleur Air",
    "PP": "Air Indus",
    "OAI": "Orbit International Airlines",
    "OAR": "Orbit Regional Airlines",
    "OAN": "Orbit Atlantic Airways",
    "VOO": "Volotea",
    "MM": "Peach Aviation",
    "HTH": "Helitt Líneas Aéreas",
    "RSD": "Russia State Transport",
    "MWI": "Malaysia Wings",
    "U1": "Aviabus",
    "ABI": "Aviabus",
    "DF": "Michael Airlines",
    "MJG": "Michael Airlines",
    "ZC": "Korongo Airlines",
    "KGO": "Korongo Airlines",
    "I5": "Indonesia Sky",
    "IDS": "Indonesia Sky",
    "B0": "Aws express",
    "76": "Southjet",
    "SJS": "Southjet",
    "77": "Southjet connect",
    "ZCS": "Southjet connect",
    "78": "Southjet cargo",
    "XAN": "Southjet cargo",
    "I2": "Iberia Express",
    "IBS": "Iberia Express",
    "4O": "Interjet (ABC Aerolineas)",
    "OG": "AirOnix",
    "NJ": "Nordic Global Airlines",
    "NGB": "Nordic Global Airlines",
    "SCO": "Scoot",
    "5K": "Hi Fly (5K)",
    "WH": "China Northwest Airlines (WH)",
    "ZN": "Zenith International Airline",
    "ZNA": "Zenith International Airline",
    "O1": "Orbit Airlines Azerbaijan",
    "OAB": "Orbit Airlines Azerbaijan",
    "A6": "Air Alps Aviation (A6)",
    "FKA": "Flying kangaroo Airline",
    "RSJ": "RusJet",
    "VJC": "VietJet Air",
    "P4": "Patriot Airways",
    "V2": "Vision Airlines (V2)",
    "RBY": "Vision Airlines (V2)",
    "5Q": "BQB Lineas Aereas",
    "WAJ": "AirAsia Japan",
    "YE": "Yellowtail",
    "YEL": "Yellowtail",
    "KG": "Royal Airways",
    "RAW": "Royal Airways",
    "FH": "FlyHigh Airlines Ireland (FH)",
    "FHI": "FlyHigh Airlines Ireland (FH)",
    "XSR": "Executive AirShare",
    "HBH": "Hebei Airlines",
    "KBZ": "Air KBZ",
    "2D": "Aero VIP (2D)",
    "YH": "Yangon Airways Ltd.",
    "TJ": "T.J. Air",
    "TJA": "T.J. Air",
    "SX": "SkyWork Airlines ",
    "W2": "Maastricht Airlines",
    "24": "Euro Jet",
    "UAT": "Ukraine Atlantic",
    "NMA": "Nesma Airlines",
    "EHN": "East Horizon",
    "MJP": "Air Majoro",
    "RJD": "Rotana Jet",
    "Q3": "SOCHI AIR CHATER",
    "QER": "SOCHI AIR CHATER",
    "J7": "Denim Air ",
    "OD": "Malindo Air",
    "MXD": "Malindo Air",
    "HRM": "Hermes Airlines",
    "Z9": "Flightlink Tanzania",
    "I8": "IzAvia",
    "КТК": "Катэкавиа",
    "PKV": "Псковавиа",
    "M1": "Maryland Air",
    "7I": "Insel Air (7I/INC) (Priv)",
    "5Z": "VivaColombia",
    "VVC": "VivaColombia",
    "FCM": "Flybe Finland Oy",
    "BGY": "Bingo Airways",
    "BBG": "Bluebird Airways (BZ)",
    "ZM": "Apache Air",
    "IWA": "Apache Air",
    "M2": "MHS Aviation GmbH",
    "NR": "Jettor Airlines",
    "JTO": "Jettor Airlines",
    "VQI": "Flyme (VP)",
    "SL": "Thai Lion Air",
    "TLM": "Thai Lion Air",
    "GMR": "Golden Myanmar Airlines",
    "CNF": "Canaryfly",
    "KSZ": "Sunrise Airways",
    "N8": "National Air Cargo",
    "NCR": "National Air Cargo",
    "13": "Eastern Atlantic Virtual Airlines",
    "EAV": "Eastern Atlantic Virtual Airlines",
    "QG": "Citilink Indonesia",
    "TTZ": "Transair",
    "EVC": "Comfort Express Virtual Charters Albany",
    "CEO": "Comfort Express Virtual Charters",
    "FYJ": "FLYJET",
    "S8": "Snowbird Airlines",
    "SBD": "Snowbird Airlines",
    "KRY": "Russkie Krylya",
    "KH": "Kharkiv Airlines",
    "KHK": "Kharkiv Airlines",
    "XA": "XAIR USA",
    "XAU": "XAIR USA",
    "LB": "Air Costa",
    "RMK": "Simrik Airlines",
    "XP": "XPTO",
    "XPT": "XPTO",
    "DME": "Royal Flight",
    "EGH": "BBN-Airways",
    "TKS": "Tomsk-Avia",
    "3W": "Malawian Airlines",
    "NYT": "Yeti Airlines ",
    "KCU": "Skyline Ulasim Ticaret A.S.",
    "ENY": "Envoy Air",
    "CCB": "CARICOM AIRWAYS (BARBADOS) INC.",
    "RN": "Rainbow Air (RAI)",
    "RAB": "Rainbow Air (RAI)",
    "RY": "Rainbow Air Canada",
    "RAY": "Rainbow Air Canada",
    "RX": "Regent Airways",
    "RPO": "Rainbow Air Polynesia",
    "RU": "Rainbow Air Euro",
    "RUE": "Rainbow Air Euro",
    "RM": "Rainbow Air US",
    "RNY": "Rainbow Air US",
    "TNS": "Transilvania",
    "QD": "Dobrolet",
    "DOB": "Dobrolet",
    "S0": "Spike Airlines",
    "SAL": "Spike Airlines",
    "GCA": "Grand Cru Airlines",
    "RLX": "Go2Sky",
    "L1": "All Argentina",
    "A2": "All America",
    "L9": "All Asia",
    "9A": "All Africa",
    "N4": "Regionalia México",
    "N9": "All Europe",
    "N7": "All Spain",
    "9N": "Regional Air Iceland",
    "8K": "Voestar",
    "7O": "All Colombia",
    "2X": "Regionalia Uruguay",
    "9X": "Regionalia Venezuela",
    "9J": "Regionalia Chile",
    "6C": "Vuela Cuba",
    "88": "All Australia",
    "ER": "Fly Europa",
    "RWW": "Fly Europa",
    "PO": "FlyPortugal",
    "FPT": "FlyPortugal",
    "MMA": "Myanmar Airways International",
    "UK": "Vistara",
    "VTI": "Vistara",
    "CUH": "Urumqi Air",
    "CBG": "Guangxi Beibu Gulf Airlines",
    "2Y": "My Indo Airlines",
    "MYU": "My Indo Airlines",
    "FRV": "Government of Morocco",
    "HKC": "Hong Kong Air Cargo",
    "UBG": "US-Bangla Airlines",
    "NJE": "NetJets Europe",
    "BTN": "Bhutan Airlines",
    "IRB": "Iran Airtour",
    "AOJ": "Avcon Jet",
    "IDX": "Indonesia AirAsia X",
    "QE": "Qatar Executive",
    "QQE": "Qatar Executive",
    "O3": "SF Airlines",
    "CSS": "SF Airlines",
    "RGE": "Regent Airways",
    "CXM": "AsiaCargo Express",
}
