"""Module containing static airline name-code data"""

# Name : IATA mapping with ICAO as backup
NAME_TO_AIRLINE_CODE_MAPPING = {
    "1time airline": "1T",
    "40-mile air": "Q5",
    "ansett australia": "AN",
    "abacus international": "1B",
    "aigle azur": "ZI",
    "aloha airlines": "AQ",
    "american airlines": "AA",
    "asiana airlines": "OZ",
    "askari aviation": "4K",
    "afriqiyah airways": "8U",
    "allegiant air": "G4",
    "absa - aerolinhas brasileiras": "M3",
    "astral aviation": "8V",
    "air tindi": "8T",
    "ada air": "ZY",
    "adria airways": "JP",
    "air europa": "UX",
    "aero benin": "EM",
    "aegean airlines": "A3",
    "air europe": "PE",
    "alaska central express": "KO",
    "aces colombia": "AES",
    "astraeus": "5W",
    "aerosvit airlines": "VV",
    "air italy": "I9",
    "alliance airlines": "QQ",
    "ariana afghan airlines": "FG",
    "aeroflot russian airlines": "SU",
    "air bosna": "JA",
    "air france": "AF",
    "air caledonie international": "SB",
    "air salone": "20",
    "air cargo carriers": "2Q",
    "air namibia": "SW",
    "aerolitoral": "5D",
    "air glaciers": "7T",
    "aviogenex": "AGX",
    "aeroper": "PL",
    "atlas blue": "8A",
    "azerbaijan airlines": "J2",
    "avies": "U3",
    "airblue": "ED",
    "airlift international": "AIR",
    "air berlin": "AB",
    "air india limited": "AI",
    "air bourbon": "ZB",
    "air atlanta icelandic": "CC",
    "air tahiti nui": "TN",
    "arkia israel airlines": "IZ",
    "air jamaica": "JM",
    "air one": "AP",
    "air sahara": "S2",
    "air malta": "KM",
    "air japan": "NQ",
    "air korea co. ltd.": "AKA",
    "air kiribati": "4A",
    "america west airlines": "HP",
    "air wisconsin": "ZW",
    "tatarstan airlines": "U9",
    "allegheny commuter airlines": "ALO",
    "air sunshine": "RSI",
    "air libert": "VD",
    "air malawi": "QM",
    "air sicilia": "BM",
    "ata airlines": "AMT",
    "air macau": "NX",
    "amc airlines": "AMV",
    "air seychelles": "HM",
    "aeroméxico": "AM",
    "all nippon airways": "NH",
    "air nostrum": "YW",
    "air niugini": "PX",
    "air arabia": "G9",
    "air canada": "AC",
    "air baltic": "BT",
    "air nippon": "EL",
    "airnorth": "TL",
    "air north charter - canada": "4N",
    "air new zealand": "NZ",
    "alitalia express": "XM",
    "aero flight": "GV",
    "arrow air": "JW",
    "aerocondor": "2B",
    "aires": "4C",
    "aerolineas argentinas": "AR",
    "alaska airlines": "AS",
    "air sinai": "4D",
    "atlantic southeast airlines": "EV",
    "astrakhan airlines": "OB",
    "air tanzania": "TC",
    "air burkina": "2J",
    "airlines of tasmania": "FO",
    "air saint pierre": "PJ",
    "austrian airlines": "OS",
    "air southwest": "WOW",
    "augsburg airways": "IQ",
    "atur": "TUR",
    "abu dhabi amiri flight": "MO",
    "aeroflot-nord": "5N",
    "aurigny air services": "GR",
    "austral lineas aereas": "AU",
    "avianca - aerovias nacionales de colombia": "AV",
    "air vanuatu": "NF",
    "air bangladesh": "B9",
    "air mediterranee": "DR",
    "air moorea": "TAH",
    "aeroline gmbh": "7E",
    "air wales": "6G",
    "air caraïbes": "TX",
    "air india express": "IX",
    "air exel": "XT",
    "airasia": "AK",
    "atlant-soyuz airlines": "3G",
    "alitalia": "AZ",
    "amaszonas": "Z8",
    "air zimbabwe": "UM",
    "aserca airlines": "R7",
    "rossiya-russian airlines": "FV",
    "american eagle airlines": "MQ",
    "ad aviation": "VUE",
    "air ivoire": "VU",
    "air botswana": "BP",
    "air foyle": "GS",
    "air tahiti": "VT",
    "air via": "VL",
    "africa west": "FK",
    "atran cargo airlines": "V8",
    "air china": "CA",
    "aero condor peru": "Q6",
    "air chathams": "CV",
    "air marshall islands": "CW",
    "access air": "ZA",
    "air algerie": "AH",
    "adam air": "KI",
    "air dolomiti": "EN",
    "aeroflot-don": "D9",
    "air madrid": "NM",
    "aer lingus": "EI",
    "air finland": "OF",
    "airfix aviation": "FIX",
    "air pacific": "FJ",
    "atlantic airways": "RC",
    "air florida": "QH",
    "air iceland": "NY",
    "air philippines": "2P",
    "air guinee express": "2U",
    "air greenland": "GL",
    "atlas air": "5Y",
    "air guyane": "GG",
    "air bagan": "W9",
    "air canada jazz": "QK",
    "atlasjet": "KK",
    "air koryo": "JS",
    "air astana": "KC",
    "albanian airlines": "LV",
    "air alfa": "LFA",
    "aerolane": "XL",
    "atlantis european airways": "TD",
    "air luxor": "LK",
    "air mauritius": "MK",
    "air madagascar": "MD",
    "air moldova": "9U",
    "alsie express": "6I",
    "air plus comet": "A7",
    "astair": "8D",
    "aero contractors": "AJ",
    "aeropelican air services": "OT",
    "aer arann": "RE",
    "air austral": "UU",
    "asian spirit": "6K",
    "air afrique": "RK",
    "airlinair": "A5",
    "aero lanka": "QL",
    "armavia": "U8",
    "aerorep": "P5",
    "aero-service": "BF",
    "aerosur": "5L",
    "aeronorte": "RTE",
    "avient aviation": "Z3",
    "aircompany yakutia": "R3",
    "aeromar": "VW",
    "arkefly": "OR",
    "airlines png": "CG",
    "airtran airways": "FL",
    "air transat": "TS",
    "avialeasing aviation company": "EC",
    "tyrolean airways": "TYR",
    "aerolineas galapagos (aerogal)": "2K",
    "alrosa mirny air enterprise": "6R",
    "british airways": "BA",
    "biman bangladesh airlines": "BG",
    "belair airlines": "4T",
    "bahamasair": "UP",
    "balkan bulgarian airlines": "LZ",
    "british international helicopters": "BS",
    "bf-lento oy": "BKF",
    "bangkok airways": "PG",
    "blue1": "KF",
    "baltic airlines": "BLL",
    "bearskin lake air service": "JV",
    "bellview airlines": "B3",
    "bmi": "BD",
    "bmibaby": "WW",
    "bemidji airlines": "CH",
    "british midland regional": "BMR",
    "blue panorama airlines": "BV",
    "budapest aircraft services/manx2": "BPS",
    "bering air": "8E",
    "brazilian air force": "BRS",
    "belavia belarusian airlines": "B2",
    "metro batavia": "7P",
    "berjaya air": "J8",
    "blue wings": "QW",
    "brit air": "DB",
    "brussels airlines": "SN",
    "binter canarias": "NT",
    "blue air": "0B",
    "british mediterranean airways": "KJ",
    "bulgaria air": "FB",
    "barents airlink": "8N",
    "cal cargo air lines": "5C",
    "calima aviacion": "XG",
    "canadian airlines": "CP",
    "canadian north": "5T",
    "cape air": "9K",
    "caribbean airlines": "BW",
    "carpatair": "V3",
    "caspian airlines": "RV",
    "cathay pacific": "CX",
    "cayman airways": "KX",
    "cebu pacific": "5J",
    "central connect airlines": "CCG",
    "centralwings": "C0",
    "charter air": "CHW",
    "chautauqua airlines": "RP",
    "china airlines": "CI",
    "china eastern airlines": "MU",
    "china southern airlines": "CZ",
    "china united airlines": "HR",
    "yunnan airlines": "3Q",
    "cimber air": "QI",
    "cirrus airlines": "C9",
    "city airline": "CF",
    "city connexion airlines": "G3",
    "cityjet": "WX",
    "ba cityflyer": "CJ",
    "click airways": "CGK",
    "coastal air": "DQ",
    "colgan air": "9L",
    "comair": "MN",
    "commutair": "C5",
    "comores airlines": "KR",
    "compass airlines": "CP",
    "condor flugdienst": "DE",
    "consorcio aviaxsa": "6A",
    "contact air": "C3",
    "continental airlines": "CO",
    "continental express": "CO",
    "continental micronesia": "CS",
    "conviasa": "V0",
    "copa airlines": "CM",
    "copterline": "AAQ",
    "corendon airlines": "CAI",
    "corsairfly": "SS",
    "corse-mediterranee": "XK",
    "crest aviation": "CAN",
    "croatia airlines": "OU",
    "crown airways": "CRO",
    "cubana de aviación": "CU",
    "cyprus airways": "CY",
    "cyprus turkish airlines": "YK",
    "czech airlines": "OK",
    "dat danish air transport": "DX",
    "daallo airlines": "D3",
    "dalavia": "H8",
    "darwin airline": "0D",
    "delta aerotaxi": "DEA",
    "delta air lines": "DL",
    "denim air": "DNM",
    "deutsche bahn": "2A",
    "djibouti airlines": "D8",
    "dniproavia": "UDN",
    "dominicana de aviaci": "DO",
    "domodedovo airlines": "E3",
    "donbassaero": "5D",
    "dragonair": "KA",
    "druk air": "KB",
    "dubrovnik air": "DBK",
    "dutch antilles express": "DNL",
    "dba": "DI",
    "eva air": "BR",
    "eagle air": "H7",
    "east african": "QU",
    "eastern airways": "T3",
    "eastland air": "DK",
    "ecuavia": "ECU",
    "edelweiss air": "WK",
    "egyptair": "MS",
    "el al israel airlines": "LY",
    "el-buraq air transport": "UZ",
    "emirates": "EK",
    "empresa ecuatoriana de aviacion": "EU",
    "eritrean airlines": "B8",
    "estonian air": "OV",
    "ethiopian airlines": "ET",
    "etihad airways": "EY",
    "euro exec express": "RZ",
    "eurocypria airlines": "UI",
    "eurofly service": "GJ",
    "eurolot": "K2",
    "european air express": "EA",
    "eurowings": "EW",
    "evergreen international airlines": "EZ",
    "excel airways": "JN",
    "excel charter": "XEL",
    "express one international": "EO",
    "expressjet": "XE",
    "easyjet": "U2",
    "far eastern air transport": "EF",
    "finnair": "AY",
    "finncomm airlines": "FC",
    "firefly": "FY",
    "first air": "7F",
    "first choice airways": "DP",
    "flightline": "B5",
    "florida west international airways": "RF",
    "airasia x": "D7",
    "flylal": "TE",
    "flynordic": "LF",
    "flybaboo": "F7",
    "flybe": "BE",
    "flyglobespan": "B4",
    "flyhy cargo airlines": "FYH",
    "formosa airlines": "VY",
    "freedom air": "FP",
    "freedom airlines": "FRL",
    "frontier airlines": "F9",
    "frontier flying service": "2F",
    "gb airways": "GT",
    "garuda indonesia": "GA",
    "gazpromavia": "4G",
    "georgian airways": "A9",
    "georgian national airlines": "QB",
    "germania": "ST",
    "germanwings": "4U",
    "ghana international airlines": "G0",
    "go air": "G8",
    "gojet airlines": "G7",
    "gol transportes aéreos": "G3",
    "golden air": "DC",
    "great lakes airlines": "ZK",
    "grupo taca": "TA",
    "gulf air": "GFA",
    "gulf air bahrain": "GF",
    "gulfstream international airlines": "GFT",
    "hageland aviation services": "H6",
    "hainan airlines": "HU",
    "haiti ambassador airlines": "2T",
    "hamburg international": "4R",
    "tuifly": "X3",
    "hapagfly": "HF",
    "hawaiian airlines": "HA",
    "hawkair": "BH",
    "heli france": "8H",
    "helijet": "JB",
    "hellas jet": "T4",
    "hello": "HW",
    "helvetic airways": "2L",
    "hex'air": "UD",
    "highland airways": "HWY",
    "hokkaido international airlines": "HD",
    "hong kong airlines": "HX",
    "hong kong express airways": "UO",
    "horizon air": "QX",
    "horizon airlines": "BN",
    "iberia airlines": "IB",
    "iberworld": "TY",
    "ibex airlines": "FW",
    "icar air": "RAC",
    "icelandair": "FI",
    "imair airlines": "IK",
    "indigo airlines": "6E",
    "indian airlines": "IC",
    "indigo": "I9",
    "indonesia airasia": "QZ",
    "indonesian airlines": "IO",
    "interair south africa": "D6",
    "interavia airlines": "ZA",
    "interlink airlines": "ID",
    "intersky": "3L",
    "iran air": "IR",
    "iran aseman airlines": "EP",
    "iraqi airways": "IA",
    "island airlines": "IS",
    "cargo plus aviation": "8L",
    "islas airways": "IF",
    "islena de inversiones": "WC",
    "israir": "6H",
    "itek air": "GI",
    "jal express": "JC",
    "jalways": "JO",
    "japan airlines": "JL",
    "japan asia airways": "EG",
    "japan transocean air": "NU",
    "jat airways": "JU",
    "jazeera airways": "J9",
    "jeju air": "7C",
    "jet airways": "QJ",
    "jetstar asia airways": "3K",
    "jet2.com": "LS",
    "jet4you": "8J",
    "jetblue airways": "B6",
    "jetairfly": "JF",
    "jetflite": "JEF",
    "jetstar airways": "JQ",
    "juneyao airlines": "HO",
    "kd avia": "KD",
    "klm cityhopper": "WA",
    "klm royal dutch airlines": "KL",
    "kam air": "RQ",
    "kavminvodyavia": "KV",
    "kendell airlines": "KDA",
    "kenmore air": "M5",
    "kenya airways": "KQ",
    "kingfisher airlines": "IT",
    "kish air": "Y9",
    "kogalymavia air company": "7K",
    "korean air": "KE",
    "kosmos": "KSM",
    "krasnojarsky airlines": "7B",
    "kuban airlines": "GW",
    "kuwait airways": "KU",
    "kuzu airlines cargo": "GO",
    "lacsa": "LR",
    "lan airlines": "LA",
    "lan argentina": "4M",
    "lan express": "LU",
    "lan peru": "LP",
    "lot polish airlines": "LO",
    "lte international airways": "XO",
    "ltu austria": "L3",
    "ltu international": "LT",
    "lao airlines": "QV",
    "latcharter": "LTC",
    "lauda air": "NG",
    "leeward islands air transport": "LI",
    "libyan arab airlines": "LN",
    "linhas a": "LM",
    "lion mentari airlines": "JT",
    "luftfahrtgesellschaft walter": "HE",
    "lufthansa": "LH",
    "lufthansa cargo": "LH",
    "lufthansa cityline": "CL",
    "lufttransport": "L5",
    "luxair": "LG",
    "l": "MJ",
    "masair": "M7",
    "mat macedonian airlines": "IN",
    "miat mongolian airlines": "OM",
    "mng airlines": "MB",
    "macair airlines": "CC",
    "maersk": "DM",
    "mahan air": "W5",
    "malaysia airlines": "MH",
    "malta air charter": "R5",
    "malév": "MA",
    "mandala airlines": "RI",
    "mandarin airlines": "AE",
    "mango": "JE",
    "martinair": "MP",
    "maxair": "8M",
    "maya island air": "MW",
    "meridiana": "IG",
    "merpati nusantara airlines": "MZ",
    "mesa airlines": "YV",
    "mesaba airlines": "XJ",
    "mexicana de aviaci": "MX",
    "middle east airlines": "ME",
    "midway airlines": "JI",
    "midwest airlines": "YX",
    "midwest airlines (egypt)": "MY",
    "moldavian airlines": "2M",
    "monarch airlines": "ZB",
    "myway airlines": "8I",
    "montenegro airlines": "YM",
    "morningstar air express": "MAL",
    "moskovia airlines": "3R",
    "motor sich": "M9",
    "mytravel airways": "VZ",
    "myanma airways": "UB",
    "myanmar airways international": "8M",
    "myflug": "MYA",
    "nasair": "UE",
    "national jet systems": "NC",
    "nationwide airlines": "CE",
    "nauru air corporation": "ON",
    "nepal airlines": "RA",
    "netjets": "1I",
    "new england airlines": "EJ",
    "nextjet": "2N",
    "niki": "HG",
    "nok air": "DD",
    "norfolk county flight college": "NCF",
    "north american airlines": "NTM",
    "north american charters": "HMR",
    "northern dene airways": "U7",
    "northwest airlines": "NW",
    "northwestern air": "J3",
    "norwegian air shuttle": "DY",
    "norwegian aviation college": "TFN",
    "nouvel air tunisie": "BJ",
    "novair": "1I",
    "nas air": "XY",
    "oasis hong kong airlines": "O8",
    "ocean air": "BCN",
    "oceanair": "O6",
    "oceanic airlines": "O2",
    "olympic airlines": "OA",
    "oman air": "WY",
    "omni air international": "OY",
    "one two go airlines": "OTG",
    "onur air": "8Q",
    "orenburg airlines": "R2",
    "orient thai airlines": "OX",
    "origin pacific airways": "QO",
    "ostfriesische lufttransport": "OL",
    "overland airways": "OJ",
    "ozjet airlines": "O7",
    "pan air": "PV",
    "pb air": "9Q",
    "pluna": "PU",
    "pmtair": "U4",
    "jetstar pacific": "BL",
    "pacific coastal airline": "8P",
    "pacific east asia cargo airlines": "Q8",
    "pacific island aviation": "PSA",
    "pacific wings": "LW",
    "pakistan international airlines": "PK",
    "paramount airways": "I7",
    "passaredo transportes aereos": "PTB",
    "pegasus airlines": "PC",
    "peninsula airways": "KS",
    "philippine airlines": "PR",
    "piedmont airlines (1948-1989)": "PI",
    "pinnacle airlines": "9E",
    "polet": "POT",
    "polynesian airlines": "PH",
    "porter airlines": "PD",
    "portugalia": "NI",
    "potomac air": "BK",
    "precision air": "PW",
    "privatair": "PTI",
    "proflight commuter services": "P0",
    "qantas": "QF",
    "qatar airways": "QR",
    "racsa": "R6",
    "kinloss flying training unit": "KIN",
    "regional airlines": "FN",
    "regional express": "ZL",
    "republic airlines": "RW",
    "republic express airlines": "RH",
    "rossiya": "R4",
    "air rarotonga": "GZ",
    "royal air maroc": "AT",
    "royal brunei airlines": "BI",
    "royal jordanian": "RJ",
    "royal phnom penh airways": "PPW",
    "rusline": "RLU",
    "rwandair express": "WB",
    "ryan air services": "RYA",
    "ryan international airlines": "RD",
    "ryanair": "FR",
    "régional": "YS",
    "sata international": "S4",
    "south african airways": "SA",
    "shaheen air international": "NL",
    "scandinavian airlines system": "SK",
    "scotairways": "SAY",
    "s7 airlines": "S7",
    "seaborne airlines": "BB",
    "scenic airlines": "SCE",
    "srilankan airlines": "UL",
    "sun country airlines": "SY",
    "southeast air": "SEA",
    "sky express": "XW",
    "spicejet": "SG",
    "star flyer": "7G",
    "skagway air service": "N5",
    "sahara airlines": "SHD",
    "sata air acores": "SP",
    "singapore airlines": "SQ",
    "sibaviatrans": "5M",
    "skynet airlines": "SI",
    "sriwijaya air": "SJ",
    "sama airlines": "ZS",
    "singapore airlines cargo": "SQ",
    "siem reap airways": "FT",
    "south east asian airlines": "DG",
    "skyservice airlines": "5G",
    "servicios de transportes a": "FS",
    "sudan airways": "SD",
    "saudi arabian airlines": "SV",
    "southwest airlines": "WN",
    "southern winds airlines": "A4",
    "swiss international air lines": "LX",
    "swiss european air lines": "SWU",
    "swe fly": "WV",
    "sunexpress": "XQ",
    "syrian arab airlines": "RB",
    "skywalk airlines": "AL",
    "shandong airlines": "SC",
    "sas braathens": "CNO",
    "spring airlines": "9S",
    "sichuan airlines": "3U",
    "shanghai airlines": "FM",
    "shenzhen airlines": "ZH",
    "sun d'or": "7L",
    "skyeurope": "NE",
    "sky europe airlines": "HSK",
    "spanair": "JK",
    "spirit airlines": "NK",
    "satena": "9R",
    "skywest airlines": "OZW",
    "santa barbara airlines": "S3",
    "sky airline": "H2",
    "skywest": "OO",
    "skyways express": "JZ",
    "skymark airlines": "BC",
    "silkair": "MI",
    "surinam airways": "PY",
    "sterling airlines": "NB",
    "skynet asia airways": "6J",
    "solomon airlines": "IE",
    "southern airways": "SOU",
    "saratov aviation division": "6W",
    "sat airlines": "HZ",
    "south pacific island airways": "SPI",
    "shuttle america": "S5",
    "scat air": "DV",
    "tame": "EQ",
    "tam brazilian airlines": "JJ",
    "tap portugal": "TP",
    "tunisair": "TU",
    "thai air cargo": "T2",
    "thomas cook airlines": "MT",
    "trigana air service": "TGN",
    "tiger airways": "TR",
    "tigerair australia": "TT",
    "thai airways international": "TG",
    "turk hava kurumu hava taksi isletmesi": "THK",
    "thai airasia": "FD",
    "turkish airlines": "TK",
    "tajikistan international airlines": "TIL",
    "twin jet": "T7",
    "translift airways": "TLA",
    "trans mediterranean airlines": "TL",
    "tiara air": "3P",
    "thomsonfly": "BY",
    "tropic air": "PM",
    "tampa": "QT",
    "transasia airways": "GE",
    "transavia holland": "HV",
    "tacv": "VR",
    "transwest air": "9T",
    "transaero airlines": "UN",
    "turkmenistan airlines": "T5",
    "tuninter": "UG",
    "travel service": "QS",
    "tuifly nordic": "6B",
    "taag angola airlines": "DT",
    "turkish air force": "HVK",
    "tam mercosur": "PZ",
    "trans states airlines": "AX",
    "tarom": "RO",
    "turan air": "3T",
    "trip linhas a": "8R",
    "usa3000 airlines": "U5",
    "united airlines": "UA",
    "united air charters": "UAC",
    "ural airlines": "U6",
    "um airlines": "UF",
    "us airways": "US",
    "us helicopter": "USH",
    "utair aviation": "UT",
    "united states air force": "AIO",
    "uzbekistan airways": "HY",
    "ukraine international airlines": "PS",
    "us helicopter corporation": "UH",
    "valuair": "VF",
    "vasco air": "VFC",
    "vietnam airlines": "VN",
    "vim airlines": "NN",
    "volaris": "Y4",
    "volga-dnepr airlines": "VI",
    "virgin america": "VX",
    "virgin express": "TV",
    "virgin nigeria airways": "VK",
    "virgin atlantic airways": "VS",
    "viva macau": "ZG",
    "volare airlines": "VE",
    "vueling airlines": "VY",
    "vladivostok air": "XF",
    "varig log": "LC",
    "virgin australia": "VA",
    "vrg linhas aereas": "RG",
    "vasp": "VP",
    "vlm airlines": "VG",
    "wayraper": "7W",
    "webjet linhas a": "WJ",
    "welcome air": "2W",
    "west coast air": "8O",
    "westjet": "WS",
    "western airlines": "WA",
    "widerøe": "WF",
    "wind jet": "IV",
    "wings air": "IW",
    "wizz air": "W6",
    "wizz air hungary": "8Z",
    "world airways": "WO",
    "xl airways france": "SE",
    "xiamen airlines": "MF",
    "yamal airlines": "YL",
    "yemenia": "IY",
    "yuzhmashavia": "UMK",
    "zanair": "TAN",
    "zoom airlines": "Z4",
    "maldivian air taxi": "8Q",
    "royal air cambodge": "VJ",
    "air mandalay": "6T",
    "air busan": "BX",
    "globus": "GH",
    "air kazakhstan": "9Y",
    "japan air system": "JD",
    "easyjet (ds)": "DS",
    "star peru (2i)": "2I",
    "carnival air lines": "KW",
    "united airways": "4H",
    "fly540": "5H",
    "transavia france": "TO",
    "island air (wp)": "WP",
    "uni air": "B7",
    "gomelavia": "YD",
    "red wings": "WZ",
    "tuifly (x3)": "11",
    "felix airways": "FU",
    "kostromskie avialinii": "K1",
    "greenfly": "XX",
    "tajik air": "7J",
    "air mozambique": "TM",
    "elk airways": "ELK",
    "gabon airlines": "GY",
    "mca airlines": "MCA",
    "maldivo airlines": "ML",
    "virgin pacific": "VH",
    "zest air": "Z2",
    "yangon airways": "HK",
    "eastar jet": "ZE",
    "jin air": "LJ",
    "air arabia maroc": "3O",
    "baltic air lines": "B1",
    "ciel canadien": "YC",
    "canadian national airways": "CN",
    "epic holiday": "FA",
    "indochina airlines": "AXC",
    "air comet chile": "3I",
    "german air force - flb": "FLB",
    "line blue": "L8",
    "flylal charters": "LLC",
    "salzburg arrows": "SZ",
    "texas wings": "TQ",
    "dennis sky": "DH",
    "zz": "ZZ",
    "atifly": "A1",
    "aerolineas heredas santa maria": "SZB",
    "ciao air": "99",
    "jc royal.britannica": "JRB",
    "pal airlines": "5P",
    "canxpress": "C1",
    "danube wings (v5)": "V5",
    "sharp airlines": "SH",
    "canxplorer": "C2",
    "click (mexicana)": "QA",
    "world experience airline": "W1",
    "alak": "J4",
    "air choice one": "3E",
    "tianjin airlines": "GCR",
    "china united": "KN",
    "locair": "ZQ",
    "safi airlines": "4Q",
    "seaport airlines": "K5",
    "salmon air": "S6",
    "bobb air freight": "01",
    "star1 airlines": "V9",
    "pelita": "6D",
    "alaska seaplane service": "J5",
    "enerjet": "ENJ",
    "mexicanalink": "I6",
    "island spirit": "IP",
    "taca peru": "T0",
    "orbest": "OBS",
    "southern air charter": "SOA",
    "svg air": "SVG",
    "air century": "CEY",
    "pan am world airways dominicana": "7Q",
    "primera air": "PF",
    "air antilles express": "3S",
    "sol lineas aereas": "OLS",
    "regional paraguaya": "P7",
    "vip ecuador": "V6",
    "transportes aereos cielos andinos": "NDN",
    "peruvian airlines": "P9",
    "easyfly": "EFY",
    "polar airlines": "ЯП",
    "catovair": "OC",
    "andalus lineas aereas": "ANU",
    "air 26": "DCD",
    "mauritania airways": "MTW",
    "ceiba intercontinental": "CEL",
    "halcyonair": "7Z",
    "business aviation": "4P",
    "compagnie africaine d\\\\'aviation": "E9",
    "zambia skyways": "K8",
    "almasria universal airlines": "UJ",
    "egyptair express": "MSE",
    "smartlynx airlines": "6Y",
    "air italy egypt": "EUD",
    "koralblue airlines": "K7",
    "wind rose aviation": "WRC",
    "elysian airlines": "E4",
    "sevenair": "SEN",
    "hellenic imperial airways": "HT",
    "amsterdam airlines": "WD",
    "arik niger": "Q9",
    "dana air": "DA",
    "stp airways": "8F",
    "med airways": "7Y",
    "skyjet airlines": "UQ",
    "air volga": "G6",
    "transavia denmark": "TDK",
    "royal falcon": "RL",
    "euroline": "4L",
    "turkuaz airlines": "TRK",
    "athens airways": "ZF",
    "viking hellas": "VQ",
    "norlandair": "FNA",
    "flugfelag vestmannaeyja": "FVM",
    "starline.kz": "DZ",
    "lugansk airlines": "L7",
    "gryphon airlines": "6P",
    "gadair european airlines": "GP",
    "spirit of manila airlines": "SM",
    "chongqing airlines": "OQ",
    "grand china air": "GDC",
    "west air china": "PN",
    "qatxpress": "C3",
    "onechina": "1C",
    "nordstar airlines": "Y7",
    "joy air": "JR",
    "air india regional": "CD",
    "mdlr airlines": "9H",
    "jagson airlines": "JGN",
    "maldivian": "Q2",
    "xpressair": "XN",
    "strategic airlines": "VC",
    "fars air qeshm": "QFZ",
    "eastok avia": "EAA",
    "jupiter airlines": "JPU",
    "vision air international": "VIS",
    "al-naser airlines": "NA",
    "fuji dream airlines": "JH",
    "korea express air": "KEA",
    "eznis airways": "EZA",
    "pacific flier": "PFL",
    "syrian pearl airlines": "PSB",
    "sga airlines": "5E",
    "air2there": "F8",
    "avianova (russia)": "AO",
    "parmiss airlines (ipv)": "PA",
    "europesky": "ES",
    "brazil air": "GB",
    "homer air": "MR",
    "panam world airways": "WQ",
    "virginwings": "YY",
    "ksy": "KY",
    "buquebus líneas aéreas": "BQ",
    "sochi air": "CQ",
    "wizz air ukraine": "WU",
    "88": "47",
    "lcm airlines": "LQ",
    "cambodia angkor air (k6)": "K6",
    "royal european airlines": "69",
    "azul": "AD",
    "lsm airlines": "PQ",
    "zapolyarie airlines": "PZY",
    "lionxpress": "C4",
    "genesis": "GK",
    "congo express": "XZ",
    "fly dubai": "FZ",
    "domenican airlines": "D1",
    "aereonautica militare": "JY",
    "kal star aviation": "KLS",
    "lsm airlines ": "YZ",
    "utair-express": "UR",
    "huaxia": "G5",
    "zabaykalskii airlines": "ZP",
    "cbm america": "XBM",
    "marysya airlines": "M4",
    "n1": "N1",
    "airlink (saa)": "4Z",
    "westfalia express va": "WFX",
    "jobair": "3B",
    "black stallion airways": "BZ",
    "german international air lines": "GM",
    "trasbrasil": "TB",
    "transbrasil airlines": "TH",
    "china sss": "9C",
    "air indochine": "IIA",
    "happy air": "HPY",
    "solar air": "SRB",
    "air mekong": "P8",
    "harbour air (priv)": "H3",
    "air hamburg (aho)": "HH",
    "zabaikal airlines": "Z6",
    "transholding": "TI",
    "sur lineas aereas": "SZZ",
    "yeti airways": "YT",
    "yellowstone club private shuttle": "Y1",
    "caucasus airlines": "NS",
    "serbian airlines": "S1",
    "windward islands airways": "WM",
    "transholding system": "YO",
    "ccml airlines": "CB",
    "small planet airlines": "ELC",
    "fly brasil": "F1",
    "cb airways uk ( interliging flights )": "1F",
    "fly colombia ( interliging flights )": "3F",
    "trans pas air": "T6",
    "kmv": "МИ",
    "himalayan airlines": "HC",
    "indya airline group": "G1",
    "sunwing": "WG",
    "turkish wings domestic": "TWD",
    "japan regio": "ZX",
    "ocean air cargo": "IXO",
    "norte lineas aereas": "N0",
    "austral brasil": "W7",
    "pegasus airlines-": "H9",
    "camair-co": "QC",
    "sky regional": "RS",
    "lsm international ": "II",
    "baikotovitchestrian airlines ": "BU",
    "luchsh airlines ": "L4",
    "enterair": "QQQ",
    "air cargo germany": "6U",
    "mongolian international air lines ": "7M",
    "tway airlines": "TW",
    "papillon grand canyon helicopters": "HI",
    "jusur airways": "JX",
    "next brasil": "XB",
    "aeroworld ": "W4",
    "gnb linhas aereas": "GN",
    "usa sky cargo": "E1",
    "hankook airline": "HN",
    "redjet": "Z7",
    "red jet andes": "PT",
    "red jet canada": "QY",
    "sprintair": "0G",
    "red jet mexico": "4X",
    "marusya airways": "Y8",
    "era alaska": "7H",
    "airrussia": "R8",
    "hankook air us": "H1",
    "carpatair flight training": "SMW",
    "i-fly": "H5",
    "whitejets": "WTJ",
    "vickjet": "KT",
    "bvi airways": "XV",
    "hamburg airways": "HAY",
    "salsa d\\\\'haiti": "SO",
    "zambezi airlines (zma)": "ZJ",
    "kan air": "KND",
    "air cudlua": "CUD",
    "polet airlines (priv)": "YQ",
    "air explore": "AXE",
    "12 north": "12",
    "holidays czech airlines": "HCC",
    "comtel air": "COE",
    "mint airways": "MIC",
    "orbit airlines": "OBT",
    "air bucharest": "BUR",
    "albastar": "LAV",
    "mauritania airlines international": "L6",
    "mat airways": "6F",
    "asian wings airways": "AW",
    "air arabia egypt": "E5",
    "eagles airlines": "EGS",
    "yes airways": "YEP",
    "alitalia cityliner": "CT",
    "direct aero services": "DSV",
    "medallion air": "MDP",
    "orchid airlines": "OI",
    "asia wings": "Y5",
    "georgian international airlines": "GNN",
    "air batumi": "BTM",
    "skywest australia": "XR",
    "nile air": "NP",
    "feeder airlines": "FDD",
    "senegal airlines": "DN",
    "starbow airlines": "S9",
    "copenhagen express": "0X",
    "businessair": "8B",
    "senic airlines": "YR",
    "xojet": "XOJ",
    "sky wing pacific": "C7",
    "bateleur air": "BEU",
    "air indus": "PP",
    "orbit international airlines": "OAI",
    "orbit regional airlines": "OAR",
    "orbit atlantic airways": "OAN",
    "volotea": "VOO",
    "peach aviation": "MM",
    "helitt líneas aéreas": "HTH",
    "russia state transport": "RSD",
    "malaysia wings": "MWI",
    "aviabus": "U1",
    "michael airlines": "DF",
    "korongo airlines": "ZC",
    "indonesia sky": "I5",
    "aws express": "B0",
    "southjet": "76",
    "southjet connect": "77",
    "southjet cargo": "78",
    "iberia express": "I2",
    "interjet (abc aerolineas)": "4O",
    "aironix": "OG",
    "nordic global airlines": "NJ",
    "scoot": "TR",
    "hi fly (5k)": "5K",
    "china northwest airlines (wh)": "WH",
    "zenith international airline": "ZN",
    "orbit airlines azerbaijan": "O1",
    "air alps aviation (a6)": "A6",
    "flying kangaroo airline": "FKA",
    "rusjet": "RSJ",
    "vietjet air": "VJC",
    "patriot airways": "P4",
    "vision airlines (v2)": "V2",
    "bqb lineas aereas": "5Q",
    "airasia japan": "WAJ",
    "yellowtail": "YE",
    "royal airways": "KG",
    "flyhigh airlines ireland (fh)": "FH",
    "executive airshare": "XSR",
    "hebei airlines": "HBH",
    "air kbz": "KBZ",
    "aero vip (2d)": "2D",
    "yangon airways ltd.": "YH",
    "t.j. air": "TJ",
    "skywork airlines ": "SX",
    "maastricht airlines": "W2",
    "euro jet": "24",
    "ukraine atlantic": "UAT",
    "nesma airlines": "NMA",
    "east horizon": "EHN",
    "air majoro": "MJP",
    "rotana jet": "RJD",
    "sochi air chater": "Q3",
    "denim air ": "J7",
    "malindo air": "OD",
    "hermes airlines": "HRM",
    "flightlink tanzania": "Z9",
    "izavia": "I8",
    "катэкавиа": "КТК",
    "псковавиа": "PKV",
    "maryland air": "M1",
    "insel air (7i/inc) (priv)": "7I",
    "vivacolombia": "5Z",
    "flybe finland oy": "FCM",
    "bingo airways": "BGY",
    "bluebird airways (bz)": "BBG",
    "apache air": "ZM",
    "mhs aviation gmbh": "M2",
    "jettor airlines": "NR",
    "flyme (vp)": "VQI",
    "thai lion air": "SL",
    "golden myanmar airlines": "GMR",
    "canaryfly": "CNF",
    "sunrise airways": "KSZ",
    "national air cargo": "N8",
    "eastern atlantic virtual airlines": "13",
    "citilink indonesia": "QG",
    "transair": "TTZ",
    "comfort express virtual charters albany": "EVC",
    "comfort express virtual charters": "CEO",
    "flyjet": "FYJ",
    "snowbird airlines": "S8",
    "russkie krylya": "KRY",
    "kharkiv airlines": "KH",
    "xair usa": "XA",
    "air costa": "LB",
    "simrik airlines": "RMK",
    "xpto": "XP",
    "royal flight": "DME",
    "bbn-airways": "EGH",
    "tomsk-avia": "TKS",
    "malawian airlines": "3W",
    "yeti airlines ": "NYT",
    "skyline ulasim ticaret a.s.": "KCU",
    "envoy air": "ENY",
    "caricom airways (barbados) inc.": "CCB",
    "rainbow air (rai)": "RN",
    "rainbow air canada": "RY",
    "rainbow air polynesia": "RX",
    "rainbow air euro": "RU",
    "rainbow air us": "RM",
    "transilvania": "TNS",
    "dobrolet": "QD",
    "spike airlines": "S0",
    "grand cru airlines": "GCA",
    "go2sky": "RLX",
    "all argentina": "L1",
    "all america": "A2",
    "all asia": "L9",
    "all africa": "9A",
    "regionalia méxico": "N4",
    "all europe": "N9",
    "all spain": "N7",
    "regional air iceland": "9N",
    "voestar": "8K",
    "all colombia": "7O",
    "regionalia uruguay": "2X",
    "regionalia venezuela": "9X",
    "regionalia chile": "9J",
    "vuela cuba": "6C",
    "all australia": "88",
    "fly europa": "ER",
    "flyportugal": "PO",
    "vistara": "UK",
    "urumqi air": "UQ",
    "guangxi beibu gulf airlines": "UQ",
    "my indo airlines": "2Y",
    "government of morocco": "FRV",
    "hong kong air cargo": "RH",
    "us-bangla airlines": "BS",
    "netjets europe": "1I",
    "bhutan airlines": "B3",
    "iran airtour": "B9",
    "avcon jet": "AOJ",
    "indonesia airasia x": "XT",
    "qatar executive": "QE",
    "sf airlines": "O3",
    "regent airways": "RX",
    "asiacargo express": "3G",
}


# IATA : Name and ICAO : Name mapping
AIRLINE_CODE_TO_NAME_MAPPING = {
    "1T": "1time airline",
    "Q5": "40-mile air",
    "AN": "ansett australia",
    "1B": "abacus international",
    "ZI": "aigle azur",
    "AQ": "aloha airlines",
    "AA": "american airlines",
    "OZ": "asiana airlines",
    "4K": "askari aviation",
    "8U": "afriqiyah airways",
    "G4": "allegiant air",
    "M3": "absa - aerolinhas brasileiras",
    "8V": "astral aviation",
    "8T": "air tindi",
    "ZY": "ada air",
    "JP": "adria airways",
    "UX": "air europa",
    "EM": "aero benin",
    "A3": "aegean airlines",
    "PE": "air europe",
    "KO": "alaska central express",
    "AES": "aces colombia",
    "5W": "astraeus",
    "VV": "aerosvit airlines",
    "I9": "indigo",
    "QQ": "alliance airlines",
    "FG": "ariana afghan airlines",
    "SU": "aeroflot russian airlines",
    "JA": "air bosna",
    "AF": "air france",
    "SB": "air caledonie international",
    "2O": "air salone",
    "2Q": "air cargo carriers",
    "SW": "air namibia",
    "5D": "donbassaero",
    "7T": "air glaciers",
    "AGX": "aviogenex",
    "PL": "aeroper",
    "8A": "atlas blue",
    "J2": "azerbaijan airlines",
    "U3": "avies",
    "ED": "airblue",
    "AIR": "airlift international",
    "AB": "air berlin",
    "AI": "air india limited",
    "ZB": "monarch airlines",
    "CC": "macair airlines",
    "TN": "air tahiti nui",
    "IZ": "arkia israel airlines",
    "JM": "air jamaica",
    "AP": "air one",
    "S2": "air sahara",
    "KM": "air malta",
    "NQ": "air japan",
    "AKA": "air korea co. ltd.",
    "4A": "air kiribati",
    "HP": "america west airlines",
    "ZW": "air wisconsin",
    "U9": "tatarstan airlines",
    "ALO": "allegheny commuter airlines",
    "RSI": "air sunshine",
    "VD": "air libert",
    "QM": "air malawi",
    "BM": "air sicilia",
    "AMT": "ata airlines",
    "NX": "air macau",
    "AMV": "amc airlines",
    "HM": "air seychelles",
    "AM": "aeroméxico",
    "NH": "all nippon airways",
    "YW": "air nostrum",
    "PX": "air niugini",
    "G9": "air arabia",
    "AC": "air canada",
    "BT": "air baltic",
    "EL": "air nippon",
    "TL": "trans mediterranean airlines",
    "4N": "air north charter - canada",
    "NZ": "air new zealand",
    "XM": "alitalia express",
    "GV": "aero flight",
    "JW": "arrow air",
    "2B": "aerocondor",
    "4C": "aires",
    "AR": "aerolineas argentinas",
    "AS": "alaska airlines",
    "4D": "air sinai",
    "EV": "atlantic southeast airlines",
    "OB": "astrakhan airlines",
    "TC": "air tanzania",
    "2J": "air burkina",
    "FO": "airlines of tasmania",
    "PJ": "air saint pierre",
    "OS": "austrian airlines",
    "WOW": "air southwest",
    "IQ": "augsburg airways",
    "TUR": "atur",
    "MO": "abu dhabi amiri flight",
    "5N": "aeroflot-nord",
    "GR": "aurigny air services",
    "AU": "austral lineas aereas",
    "AV": "avianca - aerovias nacionales de colombia",
    "NF": "air vanuatu",
    "B9": "iran airtour",
    "DR": "air mediterranee",
    "TAH": "air moorea",
    "7E": "aeroline gmbh",
    "6G": "air wales",
    "TX": "air caraïbes",
    "IX": "air india express",
    "XT": "indonesia airasia x",
    "AK": "airasia",
    "3G": "asiacargo express",
    "AZ": "alitalia",
    "Z8": "amaszonas",
    "UM": "air zimbabwe",
    "R7": "aserca airlines",
    "FV": "rossiya-russian airlines",
    "MQ": "american eagle airlines",
    "VUE": "ad aviation",
    "VU": "air ivoire",
    "BP": "air botswana",
    "GS": "air foyle",
    "VT": "air tahiti",
    "VL": "air via",
    "FK": "africa west",
    "V8": "atran cargo airlines",
    "CA": "air china",
    "Q6": "aero condor peru",
    "CV": "air chathams",
    "CW": "air marshall islands",
    "ZA": "interavia airlines",
    "AH": "air algerie",
    "KI": "adam air",
    "EN": "air dolomiti",
    "D9": "aeroflot-don",
    "NM": "air madrid",
    "EI": "aer lingus",
    "OF": "air finland",
    "FIX": "airfix aviation",
    "FJ": "air pacific",
    "RC": "atlantic airways",
    "QH": "air florida",
    "NY": "air iceland",
    "2P": "air philippines",
    "2U": "air guinee express",
    "GL": "air greenland",
    "5Y": "atlas air",
    "GG": "air guyane",
    "W9": "air bagan",
    "QK": "air canada jazz",
    "KK": "atlasjet",
    "JS": "air koryo",
    "KC": "air astana",
    "LV": "albanian airlines",
    "LFA": "air alfa",
    "XL": "aerolane",
    "TD": "atlantis european airways",
    "LK": "air luxor",
    "MK": "air mauritius",
    "MD": "air madagascar",
    "9U": "air moldova",
    "6I": "alsie express",
    "A7": "air plus comet",
    "8D": "astair",
    "AJ": "aero contractors",
    "OT": "aeropelican air services",
    "RE": "aer arann",
    "UU": "air austral",
    "6K": "asian spirit",
    "RK": "air afrique",
    "A5": "airlinair",
    "QL": "aero lanka",
    "20": "air salone",
    "U8": "armavia",
    "P5": "aerorep",
    "BF": "aero-service",
    "5L": "aerosur",
    "RTE": "aeronorte",
    "Z3": "avient aviation",
    "R3": "aircompany yakutia",
    "VW": "aeromar",
    "OR": "arkefly",
    "CG": "airlines png",
    "FL": "airtran airways",
    "TS": "air transat",
    "EC": "avialeasing aviation company",
    "VO": "tyrolean airways",
    "2K": "aerolineas galapagos (aerogal)",
    "6R": "alrosa mirny air enterprise",
    "BA": "british airways",
    "BG": "biman bangladesh airlines",
    "4T": "belair airlines",
    "UP": "bahamasair",
    "LZ": "balkan bulgarian airlines",
    "BS": "us-bangla airlines",
    "BKF": "bf-lento oy",
    "PG": "bangkok airways",
    "KF": "blue1",
    "BLL": "baltic airlines",
    "JV": "bearskin lake air service",
    "B3": "bhutan airlines",
    "BD": "bmi",
    "WW": "bmibaby",
    "CH": "bemidji airlines",
    "BMR": "british midland regional",
    "BV": "blue panorama airlines",
    "BPS": "budapest aircraft services/manx2",
    "8E": "bering air",
    "BRS": "brazilian air force",
    "B2": "belavia belarusian airlines",
    "7P": "metro batavia",
    "J8": "berjaya air",
    "QW": "blue wings",
    "DB": "brit air",
    "SN": "brussels airlines",
    "NT": "binter canarias",
    "0B": "blue air",
    "KJ": "british mediterranean airways",
    "FB": "bulgaria air",
    "8N": "barents airlink",
    "5C": "cal cargo air lines",
    "XG": "calima aviacion",
    "CP": "compass airlines",
    "5T": "canadian north",
    "9K": "cape air",
    "BW": "caribbean airlines",
    "V3": "carpatair",
    "RV": "caspian airlines",
    "CX": "cathay pacific",
    "KX": "cayman airways",
    "5J": "cebu pacific",
    "CCG": "central connect airlines",
    "C0": "centralwings",
    "CHW": "charter air",
    "RP": "chautauqua airlines",
    "CI": "china airlines",
    "MU": "china eastern airlines",
    "CZ": "china southern airlines",
    "HR": "china united airlines",
    "3Q": "yunnan airlines",
    "QI": "cimber air",
    "C9": "cirrus airlines",
    "CF": "city airline",
    "G3": "sky express",
    "WX": "cityjet",
    "CJ": "ba cityflyer",
    "CGK": "click airways",
    "DQ": "coastal air",
    "9L": "colgan air",
    "OH": "comair",
    "MN": "comair",
    "C5": "commutair",
    "KR": "comores airlines",
    "DE": "condor flugdienst",
    "6A": "consorcio aviaxsa",
    "C3": "qatxpress",
    "CO": "continental express",
    "CS": "continental micronesia",
    "V0": "conviasa",
    "CM": "copa airlines",
    "AAQ": "copterline",
    "CAI": "corendon airlines",
    "SS": "corsairfly",
    "XK": "corse-mediterranee",
    "CAN": "crest aviation",
    "OU": "croatia airlines",
    "CRO": "crown airways",
    "CU": "cubana de aviación",
    "CY": "cyprus airways",
    "YK": "cyprus turkish airlines",
    "OK": "czech airlines",
    "DX": "dat danish air transport",
    "D3": "daallo airlines",
    "H8": "dalavia",
    "0D": "darwin airline",
    "DEA": "delta aerotaxi",
    "DL": "delta air lines",
    "DNM": "denim air",
    "2A": "deutsche bahn",
    "D8": "djibouti airlines",
    "UDN": "dniproavia",
    "DO": "dominicana de aviaci",
    "E3": "domodedovo airlines",
    "KA": "dragonair",
    "KB": "druk air",
    "DBK": "dubrovnik air",
    "DNL": "dutch antilles express",
    "DI": "dba",
    "BR": "eva air",
    "H7": "eagle air",
    "QU": "east african",
    "T3": "eastern airways",
    "DK": "eastland air",
    "ECU": "ecuavia",
    "WK": "edelweiss air",
    "MS": "egyptair",
    "LY": "el al israel airlines",
    "UZ": "el-buraq air transport",
    "EK": "emirates",
    "EU": "empresa ecuatoriana de aviacion",
    "B8": "eritrean airlines",
    "OV": "estonian air",
    "ET": "ethiopian airlines",
    "EY": "etihad airways",
    "RZ": "euro exec express",
    "UI": "eurocypria airlines",
    "GJ": "eurofly service",
    "K2": "eurolot",
    "EA": "european air express",
    "EW": "eurowings",
    "EZ": "evergreen international airlines",
    "JN": "excel airways",
    "XEL": "excel charter",
    "EO": "express one international",
    "XE": "expressjet",
    "U2": "easyjet",
    "EF": "far eastern air transport",
    "AY": "finnair",
    "FC": "finncomm airlines",
    "FY": "firefly",
    "7F": "first air",
    "DP": "first choice airways",
    "B5": "flightline",
    "RF": "florida west international airways",
    "D7": "airasia x",
    "TE": "flylal",
    "LF": "flynordic",
    "F7": "flybaboo",
    "BE": "flybe",
    "B4": "flyglobespan",
    "FYH": "flyhy cargo airlines",
    "VY": "vueling airlines",
    "FP": "freedom air",
    "FRL": "freedom airlines",
    "F9": "frontier airlines",
    "2F": "frontier flying service",
    "GT": "gb airways",
    "GA": "garuda indonesia",
    "4G": "gazpromavia",
    "A9": "georgian airways",
    "QB": "georgian national airlines",
    "ST": "germania",
    "4U": "germanwings",
    "G0": "ghana international airlines",
    "G8": "go air",
    "G7": "gojet airlines",
    "DC": "golden air",
    "ZK": "great lakes airlines",
    "TA": "grupo taca",
    "GFA": "gulf air",
    "GF": "gulf air bahrain",
    "GFT": "gulfstream international airlines",
    "H6": "hageland aviation services",
    "HU": "hainan airlines",
    "2T": "haiti ambassador airlines",
    "4R": "hamburg international",
    "X3": "tuifly",
    "HF": "hapagfly",
    "HA": "hawaiian airlines",
    "BH": "hawkair",
    "8H": "heli france",
    "JB": "helijet",
    "T4": "hellas jet",
    "HW": "hello",
    "2L": "helvetic airways",
    "UD": "hex'air",
    "HWY": "highland airways",
    "HD": "hokkaido international airlines",
    "HX": "hong kong airlines",
    "UO": "hong kong express airways",
    "QX": "horizon air",
    "BN": "horizon airlines",
    "IB": "iberia airlines",
    "TY": "iberworld",
    "FW": "ibex airlines",
    "RAC": "icar air",
    "FI": "icelandair",
    "IK": "imair airlines",
    "6E": "indigo airlines",
    "IC": "indian airlines",
    "QZ": "indonesia airasia",
    "IO": "indonesian airlines",
    "D6": "interair south africa",
    "ID": "interlink airlines",
    "3L": "intersky",
    "IR": "iran air",
    "EP": "iran aseman airlines",
    "IA": "iraqi airways",
    "IS": "island airlines",
    "8L": "cargo plus aviation",
    "IF": "islas airways",
    "WC": "islena de inversiones",
    "6H": "israir",
    "GI": "itek air",
    "JC": "jal express",
    "JO": "jalways",
    "JL": "japan airlines",
    "EG": "japan asia airways",
    "NU": "japan transocean air",
    "JU": "jat airways",
    "J9": "jazeera airways",
    "7C": "jeju air",
    "9W": "jet airways",
    "QJ": "jet airways",
    "3K": "jetstar asia airways",
    "LS": "jet2.com",
    "8J": "jet4you",
    "B6": "jetblue airways",
    "JF": "jetairfly",
    "JEF": "jetflite",
    "JQ": "jetstar airways",
    "HO": "juneyao airlines",
    "KD": "kd avia",
    "WA": "western airlines",
    "KL": "klm royal dutch airlines",
    "RQ": "kam air",
    "KV": "kavminvodyavia",
    "KDA": "kendell airlines",
    "M5": "kenmore air",
    "KQ": "kenya airways",
    "IT": "kingfisher airlines",
    "Y9": "kish air",
    "7K": "kogalymavia air company",
    "KE": "korean air",
    "KSM": "kosmos",
    "7B": "krasnojarsky airlines",
    "GW": "kuban airlines",
    "KU": "kuwait airways",
    "GO": "kuzu airlines cargo",
    "LR": "lacsa",
    "LA": "lan airlines",
    "4M": "lan argentina",
    "LU": "lan express",
    "LP": "lan peru",
    "LO": "lot polish airlines",
    "XO": "lte international airways",
    "L3": "ltu austria",
    "LT": "ltu international",
    "QV": "lao airlines",
    "LTC": "latcharter",
    "NG": "lauda air",
    "LI": "leeward islands air transport",
    "LN": "libyan arab airlines",
    "LM": "linhas a",
    "JT": "lion mentari airlines",
    "HE": "luftfahrtgesellschaft walter",
    "LH": "lufthansa cargo",
    "CL": "lufthansa cityline",
    "L5": "lufttransport",
    "LG": "luxair",
    "MJ": "l",
    "M7": "masair",
    "IN": "mat macedonian airlines",
    "OM": "miat mongolian airlines",
    "MB": "mng airlines",
    "DM": "maersk",
    "W5": "mahan air",
    "MH": "malaysia airlines",
    "R5": "malta air charter",
    "MA": "malév",
    "RI": "mandala airlines",
    "AE": "mandarin airlines",
    "JE": "mango",
    "MP": "martinair",
    "8M": "myanmar airways international",
    "MW": "maya island air",
    "IG": "meridiana",
    "MZ": "merpati nusantara airlines",
    "YV": "mesa airlines",
    "XJ": "mesaba airlines",
    "MX": "mexicana de aviaci",
    "ME": "middle east airlines",
    "JI": "midway airlines",
    "YX": "midwest airlines",
    "MY": "midwest airlines (egypt)",
    "2M": "moldavian airlines",
    "8I": "myway airlines",
    "YM": "montenegro airlines",
    "MAL": "morningstar air express",
    "3R": "moskovia airlines",
    "M9": "motor sich",
    "VZ": "mytravel airways",
    "UB": "myanma airways",
    "MYA": "myflug",
    "UE": "nasair",
    "NC": "national jet systems",
    "CE": "nationwide airlines",
    "ON": "nauru air corporation",
    "RA": "nepal airlines",
    "1I": "netjets europe",
    "EJ": "new england airlines",
    "2N": "nextjet",
    "HG": "niki",
    "DD": "nok air",
    "NCF": "norfolk county flight college",
    "NTM": "north american airlines",
    "HMR": "north american charters",
    "U7": "northern dene airways",
    "NW": "northwest airlines",
    "J3": "northwestern air",
    "DY": "norwegian air shuttle",
    "TFN": "norwegian aviation college",
    "BJ": "nouvel air tunisie",
    "XY": "nas air",
    "O8": "oasis hong kong airlines",
    "BCN": "ocean air",
    "O6": "oceanair",
    "O2": "oceanic airlines",
    "OA": "olympic airlines",
    "WY": "oman air",
    "OY": "omni air international",
    "OTG": "one two go airlines",
    "8Q": "maldivian air taxi",
    "R2": "orenburg airlines",
    "OX": "orient thai airlines",
    "QO": "origin pacific airways",
    "OL": "ostfriesische lufttransport",
    "OJ": "overland airways",
    "O7": "ozjet airlines",
    "PV": "pan air",
    "9Q": "pb air",
    "PU": "pluna",
    "U4": "pmtair",
    "BL": "jetstar pacific",
    "8P": "pacific coastal airline",
    "Q8": "pacific east asia cargo airlines",
    "PSA": "pacific island aviation",
    "LW": "pacific wings",
    "PK": "pakistan international airlines",
    "I7": "paramount airways",
    "PTB": "passaredo transportes aereos",
    "PC": "pegasus airlines",
    "KS": "peninsula airways",
    "PR": "philippine airlines",
    "PI": "piedmont airlines (1948-1989)",
    "9E": "pinnacle airlines",
    "POT": "polet",
    "PH": "polynesian airlines",
    "PD": "porter airlines",
    "NI": "portugalia",
    "BK": "potomac air",
    "PW": "precision air",
    "PTI": "privatair",
    "P0": "proflight commuter services",
    "QF": "qantas",
    "QR": "qatar airways",
    "R6": "racsa",
    "KIN": "kinloss flying training unit",
    "FN": "regional airlines",
    "ZL": "regional express",
    "RW": "republic airlines",
    "RH": "hong kong air cargo",
    "R4": "rossiya",
    "GZ": "air rarotonga",
    "AT": "royal air maroc",
    "BI": "royal brunei airlines",
    "RJ": "royal jordanian",
    "PPW": "royal phnom penh airways",
    "RLU": "rusline",
    "WB": "rwandair express",
    "RYA": "ryan air services",
    "RD": "ryan international airlines",
    "FR": "ryanair",
    "YS": "régional",
    "S4": "sata international",
    "SA": "south african airways",
    "NL": "shaheen air international",
    "SK": "scandinavian airlines system",
    "SAY": "scotairways",
    "S7": "s7 airlines",
    "BB": "seaborne airlines",
    "SCE": "scenic airlines",
    "UL": "srilankan airlines",
    "SY": "sun country airlines",
    "SEA": "southeast air",
    "SG": "spicejet",
    "7G": "star flyer",
    "N5": "skagway air service",
    "SHD": "sahara airlines",
    "SP": "sata air acores",
    "SQ": "singapore airlines cargo",
    "5M": "sibaviatrans",
    "SI": "skynet airlines",
    "SJ": "sriwijaya air",
    "ZS": "sama airlines",
    "FT": "siem reap airways",
    "DG": "south east asian airlines",
    "5G": "skyservice airlines",
    "FS": "servicios de transportes a",
    "SD": "sudan airways",
    "SV": "saudi arabian airlines",
    "WN": "southwest airlines",
    "A4": "southern winds airlines",
    "LX": "swiss international air lines",
    "SWU": "swiss european air lines",
    "WV": "swe fly",
    "XQ": "sunexpress",
    "RB": "syrian arab airlines",
    "AL": "skywalk airlines",
    "SC": "shandong airlines",
    "CNO": "sas braathens",
    "9S": "spring airlines",
    "3U": "sichuan airlines",
    "FM": "shanghai airlines",
    "ZH": "shenzhen airlines",
    "7L": "sun d'or",
    "NE": "skyeurope",
    "HSK": "sky europe airlines",
    "JK": "spanair",
    "NK": "spirit airlines",
    "9R": "satena",
    "OZW": "skywest airlines",
    "S3": "santa barbara airlines",
    "H2": "sky airline",
    "OO": "skywest",
    "JZ": "skyways express",
    "BC": "skymark airlines",
    "MI": "silkair",
    "PY": "surinam airways",
    "NB": "sterling airlines",
    "6J": "skynet asia airways",
    "IE": "solomon airlines",
    "SOU": "southern airways",
    "6W": "saratov aviation division",
    "HZ": "sat airlines",
    "SPI": "south pacific island airways",
    "S5": "shuttle america",
    "DV": "scat air",
    "EQ": "tame",
    "JJ": "tam brazilian airlines",
    "TP": "tap portugal",
    "TU": "tunisair",
    "T2": "thai air cargo",
    "FQ": "thomas cook airlines",
    "MT": "thomas cook airlines",
    "TGN": "trigana air service",
    "TR": "scoot",
    "TT": "tigerair australia",
    "TG": "thai airways international",
    "THK": "turk hava kurumu hava taksi isletmesi",
    "FD": "thai airasia",
    "TK": "turkish airlines",
    "TIL": "tajikistan international airlines",
    "T7": "twin jet",
    "TLA": "translift airways",
    "3P": "tiara air",
    "BY": "thomsonfly",
    "PM": "tropic air",
    "QT": "tampa",
    "GE": "transasia airways",
    "HV": "transavia holland",
    "VR": "tacv",
    "9T": "transwest air",
    "UN": "transaero airlines",
    "T5": "turkmenistan airlines",
    "UG": "tuninter",
    "QS": "travel service",
    "6B": "tuifly nordic",
    "DT": "taag angola airlines",
    "HVK": "turkish air force",
    "PZ": "tam mercosur",
    "AX": "trans states airlines",
    "RO": "tarom",
    "3T": "turan air",
    "8R": "trip linhas a",
    "U5": "usa3000 airlines",
    "UA": "united airlines",
    "UAC": "united air charters",
    "U6": "ural airlines",
    "UF": "um airlines",
    "US": "us airways",
    "USH": "us helicopter",
    "UT": "utair aviation",
    "AIO": "united states air force",
    "HY": "uzbekistan airways",
    "PS": "ukraine international airlines",
    "UH": "us helicopter corporation",
    "VF": "valuair",
    "VFC": "vasco air",
    "VN": "vietnam airlines",
    "NN": "vim airlines",
    "Y4": "volaris",
    "VI": "volga-dnepr airlines",
    "VX": "virgin america",
    "TV": "virgin express",
    "VK": "virgin nigeria airways",
    "VS": "virgin atlantic airways",
    "ZG": "viva macau",
    "VE": "volare airlines",
    "XF": "vladivostok air",
    "LC": "varig log",
    "VA": "virgin australia",
    "RG": "vrg linhas aereas",
    "VP": "vasp",
    "VG": "vlm airlines",
    "7W": "wayraper",
    "WJ": "webjet linhas a",
    "2W": "welcome air",
    "8O": "west coast air",
    "WS": "westjet",
    "WF": "widerøe",
    "IV": "wind jet",
    "IW": "wings air",
    "W6": "wizz air",
    "8Z": "wizz air hungary",
    "WO": "world airways",
    "SE": "xl airways france",
    "MF": "xiamen airlines",
    "YL": "yamal airlines",
    "IY": "yemenia",
    "UMK": "yuzhmashavia",
    "TAN": "zanair",
    "Z4": "zoom airlines",
    "TYR": "tyrolean airways",
    "VJ": "royal air cambodge",
    "6T": "air mandalay",
    "BX": "air busan",
    "XW": "sky express",
    "GH": "globus",
    "9Y": "air kazakhstan",
    "JD": "japan air system",
    "DS": "easyjet (ds)",
    "2I": "star peru (2i)",
    "KW": "carnival air lines",
    "4H": "united airways",
    "5H": "fly540",
    "TO": "transavia france",
    "WP": "island air (wp)",
    "B7": "uni air",
    "YD": "gomelavia",
    "WZ": "red wings",
    "11": "tuifly (x3)",
    "FU": "felix airways",
    "K1": "kostromskie avialinii",
    "XX": "greenfly",
    "7J": "tajik air",
    "TM": "air mozambique",
    "ELK": "elk airways",
    "GY": "gabon airlines",
    "MCA": "mca airlines",
    "ML": "maldivo airlines",
    "VH": "virgin pacific",
    "Z2": "zest air",
    "HK": "yangon airways",
    "ZE": "eastar jet",
    "LJ": "jin air",
    "3O": "air arabia maroc",
    "B1": "baltic air lines",
    "YC": "ciel canadien",
    "CN": "canadian national airways",
    "FA": "epic holiday",
    "AXC": "indochina airlines",
    "3I": "air comet chile",
    "FLB": "german air force - flb",
    "L8": "line blue",
    "LLC": "flylal charters",
    "SZ": "salzburg arrows",
    "TQ": "texas wings",
    "DH": "dennis sky",
    "ZZ": "zz",
    "A1": "atifly",
    "SZB": "aerolineas heredas santa maria",
    "99": "ciao air",
    "JRB": "jc royal.britannica",
    "5P": "pal airlines",
    "C1": "canxpress",
    "V5": "danube wings (v5)",
    "SH": "sharp airlines",
    "C2": "canxplorer",
    "QA": "click (mexicana)",
    "W1": "world experience airline",
    "J4": "alak",
    "3E": "air choice one",
    "GCR": "tianjin airlines",
    "KN": "china united",
    "ZQ": "locair",
    "4Q": "safi airlines",
    "K5": "seaport airlines",
    "S6": "salmon air",
    "01": "bobb air freight",
    "V9": "star1 airlines",
    "6D": "pelita",
    "J5": "alaska seaplane service",
    "ENJ": "enerjet",
    "I6": "mexicanalink",
    "IP": "island spirit",
    "T0": "taca peru",
    "OBS": "orbest",
    "SOA": "southern air charter",
    "SVG": "svg air",
    "CEY": "air century",
    "7Q": "pan am world airways dominicana",
    "PF": "primera air",
    "3S": "air antilles express",
    "OLS": "sol lineas aereas",
    "P7": "regional paraguaya",
    "V6": "vip ecuador",
    "NDN": "transportes aereos cielos andinos",
    "P9": "peruvian airlines",
    "EFY": "easyfly",
    "ЯП": "polar airlines",
    "OC": "catovair",
    "ANU": "andalus lineas aereas",
    "DCD": "air 26",
    "MTW": "mauritania airways",
    "CEL": "ceiba intercontinental",
    "7Z": "halcyonair",
    "4P": "business aviation",
    "E9": "compagnie africaine d\\\\'aviation",
    "K8": "zambia skyways",
    "UJ": "almasria universal airlines",
    "MSE": "egyptair express",
    "6Y": "smartlynx airlines",
    "EUD": "air italy egypt",
    "K7": "koralblue airlines",
    "WRC": "wind rose aviation",
    "E4": "elysian airlines",
    "SEN": "sevenair",
    "HT": "hellenic imperial airways",
    "WD": "amsterdam airlines",
    "Q9": "arik niger",
    "DA": "dana air",
    "8F": "stp airways",
    "7Y": "med airways",
    "UQ": "guangxi beibu gulf airlines",
    "G6": "air volga",
    "TDK": "transavia denmark",
    "RL": "royal falcon",
    "4L": "euroline",
    "TRK": "turkuaz airlines",
    "ZF": "athens airways",
    "VQ": "viking hellas",
    "FNA": "norlandair",
    "FVM": "flugfelag vestmannaeyja",
    "DZ": "starline.kz",
    "L7": "lugansk airlines",
    "6P": "gryphon airlines",
    "GP": "gadair european airlines",
    "SM": "spirit of manila airlines",
    "OQ": "chongqing airlines",
    "GDC": "grand china air",
    "PN": "west air china",
    "1C": "onechina",
    "Y7": "nordstar airlines",
    "JR": "joy air",
    "CD": "air india regional",
    "9H": "mdlr airlines",
    "JGN": "jagson airlines",
    "Q2": "maldivian",
    "XN": "xpressair",
    "VC": "strategic airlines",
    "QFZ": "fars air qeshm",
    "EAA": "eastok avia",
    "JPU": "jupiter airlines",
    "VIS": "vision air international",
    "NA": "al-naser airlines",
    "JH": "fuji dream airlines",
    "KEA": "korea express air",
    "EZA": "eznis airways",
    "PFL": "pacific flier",
    "PSB": "syrian pearl airlines",
    "5E": "sga airlines",
    "F8": "air2there",
    "AO": "avianova (russia)",
    "PA": "parmiss airlines (ipv)",
    "ES": "europesky",
    "GB": "brazil air",
    "MR": "homer air",
    "WQ": "panam world airways",
    "YY": "virginwings",
    "KY": "ksy",
    "BQ": "buquebus líneas aéreas",
    "CQ": "sochi air",
    "WU": "wizz air ukraine",
    "47": "88",
    "LQ": "lcm airlines",
    "K6": "cambodia angkor air (k6)",
    "69": "royal european airlines",
    "AD": "azul",
    "PQ": "lsm airlines",
    "PZY": "zapolyarie airlines",
    "C4": "lionxpress",
    "GK": "genesis",
    "XZ": "congo express",
    "FZ": "fly dubai",
    "D1": "domenican airlines",
    "JY": "aereonautica militare",
    "KLS": "kal star aviation",
    "YZ": "lsm airlines ",
    "UR": "utair-express",
    "G5": "huaxia",
    "ZP": "zabaykalskii airlines",
    "XBM": "cbm america",
    "M4": "marysya airlines",
    "N1": "n1",
    "4Z": "airlink (saa)",
    "WFX": "westfalia express va",
    "3B": "jobair",
    "BZ": "black stallion airways",
    "GM": "german international air lines",
    "TB": "trasbrasil",
    "TH": "transbrasil airlines",
    "9C": "china sss",
    "IIA": "air indochine",
    "HPY": "happy air",
    "SRB": "solar air",
    "P8": "air mekong",
    "H3": "harbour air (priv)",
    "HH": "air hamburg (aho)",
    "Z6": "zabaikal airlines",
    "TI": "transholding",
    "SZZ": "sur lineas aereas",
    "YT": "yeti airways",
    "Y1": "yellowstone club private shuttle",
    "NS": "caucasus airlines",
    "S1": "serbian airlines",
    "WM": "windward islands airways",
    "YO": "transholding system",
    "CB": "ccml airlines",
    "ELC": "small planet airlines",
    "F1": "fly brasil",
    "1F": "cb airways uk ( interliging flights )",
    "3F": "fly colombia ( interliging flights )",
    "T6": "trans pas air",
    "МИ": "kmv",
    "HC": "himalayan airlines",
    "G1": "indya airline group",
    "WG": "sunwing",
    "TWD": "turkish wings domestic",
    "ZX": "japan regio",
    "IXO": "ocean air cargo",
    "N0": "norte lineas aereas",
    "W7": "austral brasil",
    "H9": "pegasus airlines-",
    "QC": "camair-co",
    "RS": "sky regional",
    "II": "lsm international ",
    "BU": "baikotovitchestrian airlines ",
    "L4": "luchsh airlines ",
    "QQQ": "enterair",
    "6U": "air cargo germany",
    "7M": "mongolian international air lines ",
    "TW": "tway airlines",
    "HI": "papillon grand canyon helicopters",
    "JX": "jusur airways",
    "XB": "next brasil",
    "W4": "aeroworld ",
    "GN": "gnb linhas aereas",
    "E1": "usa sky cargo",
    "HN": "hankook airline",
    "Z7": "redjet",
    "PT": "red jet andes",
    "QY": "red jet canada",
    "0G": "sprintair",
    "4X": "red jet mexico",
    "Y8": "marusya airways",
    "7H": "era alaska",
    "R8": "airrussia",
    "H1": "hankook air us",
    "SMW": "carpatair flight training",
    "H5": "i-fly",
    "WTJ": "whitejets",
    "KT": "vickjet",
    "XV": "bvi airways",
    "HAY": "hamburg airways",
    "SO": "salsa d\\\\'haiti",
    "ZJ": "zambezi airlines (zma)",
    "KND": "kan air",
    "CUD": "air cudlua",
    "YQ": "polet airlines (priv)",
    "AXE": "air explore",
    "12": "12 north",
    "HCC": "holidays czech airlines",
    "COE": "comtel air",
    "MIC": "mint airways",
    "OBT": "orbit airlines",
    "BUR": "air bucharest",
    "LAV": "albastar",
    "L6": "mauritania airlines international",
    "6F": "mat airways",
    "AW": "asian wings airways",
    "E5": "air arabia egypt",
    "EGS": "eagles airlines",
    "YEP": "yes airways",
    "CT": "alitalia cityliner",
    "DSV": "direct aero services",
    "MDP": "medallion air",
    "OI": "orchid airlines",
    "Y5": "asia wings",
    "GNN": "georgian international airlines",
    "BTM": "air batumi",
    "XR": "skywest australia",
    "NP": "nile air",
    "FDD": "feeder airlines",
    "DN": "senegal airlines",
    "S9": "starbow airlines",
    "0X": "copenhagen express",
    "8B": "businessair",
    "YR": "senic airlines",
    "XOJ": "xojet",
    "C7": "sky wing pacific",
    "BEU": "bateleur air",
    "PP": "air indus",
    "OAI": "orbit international airlines",
    "OAR": "orbit regional airlines",
    "OAN": "orbit atlantic airways",
    "VOO": "volotea",
    "MM": "peach aviation",
    "HTH": "helitt líneas aéreas",
    "RSD": "russia state transport",
    "MWI": "malaysia wings",
    "U1": "aviabus",
    "DF": "michael airlines",
    "ZC": "korongo airlines",
    "I5": "indonesia sky",
    "B0": "aws express",
    "76": "southjet",
    "77": "southjet connect",
    "78": "southjet cargo",
    "I2": "iberia express",
    "4O": "interjet (abc aerolineas)",
    "OG": "aironix",
    "NJ": "nordic global airlines",
    "5K": "hi fly (5k)",
    "WH": "china northwest airlines (wh)",
    "ZN": "zenith international airline",
    "O1": "orbit airlines azerbaijan",
    "A6": "air alps aviation (a6)",
    "FKA": "flying kangaroo airline",
    "RSJ": "rusjet",
    "VJC": "vietjet air",
    "P4": "patriot airways",
    "V2": "vision airlines (v2)",
    "5Q": "bqb lineas aereas",
    "WAJ": "airasia japan",
    "YE": "yellowtail",
    "KG": "royal airways",
    "FH": "flyhigh airlines ireland (fh)",
    "XSR": "executive airshare",
    "HBH": "hebei airlines",
    "KBZ": "air kbz",
    "2D": "aero vip (2d)",
    "YH": "yangon airways ltd.",
    "TJ": "t.j. air",
    "SX": "skywork airlines ",
    "W2": "maastricht airlines",
    "24": "euro jet",
    "UAT": "ukraine atlantic",
    "NMA": "nesma airlines",
    "EHN": "east horizon",
    "MJP": "air majoro",
    "RJD": "rotana jet",
    "Q3": "sochi air chater",
    "J7": "denim air ",
    "OD": "malindo air",
    "HRM": "hermes airlines",
    "Z9": "flightlink tanzania",
    "I8": "izavia",
    "КТК": "катэкавиа",
    "PKV": "псковавиа",
    "M1": "maryland air",
    "7I": "insel air (7i/inc) (priv)",
    "5Z": "vivacolombia",
    "FCM": "flybe finland oy",
    "BGY": "bingo airways",
    "BBG": "bluebird airways (bz)",
    "ZM": "apache air",
    "M2": "mhs aviation gmbh",
    "NR": "jettor airlines",
    "VQI": "flyme (vp)",
    "SL": "thai lion air",
    "GMR": "golden myanmar airlines",
    "CNF": "canaryfly",
    "KSZ": "sunrise airways",
    "N8": "national air cargo",
    "13": "eastern atlantic virtual airlines",
    "QG": "citilink indonesia",
    "TTZ": "transair",
    "EVC": "comfort express virtual charters albany",
    "CEO": "comfort express virtual charters",
    "FYJ": "flyjet",
    "S8": "snowbird airlines",
    "KRY": "russkie krylya",
    "KH": "kharkiv airlines",
    "XA": "xair usa",
    "LB": "air costa",
    "RMK": "simrik airlines",
    "XP": "xpto",
    "DME": "royal flight",
    "EGH": "bbn-airways",
    "TKS": "tomsk-avia",
    "3W": "malawian airlines",
    "NYT": "yeti airlines ",
    "KCU": "skyline ulasim ticaret a.s.",
    "ENY": "envoy air",
    "CCB": "caricom airways (barbados) inc.",
    "RN": "rainbow air (rai)",
    "RY": "rainbow air canada",
    "RX": "regent airways",
    "RU": "rainbow air euro",
    "RM": "rainbow air us",
    "TNS": "transilvania",
    "QD": "dobrolet",
    "S0": "spike airlines",
    "GCA": "grand cru airlines",
    "RLX": "go2sky",
    "L1": "all argentina",
    "A2": "all america",
    "L9": "all asia",
    "9A": "all africa",
    "N4": "regionalia méxico",
    "N9": "all europe",
    "N7": "all spain",
    "9N": "regional air iceland",
    "8K": "voestar",
    "7O": "all colombia",
    "2X": "regionalia uruguay",
    "9X": "regionalia venezuela",
    "9J": "regionalia chile",
    "6C": "vuela cuba",
    "88": "all australia",
    "ER": "fly europa",
    "PO": "flyportugal",
    "UK": "vistara",
    "2Y": "my indo airlines",
    "FRV": "government of morocco",
    "AOJ": "avcon jet",
    "QE": "qatar executive",
    "O3": "sf airlines",
}


# Set of valid airline codes
VALID_AIRLINE_CODES = {
    "6A",
    "L9",
    "TLA",
    "VR",
    "AQ",
    "ES",
    "WM",
    "XOJ",
    "B9",
    "9Y",
    "BGY",
    "AGX",
    "DD",
    "SV",
    "WB",
    "4U",
    "MI",
    "KD",
    "JF",
    "UAT",
    "PV",
    "CD",
    "VS",
    "AI",
    "HPY",
    "CM",
    "QI",
    "VL",
    "AOJ",
    "BCN",
    "I2",
    "BMR",
    "IO",
    "AC",
    "4L",
    "JW",
    "EY",
    "AAQ",
    "U5",
    "P8",
    "VC",
    "FM",
    "GS",
    "8Z",
    "USH",
    "PZ",
    "SM",
    "XL",
    "RH",
    "TO",
    "EM",
    "AJ",
    "7C",
    "4X",
    "Y9",
    "TV",
    "W6",
    "ZX",
    "G7",
    "DQ",
    "HMR",
    "VQI",
    "PR",
    "QE",
    "NN",
    "RM",
    "KA",
    "3T",
    "OBS",
    "VU",
    "JB",
    "LI",
    "ZW",
    "ME",
    "BK",
    "Z4",
    "FA",
    "5E",
    "T7",
    "I9",
    "HV",
    "RO",
    "MM",
    "Q2",
    "OZ",
    "LO",
    "GH",
    "RP",
    "EQ",
    "O1",
    "VT",
    "THK",
    "OR",
    "C2",
    "ZH",
    "FIX",
    "R4",
    "DEA",
    "IN",
    "IE",
    "IP",
    "A6",
    "PE",
    "AS",
    "LT",
    "PL",
    "DI",
    "6B",
    "MH",
    "RTE",
    "SP",
    "HY",
    "U6",
    "CUD",
    "WX",
    "JQ",
    "OH",
    "UQ",
    "ZB",
    "H8",
    "GFA",
    "E5",
    "N8",
    "OAR",
    "WK",
    "KR",
    "B2",
    "3L",
    "S1",
    "KH",
    "Z9",
    "MWI",
    "NDN",
    "KF",
    "S4",
    "BW",
    "WC",
    "1I",
    "O2",
    "RLU",
    "UH",
    "BRS",
    "CN",
    "A1",
    "NH",
    "2B",
    "NYT",
    "BN",
    "G3",
    "11",
    "SO",
    "MDP",
    "JPU",
    "XA",
    "BEU",
    "L8",
    "CQ",
    "LJ",
    "CF",
    "IIA",
    "LZ",
    "1B",
    "AF",
    "8V",
    "Q8",
    "7G",
    "SZ",
    "WQ",
    "KK",
    "PFL",
    "V8",
    "EZ",
    "O8",
    "SH",
    "3G",
    "BU",
    "RA",
    "N9",
    "IW",
    "JL",
    "6J",
    "EU",
    "SJ",
    "CO",
    "6P",
    "R5",
    "H5",
    "9H",
    "XJ",
    "TS",
    "CEO",
    "IA",
    "FS",
    "GV",
    "TU",
    "RS",
    "RE",
    "VK",
    "2N",
    "AN",
    "G9",
    "JP",
    "TUR",
    "RJD",
    "GL",
    "DE",
    "YE",
    "2L",
    "B7",
    "TN",
    "9J",
    "OC",
    "RG",
    "9X",
    "DL",
    "R3",
    "TP",
    "3R",
    "LQ",
    "BLL",
    "2T",
    "HD",
    "GG",
    "LY",
    "MX",
    "SQ",
    "99",
    "F7",
    "LS",
    "VY",
    "U8",
    "5N",
    "I5",
    "DM",
    "OL",
    "US",
    "CCG",
    "FC",
    "FI",
    "B1",
    "PH",
    "CU",
    "VI",
    "GA",
    "EC",
    "OBT",
    "ZA",
    "BUR",
    "TD",
    "PKV",
    "AKA",
    "PSB",
    "B5",
    "GDC",
    "CEL",
    "7F",
    "KND",
    "RLX",
    "AY",
    "JC",
    "JT",
    "UU",
    "WA",
    "NW",
    "OA",
    "P9",
    "IZ",
    "OLS",
    "AK",
    "RMK",
    "5M",
    "IT",
    "4T",
    "YO",
    "MJ",
    "24",
    "JX",
    "2A",
    "DME",
    "1C",
    "KE",
    "FR",
    "JZ",
    "VE",
    "RF",
    "EP",
    "G4",
    "ALO",
    "QD",
    "J9",
    "CRO",
    "SA",
    "TH",
    "8D",
    "XE",
    "M7",
    "MA",
    "DK",
    "ZL",
    "DX",
    "LW",
    "JD",
    "5Q",
    "WH",
    "7T",
    "PY",
    "RB",
    "ZY",
    "LA",
    "TRK",
    "F8",
    "78",
    "EL",
    "MO",
    "DH",
    "Q6",
    "EUD",
    "F1",
    "9K",
    "S8",
    "YZ",
    "ELK",
    "3F",
    "A9",
    "L6",
    "3W",
    "FL",
    "9A",
    "YM",
    "KM",
    "EV",
    "TE",
    "JEF",
    "NC",
    "PC",
    "EO",
    "GNN",
    "5H",
    "7L",
    "3P",
    "YV",
    "BS",
    "3Q",
    "9S",
    "KC",
    "GK",
    "UR",
    "ZC",
    "PI",
    "6F",
    "D7",
    "SAY",
    "HT",
    "5T",
    "GF",
    "7O",
    "BY",
    "ЯП",
    "NTM",
    "69",
    "BTM",
    "A7",
    "VN",
    "3E",
    "7H",
    "RK",
    "DNL",
    "QB",
    "HI",
    "B3",
    "R8",
    "FDD",
    "SB",
    "CGK",
    "O6",
    "XT",
    "M4",
    "OY",
    "FRV",
    "SI",
    "QQ",
    "TM",
    "BD",
    "GCR",
    "4N",
    "KLS",
    "ELC",
    "TR",
    "L1",
    "EI",
    "CHW",
    "MS",
    "OS",
    "OX",
    "PX",
    "UL",
    "ZZ",
    "FN",
    "AH",
    "OZW",
    "RSJ",
    "E3",
    "TYR",
    "WU",
    "XV",
    "XM",
    "4C",
    "L5",
    "U2",
    "YH",
    "TT",
    "BP",
    "JK",
    "ZF",
    "KRY",
    "KV",
    "FK",
    "BJ",
    "FZ",
    "P7",
    "OJ",
    "NA",
    "LX",
    "K8",
    "K5",
    "B8",
    "NU",
    "TAH",
    "LG",
    "BE",
    "AA",
    "GCA",
    "CEY",
    "MU",
    "EF",
    "T0",
    "FKA",
    "A3",
    "4P",
    "RX",
    "U9",
    "SK",
    "C5",
    "XK",
    "YY",
    "TG",
    "MYA",
    "I8",
    "A5",
    "TX",
    "RZ",
    "IB",
    "RQ",
    "KSM",
    "ZG",
    "K1",
    "SVG",
    "KY",
    "HBH",
    "VA",
    "WV",
    "OQ",
    "5Y",
    "SC",
    "FW",
    "88",
    "5K",
    "VO",
    "TI",
    "AMV",
    "Y7",
    "8R",
    "H9",
    "S5",
    "5Z",
    "AT",
    "WRC",
    "8L",
    "PTI",
    "L4",
    "UP",
    "CZ",
    "NX",
    "CL",
    "KCU",
    "3K",
    "Q9",
    "N1",
    "QM",
    "KJ",
    "IQ",
    "MQ",
    "AZ",
    "M1",
    "J5",
    "GI",
    "K6",
    "GO",
    "MB",
    "5L",
    "AX",
    "3O",
    "XN",
    "RSD",
    "DC",
    "GE",
    "G1",
    "BF",
    "BL",
    "FNA",
    "MIC",
    "SEA",
    "H1",
    "0B",
    "D9",
    "A4",
    "4H",
    "GY",
    "TGN",
    "JH",
    "W5",
    "H7",
    "MZ",
    "W9",
    "Z8",
    "UDN",
    "2J",
    "JV",
    "QF",
    "NCF",
    "I6",
    "NP",
    "6C",
    "8N",
    "G0",
    "3B",
    "T4",
    "YR",
    "OI",
    "PK",
    "KEA",
    "2Q",
    "7E",
    "GW",
    "O7",
    "3U",
    "YC",
    "BH",
    "CT",
    "U1",
    "CNO",
    "DY",
    "IC",
    "SE",
    "V6",
    "9R",
    "OK",
    "JU",
    "7Z",
    "XBM",
    "VH",
    "XEL",
    "AE",
    "MN",
    "CC",
    "SEN",
    "NJ",
    "LB",
    "HWY",
    "BX",
    "K7",
    "PQ",
    "NS",
    "XO",
    "KI",
    "OO",
    "TIL",
    "GT",
    "RJ",
    "S7",
    "KU",
    "TKS",
    "POT",
    "MP",
    "HVK",
    "LV",
    "FH",
    "4G",
    "J8",
    "1F",
    "KN",
    "Z3",
    "0D",
    "H2",
    "PPW",
    "L7",
    "M9",
    "G6",
    "WJ",
    "8Q",
    "K2",
    "KQ",
    "XW",
    "LR",
    "WOW",
    "D3",
    "FYH",
    "LU",
    "LM",
    "HSK",
    "SPI",
    "GMR",
    "GJ",
    "8E",
    "0X",
    "N4",
    "ER",
    "SN",
    "9L",
    "CV",
    "NZ",
    "NK",
    "PZY",
    "B0",
    "BA",
    "DG",
    "S6",
    "NF",
    "IK",
    "2P",
    "HM",
    "8H",
    "FVM",
    "TJ",
    "KBZ",
    "EAA",
    "RN",
    "VD",
    "AM",
    "CAN",
    "HU",
    "OG",
    "XX",
    "ENJ",
    "DR",
    "GM",
    "LN",
    "U7",
    "JE",
    "WN",
    "9T",
    "MT",
    "RL",
    "2U",
    "FB",
    "JR",
    "XR",
    "FP",
    "6H",
    "KS",
    "KW",
    "FV",
    "QL",
    "DB",
    "CX",
    "2W",
    "01",
    "WAJ",
    "FG",
    "BC",
    "4M",
    "CG",
    "PN",
    "PSA",
    "EGH",
    "LC",
    "W7",
    "AV",
    "QU",
    "7J",
    "YK",
    "U3",
    "VW",
    "6E",
    "КТК",
    "2Y",
    "ZK",
    "P5",
    "XB",
    "QK",
    "9U",
    "WZ",
    "J2",
    "PG",
    "MD",
    "DT",
    "FQ",
    "N0",
    "Q3",
    "7K",
    "L3",
    "WY",
    "VQ",
    "SX",
    "UF",
    "47",
    "VFC",
    "V0",
    "RAC",
    "LTC",
    "FYJ",
    "D6",
    "KDA",
    "XG",
    "QJ",
    "EGS",
    "AW",
    "HF",
    "ENY",
    "UI",
    "NQ",
    "TA",
    "SZB",
    "DA",
    "YS",
    "KT",
    "PF",
    "N7",
    "D1",
    "BKF",
    "HX",
    "UE",
    "ML",
    "QC",
    "IF",
    "V3",
    "8P",
    "Y8",
    "6K",
    "LP",
    "6I",
    "MF",
    "DBK",
    "8M",
    "H3",
    "XP",
    "S0",
    "2O",
    "8K",
    "CE",
    "BM",
    "AU",
    "OU",
    "WG",
    "UM",
    "HE",
    "CY",
    "EFY",
    "VIS",
    "J3",
    "4A",
    "KB",
    "PJ",
    "GP",
    "C3",
    "ZQ",
    "HTH",
    "NE",
    "0G",
    "SW",
    "NY",
    "JA",
    "TW",
    "UJ",
    "6R",
    "F9",
    "QFZ",
    "SOA",
    "8U",
    "FY",
    "DZ",
    "TB",
    "DSV",
    "8F",
    "UK",
    "IX",
    "ZI",
    "DCD",
    "OT",
    "BI",
    "RW",
    "OM",
    "BBG",
    "QG",
    "2K",
    "FCM",
    "12",
    "RSI",
    "TWD",
    "HH",
    "SL",
    "WTJ",
    "R6",
    "AL",
    "YX",
    "RYA",
    "H6",
    "B6",
    "UO",
    "8B",
    "JM",
    "EW",
    "YQ",
    "RC",
    "HA",
    "QR",
    "JI",
    "NL",
    "WF",
    "C4",
    "IG",
    "NT",
    "5D",
    "JO",
    "7B",
    "4O",
    "5G",
    "QS",
    "HK",
    "VJ",
    "UAC",
    "AR",
    "ET",
    "UT",
    "VX",
    "WP",
    "FJ",
    "IXO",
    "OTG",
    "LLC",
    "PU",
    "77",
    "QA",
    "NMA",
    "SY",
    "Z7",
    "ED",
    "ECU",
    "EJ",
    "ANU",
    "JS",
    "QT",
    "Y1",
    "QO",
    "EA",
    "PD",
    "3S",
    "RI",
    "8O",
    "OD",
    "9E",
    "CH",
    "VV",
    "AB",
    "UZ",
    "ZP",
    "UA",
    "ZM",
    "KO",
    "IV",
    "EHN",
    "ZE",
    "LFA",
    "JGN",
    "6W",
    "FLB",
    "QX",
    "VF",
    "GB",
    "T3",
    "TAN",
    "CCB",
    "FD",
    "SRB",
    "9W",
    "DNM",
    "QH",
    "DP",
    "S3",
    "WW",
    "J4",
    "IR",
    "HCC",
    "BPS",
    "HW",
    "SS",
    "FU",
    "UX",
    "EK",
    "9C",
    "PP",
    "C1",
    "ZS",
    "HO",
    "EG",
    "M5",
    "B4",
    "XSR",
    "RD",
    "2I",
    "SCE",
    "AES",
    "BQ",
    "G5",
    "YT",
    "UD",
    "LH",
    "BT",
    "YEP",
    "GR",
    "TDK",
    "MTW",
    "8A",
    "HP",
    "CI",
    "PTB",
    "9N",
    "TK",
    "N5",
    "E4",
    "MJP",
    "SU",
    "XF",
    "NB",
    "CA",
    "SWU",
    "W1",
    "AXE",
    "V2",
    "13",
    "BR",
    "5C",
    "KIN",
    "AD",
    "CJ",
    "CB",
    "C7",
    "UN",
    "OAI",
    "FO",
    "ZJ",
    "4D",
    "CNF",
    "MSE",
    "C0",
    "NM",
    "U4",
    "QZ",
    "PM",
    "WFX",
    "R7",
    "3I",
    "GZ",
    "JJ",
    "T5",
    "HR",
    "TNS",
    "IY",
    "EN",
    "DF",
    "KL",
    "GFT",
    "PT",
    "7I",
    "HAY",
    "6G",
    "YL",
    "PW",
    "S9",
    "20",
    "4K",
    "M3",
    "ID",
    "МИ",
    "FRL",
    "P0",
    "SHD",
    "FT",
    "Q5",
    "W4",
    "ST",
    "Z6",
    "NR",
    "2D",
    "DN",
    "MR",
    "PS",
    "O3",
    "E9",
    "OF",
    "SD",
    "QQQ",
    "QV",
    "G8",
    "ON",
    "HN",
    "HC",
    "TQ",
    "5J",
    "5P",
    "BB",
    "IS",
    "R2",
    "E1",
    "QY",
    "COE",
    "OV",
    "DO",
    "MY",
    "VP",
    "MCA",
    "TTZ",
    "DS",
    "YW",
    "BG",
    "PA",
    "OB",
    "Y4",
    "9Q",
    "QW",
    "VZ",
    "7W",
    "4Z",
    "XZ",
    "Y5",
    "TC",
    "VOO",
    "BV",
    "SG",
    "SOU",
    "DV",
    "HG",
    "A2",
    "KX",
    "8I",
    "7Q",
    "2X",
    "1T",
    "6U",
    "JN",
    "I7",
    "2M",
    "6Y",
    "ZN",
    "UB",
    "WS",
    "M2",
    "CS",
    "YD",
    "UMK",
    "SMW",
    "D8",
    "AXC",
    "OAN",
    "XQ",
    "JY",
    "VJC",
    "EVC",
    "4R",
    "BZ",
    "C9",
    "CP",
    "J7",
    "6T",
    "T2",
    "7M",
    "EZA",
    "LAV",
    "AIO",
    "II",
    "7P",
    "MW",
    "TFN",
    "7Y",
    "UG",
    "5W",
    "S2",
    "V5",
    "W2",
    "Z2",
    "V9",
    "VUE",
    "76",
    "MK",
    "NG",
    "X3",
    "PO",
    "TL",
    "8T",
    "AMT",
    "4Q",
    "CAI",
    "JRB",
    "MAL",
    "RU",
    "6D",
    "SZZ",
    "WD",
    "RV",
    "CW",
    "T6",
    "LF",
    "XY",
    "LK",
    "HZ",
    "VG",
    "GN",
    "HRM",
    "AP",
    "NI",
    "WO",
    "KSZ",
    "2F",
    "KG",
    "RY",
    "8J",
    "TY",
    "AO",
    "AIR",
    "P4",
}
