"""Module containing static airline name-code data"""

# Name : IATA mapping with ICAO as backup
NAME_TO_AIRLINE_CODE_MAPPING = {
    "1time airline": "1T",
    "40-mile air": "Q5",
    "ansett australia": "AN",
    "abacus international": "1B",
    "aigle azur": "ZI",
    "aloha airlines": "AQ",
    "american airlines": "AA",
    "asiana airlines": "OZ",
    "askari aviation": "4K",
    "afriqiyah airways": "8U",
    "allegiant air": "G4",
    "absa - aerolinhas brasileiras": "M3",
    "astral aviation": "8V",
    "air tindi": "8T",
    "ada air": "ZY",
    "adria airways": "JP",
    "air europa": "UX",
    "aero benin": "EM",
    "aegean airlines": "A3",
    "air europe": "PE",
    "alaska central express": "KO",
    "aces colombia": "AES",
    "astraeus": "5W",
    "aerosvit airlines": "VV",
    "air italy": "I9",
    "alliance airlines": "QQ",
    "ariana afghan airlines": "FG",
    "aeroflot russian airlines": "SU",
    "air bosna": "JA",
    "air france": "AF",
    "air caledonie international": "SB",
    "air salone": "20",
    "air cargo carriers": "2Q",
    "air namibia": "SW",
    "aerolitoral": "5D",
    "air glaciers": "7T",
    "aviogenex": "AGX",
    "aeroper": "PL",
    "atlas blue": "8A",
    "azerbaijan airlines": "J2",
    "avies": "U3",
    "airblue": "ED",
    "airlift international": "AIR",
    "air berlin": "AB",
    "air india limited": "AI",
    "air bourbon": "ZB",
    "air atlanta icelandic": "CC",
    "air tahiti nui": "TN",
    "arkia israel airlines": "IZ",
    "air jamaica": "JM",
    "air one": "AP",
    "air sahara": "S2",
    "air malta": "KM",
    "air japan": "NQ",
    "air korea co. ltd.": "AKA",
    "air kiribati": "4A",
    "america west airlines": "HP",
    "air wisconsin": "ZW",
    "tatarstan airlines": "U9",
    "allegheny commuter airlines": "ALO",
    "air sunshine": "RSI",
    "air libert": "VD",
    "air malawi": "QM",
    "air sicilia": "BM",
    "ata airlines": "AMT",
    "air macau": "NX",
    "amc airlines": "AMV",
    "air seychelles": "HM",
    "aeroméxico": "AM",
    "all nippon airways": "NH",
    "ana all nippon airways": "NH",
    "air nostrum": "YW",
    "air niugini": "PX",
    "air arabia": "G9",
    "air canada": "AC",
    "air baltic": "BT",
    "air nippon": "EL",
    "airnorth": "TL",
    "air north charter - canada": "4N",
    "air new zealand": "NZ",
    "alitalia express": "XM",
    "aero flight": "GV",
    "arrow air": "JW",
    "aerocondor": "2B",
    "aires": "4C",
    "aerolineas argentinas": "AR",
    "alaska airlines": "AS",
    "air sinai": "4D",
    "atlantic southeast airlines": "EV",
    "astrakhan airlines": "OB",
    "air tanzania": "TC",
    "air burkina": "2J",
    "airlines of tasmania": "FO",
    "air saint pierre": "PJ",
    "austrian airlines": "OS",
    "air southwest": "WOW",
    "augsburg airways": "IQ",
    "atur": "TUR",
    "abu dhabi amiri flight": "MO",
    "aeroflot-nord": "5N",
    "aurigny air services": "GR",
    "austral lineas aereas": "AU",
    "avianca - aerovias nacionales de colombia": "AV",
    "air vanuatu": "NF",
    "air bangladesh": "B9",
    "air mediterranee": "DR",
    "air moorea": "TAH",
    "aeroline gmbh": "7E",
    "air wales": "6G",
    "air caraïbes": "TX",
    "air india express": "IX",
    "air exel": "XT",
    "airasia": "AK",
    "air asia": "AK",
    "atlant-soyuz airlines": "3G",
    "alitalia": "AZ",
    "amaszonas": "Z8",
    "air zimbabwe": "UM",
    "aserca airlines": "R7",
    "rossiya-russian airlines": "FV",
    "pulkovo aviation enterprise": "FV",
    "american eagle airlines": "MQ",
    "ad aviation": "VUE",
    "air ivoire": "VU",
    "air botswana": "BP",
    "air foyle": "GS",
    "air tahiti": "VT",
    "air via": "VL",
    "africa west": "FK",
    "atran cargo airlines": "V8",
    "air china": "CA",
    "aero condor peru": "Q6",
    "air chathams": "CV",
    "air marshall islands": "CW",
    "access air": "ZA",
    "air algerie": "AH",
    "adam air": "KI",
    "air dolomiti": "EN",
    "aeroflot-don": "D9",
    "air madrid": "NM",
    "aer lingus": "EI",
    "air finland": "OF",
    "airfix aviation": "FIX",
    "air pacific": "FJ",
    "atlantic airways": "RC",
    "air florida": "QH",
    "air iceland": "NY",
    "air philippines": "2P",
    "air guinee express": "2U",
    "air greenland": "GL",
    "atlas air": "5Y",
    "air guyane": "GG",
    "air bagan": "W9",
    "air canada jazz": "QK",
    "atlasjet": "KK",
    "air koryo": "JS",
    "air astana": "KC",
    "albanian airlines": "LV",
    "air alfa": "LFA",
    "aerolane": "XL",
    "atlantis european airways": "TD",
    "air luxor": "LK",
    "air mauritius": "MK",
    "air madagascar": "MD",
    "air moldova": "9U",
    "alsie express": "6I",
    "air alsie": "6I",
    "air plus comet": "A7",
    "astair": "8D",
    "aero contractors": "AJ",
    "aeropelican air services": "OT",
    "aer arann": "RE",
    "air austral": "UU",
    "asian spirit": "6K",
    "air afrique": "RK",
    "airlinair": "A5",
    "aero lanka": "QL",
    "armavia": "U8",
    "aerorep": "P5",
    "aero-service": "BF",
    "aerosur": "5L",
    "aeronorte": "RTE",
    "avient aviation": "Z3",
    "aircompany yakutia": "R3",
    "aeromar": "VW",
    "arkefly": "OR",
    "airlines png": "CG",
    "airtran airways": "FL",
    "air transat": "TS",
    "avialeasing aviation company": "EC",
    "tyrolean airways": "TYR",
    "aerolineas galapagos (aerogal)": "2K",
    "alrosa mirny air enterprise": "6R",
    "british airways": "BA",
    "biman bangladesh airlines": "BG",
    "belair airlines": "4T",
    "bahamasair": "UP",
    "balkan bulgarian airlines": "LZ",
    "british international helicopters": "BS",
    "bf-lento oy": "BKF",
    "bangkok airways": "PG",
    "blue1": "KF",
    "baltic airlines": "BLL",
    "bearskin lake air service": "JV",
    "bellview airlines": "B3",
    "bmi": "BD",
    "bmi british midland": "BD",
    "bmibaby": "WW",
    "bemidji airlines": "CH",
    "british midland regional": "BMR",
    "blue panorama airlines": "BV",
    "budapest aircraft services/manx2": "BPS",
    "bering air": "8E",
    "brazilian air force": "BRS",
    "belavia belarusian airlines": "B2",
    "metro batavia": "7P",
    "berjaya air": "J8",
    "blue wings": "QW",
    "brit air": "DB",
    "brussels airlines": "SN",
    "sn brussels airlines": "SN",
    "binter canarias": "NT",
    "blue air": "0B",
    "british mediterranean airways": "KJ",
    "bulgaria air": "FB",
    "barents airlink": "8N",
    "cal cargo air lines": "5C",
    "calima aviacion": "XG",
    "canadian airlines": "CP",
    "canadian north": "5T",
    "cape air": "9K",
    "caribbean airlines": "BW",
    "carpatair": "V3",
    "caspian airlines": "RV",
    "cathay pacific": "CX",
    "cayman airways": "KX",
    "cebu pacific": "5J",
    "central connect airlines": "CCG",
    "centralwings": "C0",
    "charter air": "CHW",
    "chautauqua airlines": "RP",
    "china airlines": "CI",
    "china eastern airlines": "MU",
    "china southern airlines": "CZ",
    "china united airlines": "HR",
    "yunnan airlines": "3Q",
    "cimber air": "QI",
    "cirrus airlines": "C9",
    "city airline": "CF",
    "city connexion airlines": "G3",
    "cityjet": "WX",
    "ba cityflyer": "CJ",
    "click airways": "CGK",
    "coastal air": "DQ",
    "colgan air": "9L",
    "comair": "MN",
    "commutair": "C5",
    "comores airlines": "KR",
    "compass airlines": "CP",
    "condor flugdienst": "DE",
    "consorcio aviaxsa": "6A",
    "contact air": "C3",
    "contactair": "C3",
    "continental airlines": "CO",
    "continental express": "CO",
    "continental micronesia": "CS",
    "conviasa": "V0",
    "copa airlines": "CM",
    "copterline": "AAQ",
    "corendon airlines": "CAI",
    "corsairfly": "SS",
    "corse-mediterranee": "XK",
    "crest aviation": "CAN",
    "croatia airlines": "OU",
    "crown airways": "CRO",
    "cubana de aviación": "CU",
    "cyprus airways": "CY",
    "cyprus turkish airlines": "YK",
    "czech airlines": "OK",
    "csa czech airlines": "OK",
    "dat danish air transport": "DX",
    "daallo airlines": "D3",
    "dalavia": "H8",
    "darwin airline": "0D",
    "delta aerotaxi": "DEA",
    "delta air lines": "DL",
    "denim air": "DNM",
    "deutsche bahn": "2A",
    "djibouti airlines": "D8",
    "dniproavia": "UDN",
    "dominicana de aviaci": "DO",
    "domodedovo airlines": "E3",
    "donbassaero": "5D",
    "dragonair": "KA",
    "druk air": "KB",
    "dubrovnik air": "DBK",
    "dutch antilles express": "DNL",
    "dba": "DI",
    "eva air": "BR",
    "eagle air": "H7",
    "east african": "QU",
    "eastern airways": "T3",
    "eastland air": "DK",
    "ecuavia": "ECU",
    "edelweiss air": "WK",
    "egyptair": "MS",
    "el al israel airlines": "LY",
    "el-buraq air transport": "UZ",
    "emirates": "EK",
    "emirates airlines": "EK",
    "empresa ecuatoriana de aviacion": "EU",
    "eritrean airlines": "B8",
    "estonian air": "OV",
    "ethiopian airlines": "ET",
    "etihad airways": "EY",
    "euro exec express": "RZ",
    "eurocypria airlines": "UI",
    "eurofly service": "GJ",
    "eurolot": "K2",
    "european air express": "EA",
    "eurowings": "EW",
    "evergreen international airlines": "EZ",
    "excel airways": "JN",
    "excel charter": "XEL",
    "express one international": "EO",
    "expressjet": "XE",
    "easyjet": "U2",
    "easyjet airline": "U2",
    "far eastern air transport": "EF",
    "finnair": "AY",
    "finncomm airlines": "FC",
    "firefly": "FY",
    "first air": "7F",
    "first choice airways": "DP",
    "flightline": "B5",
    "florida west international airways": "RF",
    "airasia x": "D7",
    "flyasianxpress": "D7",
    "flylal": "TE",
    "flynordic": "LF",
    "flybaboo": "F7",
    "flybe": "BE",
    "flyglobespan": "B4",
    "flyhy cargo airlines": "FYH",
    "formosa airlines": "VY",
    "freedom air": "FP",
    "freedom airlines": "FRL",
    "frontier airlines": "F9",
    "frontier flying service": "2F",
    "gb airways": "GT",
    "garuda indonesia": "GA",
    "gazpromavia": "4G",
    "georgian airways": "A9",
    "georgian national airlines": "QB",
    "germania": "ST",
    "germanwings": "4U",
    "ghana international airlines": "G0",
    "go air": "G8",
    "gojet airlines": "G7",
    "gol transportes aéreos": "G3",
    "golden air": "DC",
    "great lakes airlines": "ZK",
    "grupo taca": "TA",
    "taca": "TA",
    "gulf air": "GFA",
    "gulf air bahrain": "GF",
    "gulfstream international airlines": "GFT",
    "hageland aviation services": "H6",
    "hainan airlines": "HU",
    "haiti ambassador airlines": "2T",
    "hamburg international": "4R",
    "tuifly": "X3",
    "hapagfly": "HF",
    "hawaiian airlines": "HA",
    "hawkair": "BH",
    "heli france": "8H",
    "helijet": "JB",
    "hellas jet": "T4",
    "hello": "HW",
    "helvetic airways": "2L",
    "hex'air": "UD",
    "highland airways": "HWY",
    "hokkaido international airlines": "HD",
    "hong kong airlines": "HX",
    "hong kong express airways": "UO",
    "horizon air": "QX",
    "horizon airlines": "BN",
    "iberia airlines": "IB",
    "iberworld": "TY",
    "ibex airlines": "FW",
    "icar air": "RAC",
    "icelandair": "FI",
    "imair airlines": "IK",
    "indigo airlines": "6E",
    "indian airlines": "IC",
    "indigo": "I9",
    "indonesia airasia": "QZ",
    "indonesian airlines": "IO",
    "interair south africa": "D6",
    "interavia airlines": "ZA",
    "interlink airlines": "ID",
    "intersky": "3L",
    "iran air": "IR",
    "iran aseman airlines": "EP",
    "iraqi airways": "IA",
    "island airlines": "IS",
    "cargo plus aviation": "8L",
    "islas airways": "IF",
    "islena de inversiones": "WC",
    "israir": "6H",
    "itek air": "GI",
    "jal express": "JC",
    "jalways": "JO",
    "japan airlines": "JL",
    "jal japan airlines": "JL",
    "japan asia airways": "EG",
    "japan transocean air": "NU",
    "jat airways": "JU",
    "jazeera airways": "J9",
    "jeju air": "7C",
    "jet airways": "QJ",
    "jetstar asia airways": "3K",
    "jet2.com": "LS",
    "jet4you": "8J",
    "jetblue airways": "B6",
    "jetairfly": "JF",
    "jetflite": "JEF",
    "jetstar airways": "JQ",
    "juneyao airlines": "HO",
    "kd avia": "KD",
    "klm cityhopper": "WA",
    "klm royal dutch airlines": "KL",
    "kam air": "RQ",
    "kavminvodyavia": "KV",
    "kendell airlines": "KDA",
    "kenmore air": "M5",
    "kenya airways": "KQ",
    "kingfisher airlines": "IT",
    "kish air": "Y9",
    "kogalymavia air company": "7K",
    "korean air": "KE",
    "kosmos": "KSM",
    "krasnojarsky airlines": "7B",
    "kuban airlines": "GW",
    "kuwait airways": "KU",
    "kuzu airlines cargo": "GO",
    "lacsa": "LR",
    "lan airlines": "LA",
    "lan argentina": "4M",
    "lan express": "LU",
    "lan peru": "LP",
    "lot polish airlines": "LO",
    "lte international airways": "XO",
    "ltu austria": "L3",
    "ltu international": "LT",
    "lao airlines": "QV",
    "latcharter": "LTC",
    "lauda air": "NG",
    "leeward islands air transport": "LI",
    "libyan arab airlines": "LN",
    "linhas a": "LM",
    "lion mentari airlines": "JT",
    "luftfahrtgesellschaft walter": "HE",
    "lufthansa": "LH",
    "lufthansa cargo": "LH",
    "lufthansa cityline": "CL",
    "lufttransport": "L5",
    "luxair": "LG",
    "l": "MJ",
    "masair": "M7",
    "mat macedonian airlines": "IN",
    "miat mongolian airlines": "OM",
    "mng airlines": "MB",
    "macair airlines": "CC",
    "maersk": "DM",
    "mahan air": "W5",
    "malaysia airlines": "MH",
    "malta air charter": "R5",
    "malév": "MA",
    "mandala airlines": "RI",
    "mandarin airlines": "AE",
    "mango": "JE",
    "martinair": "MP",
    "maxair": "8M",
    "maya island air": "MW",
    "meridiana": "IG",
    "merpati nusantara airlines": "MZ",
    "mesa airlines": "YV",
    "mesaba airlines": "XJ",
    "mexicana de aviaci": "MX",
    "middle east airlines": "ME",
    "midway airlines": "JI",
    "midwest airlines": "YX",
    "midwest airlines (egypt)": "MY",
    "moldavian airlines": "2M",
    "monarch airlines": "ZB",
    "myway airlines": "8I",
    "montenegro airlines": "YM",
    "morningstar air express": "MAL",
    "moskovia airlines": "3R",
    "motor sich": "M9",
    "mytravel airways": "VZ",
    "myanma airways": "UB",
    "myanmar airways international": "8M",
    "myflug": "MYA",
    "nasair": "UE",
    "national jet systems": "NC",
    "nationwide airlines": "CE",
    "nauru air corporation": "ON",
    "nepal airlines": "RA",
    "netjets": "1I",
    "new england airlines": "EJ",
    "nextjet": "2N",
    "niki": "HG",
    "nok air": "DD",
    "norfolk county flight college": "NCF",
    "north american airlines": "NTM",
    "north american charters": "HMR",
    "northern dene airways": "U7",
    "northwest airlines": "NW",
    "northwestern air": "J3",
    "norwegian air shuttle": "DY",
    "norwegian aviation college": "TFN",
    "nouvel air tunisie": "BJ",
    "novair": "1I",
    "nas air": "XY",
    "oasis hong kong airlines": "O8",
    "ocean air": "BCN",
    "oceanair": "O6",
    "oceanic airlines": "O2",
    "olympic airlines": "OA",
    "oman air": "WY",
    "omni air international": "OY",
    "one two go airlines": "OTG",
    "onur air": "8Q",
    "orenburg airlines": "R2",
    "orient thai airlines": "OX",
    "origin pacific airways": "QO",
    "ostfriesische lufttransport": "OL",
    "overland airways": "OJ",
    "ozjet airlines": "O7",
    "pan air": "PV",
    "pb air": "9Q",
    "pluna": "PU",
    "pmtair": "U4",
    "jetstar pacific": "BL",
    "pacific airlines": "BL",
    "pacific coastal airline": "8P",
    "pacific east asia cargo airlines": "Q8",
    "pacific island aviation": "PSA",
    "pacific wings": "LW",
    "pakistan international airlines": "PK",
    "pia pakistan international": "PK",
    "paramount airways": "I7",
    "passaredo transportes aereos": "PTB",
    "pegasus airlines": "PC",
    "peninsula airways": "KS",
    "philippine airlines": "PR",
    "piedmont airlines (1948-1989)": "PI",
    "pinnacle airlines": "9E",
    "polet": "POT",
    "polynesian airlines": "PH",
    "porter airlines": "PD",
    "portugalia": "NI",
    "potomac air": "BK",
    "precision air": "PW",
    "privatair": "PTI",
    "proflight commuter services": "P0",
    "qantas": "QF",
    "qantas airways": "QF",
    "qatar airways": "QR",
    "racsa": "R6",
    "kinloss flying training unit": "KIN",
    "regional airlines": "FN",
    "regional express": "ZL",
    "republic airlines": "RW",
    "republic express airlines": "RH",
    "rossiya": "R4",
    "air rarotonga": "GZ",
    "royal air maroc": "AT",
    "royal brunei airlines": "BI",
    "royal jordanian": "RJ",
    "royal phnom penh airways": "PPW",
    "rusline": "RLU",
    "rwandair express": "WB",
    "ryan air services": "RYA",
    "ryan international airlines": "RD",
    "ryanair": "FR",
    "régional": "YS",
    "sata international": "S4",
    "south african airways": "SA",
    "saa south african airways": "SA",
    "shaheen air international": "NL",
    "scandinavian airlines system": "SK",
    "sas scandinavian airlines": "SK",
    "scotairways": "SAY",
    "s7 airlines": "S7",
    "sibir airlines": "S7",
    "seaborne airlines": "BB",
    "scenic airlines": "SCE",
    "srilankan airlines": "UL",
    "sun country airlines": "SY",
    "southeast air": "SEA",
    "sky express": "XW",
    "spicejet": "SG",
    "star flyer": "7G",
    "skagway air service": "N5",
    "sahara airlines": "SHD",
    "sata air acores": "SP",
    "singapore airlines": "SQ",
    "sibaviatrans": "5M",
    "skynet airlines": "SI",
    "sriwijaya air": "SJ",
    "sama airlines": "ZS",
    "singapore airlines cargo": "SQ",
    "siem reap airways": "FT",
    "south east asian airlines": "DG",
    "skyservice airlines": "5G",
    "servicios de transportes a": "FS",
    "sudan airways": "SD",
    "saudi arabian airlines": "SV",
    "southwest airlines": "WN",
    "southern winds airlines": "A4",
    "swiss international air lines": "LX",
    "swiss airlines": "LX",
    "swiss european air lines": "SWU",
    "swiss european": "",
    "swe fly": "WV",
    "sunexpress": "XQ",
    "syrian arab airlines": "RB",
    "skywalk airlines": "AL",
    "shandong airlines": "SC",
    "sas braathens": "CNO",
    "spring airlines": "9S",
    "sichuan airlines": "3U",
    "shanghai airlines": "FM",
    "shenzhen airlines": "ZH",
    "sun d'or": "7L",
    "skyeurope": "NE",
    "sky europe airlines": "HSK",
    "spanair": "JK",
    "spirit airlines": "NK",
    "satena": "9R",
    "skywest airlines": "OZW",
    "santa barbara airlines": "S3",
    "sky airline": "H2",
    "skywest": "OO",
    "skyways express": "JZ",
    "skymark airlines": "BC",
    "silkair": "MI",
    "surinam airways": "PY",
    "sterling airlines": "NB",
    "skynet asia airways": "6J",
    "solomon airlines": "IE",
    "southern airways": "SOU",
    "saratov aviation division": "6W",
    "sat airlines": "HZ",
    "south pacific island airways": "SPI",
    "shuttle america": "S5",
    "scat air": "DV",
    "tame": "EQ",
    "tam brazilian airlines": "JJ",
    "tap portugal": "TP",
    "tap air portugal": "TP",
    "tunisair": "TU",
    "thai air cargo": "T2",
    "thomas cook airlines": "MT",
    "trigana air service": "TGN",
    "tiger airways": "TR",
    "tigerair australia": "TT",
    "thai airways international": "TG",
    "turk hava kurumu hava taksi isletmesi": "THK",
    "thai airasia": "FD",
    "thai air asia": "FD",
    "turkish airlines": "TK",
    "tajikistan international airlines": "TIL",
    "twin jet": "T7",
    "translift airways": "TLA",
    "trans mediterranean airlines": "TL",
    "tiara air": "3P",
    "thomsonfly": "BY",
    "tropic air": "PM",
    "tampa": "QT",
    "transasia airways": "GE",
    "transavia holland": "HV",
    "tacv": "VR",
    "transwest air": "9T",
    "transaero airlines": "UN",
    "turkmenistan airlines": "T5",
    "turkmenhovayollary": "T5",
    "tuninter": "UG",
    "travel service": "QS",
    "tuifly nordic": "6B",
    "taag angola airlines": "DT",
    "turkish air force": "HVK",
    "tam mercosur": "PZ",
    "trans states airlines": "AX",
    "tarom": "RO",
    "turan air": "3T",
    "trip linhas a": "8R",
    "usa3000 airlines": "U5",
    "united airlines": "UA",
    "united air charters": "UAC",
    "ural airlines": "U6",
    "um airlines": "UF",
    "us airways": "US",
    "us helicopter": "USH",
    "utair aviation": "UT",
    "united states air force": "AIO",
    "uzbekistan airways": "HY",
    "ukraine international airlines": "PS",
    "us helicopter corporation": "UH",
    "valuair": "VF",
    "vasco air": "VFC",
    "vietnam airlines": "VN",
    "vim airlines": "NN",
    "volaris": "Y4",
    "volga-dnepr airlines": "VI",
    "virgin america": "VX",
    "virgin express": "TV",
    "virgin nigeria airways": "VK",
    "virgin atlantic airways": "VS",
    "viva macau": "ZG",
    "volare airlines": "VE",
    "vueling airlines": "VY",
    "vladivostok air": "XF",
    "varig log": "LC",
    "virgin australia": "VA",
    "vrg linhas aereas": "RG",
    "varig": "RG",
    "vasp": "VP",
    "vlm airlines": "VG",
    "wayraper": "7W",
    "webjet linhas a": "WJ",
    "welcome air": "2W",
    "west coast air": "8O",
    "westjet": "WS",
    "western airlines": "WA",
    "widerøe": "WF",
    "wind jet": "IV",
    "wings air": "IW",
    "wizz air": "W6",
    "wizz air hungary": "8Z",
    "world airways": "WO",
    "xl airways france": "SE",
    "xiamen airlines": "MF",
    "yamal airlines": "YL",
    "yemenia": "IY",
    "yuzhmashavia": "UMK",
    "zanair": "TAN",
    "zoom airlines": "Z4",
    "maldivian air taxi": "8Q",
    "royal air cambodge": "VJ",
    "air mandalay": "6T",
    "air busan": "BX",
    "skyexpress": "XW",
    "globus": "GH",
    "air kazakhstan": "9Y",
    "japan air system": "JD",
    "easyjet (ds)": "DS",
    "star peru (2i)": "2I",
    "carnival air lines": "KW",
    "united airways": "4H",
    "fly540": "5H",
    "transavia france": "TO",
    "island air (wp)": "WP",
    "uni air": "B7",
    "gomelavia": "YD",
    "red wings": "WZ",
    "avialinii 400": "WZ",
    "tuifly (x3)": "11",
    "felix airways": "FU",
    "kostromskie avialinii": "K1",
    "greenfly": "XX",
    "tajik air": "7J",
    "air mozambique": "TM",
    "elk airways": "ELK",
    "gabon airlines": "GY",
    "mca airlines": "MCA",
    "maldivo airlines": "ML",
    "virgin pacific": "VH",
    "zest air": "Z2",
    "yangon airways": "HK",
    "eastar jet": "ZE",
    "jin air": "LJ",
    "air arabia maroc": "3O",
    "baltic air lines": "B1",
    "ciel canadien": "YC",
    "canadian national airways": "CN",
    "epic holiday": "FA",
    "epic holidays": "FA",
    "indochina airlines": "AXC",
    "air comet chile": "3I",
    "german air force - flb": "FLB",
    "line blue": "L8",
    "flylal charters": "LLC",
    "salzburg arrows": "SZ",
    "sza": "SZ",
    "texas wings": "TQ",
    "dennis sky": "DH",
    "dennis sky holding": "DH",
    "zz": "ZZ",
    "atifly": "A1",
    "aerolineas heredas santa maria": "SZB",
    "ciao air": "99",
    "jc royal.britannica": "JRB",
    "pal airlines": "5P",
    "canxpress": "C1",
    "danube wings (v5)": "V5",
    "sharp airlines": "SH",
    "canxplorer": "C2",
    "click (mexicana)": "QA",
    "world experience airline": "W1",
    "wea": "W1",
    "alak": "J4",
    "air choice one": "3E",
    "tianjin airlines": "GCR",
    "china united": "KN",
    "locair": "ZQ",
    "safi airlines": "4Q",
    "seaport airlines": "K5",
    "salmon air": "S6",
    "bobb air freight": "01",
    "star1 airlines": "V9",
    "pelita": "6D",
    "alaska seaplane service": "J5",
    "enerjet": "ENJ",
    "mexicanalink": "I6",
    "island spirit": "IP",
    "taca peru": "T0",
    "orbest": "OBS",
    "southern air charter": "SOA",
    "svg air": "SVG",
    "air century": "CEY",
    "pan am world airways dominicana": "7Q",
    "pawa dominicana": "7Q",
    "primera air": "PF",
    "air antilles express": "3S",
    "sol lineas aereas": "OLS",
    "regional paraguaya": "P7",
    "vip ecuador": "V6",
    "transportes aereos cielos andinos": "NDN",
    "peruvian airlines": "P9",
    "easyfly": "EFY",
    "polar airlines": "ЯП",
    "catovair": "OC",
    "andalus lineas aereas": "ANU",
    "air 26": "DCD",
    "mauritania airways": "MTW",
    "ceiba intercontinental": "CEL",
    "halcyonair": "7Z",
    "business aviation": "4P",
    "compagnie africaine d\\\\'aviation": "E9",
    "zambia skyways": "K8",
    "almasria universal airlines": "UJ",
    "egyptair express": "MSE",
    "smartlynx airlines": "6Y",
    "air italy egypt": "EUD",
    "koralblue airlines": "K7",
    "wind rose aviation": "WRC",
    "elysian airlines": "E4",
    "sevenair": "SEN",
    "hellenic imperial airways": "HT",
    "amsterdam airlines": "WD",
    "arik niger": "Q9",
    "dana air": "DA",
    "stp airways": "8F",
    "med airways": "7Y",
    "skyjet airlines": "UQ",
    "air volga": "G6",
    "transavia denmark": "TDK",
    "royal falcon": "RL",
    "euroline": "4L",
    "turkuaz airlines": "TRK",
    "athens airways": "ZF",
    "viking hellas": "VQ",
    "norlandair": "FNA",
    "flugfelag vestmannaeyja": "FVM",
    "starline.kz": "DZ",
    "lugansk airlines": "L7",
    "gryphon airlines": "6P",
    "gadair european airlines": "GP",
    "spirit of manila airlines": "SM",
    "chongqing airlines": "OQ",
    "grand china air": "GDC",
    "west air china": "PN",
    "qatxpress": "C3",
    "onechina": "1C",
    "nordstar airlines": "Y7",
    "joy air": "JR",
    "air india regional": "CD",
    "mdlr airlines": "9H",
    "jagson airlines": "JGN",
    "maldivian": "Q2",
    "xpressair": "XN",
    "strategic airlines": "VC",
    "fars air qeshm": "QFZ",
    "eastok avia": "EAA",
    "jupiter airlines": "JPU",
    "vision air international": "VIS",
    "al-naser airlines": "NA",
    "fuji dream airlines": "JH",
    "korea express air": "KEA",
    "eznis airways": "EZA",
    "pacific flier": "PFL",
    "syrian pearl airlines": "PSB",
    "sga airlines": "5E",
    "air2there": "F8",
    "avianova (russia)": "AO",
    "parmiss airlines (ipv)": "PA",
    "europesky": "ES",
    "brazil air": "GB",
    "homer air": "MR",
    "homer sky": "MR",
    "panam world airways": "WQ",
    "virginwings": "YY",
    "ksy": "KY",
    "kreta sky": "KY",
    "buquebus líneas aéreas": "BQ",
    "sochi air": "CQ",
    "sochi": "CQ",
    "wizz air ukraine": "WU",
    "88": "47",
    "lcm airlines": "LQ",
    "cambodia angkor air (k6)": "K6",
    "royal european airlines": "69",
    "azul": "AD",
    "azul linhas aéreas brasileiras": "AD",
    "lsm airlines": "PQ",
    "slowbird": "PQ",
    "zapolyarie airlines": "PZY",
    "zapolyarye airlines": "",
    "lionxpress": "C4",
    "genesis": "GK",
    "congo express": "XZ",
    "fly dubai": "FZ",
    "domenican airlines": "D1",
    "domenican": "D1",
    "aereonautica militare": "JY",
    "kal star aviation": "KLS",
    "lsm airlines ": "YZ",
    "russian. yours air lines ": "YZ",
    "utair-express": "UR",
    "huaxia": "G5",
    "zabaykalskii airlines": "ZP",
    "baikal airlines": "ZP",
    "cbm america": "XBM",
    "marysya airlines": "M4",
    "n1": "N1",
    "airlink (saa)": "4Z",
    "westfalia express va": "WFX",
    "jobair": "3B",
    "black stallion airways": "BZ",
    "german international air lines": "GM",
    "germanair": "GM",
    "trasbrasil": "TB",
    "transbrasil airlines": "TH",
    "china sss": "9C",
    "chunqiu airlines": "9C",
    "air indochine": "IIA",
    "happy air": "HPY",
    "solar air": "SRB",
    "air mekong": "P8",
    "harbour air (priv)": "H3",
    "air hamburg (aho)": "HH",
    "zabaikal airlines": "Z6",
    "zabaikal ": "Z6",
    "transholding": "TI",
    "trans": "TI",
    "sur lineas aereas": "SZZ",
    "yeti airways": "YT",
    "yellowstone club private shuttle": "Y1",
    "caucasus airlines": "NS",
    "serbian airlines": "S1",
    "windward islands airways": "WM",
    "transholding system": "YO",
    "ccml airlines": "CB",
    "small planet airlines": "ELC",
    "fly brasil": "F1",
    "cb airways uk ( interliging flights )": "1F",
    "fly colombia ( interliging flights )": "3F",
    "trans pas air": "T6",
    "kmv": "МИ",
    "himalayan airlines": "HC",
    "himalaya": "HC",
    "indya airline group": "G1",
    "indya1": "G1",
    "sunwing": "WG",
    "turkish wings domestic": "TWD",
    "japan regio": "ZX",
    "ocean air cargo": "IXO",
    "norte lineas aereas": "N0",
    "norte": "N0",
    "austral brasil": "W7",
    "austral brasil lineas aereas": "W7",
    "pegasus airlines-": "H9",
    "camair-co": "QC",
    "sky regional": "RS",
    "air canada express": "RS",
    "lsm international ": "II",
    "moskva-air": "II",
    "baikotovitchestrian airlines ": "BU",
    "luchsh airlines ": "L4",
    "air luch": "L4",
    "enterair": "QQQ",
    "air cargo germany": "6U",
    "mongolian international air lines ": "7M",
    "mongol air ": "7M",
    "tway airlines": "TW",
    "papillon grand canyon helicopters": "HI",
    "jusur airways": "JX",
    "next brasil": "XB",
    "next": "XB",
    "aeroworld ": "W4",
    "sovet air ": "W4",
    "gnb linhas aereas": "GN",
    "usa sky cargo": "E1",
    "usky": "E1",
    "hankook airline": "HN",
    "redjet": "Z7",
    "red jet andes": "PT",
    "red jet canada": "QY",
    "sprintair": "0G",
    "red jet mexico": "4X",
    "marusya airways": "Y8",
    "marusya air": "Y8",
    "era alaska": "7H",
    "airrussia": "R8",
    "russianconector": "R8",
    "hankook air us": "H1",
    "carpatair flight training": "SMW",
    "i-fly": "H5",
    "whitejets": "WTJ",
    "vickjet": "KT",
    "bvi airways": "XV",
    "hamburg airways": "HAY",
    "salsa d\\\\'haiti": "SO",
    "zambezi airlines (zma)": "ZJ",
    "kan air": "KND",
    "air cudlua": "CUD",
    "polet airlines (priv)": "YQ",
    "air explore": "AXE",
    "12 north": "12",
    "holidays czech airlines": "HCC",
    "comtel air": "COE",
    "mint airways": "MIC",
    "orbit airlines": "OBT",
    "orbit": "",
    "air bucharest": "BUR",
    "albastar": "LAV",
    "mauritania airlines international": "L6",
    "mat airways": "6F",
    "asian wings airways": "AW",
    "air arabia egypt": "E5",
    "eagles airlines": "EGS",
    "yes airways": "YEP",
    "alitalia cityliner": "CT",
    "direct aero services": "DSV",
    "medallion air": "MDP",
    "orchid airlines": "OI",
    "asia wings": "Y5",
    "georgian international airlines": "GNN",
    "air batumi": "BTM",
    "skywest australia": "XR",
    "nile air": "NP",
    "feeder airlines": "FDD",
    "senegal airlines": "DN",
    "starbow airlines": "S9",
    "copenhagen express": "0X",
    "businessair": "8B",
    "senic airlines": "YR",
    "xojet": "XOJ",
    "sky wing pacific": "C7",
    "bateleur air": "BEU",
    "air indus": "PP",
    "indus airlines pak": "PP",
    "orbit international airlines": "OAI",
    "orbit regional airlines": "OAR",
    "orbit atlantic airways": "OAN",
    "volotea": "VOO",
    "peach aviation": "MM",
    "helitt líneas aéreas": "HTH",
    "russia state transport": "RSD",
    "federal state budget inst": "",
    "malaysia wings": "MWI",
    "aviabus": "U1",
    "michael airlines": "DF",
    "javi": "DF",
    "korongo airlines": "ZC",
    "indonesia sky": "I5",
    "aws express": "B0",
    "southjet": "76",
    "southjet connect": "77",
    "southjet cargo": "78",
    "iberia express": "I2",
    "interjet (abc aerolineas)": "4O",
    "aironix": "OG",
    "nordic global airlines": "NJ",
    "scoot": "TR",
    "hi fly (5k)": "5K",
    "china northwest airlines (wh)": "WH",
    "zenith international airline": "ZN",
    "zenith": "ZN",
    "orbit airlines azerbaijan": "O1",
    "orbit azerbaijan": "O1",
    "air alps aviation (a6)": "A6",
    "flying kangaroo airline": "FKA",
    "skippy": "",
    "rusjet": "RSJ",
    "vietjet air": "VJC",
    "vietjet": "",
    "patriot airways": "P4",
    "vision airlines (v2)": "V2",
    "bqb lineas aereas": "5Q",
    "buquebus": "5Q",
    "airasia japan": "WAJ",
    "yellowtail": "YE",
    "royal airways": "KG",
    "royal inc.": "KG",
    "flyhigh airlines ireland (fh)": "FH",
    "executive airshare": "XSR",
    "hebei airlines": "HBH",
    "air kbz": "KBZ",
    "aero vip (2d)": "2D",
    "yangon airways ltd.": "YH",
    "t.j. air": "TJ",
    "skywork airlines ": "SX",
    "maastricht airlines": "W2",
    "euro jet": "24",
    "ukraine atlantic": "UAT",
    "nesma airlines": "NMA",
    "east horizon": "EHN",
    "air majoro": "MJP",
    "rotana jet": "RJD",
    "sochi air chater": "Q3",
    "sochi air ": "Q3",
    "denim air ": "J7",
    "flynonstop": "J7",
    "malindo air": "OD",
    "hermes airlines": "HRM",
    "flightlink tanzania": "Z9",
    "flightlink": "Z9",
    "izavia": "I8",
    "катэкавиа": "КТК",
    "псковавиа": "PKV",
    "псков авиа": "",
    "maryland air": "M1",
    "maryland": "M1",
    "insel air (7i/inc) (priv)": "7I",
    "vivacolombia": "5Z",
    "flybe finland oy": "FCM",
    "bingo airways": "BGY",
    "bingo": "",
    "bluebird airways (bz)": "BBG",
    "apache air": "ZM",
    "apache": "ZM",
    "mhs aviation gmbh": "M2",
    "jettor airlines": "NR",
    "jettor": "NR",
    "flyme (vp)": "VQI",
    "thai lion air": "SL",
    "golden myanmar airlines": "GMR",
    "canaryfly": "CNF",
    "sunrise airways": "KSZ",
    "national air cargo": "N8",
    "eastern atlantic virtual airlines": "13",
    "citilink indonesia": "QG",
    "transair": "TTZ",
    "comfort express virtual charters albany": "EVC",
    "comfort express virtual charters": "CEO",
    "flyjet": "FYJ",
    "snowbird airlines": "S8",
    "russkie krylya": "KRY",
    "kharkiv airlines": "KH",
    "xair usa": "XA",
    "air costa": "LB",
    "simrik airlines": "RMK",
    "xpto": "XP",
    "xpto  ": "XP",
    "royal flight": "DME",
    "bbn-airways": "EGH",
    "blackburn": "",
    "tomsk-avia": "TKS",
    "malawian airlines": "3W",
    "yeti airlines ": "NYT",
    "skyline ulasim ticaret a.s.": "KCU",
    "envoy air": "ENY",
    "caricom airways (barbados) inc.": "CCB",
    "caricom airways": "",
    "rainbow air (rai)": "RN",
    "rainbow air canada": "RY",
    "rainbow air can": "RY",
    "rainbow air polynesia": "RX",
    "rainbow air pol": "RX",
    "rainbow air euro": "RU",
    "rainbow air eu": "RU",
    "rainbow air us": "RM",
    "transilvania": "TNS",
    "dobrolet": "QD",
    "добролёт": "QD",
    "spike airlines": "S0",
    "aero spike": "S0",
    "grand cru airlines": "GCA",
    "go2sky": "RLX",
    "all argentina": "L1",
    "all america": "A2",
    "all asia": "L9",
    "all africa": "9A",
    "regionalia méxico": "N4",
    "all europe": "N9",
    "all spain": "N7",
    "regional air iceland": "9N",
    "voestar": "8K",
    "voestar brasil": "8K",
    "all colombia": "7O",
    "regionalia uruguay": "2X",
    "regionalia venezuela": "9X",
    "regionalia chile": "9J",
    "vuela cuba": "6C",
    "all australia": "88",
    "fly europa": "ER",
    "flyportugal": "PO",
    "vistara": "UK",
    "urumqi air": "UQ",
    "guangxi beibu gulf airlines": "UQ",
    "my indo airlines": "2Y",
    "government of morocco": "FRV",
    "hong kong air cargo": "RH",
    "us-bangla airlines": "BS",
    "netjets europe": "1I",
    "bhutan airlines": "B3",
    "iran airtour": "B9",
    "avcon jet": "AOJ",
    "indonesia airasia x": "XT",
    "qatar executive": "QE",
    "sf airlines": "O3",
    "regent airways": "RX",
    "asiacargo express": "3G",
}


# IATA : Name and ICAO : Name mapping
AIRLINE_CODE_TO_NAME_MAPPING = {
    "1T": "1time airline",
    "RNX": "1time airline",
    "Q5": "40-mile air",
    "MLA": "40-mile air",
    "AN": "ansett australia",
    "AAA": "ansett australia",
    "1B": "abacus international",
    "ZI": "aigle azur",
    "AAF": "aigle azur",
    "AQ": "aloha airlines",
    "AAH": "aloha airlines",
    "AA": "american airlines",
    "AAL": "american airlines",
    "OZ": "asiana airlines",
    "AAR": "asiana airlines",
    "4K": "askari aviation",
    "AAS": "askari aviation",
    "8U": "afriqiyah airways",
    "AAW": "afriqiyah airways",
    "G4": "allegiant air",
    "AAY": "allegiant air",
    "M3": "absa - aerolinhas brasileiras",
    "TUS": "absa - aerolinhas brasileiras",
    "8V": "astral aviation",
    "ACP": "astral aviation",
    "8T": "air tindi",
    "ZY": "ada air",
    "ADE": "ada air",
    "JP": "adria airways",
    "ADR": "adria airways",
    "UX": "air europa",
    "AEA": "air europa",
    "EM": "aero benin",
    "AEB": "aero benin",
    "A3": "aegean airlines",
    "AEE": "aegean airlines",
    "PE": "air europe",
    "AEL": "air europe",
    "KO": "alaska central express",
    "AER": "alaska central express",
    "AES": "aces colombia",
    "5W": "astraeus",
    "AEU": "astraeus",
    "VV": "aerosvit airlines",
    "AEW": "aerosvit airlines",
    "I9": "indigo",
    "AEY": "air italy",
    "QQ": "alliance airlines",
    "UTY": "alliance airlines",
    "FG": "ariana afghan airlines",
    "AFG": "ariana afghan airlines",
    "SU": "aeroflot russian airlines",
    "AFL": "aeroflot russian airlines",
    "JA": "air bosna",
    "BON": "air bosna",
    "AF": "air france",
    "AFR": "air france",
    "SB": "air caledonie international",
    "ACI": "air caledonie international",
    "2O": "air salone",
    "2Q": "air cargo carriers",
    "SNC": "air cargo carriers",
    "SW": "air namibia",
    "NMB": "air namibia",
    "5D": "donbassaero",
    "SLI": "aerolitoral",
    "7T": "air glaciers",
    "AGV": "air glaciers",
    "AGX": "aviogenex",
    "PL": "aeroper",
    "PLI": "aeroper",
    "8A": "atlas blue",
    "BMM": "atlas blue",
    "J2": "azerbaijan airlines",
    "AHY": "azerbaijan airlines",
    "U3": "avies",
    "AIA": "avies",
    "ED": "airblue",
    "ABQ": "airblue",
    "AIR": "airlift international",
    "AB": "air berlin",
    "BER": "air berlin",
    "AI": "air india limited",
    "AIC": "air india limited",
    "ZB": "monarch airlines",
    "BUB": "air bourbon",
    "CC": "macair airlines",
    "ABD": "air atlanta icelandic",
    "TN": "air tahiti nui",
    "THT": "air tahiti nui",
    "IZ": "arkia israel airlines",
    "AIZ": "arkia israel airlines",
    "JM": "air jamaica",
    "AJM": "air jamaica",
    "AP": "air one",
    "ADH": "air one",
    "S2": "air sahara",
    "RSH": "air sahara",
    "KM": "air malta",
    "AMC": "air malta",
    "NQ": "air japan",
    "AJX": "air japan",
    "AKA": "air korea co. ltd.",
    "4A": "air kiribati",
    "AKL": "air kiribati",
    "HP": "america west airlines",
    "AWE": "america west airlines",
    "ZW": "air wisconsin",
    "AWI": "air wisconsin",
    "U9": "tatarstan airlines",
    "TAK": "tatarstan airlines",
    "ALO": "allegheny commuter airlines",
    "RSI": "air sunshine",
    "VD": "air libert",
    "QM": "air malawi",
    "AML": "air malawi",
    "BM": "air sicilia",
    "AMT": "ata airlines",
    "NX": "air macau",
    "AMU": "air macau",
    "AMV": "amc airlines",
    "HM": "air seychelles",
    "SEY": "air seychelles",
    "AM": "aeroméxico",
    "AMX": "aeroméxico",
    "NH": "all nippon airways",
    "ANA": "all nippon airways",
    "YW": "air nostrum",
    "ANE": "air nostrum",
    "PX": "air niugini",
    "ANG": "air niugini",
    "G9": "air arabia",
    "ABY": "air arabia",
    "AC": "air canada",
    "ACA": "air canada",
    "BT": "air baltic",
    "BTI": "air baltic",
    "EL": "air nippon",
    "ANK": "air nippon",
    "TL": "trans mediterranean airlines",
    "ANO": "airnorth",
    "4N": "air north charter - canada",
    "ANT": "air north charter - canada",
    "NZ": "air new zealand",
    "ANZ": "air new zealand",
    "XM": "alitalia express",
    "SMX": "alitalia express",
    "GV": "aero flight",
    "ARF": "aero flight",
    "JW": "arrow air",
    "APW": "arrow air",
    "2B": "aerocondor",
    "ARD": "aerocondor",
    "4C": "aires",
    "ARE": "aires",
    "AR": "aerolineas argentinas",
    "ARG": "aerolineas argentinas",
    "AS": "alaska airlines",
    "ASA": "alaska airlines",
    "4D": "air sinai",
    "ASD": "air sinai",
    "EV": "atlantic southeast airlines",
    "ASQ": "atlantic southeast airlines",
    "OB": "astrakhan airlines",
    "ASZ": "astrakhan airlines",
    "TC": "air tanzania",
    "ATC": "air tanzania",
    "2J": "air burkina",
    "VBW": "air burkina",
    "FO": "airlines of tasmania",
    "ATM": "airlines of tasmania",
    "PJ": "air saint pierre",
    "SPM": "air saint pierre",
    "OS": "austrian airlines",
    "AUA": "austrian airlines",
    "WOW": "air southwest",
    "IQ": "augsburg airways",
    "AUB": "augsburg airways",
    "TUR": "atur",
    "MO": "abu dhabi amiri flight",
    "AUH": "abu dhabi amiri flight",
    "5N": "aeroflot-nord",
    "AUL": "aeroflot-nord",
    "GR": "aurigny air services",
    "AUR": "aurigny air services",
    "AU": "austral lineas aereas",
    "AUT": "austral lineas aereas",
    "AV": "avianca - aerovias nacionales de colombia",
    "AVA": "avianca - aerovias nacionales de colombia",
    "NF": "air vanuatu",
    "AVN": "air vanuatu",
    "B9": "iran airtour",
    "BGD": "air bangladesh",
    "DR": "air mediterranee",
    "BIE": "air mediterranee",
    "TAH": "air moorea",
    "7E": "aeroline gmbh",
    "AWU": "aeroline gmbh",
    "6G": "air wales",
    "AWW": "air wales",
    "TX": "air caraïbes",
    "FWI": "air caraïbes",
    "IX": "air india express",
    "AXB": "air india express",
    "XT": "indonesia airasia x",
    "AXL": "air exel",
    "AK": "airasia",
    "AXM": "airasia",
    "3G": "asiacargo express",
    "AYZ": "atlant-soyuz airlines",
    "AZ": "alitalia",
    "AZA": "alitalia",
    "Z8": "amaszonas",
    "AZN": "amaszonas",
    "UM": "air zimbabwe",
    "AZW": "air zimbabwe",
    "R7": "aserca airlines",
    "OCA": "aserca airlines",
    "FV": "rossiya-russian airlines",
    "SDM": "rossiya-russian airlines",
    "MQ": "american eagle airlines",
    "EGF": "american eagle airlines",
    "VUE": "ad aviation",
    "VU": "air ivoire",
    "VUN": "air ivoire",
    "BP": "air botswana",
    "BOT": "air botswana",
    "GS": "air foyle",
    "UPA": "air foyle",
    "VT": "air tahiti",
    "VTA": "air tahiti",
    "VL": "air via",
    "VIM": "air via",
    "FK": "africa west",
    "WTA": "africa west",
    "V8": "atran cargo airlines",
    "VAS": "atran cargo airlines",
    "CA": "air china",
    "CCA": "air china",
    "Q6": "aero condor peru",
    "CDP": "aero condor peru",
    "CV": "air chathams",
    "CVA": "air chathams",
    "CW": "air marshall islands",
    "CWM": "air marshall islands",
    "ZA": "interavia airlines",
    "CYD": "access air",
    "AH": "air algerie",
    "DAH": "air algerie",
    "KI": "adam air",
    "DHI": "adam air",
    "EN": "air dolomiti",
    "DLA": "air dolomiti",
    "D9": "aeroflot-don",
    "DNV": "aeroflot-don",
    "NM": "air madrid",
    "DRD": "air madrid",
    "EI": "aer lingus",
    "EIN": "aer lingus",
    "OF": "air finland",
    "FIF": "air finland",
    "FIX": "airfix aviation",
    "FJ": "air pacific",
    "FJI": "air pacific",
    "RC": "atlantic airways",
    "FLI": "atlantic airways",
    "QH": "air florida",
    "FLZ": "air florida",
    "NY": "air iceland",
    "FXI": "air iceland",
    "2P": "air philippines",
    "GAP": "air philippines",
    "2U": "air guinee express",
    "GIP": "air guinee express",
    "GL": "air greenland",
    "GRL": "air greenland",
    "5Y": "atlas air",
    "GTI": "atlas air",
    "GG": "air guyane",
    "GUY": "air guyane",
    "W9": "air bagan",
    "JAB": "air bagan",
    "QK": "air canada jazz",
    "JZA": "air canada jazz",
    "KK": "atlasjet",
    "KKK": "atlasjet",
    "JS": "air koryo",
    "KOR": "air koryo",
    "KC": "air astana",
    "KZR": "air astana",
    "LV": "albanian airlines",
    "LBC": "albanian airlines",
    "LFA": "air alfa",
    "XL": "aerolane",
    "LNE": "aerolane",
    "TD": "atlantis european airways",
    "LUR": "atlantis european airways",
    "LK": "air luxor",
    "LXR": "air luxor",
    "MK": "air mauritius",
    "MAU": "air mauritius",
    "MD": "air madagascar",
    "MDG": "air madagascar",
    "9U": "air moldova",
    "MLD": "air moldova",
    "6I": "alsie express",
    "MMD": "alsie express",
    "A7": "air plus comet",
    "MPD": "air plus comet",
    "8D": "astair",
    "AJ": "aero contractors",
    "NIG": "aero contractors",
    "OT": "aeropelican air services",
    "PEL": "aeropelican air services",
    "RE": "aer arann",
    "REA": "aer arann",
    "UU": "air austral",
    "REU": "air austral",
    "6K": "asian spirit",
    "RIT": "asian spirit",
    "RK": "air afrique",
    "RKA": "air afrique",
    "A5": "airlinair",
    "RLA": "airlinair",
    "QL": "aero lanka",
    "RLN": "aero lanka",
    "20": "air salone",
    "RNE": "air salone",
    "U8": "armavia",
    "RNV": "armavia",
    "P5": "aerorep",
    "RPB": "aerorep",
    "BF": "aero-service",
    "RSR": "aero-service",
    "5L": "aerosur",
    "RSU": "aerosur",
    "RTE": "aeronorte",
    "Z3": "avient aviation",
    "SMJ": "avient aviation",
    "R3": "aircompany yakutia",
    "SYL": "aircompany yakutia",
    "VW": "aeromar",
    "TAO": "aeromar",
    "OR": "arkefly",
    "TFL": "arkefly",
    "CG": "airlines png",
    "TOK": "airlines png",
    "FL": "airtran airways",
    "TRS": "airtran airways",
    "TS": "air transat",
    "TSC": "air transat",
    "EC": "avialeasing aviation company",
    "TWN": "avialeasing aviation company",
    "VO": "tyrolean airways",
    "TYR": "tyrolean airways",
    "2K": "aerolineas galapagos (aerogal)",
    "GLG": "aerolineas galapagos (aerogal)",
    "6R": "alrosa mirny air enterprise",
    "DRU": "alrosa mirny air enterprise",
    "BA": "british airways",
    "BAW": "british airways",
    "BG": "biman bangladesh airlines",
    "BBC": "biman bangladesh airlines",
    "4T": "belair airlines",
    "BHP": "belair airlines",
    "UP": "bahamasair",
    "BHS": "bahamasair",
    "LZ": "balkan bulgarian airlines",
    "BS": "us-bangla airlines",
    "BIH": "british international helicopters",
    "BKF": "bf-lento oy",
    "PG": "bangkok airways",
    "BKP": "bangkok airways",
    "KF": "blue1",
    "BLF": "blue1",
    "BLL": "baltic airlines",
    "JV": "bearskin lake air service",
    "BLS": "bearskin lake air service",
    "B3": "bhutan airlines",
    "BLV": "bellview airlines",
    "BD": "bmi",
    "BMA": "bmi",
    "WW": "bmibaby",
    "BMI": "bmibaby",
    "CH": "bemidji airlines",
    "BMJ": "bemidji airlines",
    "BMR": "british midland regional",
    "BV": "blue panorama airlines",
    "BPA": "blue panorama airlines",
    "BPS": "budapest aircraft services/manx2",
    "8E": "bering air",
    "BRG": "bering air",
    "BRS": "brazilian air force",
    "B2": "belavia belarusian airlines",
    "BRU": "belavia belarusian airlines",
    "7P": "metro batavia",
    "BTV": "metro batavia",
    "J8": "berjaya air",
    "BVT": "berjaya air",
    "QW": "blue wings",
    "BWG": "blue wings",
    "DB": "brit air",
    "BZH": "brit air",
    "SN": "brussels airlines",
    "DAT": "brussels airlines",
    "NT": "binter canarias",
    "IBB": "binter canarias",
    "0B": "blue air",
    "JOR": "blue air",
    "KJ": "british mediterranean airways",
    "LAJ": "british mediterranean airways",
    "FB": "bulgaria air",
    "LZB": "bulgaria air",
    "8N": "barents airlink",
    "NKF": "barents airlink",
    "5C": "cal cargo air lines",
    "ICL": "cal cargo air lines",
    "XG": "calima aviacion",
    "CLI": "calima aviacion",
    "CP": "compass airlines",
    "CDN": "canadian airlines",
    "5T": "canadian north",
    "MPE": "canadian north",
    "9K": "cape air",
    "KAP": "cape air",
    "BW": "caribbean airlines",
    "BWA": "caribbean airlines",
    "V3": "carpatair",
    "KRP": "carpatair",
    "RV": "caspian airlines",
    "CPN": "caspian airlines",
    "CX": "cathay pacific",
    "CPA": "cathay pacific",
    "KX": "cayman airways",
    "CAY": "cayman airways",
    "5J": "cebu pacific",
    "CEB": "cebu pacific",
    "CCG": "central connect airlines",
    "C0": "centralwings",
    "CLW": "centralwings",
    "CHW": "charter air",
    "RP": "chautauqua airlines",
    "CHQ": "chautauqua airlines",
    "CI": "china airlines",
    "CAL": "china airlines",
    "MU": "china eastern airlines",
    "CES": "china eastern airlines",
    "CZ": "china southern airlines",
    "CSN": "china southern airlines",
    "HR": "china united airlines",
    "CUA": "china united airlines",
    "3Q": "yunnan airlines",
    "CYH": "yunnan airlines",
    "QI": "cimber air",
    "CIM": "cimber air",
    "C9": "cirrus airlines",
    "RUS": "cirrus airlines",
    "CF": "city airline",
    "SDR": "city airline",
    "G3": "sky express",
    "CIX": "city connexion airlines",
    "WX": "cityjet",
    "BCY": "cityjet",
    "CJ": "ba cityflyer",
    "CFE": "ba cityflyer",
    "CGK": "click airways",
    "DQ": "coastal air",
    "9L": "colgan air",
    "CJC": "colgan air",
    "OH": "comair",
    "COM": "comair",
    "MN": "comair",
    "CAW": "comair",
    "C5": "commutair",
    "UCA": "commutair",
    "KR": "comores airlines",
    "CWK": "comores airlines",
    "CPZ": "compass airlines",
    "DE": "condor flugdienst",
    "CFG": "condor flugdienst",
    "6A": "consorcio aviaxsa",
    "CHP": "consorcio aviaxsa",
    "C3": "qatxpress",
    "KIS": "contact air",
    "CO": "continental express",
    "COA": "continental airlines",
    "CS": "continental micronesia",
    "CMI": "continental micronesia",
    "V0": "conviasa",
    "VCV": "conviasa",
    "CM": "copa airlines",
    "CMP": "copa airlines",
    "AAQ": "copterline",
    "CAI": "corendon airlines",
    "SS": "corsairfly",
    "CRL": "corsairfly",
    "XK": "corse-mediterranee",
    "CCM": "corse-mediterranee",
    "CAN": "crest aviation",
    "OU": "croatia airlines",
    "CTN": "croatia airlines",
    "CRO": "crown airways",
    "CU": "cubana de aviación",
    "CUB": "cubana de aviación",
    "CY": "cyprus airways",
    "CYP": "cyprus airways",
    "YK": "cyprus turkish airlines",
    "OK": "czech airlines",
    "CSA": "czech airlines",
    "DX": "dat danish air transport",
    "DTR": "dat danish air transport",
    "D3": "daallo airlines",
    "DAO": "daallo airlines",
    "H8": "dalavia",
    "KHB": "dalavia",
    "0D": "darwin airline",
    "DWT": "darwin airline",
    "DEA": "delta aerotaxi",
    "DL": "delta air lines",
    "DAL": "delta air lines",
    "DNM": "denim air",
    "2A": "deutsche bahn",
    "D8": "djibouti airlines",
    "DJB": "djibouti airlines",
    "UDN": "dniproavia",
    "DO": "dominicana de aviaci",
    "DOA": "dominicana de aviaci",
    "E3": "domodedovo airlines",
    "DMO": "domodedovo airlines",
    "UDC": "donbassaero",
    "KA": "dragonair",
    "HDA": "dragonair",
    "KB": "druk air",
    "DRK": "druk air",
    "DBK": "dubrovnik air",
    "DNL": "dutch antilles express",
    "DI": "dba",
    "BAG": "dba",
    "BR": "eva air",
    "EVA": "eva air",
    "H7": "eagle air",
    "QU": "east african",
    "UGX": "east african",
    "T3": "eastern airways",
    "EZE": "eastern airways",
    "DK": "eastland air",
    "ELA": "eastland air",
    "ECU": "ecuavia",
    "WK": "edelweiss air",
    "EDW": "edelweiss air",
    "MS": "egyptair",
    "MSR": "egyptair",
    "LY": "el al israel airlines",
    "ELY": "el al israel airlines",
    "UZ": "el-buraq air transport",
    "BRQ": "el-buraq air transport",
    "EK": "emirates",
    "UAE": "emirates",
    "EU": "empresa ecuatoriana de aviacion",
    "EEA": "empresa ecuatoriana de aviacion",
    "B8": "eritrean airlines",
    "ERT": "eritrean airlines",
    "OV": "estonian air",
    "ELL": "estonian air",
    "ET": "ethiopian airlines",
    "ETH": "ethiopian airlines",
    "EY": "etihad airways",
    "ETD": "etihad airways",
    "RZ": "euro exec express",
    "UI": "eurocypria airlines",
    "ECA": "eurocypria airlines",
    "GJ": "eurofly service",
    "EEU": "eurofly service",
    "K2": "eurolot",
    "ELO": "eurolot",
    "EA": "european air express",
    "EAL": "european air express",
    "EW": "eurowings",
    "EWG": "eurowings",
    "EZ": "evergreen international airlines",
    "EIA": "evergreen international airlines",
    "JN": "excel airways",
    "XLA": "excel airways",
    "XEL": "excel charter",
    "EO": "express one international",
    "LHN": "express one international",
    "XE": "expressjet",
    "BTA": "expressjet",
    "U2": "easyjet",
    "EZY": "easyjet",
    "EF": "far eastern air transport",
    "EFA": "far eastern air transport",
    "AY": "finnair",
    "FIN": "finnair",
    "FC": "finncomm airlines",
    "WBA": "finncomm airlines",
    "FY": "firefly",
    "FFM": "firefly",
    "7F": "first air",
    "FAB": "first air",
    "DP": "first choice airways",
    "FCA": "first choice airways",
    "B5": "flightline",
    "FLT": "flightline",
    "RF": "florida west international airways",
    "FWL": "florida west international airways",
    "D7": "airasia x",
    "XAX": "airasia x",
    "TE": "flylal",
    "LIL": "flylal",
    "LF": "flynordic",
    "NDC": "flynordic",
    "F7": "flybaboo",
    "BBO": "flybaboo",
    "BE": "flybe",
    "BEE": "flybe",
    "B4": "flyglobespan",
    "GSM": "flyglobespan",
    "FYH": "flyhy cargo airlines",
    "VY": "vueling airlines",
    "FOS": "formosa airlines",
    "FP": "freedom air",
    "FRE": "freedom air",
    "FRL": "freedom airlines",
    "F9": "frontier airlines",
    "FFT": "frontier airlines",
    "2F": "frontier flying service",
    "FTA": "frontier flying service",
    "GT": "gb airways",
    "GBL": "gb airways",
    "GA": "garuda indonesia",
    "GIA": "garuda indonesia",
    "4G": "gazpromavia",
    "GZP": "gazpromavia",
    "A9": "georgian airways",
    "TGZ": "georgian airways",
    "QB": "georgian national airlines",
    "GFG": "georgian national airlines",
    "ST": "germania",
    "GMI": "germania",
    "4U": "germanwings",
    "GWI": "germanwings",
    "G0": "ghana international airlines",
    "GHB": "ghana international airlines",
    "G8": "go air",
    "GOW": "go air",
    "G7": "gojet airlines",
    "GJS": "gojet airlines",
    "GLO": "gol transportes aéreos",
    "DC": "golden air",
    "GAO": "golden air",
    "ZK": "great lakes airlines",
    "GLA": "great lakes airlines",
    "TA": "grupo taca",
    "TAT": "grupo taca",
    "GFA": "gulf air",
    "GF": "gulf air bahrain",
    "GBA": "gulf air bahrain",
    "GFT": "gulfstream international airlines",
    "H6": "hageland aviation services",
    "HAG": "hageland aviation services",
    "HU": "hainan airlines",
    "CHH": "hainan airlines",
    "2T": "haiti ambassador airlines",
    "HAM": "haiti ambassador airlines",
    "4R": "hamburg international",
    "HHI": "hamburg international",
    "X3": "tuifly",
    "HLX": "tuifly",
    "HF": "hapagfly",
    "HLF": "hapagfly",
    "HA": "hawaiian airlines",
    "HAL": "hawaiian airlines",
    "BH": "hawkair",
    "8H": "heli france",
    "HFR": "heli france",
    "JB": "helijet",
    "JBA": "helijet",
    "T4": "hellas jet",
    "HEJ": "hellas jet",
    "HW": "hello",
    "FHE": "hello",
    "2L": "helvetic airways",
    "OAW": "helvetic airways",
    "UD": "hex'air",
    "HER": "hex'air",
    "HWY": "highland airways",
    "HD": "hokkaido international airlines",
    "ADO": "hokkaido international airlines",
    "HX": "hong kong airlines",
    "CRK": "hong kong airlines",
    "UO": "hong kong express airways",
    "HKE": "hong kong express airways",
    "QX": "horizon air",
    "QXE": "horizon air",
    "BN": "horizon airlines",
    "HZA": "horizon airlines",
    "IB": "iberia airlines",
    "IBE": "iberia airlines",
    "TY": "iberworld",
    "IWD": "iberworld",
    "FW": "ibex airlines",
    "IBX": "ibex airlines",
    "RAC": "royal air cambodge",
    "FI": "icelandair",
    "ICE": "icelandair",
    "IK": "imair airlines",
    "ITX": "imair airlines",
    "6E": "indigo airlines",
    "IGO": "indigo airlines",
    "IC": "indian airlines",
    "IAC": "indian airlines",
    "IBU": "indigo",
    "QZ": "indonesia airasia",
    "AWQ": "indonesia airasia",
    "IO": "indonesian airlines",
    "IAA": "indonesian airlines",
    "D6": "interair south africa",
    "ILN": "interair south africa",
    "SUW": "interavia airlines",
    "ID": "interlink airlines",
    "ITK": "interlink airlines",
    "3L": "intersky",
    "ISK": "intersky",
    "IR": "iran air",
    "IRA": "iran air",
    "EP": "iran aseman airlines",
    "IRC": "iran aseman airlines",
    "IA": "iraqi airways",
    "IAW": "iraqi airways",
    "IS": "island airlines",
    "8L": "cargo plus aviation",
    "CGP": "cargo plus aviation",
    "IF": "islas airways",
    "ISW": "islas airways",
    "WC": "islena de inversiones",
    "ISV": "islena de inversiones",
    "6H": "israir",
    "ISR": "israir",
    "GI": "itek air",
    "IKA": "itek air",
    "JC": "jal express",
    "JEX": "jal express",
    "JO": "jalways",
    "JAZ": "jalways",
    "JL": "japan airlines",
    "JAL": "japan airlines",
    "EG": "japan asia airways",
    "JAA": "japan asia airways",
    "NU": "japan transocean air",
    "JTA": "japan transocean air",
    "JU": "jat airways",
    "JAT": "jat airways",
    "J9": "jazeera airways",
    "JZR": "jazeera airways",
    "7C": "jeju air",
    "JJA": "jeju air",
    "9W": "jet airways",
    "JAI": "jet airways",
    "QJ": "jet airways",
    "3K": "jetstar asia airways",
    "JSA": "jetstar asia airways",
    "LS": "jet2.com",
    "EXS": "jet2.com",
    "8J": "jet4you",
    "JFU": "jet4you",
    "B6": "jetblue airways",
    "JBU": "jetblue airways",
    "JF": "jetairfly",
    "JAF": "jetairfly",
    "JEF": "jetflite",
    "JQ": "jetstar airways",
    "JST": "jetstar airways",
    "HO": "juneyao airlines",
    "DKH": "juneyao airlines",
    "KD": "kd avia",
    "KNI": "kd avia",
    "WA": "western airlines",
    "KLC": "klm cityhopper",
    "KL": "klm royal dutch airlines",
    "KLM": "klm royal dutch airlines",
    "RQ": "kam air",
    "KMF": "kam air",
    "KV": "kavminvodyavia",
    "MVD": "kavminvodyavia",
    "KDA": "kendell airlines",
    "M5": "kenmore air",
    "KEN": "kenmore air",
    "KQ": "kenya airways",
    "KQA": "kenya airways",
    "IT": "kingfisher airlines",
    "KFR": "kingfisher airlines",
    "Y9": "kish air",
    "IRK": "kish air",
    "7K": "kogalymavia air company",
    "KGL": "kogalymavia air company",
    "KE": "korean air",
    "KAL": "korean air",
    "KSM": "kosmos",
    "7B": "krasnojarsky airlines",
    "KJC": "krasnojarsky airlines",
    "GW": "kuban airlines",
    "KIL": "kuban airlines",
    "KU": "kuwait airways",
    "KAC": "kuwait airways",
    "GO": "kuzu airlines cargo",
    "KZU": "kuzu airlines cargo",
    "LR": "lacsa",
    "LRC": "lacsa",
    "LA": "lan airlines",
    "LAN": "lan airlines",
    "4M": "lan argentina",
    "DSM": "lan argentina",
    "LU": "lan express",
    "LXP": "lan express",
    "LP": "lan peru",
    "LPE": "lan peru",
    "LO": "lot polish airlines",
    "LOT": "lot polish airlines",
    "XO": "lte international airways",
    "LTE": "lte international airways",
    "L3": "ltu austria",
    "LTO": "ltu austria",
    "LT": "ltu international",
    "LTU": "ltu international",
    "QV": "lao airlines",
    "LAO": "lao airlines",
    "LTC": "latcharter",
    "NG": "lauda air",
    "LDA": "lauda air",
    "LI": "leeward islands air transport",
    "LIA": "leeward islands air transport",
    "LN": "libyan arab airlines",
    "LAA": "libyan arab airlines",
    "LM": "linhas a",
    "LAM": "linhas a",
    "JT": "lion mentari airlines",
    "LNI": "lion mentari airlines",
    "HE": "luftfahrtgesellschaft walter",
    "LGW": "luftfahrtgesellschaft walter",
    "LH": "lufthansa cargo",
    "DLH": "lufthansa",
    "GEC": "lufthansa cargo",
    "CL": "lufthansa cityline",
    "CLH": "lufthansa cityline",
    "L5": "lufttransport",
    "LTR": "lufttransport",
    "LG": "luxair",
    "LGL": "luxair",
    "MJ": "l",
    "LPR": "l",
    "M7": "masair",
    "MAA": "masair",
    "IN": "mat macedonian airlines",
    "MAK": "mat macedonian airlines",
    "OM": "miat mongolian airlines",
    "MGL": "miat mongolian airlines",
    "MB": "mng airlines",
    "MNB": "mng airlines",
    "MCK": "macair airlines",
    "DM": "maersk",
    "W5": "mahan air",
    "IRM": "mahan air",
    "MH": "malaysia airlines",
    "MAS": "malaysia airlines",
    "R5": "malta air charter",
    "MAC": "malta air charter",
    "MA": "malév",
    "MAH": "malév",
    "RI": "mandala airlines",
    "MDL": "mandala airlines",
    "AE": "mandarin airlines",
    "MDA": "mandarin airlines",
    "JE": "mango",
    "MNO": "mango",
    "MP": "martinair",
    "MPH": "martinair",
    "8M": "myanmar airways international",
    "MXL": "maxair",
    "MW": "maya island air",
    "MYD": "maya island air",
    "IG": "meridiana",
    "ISS": "meridiana",
    "MZ": "merpati nusantara airlines",
    "MNA": "merpati nusantara airlines",
    "YV": "mesa airlines",
    "ASH": "mesa airlines",
    "XJ": "mesaba airlines",
    "MES": "mesaba airlines",
    "MX": "mexicana de aviaci",
    "MXA": "mexicana de aviaci",
    "ME": "middle east airlines",
    "MEA": "middle east airlines",
    "JI": "midway airlines",
    "MDW": "midway airlines",
    "YX": "midwest airlines",
    "MEP": "midwest airlines",
    "MY": "midwest airlines (egypt)",
    "MWA": "midwest airlines (egypt)",
    "2M": "moldavian airlines",
    "MDV": "moldavian airlines",
    "MON": "monarch airlines",
    "8I": "myway airlines",
    "YM": "montenegro airlines",
    "MGX": "montenegro airlines",
    "MAL": "morningstar air express",
    "3R": "moskovia airlines",
    "GAI": "moskovia airlines",
    "M9": "motor sich",
    "MSI": "motor sich",
    "VZ": "mytravel airways",
    "MYT": "mytravel airways",
    "UB": "myanma airways",
    "UBA": "myanma airways",
    "MMM": "myanmar airways international",
    "MYA": "myflug",
    "UE": "nasair",
    "NAS": "nasair",
    "NC": "national jet systems",
    "NJS": "national jet systems",
    "CE": "nationwide airlines",
    "NTW": "nationwide airlines",
    "ON": "nauru air corporation",
    "RON": "nauru air corporation",
    "RA": "nepal airlines",
    "RNA": "nepal airlines",
    "1I": "netjets europe",
    "EJA": "netjets",
    "EJ": "new england airlines",
    "NEA": "new england airlines",
    "2N": "nextjet",
    "NTJ": "nextjet",
    "HG": "niki",
    "NLY": "niki",
    "DD": "nok air",
    "NOK": "nok air",
    "NCF": "norfolk county flight college",
    "NTM": "north american airlines",
    "HMR": "north american charters",
    "U7": "northern dene airways",
    "NW": "northwest airlines",
    "NWA": "northwest airlines",
    "J3": "northwestern air",
    "PLR": "northwestern air",
    "DY": "norwegian air shuttle",
    "NAX": "norwegian air shuttle",
    "TFN": "norwegian aviation college",
    "BJ": "nouvel air tunisie",
    "LBT": "nouvel air tunisie",
    "NVR": "novair",
    "XY": "nas air",
    "KNE": "nas air",
    "O8": "oasis hong kong airlines",
    "OHK": "oasis hong kong airlines",
    "BCN": "ocean air",
    "O6": "oceanair",
    "ONE": "oceanair",
    "O2": "oceanic airlines",
    "OA": "olympic airlines",
    "OAL": "olympic airlines",
    "WY": "oman air",
    "OMA": "oman air",
    "OY": "omni air international",
    "OAE": "omni air international",
    "OTG": "one two go airlines",
    "8Q": "maldivian air taxi",
    "OHY": "onur air",
    "R2": "orenburg airlines",
    "ORB": "orenburg airlines",
    "OX": "orient thai airlines",
    "OEA": "orient thai airlines",
    "QO": "origin pacific airways",
    "OGN": "origin pacific airways",
    "OL": "ostfriesische lufttransport",
    "OLT": "ostfriesische lufttransport",
    "OJ": "overland airways",
    "OLA": "overland airways",
    "O7": "ozjet airlines",
    "OZJ": "ozjet airlines",
    "PV": "pan air",
    "PNR": "pan air",
    "9Q": "pb air",
    "PBA": "pb air",
    "PU": "pluna",
    "PUA": "pluna",
    "U4": "pmtair",
    "PMT": "pmtair",
    "BL": "jetstar pacific",
    "PIC": "jetstar pacific",
    "8P": "pacific coastal airline",
    "PCO": "pacific coastal airline",
    "Q8": "pacific east asia cargo airlines",
    "PEC": "pacific east asia cargo airlines",
    "PSA": "pacific island aviation",
    "LW": "pacific wings",
    "NMI": "pacific wings",
    "PK": "pakistan international airlines",
    "PIA": "pakistan international airlines",
    "I7": "paramount airways",
    "PMW": "paramount airways",
    "PTB": "passaredo transportes aereos",
    "PC": "pegasus airlines",
    "PGT": "pegasus airlines",
    "KS": "peninsula airways",
    "PEN": "peninsula airways",
    "PR": "philippine airlines",
    "PAL": "philippine airlines",
    "PI": "piedmont airlines (1948-1989)",
    "PDT": "piedmont airlines (1948-1989)",
    "9E": "pinnacle airlines",
    "FLG": "pinnacle airlines",
    "POT": "polet",
    "PH": "polynesian airlines",
    "PAO": "polynesian airlines",
    "PD": "porter airlines",
    "POE": "porter airlines",
    "NI": "portugalia",
    "PGA": "portugalia",
    "BK": "potomac air",
    "PDC": "potomac air",
    "PW": "precision air",
    "PRF": "precision air",
    "PTI": "privatair",
    "P0": "proflight commuter services",
    "QF": "qantas",
    "QFA": "qantas",
    "QR": "qatar airways",
    "QTR": "qatar airways",
    "R6": "racsa",
    "KIN": "kinloss flying training unit",
    "FN": "regional airlines",
    "ZL": "regional express",
    "RXA": "regional express",
    "RW": "republic airlines",
    "RPA": "republic airlines",
    "RH": "hong kong air cargo",
    "RPH": "republic express airlines",
    "R4": "rossiya",
    "GZ": "air rarotonga",
    "RAR": "air rarotonga",
    "AT": "royal air maroc",
    "RAM": "royal air maroc",
    "BI": "royal brunei airlines",
    "RBA": "royal brunei airlines",
    "RJ": "royal jordanian",
    "RJA": "royal jordanian",
    "PPW": "royal phnom penh airways",
    "RLU": "rusline",
    "WB": "rwandair express",
    "RWD": "rwandair express",
    "RYA": "ryan air services",
    "RD": "ryan international airlines",
    "RYN": "ryan international airlines",
    "FR": "ryanair",
    "RYR": "ryanair",
    "YS": "régional",
    "RAE": "régional",
    "S4": "sata international",
    "RZO": "sata international",
    "SA": "south african airways",
    "SAA": "south african airways",
    "NL": "shaheen air international",
    "SAI": "shaheen air international",
    "SK": "scandinavian airlines system",
    "SAS": "scandinavian airlines system",
    "SAY": "scotairways",
    "S7": "s7 airlines",
    "SBI": "s7 airlines",
    "BB": "seaborne airlines",
    "SBS": "seaborne airlines",
    "SCE": "scenic airlines",
    "UL": "srilankan airlines",
    "ALK": "srilankan airlines",
    "SY": "sun country airlines",
    "SCX": "sun country airlines",
    "SEA": "southeast air",
    "SEH": "sky express",
    "SG": "spicejet",
    "SEJ": "spicejet",
    "7G": "star flyer",
    "SFJ": "star flyer",
    "N5": "skagway air service",
    "SGY": "skagway air service",
    "SHD": "sahara airlines",
    "SP": "sata air acores",
    "SAT": "sata air acores",
    "SQ": "singapore airlines cargo",
    "SIA": "singapore airlines",
    "5M": "sibaviatrans",
    "SIB": "sibaviatrans",
    "SI": "skynet airlines",
    "SIH": "skynet airlines",
    "SJ": "sriwijaya air",
    "SJY": "sriwijaya air",
    "ZS": "sama airlines",
    "SMY": "sama airlines",
    "SQC": "singapore airlines cargo",
    "FT": "siem reap airways",
    "SRH": "siem reap airways",
    "DG": "south east asian airlines",
    "SRQ": "south east asian airlines",
    "5G": "skyservice airlines",
    "SSV": "skyservice airlines",
    "FS": "servicios de transportes a",
    "STU": "servicios de transportes a",
    "SD": "sudan airways",
    "SUD": "sudan airways",
    "SV": "saudi arabian airlines",
    "SVA": "saudi arabian airlines",
    "WN": "southwest airlines",
    "SWA": "southwest airlines",
    "A4": "southern winds airlines",
    "SWD": "southern winds airlines",
    "LX": "swiss international air lines",
    "SWR": "swiss international air lines",
    "SWU": "swiss european air lines",
    "WV": "swe fly",
    "SWV": "swe fly",
    "XQ": "sunexpress",
    "SXS": "sunexpress",
    "RB": "syrian arab airlines",
    "SYR": "syrian arab airlines",
    "AL": "skywalk airlines",
    "SYX": "skywalk airlines",
    "SC": "shandong airlines",
    "CDG": "shandong airlines",
    "CNO": "sas braathens",
    "9S": "spring airlines",
    "CQH": "spring airlines",
    "3U": "sichuan airlines",
    "CSC": "sichuan airlines",
    "FM": "shanghai airlines",
    "CSH": "shanghai airlines",
    "ZH": "shenzhen airlines",
    "CSZ": "shenzhen airlines",
    "7L": "sun d'or",
    "ERO": "sun d'or",
    "NE": "skyeurope",
    "ESK": "skyeurope",
    "HSK": "sky europe airlines",
    "JK": "spanair",
    "JKK": "spanair",
    "NK": "spirit airlines",
    "NKS": "spirit airlines",
    "9R": "satena",
    "NSE": "satena",
    "OZW": "skywest airlines",
    "S3": "santa barbara airlines",
    "BBR": "santa barbara airlines",
    "H2": "sky airline",
    "SKU": "sky airline",
    "OO": "skywest",
    "SKW": "skywest",
    "JZ": "skyways express",
    "SKX": "skyways express",
    "BC": "skymark airlines",
    "SKY": "skymark airlines",
    "MI": "silkair",
    "SLK": "silkair",
    "PY": "surinam airways",
    "SLM": "surinam airways",
    "NB": "sterling airlines",
    "SNB": "sterling airlines",
    "6J": "skynet asia airways",
    "SNJ": "skynet asia airways",
    "IE": "solomon airlines",
    "SOL": "solomon airlines",
    "SOU": "southern airways",
    "6W": "saratov aviation division",
    "SOV": "saratov aviation division",
    "HZ": "sat airlines",
    "SOZ": "sat airlines",
    "SPI": "south pacific island airways",
    "S5": "shuttle america",
    "TCF": "shuttle america",
    "DV": "scat air",
    "VSV": "scat air",
    "EQ": "tame",
    "TAE": "tame",
    "JJ": "tam brazilian airlines",
    "TAM": "tam brazilian airlines",
    "TP": "tap portugal",
    "TAP": "tap portugal",
    "TU": "tunisair",
    "TAR": "tunisair",
    "T2": "thai air cargo",
    "TCG": "thai air cargo",
    "FQ": "thomas cook airlines",
    "TCW": "thomas cook airlines",
    "MT": "thomas cook airlines",
    "TCX": "thomas cook airlines",
    "TGN": "trigana air service",
    "TR": "scoot",
    "TGW": "tiger airways",
    "TT": "tigerair australia",
    "TGG": "tigerair australia",
    "TG": "thai airways international",
    "THA": "thai airways international",
    "THK": "turk hava kurumu hava taksi isletmesi",
    "FD": "thai airasia",
    "AIQ": "thai airasia",
    "TK": "turkish airlines",
    "THY": "turkish airlines",
    "TIL": "tajikistan international airlines",
    "T7": "twin jet",
    "TJT": "twin jet",
    "TLA": "translift airways",
    "TMA": "trans mediterranean airlines",
    "3P": "tiara air",
    "TNM": "tiara air",
    "BY": "thomsonfly",
    "TOM": "thomsonfly",
    "PM": "tropic air",
    "TOS": "tropic air",
    "QT": "tampa",
    "TPA": "tampa",
    "GE": "transasia airways",
    "TNA": "transasia airways",
    "HV": "transavia holland",
    "TRA": "transavia holland",
    "VR": "tacv",
    "TCV": "tacv",
    "9T": "transwest air",
    "ABS": "transwest air",
    "UN": "transaero airlines",
    "TSO": "transaero airlines",
    "T5": "turkmenistan airlines",
    "TUA": "turkmenistan airlines",
    "UG": "tuninter",
    "TUI": "tuninter",
    "QS": "travel service",
    "TVS": "travel service",
    "6B": "tuifly nordic",
    "BLX": "tuifly nordic",
    "DT": "taag angola airlines",
    "DTA": "taag angola airlines",
    "HVK": "turkish air force",
    "PZ": "tam mercosur",
    "LAP": "tam mercosur",
    "AX": "trans states airlines",
    "LOF": "trans states airlines",
    "RO": "tarom",
    "ROT": "tarom",
    "3T": "turan air",
    "URN": "turan air",
    "8R": "trip linhas a",
    "TIB": "trip linhas a",
    "U5": "usa3000 airlines",
    "GWY": "usa3000 airlines",
    "UA": "united airlines",
    "UAL": "united airlines",
    "UAC": "united air charters",
    "U6": "ural airlines",
    "SVR": "ural airlines",
    "UF": "um airlines",
    "UKM": "um airlines",
    "US": "us airways",
    "USA": "us airways",
    "USH": "us helicopter",
    "UT": "utair aviation",
    "UTA": "utair aviation",
    "AIO": "united states air force",
    "HY": "uzbekistan airways",
    "UZB": "uzbekistan airways",
    "PS": "ukraine international airlines",
    "AUI": "ukraine international airlines",
    "UH": "us helicopter corporation",
    "VF": "valuair",
    "VLU": "valuair",
    "VFC": "vasco air",
    "VN": "vietnam airlines",
    "HVN": "vietnam airlines",
    "NN": "vim airlines",
    "MOV": "vim airlines",
    "Y4": "volaris",
    "VOI": "volaris",
    "VI": "volga-dnepr airlines",
    "VDA": "volga-dnepr airlines",
    "VX": "virgin america",
    "VRD": "virgin america",
    "TV": "virgin express",
    "VEX": "virgin express",
    "VK": "virgin nigeria airways",
    "VGN": "virgin nigeria airways",
    "VS": "virgin atlantic airways",
    "VIR": "virgin atlantic airways",
    "ZG": "viva macau",
    "VVM": "viva macau",
    "VE": "volare airlines",
    "VLE": "volare airlines",
    "VLG": "vueling airlines",
    "XF": "vladivostok air",
    "VLK": "vladivostok air",
    "LC": "varig log",
    "VLO": "varig log",
    "VA": "virgin australia",
    "VOZ": "virgin australia",
    "RG": "vrg linhas aereas",
    "VRN": "vrg linhas aereas",
    "VP": "vasp",
    "VSP": "vasp",
    "VG": "vlm airlines",
    "VLM": "vlm airlines",
    "7W": "wayraper",
    "WJ": "webjet linhas a",
    "WEB": "webjet linhas a",
    "2W": "welcome air",
    "WLC": "welcome air",
    "8O": "west coast air",
    "WS": "westjet",
    "WJA": "westjet",
    "WAL": "western airlines",
    "WF": "widerøe",
    "WIF": "widerøe",
    "IV": "wind jet",
    "JET": "wind jet",
    "IW": "wings air",
    "WON": "wings air",
    "W6": "wizz air",
    "WZZ": "wizz air",
    "8Z": "wizz air hungary",
    "WVL": "wizz air hungary",
    "WO": "world airways",
    "WOA": "world airways",
    "SE": "xl airways france",
    "SEU": "xl airways france",
    "MF": "xiamen airlines",
    "CXA": "xiamen airlines",
    "YL": "yamal airlines",
    "LLM": "yamal airlines",
    "IY": "yemenia",
    "IYE": "yemenia",
    "UMK": "yuzhmashavia",
    "TAN": "zanair",
    "Z4": "zoom airlines",
    "OOM": "zoom airlines",
    "VJ": "royal air cambodge",
    "6T": "air mandalay",
    "BX": "air busan",
    "ABL": "air busan",
    "XW": "sky express",
    "SXR": "sky express",
    "GH": "globus",
    "GLP": "globus",
    "9Y": "air kazakhstan",
    "KZK": "air kazakhstan",
    "JD": "japan air system",
    "JAS": "japan air system",
    "DS": "easyjet (ds)",
    "2I": "star peru (2i)",
    "KW": "carnival air lines",
    "4H": "united airways",
    "UBD": "united airways",
    "5H": "fly540",
    "FFV": "fly540",
    "TO": "transavia france",
    "TVF": "transavia france",
    "WP": "island air (wp)",
    "MKU": "island air (wp)",
    "B7": "uni air",
    "UIA": "uni air",
    "YD": "gomelavia",
    "WZ": "red wings",
    "RWZ": "red wings",
    "11": "tuifly (x3)",
    "FU": "felix airways",
    "FXX": "felix airways",
    "K1": "kostromskie avialinii",
    "KOQ": "kostromskie avialinii",
    "XX": "greenfly",
    "GFY": "greenfly",
    "7J": "tajik air",
    "TM": "air mozambique",
    "ELK": "elk airways",
    "GY": "gabon airlines",
    "GBK": "gabon airlines",
    "MCA": "mca airlines",
    "ML": "maldivo airlines",
    "MAV": "maldivo airlines",
    "VH": "virgin pacific",
    "VNP": "virgin pacific",
    "Z2": "zest air",
    "HK": "yangon airways",
    "ZE": "eastar jet",
    "ESR": "eastar jet",
    "LJ": "jin air",
    "JNA": "jin air",
    "3O": "air arabia maroc",
    "B1": "baltic air lines",
    "YC": "ciel canadien",
    "YCC": "ciel canadien",
    "CN": "canadian national airways",
    "YCP": "canadian national airways",
    "FA": "epic holiday",
    "AXC": "indochina airlines",
    "3I": "air comet chile",
    "FLB": "german air force - flb",
    "L8": "line blue",
    "LBL": "line blue",
    "LLC": "flylal charters",
    "SZ": "salzburg arrows",
    "TQ": "texas wings",
    "TXW": "texas wings",
    "DH": "dennis sky",
    "DSY": "dennis sky",
    "ZZ": "zz",
    "A1": "atifly",
    "SZB": "aerolineas heredas santa maria",
    "99": "ciao air",
    "JRB": "jc royal.britannica",
    "5P": "pal airlines",
    "C1": "canxpress",
    "V5": "danube wings (v5)",
    "SH": "sharp airlines",
    "SHA": "sharp airlines",
    "C2": "canxplorer",
    "CAP": "canxplorer",
    "QA": "click (mexicana)",
    "W1": "world experience airline",
    "J4": "alak",
    "3E": "air choice one",
    "GCR": "tianjin airlines",
    "KN": "china united",
    "ZQ": "locair",
    "LOC": "locair",
    "4Q": "safi airlines",
    "K5": "seaport airlines",
    "SQH": "seaport airlines",
    "S6": "salmon air",
    "01": "bobb air freight",
    "V9": "star1 airlines",
    "HCW": "star1 airlines",
    "6D": "pelita",
    "J5": "alaska seaplane service",
    "ENJ": "enerjet",
    "I6": "mexicanalink",
    "MXI": "mexicanalink",
    "IP": "island spirit",
    "ISX": "island spirit",
    "T0": "taca peru",
    "OBS": "orbest",
    "SOA": "southern air charter",
    "SVG": "svg air",
    "CEY": "air century",
    "7Q": "pan am world airways dominicana",
    "PF": "primera air",
    "3S": "air antilles express",
    "OLS": "sol lineas aereas",
    "P7": "regional paraguaya",
    "REP": "regional paraguaya",
    "V6": "vip ecuador",
    "NDN": "transportes aereos cielos andinos",
    "P9": "peruvian airlines",
    "EFY": "easyfly",
    "ЯП": "polar airlines",
    "OC": "catovair",
    "ANU": "andalus lineas aereas",
    "DCD": "air 26",
    "MTW": "mauritania airways",
    "CEL": "ceiba intercontinental",
    "7Z": "halcyonair",
    "4P": "business aviation",
    "E9": "compagnie africaine d\\\\'aviation",
    "K8": "zambia skyways",
    "UJ": "almasria universal airlines",
    "LMU": "almasria universal airlines",
    "MSE": "egyptair express",
    "6Y": "smartlynx airlines",
    "EUD": "air italy egypt",
    "K7": "koralblue airlines",
    "KBR": "koralblue airlines",
    "WRC": "wind rose aviation",
    "E4": "elysian airlines",
    "GIE": "elysian airlines",
    "SEN": "sevenair",
    "HT": "hellenic imperial airways",
    "IMP": "hellenic imperial airways",
    "WD": "amsterdam airlines",
    "AAN": "amsterdam airlines",
    "Q9": "arik niger",
    "NAK": "arik niger",
    "DA": "dana air",
    "8F": "stp airways",
    "STP": "stp airways",
    "7Y": "med airways",
    "UQ": "guangxi beibu gulf airlines",
    "SJU": "skyjet airlines",
    "G6": "air volga",
    "TDK": "transavia denmark",
    "RL": "royal falcon",
    "RFJ": "royal falcon",
    "4L": "euroline",
    "MJX": "euroline",
    "TRK": "turkuaz airlines",
    "ZF": "athens airways",
    "VQ": "viking hellas",
    "VKH": "viking hellas",
    "FNA": "norlandair",
    "FVM": "flugfelag vestmannaeyja",
    "DZ": "starline.kz",
    "L7": "lugansk airlines",
    "6P": "gryphon airlines",
    "GP": "gadair european airlines",
    "GDR": "gadair european airlines",
    "SM": "spirit of manila airlines",
    "MNP": "spirit of manila airlines",
    "OQ": "chongqing airlines",
    "CQN": "chongqing airlines",
    "GDC": "grand china air",
    "PN": "west air china",
    "CHB": "west air china",
    "QAX": "qatxpress",
    "1C": "onechina",
    "Y7": "nordstar airlines",
    "JR": "joy air",
    "JOY": "joy air",
    "CD": "air india regional",
    "9H": "mdlr airlines",
    "JGN": "jagson airlines",
    "Q2": "maldivian",
    "XN": "xpressair",
    "VC": "strategic airlines",
    "QFZ": "fars air qeshm",
    "EAA": "eastok avia",
    "JPU": "jupiter airlines",
    "VIS": "vision air international",
    "NA": "al-naser airlines",
    "JH": "fuji dream airlines",
    "KEA": "korea express air",
    "EZA": "eznis airways",
    "PFL": "pacific flier",
    "PSB": "syrian pearl airlines",
    "5E": "sga airlines",
    "F8": "air2there",
    "AO": "avianova (russia)",
    "PA": "parmiss airlines (ipv)",
    "IPV": "parmiss airlines (ipv)",
    "ES": "europesky",
    "EUV": "europesky",
    "GB": "brazil air",
    "BZE": "brazil air",
    "MR": "homer air",
    "OME": "homer air",
    "WQ": "panam world airways",
    "PQW": "panam world airways",
    "YY": "virginwings",
    "VWA": "virginwings",
    "KY": "ksy",
    "KSY": "ksy",
    "BQ": "buquebus líneas aéreas",
    "BQB": "buquebus líneas aéreas",
    "CQ": "sochi air",
    "KOL": "sochi air",
    "WU": "wizz air ukraine",
    "WAU": "wizz air ukraine",
    "47": "88",
    "VVN": "88",
    "LQ": "lcm airlines",
    "LMM": "lcm airlines",
    "K6": "cambodia angkor air (k6)",
    "69": "royal european airlines",
    "AD": "azul",
    "AZU": "azul",
    "PQ": "lsm airlines",
    "LOO": "lsm airlines",
    "PZY": "zapolyarie airlines",
    "C4": "lionxpress",
    "LIX": "lionxpress",
    "GK": "genesis",
    "XZ": "congo express",
    "FZ": "fly dubai",
    "FDB": "fly dubai",
    "D1": "domenican airlines",
    "MDO": "domenican airlines",
    "JY": "aereonautica militare",
    "AXZ": "aereonautica militare",
    "KLS": "kal star aviation",
    "YZ": "lsm airlines ",
    "YZZ": "lsm airlines ",
    "UR": "utair-express",
    "G5": "huaxia",
    "ZP": "zabaykalskii airlines",
    "ZZZ": "zabaykalskii airlines",
    "XBM": "cbm america",
    "M4": "marysya airlines",
    "N1": "n1",
    "4Z": "airlink (saa)",
    "WFX": "westfalia express va",
    "3B": "jobair",
    "BZ": "black stallion airways",
    "BSA": "black stallion airways",
    "GM": "german international air lines",
    "GER": "german international air lines",
    "TB": "trasbrasil",
    "TBZ": "trasbrasil",
    "TH": "transbrasil airlines",
    "THS": "transbrasil airlines",
    "9C": "china sss",
    "IIA": "air indochine",
    "HPY": "happy air",
    "SRB": "solar air",
    "P8": "air mekong",
    "MKG": "air mekong",
    "H3": "harbour air (priv)",
    "HH": "air hamburg (aho)",
    "AHO": "air hamburg (aho)",
    "Z6": "zabaikal airlines",
    "ZTT": "zabaikal airlines",
    "TI": "transholding",
    "THI": "transholding",
    "SZZ": "sur lineas aereas",
    "YT": "yeti airways",
    "Y1": "yellowstone club private shuttle",
    "NS": "caucasus airlines",
    "S1": "serbian airlines",
    "WM": "windward islands airways",
    "YO": "transholding system",
    "TYS": "transholding system",
    "CB": "ccml airlines",
    "CCC": "ccml airlines",
    "ELC": "small planet airlines",
    "F1": "fly brasil",
    "FBL": "fly brasil",
    "1F": "cb airways uk ( interliging flights )",
    "CIF": "cb airways uk ( interliging flights )",
    "3F": "fly colombia ( interliging flights )",
    "T6": "trans pas air",
    "МИ": "kmv",
    "HC": "himalayan airlines",
    "HYM": "himalayan airlines",
    "G1": "indya airline group",
    "WG": "sunwing",
    "TWD": "turkish wings domestic",
    "ZX": "japan regio",
    "ZXY": "japan regio",
    "IXO": "ocean air cargo",
    "N0": "norte lineas aereas",
    "W7": "austral brasil",
    "H9": "pegasus airlines-",
    "QC": "camair-co",
    "RS": "sky regional",
    "II": "lsm international ",
    "UWW": "lsm international ",
    "BU": "baikotovitchestrian airlines ",
    "BUU": "baikotovitchestrian airlines ",
    "L4": "luchsh airlines ",
    "LJJ": "luchsh airlines ",
    "QQQ": "enterair",
    "6U": "air cargo germany",
    "7M": "mongolian international air lines ",
    "ZTF": "mongolian international air lines ",
    "TW": "tway airlines",
    "TWB": "tway airlines",
    "HI": "papillon grand canyon helicopters",
    "JX": "jusur airways",
    "JSR": "jusur airways",
    "XB": "next brasil",
    "NXB": "next brasil",
    "W4": "aeroworld ",
    "WER": "aeroworld ",
    "GN": "gnb linhas aereas",
    "E1": "usa sky cargo",
    "HN": "hankook airline",
    "HNX": "hankook airline",
    "Z7": "redjet",
    "PT": "red jet andes",
    "QY": "red jet canada",
    "0G": "sprintair",
    "SAR": "sprintair",
    "4X": "red jet mexico",
    "Y8": "marusya airways",
    "MRS": "marusya airways",
    "7H": "era alaska",
    "ERR": "era alaska",
    "R8": "airrussia",
    "RRJ": "airrussia",
    "H1": "hankook air us",
    "SMW": "carpatair flight training",
    "H5": "i-fly",
    "RSY": "i-fly",
    "WTJ": "whitejets",
    "KT": "vickjet",
    "VKJ": "vickjet",
    "XV": "bvi airways",
    "HAY": "hamburg airways",
    "SO": "salsa d\\\\'haiti",
    "SLC": "salsa d\\\\'haiti",
    "ZJ": "zambezi airlines (zma)",
    "KND": "kan air",
    "CUD": "air cudlua",
    "YQ": "polet airlines (priv)",
    "AXE": "air explore",
    "12": "12 north",
    "HCC": "holidays czech airlines",
    "COE": "comtel air",
    "MIC": "mint airways",
    "OBT": "orbit airlines",
    "BUR": "air bucharest",
    "LAV": "albastar",
    "L6": "mauritania airlines international",
    "MAI": "mauritania airlines international",
    "6F": "mat airways",
    "MKD": "mat airways",
    "AW": "asian wings airways",
    "AWM": "asian wings airways",
    "E5": "air arabia egypt",
    "RBG": "air arabia egypt",
    "EGS": "eagles airlines",
    "YEP": "yes airways",
    "CT": "alitalia cityliner",
    "DSV": "direct aero services",
    "MDP": "medallion air",
    "OI": "orchid airlines",
    "ORC": "orchid airlines",
    "Y5": "asia wings",
    "AWA": "asia wings",
    "GNN": "georgian international airlines",
    "BTM": "air batumi",
    "XR": "skywest australia",
    "NP": "nile air",
    "NIA": "nile air",
    "FDD": "feeder airlines",
    "DN": "senegal airlines",
    "SGG": "senegal airlines",
    "S9": "starbow airlines",
    "0X": "copenhagen express",
    "8B": "businessair",
    "BCC": "businessair",
    "YR": "senic airlines",
    "XOJ": "xojet",
    "C7": "sky wing pacific",
    "BEU": "bateleur air",
    "PP": "air indus",
    "OAI": "orbit international airlines",
    "OAR": "orbit regional airlines",
    "OAN": "orbit atlantic airways",
    "VOO": "volotea",
    "MM": "peach aviation",
    "HTH": "helitt líneas aéreas",
    "RSD": "russia state transport",
    "MWI": "malaysia wings",
    "U1": "aviabus",
    "ABI": "aviabus",
    "DF": "michael airlines",
    "MJG": "michael airlines",
    "ZC": "korongo airlines",
    "KGO": "korongo airlines",
    "I5": "indonesia sky",
    "IDS": "indonesia sky",
    "B0": "aws express",
    "76": "southjet",
    "SJS": "southjet",
    "77": "southjet connect",
    "ZCS": "southjet connect",
    "78": "southjet cargo",
    "XAN": "southjet cargo",
    "I2": "iberia express",
    "IBS": "iberia express",
    "4O": "interjet (abc aerolineas)",
    "OG": "aironix",
    "NJ": "nordic global airlines",
    "NGB": "nordic global airlines",
    "SCO": "scoot",
    "5K": "hi fly (5k)",
    "WH": "china northwest airlines (wh)",
    "ZN": "zenith international airline",
    "ZNA": "zenith international airline",
    "O1": "orbit airlines azerbaijan",
    "OAB": "orbit airlines azerbaijan",
    "A6": "air alps aviation (a6)",
    "FKA": "flying kangaroo airline",
    "RSJ": "rusjet",
    "VJC": "vietjet air",
    "P4": "patriot airways",
    "V2": "vision airlines (v2)",
    "RBY": "vision airlines (v2)",
    "5Q": "bqb lineas aereas",
    "WAJ": "airasia japan",
    "YE": "yellowtail",
    "YEL": "yellowtail",
    "KG": "royal airways",
    "RAW": "royal airways",
    "FH": "flyhigh airlines ireland (fh)",
    "FHI": "flyhigh airlines ireland (fh)",
    "XSR": "executive airshare",
    "HBH": "hebei airlines",
    "KBZ": "air kbz",
    "2D": "aero vip (2d)",
    "YH": "yangon airways ltd.",
    "TJ": "t.j. air",
    "TJA": "t.j. air",
    "SX": "skywork airlines ",
    "W2": "maastricht airlines",
    "24": "euro jet",
    "UAT": "ukraine atlantic",
    "NMA": "nesma airlines",
    "EHN": "east horizon",
    "MJP": "air majoro",
    "RJD": "rotana jet",
    "Q3": "sochi air chater",
    "QER": "sochi air chater",
    "J7": "denim air ",
    "OD": "malindo air",
    "MXD": "malindo air",
    "HRM": "hermes airlines",
    "Z9": "flightlink tanzania",
    "I8": "izavia",
    "КТК": "катэкавиа",
    "PKV": "псковавиа",
    "M1": "maryland air",
    "7I": "insel air (7i/inc) (priv)",
    "5Z": "vivacolombia",
    "VVC": "vivacolombia",
    "FCM": "flybe finland oy",
    "BGY": "bingo airways",
    "BBG": "bluebird airways (bz)",
    "ZM": "apache air",
    "IWA": "apache air",
    "M2": "mhs aviation gmbh",
    "NR": "jettor airlines",
    "JTO": "jettor airlines",
    "VQI": "flyme (vp)",
    "SL": "thai lion air",
    "TLM": "thai lion air",
    "GMR": "golden myanmar airlines",
    "CNF": "canaryfly",
    "KSZ": "sunrise airways",
    "N8": "national air cargo",
    "NCR": "national air cargo",
    "13": "eastern atlantic virtual airlines",
    "EAV": "eastern atlantic virtual airlines",
    "QG": "citilink indonesia",
    "TTZ": "transair",
    "EVC": "comfort express virtual charters albany",
    "CEO": "comfort express virtual charters",
    "FYJ": "flyjet",
    "S8": "snowbird airlines",
    "SBD": "snowbird airlines",
    "KRY": "russkie krylya",
    "KH": "kharkiv airlines",
    "KHK": "kharkiv airlines",
    "XA": "xair usa",
    "XAU": "xair usa",
    "LB": "air costa",
    "RMK": "simrik airlines",
    "XP": "xpto",
    "XPT": "xpto",
    "DME": "royal flight",
    "EGH": "bbn-airways",
    "TKS": "tomsk-avia",
    "3W": "malawian airlines",
    "NYT": "yeti airlines ",
    "KCU": "skyline ulasim ticaret a.s.",
    "ENY": "envoy air",
    "CCB": "caricom airways (barbados) inc.",
    "RN": "rainbow air (rai)",
    "RAB": "rainbow air (rai)",
    "RY": "rainbow air canada",
    "RAY": "rainbow air canada",
    "RX": "regent airways",
    "RPO": "rainbow air polynesia",
    "RU": "rainbow air euro",
    "RUE": "rainbow air euro",
    "RM": "rainbow air us",
    "RNY": "rainbow air us",
    "TNS": "transilvania",
    "QD": "dobrolet",
    "DOB": "dobrolet",
    "S0": "spike airlines",
    "SAL": "spike airlines",
    "GCA": "grand cru airlines",
    "RLX": "go2sky",
    "L1": "all argentina",
    "A2": "all america",
    "L9": "all asia",
    "9A": "all africa",
    "N4": "regionalia méxico",
    "N9": "all europe",
    "N7": "all spain",
    "9N": "regional air iceland",
    "8K": "voestar",
    "7O": "all colombia",
    "2X": "regionalia uruguay",
    "9X": "regionalia venezuela",
    "9J": "regionalia chile",
    "6C": "vuela cuba",
    "88": "all australia",
    "ER": "fly europa",
    "RWW": "fly europa",
    "PO": "flyportugal",
    "FPT": "flyportugal",
    "MMA": "myanmar airways international",
    "UK": "vistara",
    "VTI": "vistara",
    "CUH": "urumqi air",
    "CBG": "guangxi beibu gulf airlines",
    "2Y": "my indo airlines",
    "MYU": "my indo airlines",
    "FRV": "government of morocco",
    "HKC": "hong kong air cargo",
    "UBG": "us-bangla airlines",
    "NJE": "netjets europe",
    "BTN": "bhutan airlines",
    "IRB": "iran airtour",
    "AOJ": "avcon jet",
    "IDX": "indonesia airasia x",
    "QE": "qatar executive",
    "QQE": "qatar executive",
    "O3": "sf airlines",
    "CSS": "sf airlines",
    "RGE": "regent airways",
    "CXM": "asiacargo express",
}
