# Configurations for production. Configurations defined here will override the
# counterparts in `default.toml`.

# You can manually switch to this environment via:
#
# MERINO_ENV=production /path/to/your/command

[production]
# For `list` or `table` settings, `dynaconf_merge` allows you to merge settings with the default
# settings. This enables merge for the entire `production` environment.
dynaconf_merge = true

[production.accuweather]
url_base = "https://api.accuweather.com"
