# Configurations for production. Configurations defined here will override the
# counterparts in `default.toml`.

# You can manually switch to this environment via:
#
# MERINO_ENV=production /path/to/your/command

[production]
# For `list` or `table` settings, `dynaconf_merge` allows you to merge settings with the default
# settings. This enables merge for the entire `production` environment.
dynaconf_merge = true

[production.accuweather]
url_base = "https://api.accuweather.com"

[production.providers.top_picks]
# MERINO_PROVIDERS__TOP_PICKS__GCS_PROJECT
# GCS project name that contains domain data
gcs_project = "moz-fx-merino-prod-1c2f"

# MERINO_PROVIDERS__TOP_PICKS__GCS_BUCKET
# GCS bucket that contains domain data files
gcs_bucket = "merino-images-prodpy"

# MERINO_PROVIDERS__TOP_PICKS__DOMAIN_DATA_SOURCE
# Enum of either `remote` or `local` that defines whether domain data
# is remotely or locally acquired.
domain_data_source = "local"

[production.curated_recommendations.gcs_engagement]
# MERINO__CURATED_RECOMMENDATIONS__GCS_ENGAGEMENT__BUCKET_NAME
# GCS bucket that contains aggregate engagement data
bucket_name = "merino-airflow-data-prodpy"

# MERINO__CURATED_RECOMMENDATIONS__GCS_ENGAGEMENT__GCP_PROJECT
# GCP project name where the GCS bucket lives.
gcp_project = "moz-fx-merino-prod-1c2f"
