# Configurations for production. Configurations defined here will override the
# counterparts in `default.toml`.

# You can manually switch to this environment via:
#
# MERINO_ENV=production /path/to/your/command

[production]
# For `list` or `table` settings, `dynaconf_merge` allows you to merge settings with the default
# settings. This enables merge for the entire `production` environment.
dynaconf_merge = true

[production.accuweather]
url_base = "https://api.accuweather.com"

# MERINO_PROVIDERS__TOP_PICKS__GCS_PROJECT
# GCS project name that contains domain data
gcs_project = "moz-fx-merino-prod-1c2f"

# MERINO_PROVIDERS__TOP_PICKS__GCS_BUCKET
# GCS bucket that contains domain data files
gcs_bucket = "merino-images-prodpy"
