"""Module containing keywords for stock and ETF tickers."""

from merino.providers.suggest.finance.backends.polygon.etf_ticker_company_mapping import (
    DOW_JONES_POPULAR_3_ETF,
    NASDAQ_POPULAR_3_ETF,
    SP500_POPULAR_3_ETF,
    SP100_POPULAR_3_ETF,
    RUSSELL2000_POPULAR_3_ETF,
    HSI_POPULAR_2_ETF,
    NI225_POPULAR_3_ETF,
)

# Keyword to stock ticker mapping. Each keyword maps to its corresponding stock ticker.
# NOTE: Treat as read-only at runtime.
KEYWORD_TO_STOCK_TICKER_MAPPING = {
    "abbvie stock": "ABBV",
    "adobe stock": "ADBE",
    "advanced micro devices stock": "AMD",
    "alphabet stock": "GOOGL",
    "amazn stock": "AMZN",
    "amazon stock": "AMZN",
    "american airlines stock": "AAL",
    "apple stock": "AAPL",
    "bank of america stock": "BAC",
    "berkshire hathaway stock": "BRK.B",
    "boeing stock": "BA",
    "broadcom stock": "AVGO",
    "chevron stock": "CVX",
    "coca-cola stock": "KO",
    "coinbase stock": "COIN",
    "disney stock": "DIS",
    "eli lilly stock": "LLY",
    "exxonmobil stock": "XOM",
    "home depot stock": "HD",
    "intel stock": "INTC",
    "johnson & johnson stock": "JNJ",
    "jpmorgan chase stock": "JPM",
    "lucid group stock": "LCID",
    "mastercard stock": "MA",
    "mcdonald's stock": "MCD",
    "micron technology stock": "MU",
    "microsoft stock": "MSFT",
    "nasdaq qqq": "QQQ",
    "netflix stock": "NFLX",
    "nvidia stock": "NVDA",
    "palantir technologies stock": "PLTR",
    "paypal stock": "PYPL",
    "pepsico stock": "PEP",
    "pfizer stock": "PFE",
    "plug power stock": "PLUG",
    "procter & gamble stock": "PG",
    "qqq": "QQQ",
    "qqqm": "QQQ",
    "qualcomm stock": "QCOM",
    "roblox stock": "RBLX",
    "salesforce stock": "CRM",
    "sche": "SCHE",
    "sivr": "SIVR",
    "sofi technologies stock": "SOFI",
    "stock abbvie": "ABBV",
    "stock adobe": "ADBE",
    "stock advanced micro devices": "AMD",
    "stock alphabet": "GOOGL",
    "stock amazon": "AMZN",
    "stock american airlines": "AAL",
    "stock apple": "AAPL",
    "stock bank of america": "BAC",
    "stock berkshire hathaway": "BRK.B",
    "stock boeing": "BA",
    "stock broadcom": "AVGO",
    "stock chevron": "CVX",
    "stock coca-cola": "KO",
    "stock coinbase": "COIN",
    "stock costco": "COST",
    "stock disney": "DIS",
    "stock eli lilly": "LLY",
    "stock exxonmobil": "XOM",
    "stock home depot": "HD",
    "stock intel": "INTC",
    "stock johnson & johnson": "JNJ",
    "stock jpmorgan chase": "JPM",
    "stock lucid group": "LCID",
    "stock mastercard": "MA",
    "stock mcdonald's": "MCD",
    "stock micron technology": "MU",
    "stock microsoft": "MSFT",
    "stock netflix": "NFLX",
    "stock nvidia": "NVDA",
    "stock palantir technologies": "PLTR",
    "stock paypal": "PYPL",
    "stock pepsico": "PEP",
    "stock pfizer": "PFE",
    "stock plug power": "PLUG",
    "stock procter & gamble": "PG",
    "stock qualcomm": "QCOM",
    "stock roblox": "RBLX",
    "stock salesforce": "CRM",
    "stock sofi technologies": "SOFI",
    "stock tesla": "TSLA",
    "stock texas instruments": "TXN",
    "stock unitedhealth group": "UNH",
    "stock visa": "V",
    "stock walmart": "WMT",
    "tesla stock": "TSLA",
    "texas instruments stock": "TXN",
    "tqqq": "QQQ",
    "unitedhealth group stock": "UNH",
    "visa stock": "V",
    "vti": "VTI",
    "walmart stock": "WMT",
}

# Keyword to ETF ticker mapping. Each keyword maps to its corresponding ETF ticker.
# NOTE: Treat as read-only at runtime.
KEYWORD_TO_ETF_TICKER_MAPPING = {
    "100 nasdaq": NASDAQ_POPULAR_3_ETF,
    "529 account": NASDAQ_POPULAR_3_ETF,
    "american stock market today": NASDAQ_POPULAR_3_ETF,
    "best stocks to buy now": NASDAQ_POPULAR_3_ETF,
    "cnbc markets": NASDAQ_POPULAR_3_ETF,
    "cnbc premarket": NASDAQ_POPULAR_3_ETF,
    "cnbc us markets": NASDAQ_POPULAR_3_ETF,
    "dji index live": DOW_JONES_POPULAR_3_ETF,
    "djia": DOW_JONES_POPULAR_3_ETF,
    "djia futures": DOW_JONES_POPULAR_3_ETF,
    "djia futures now": DOW_JONES_POPULAR_3_ETF,
    "djia index": DOW_JONES_POPULAR_3_ETF,
    "djia live": DOW_JONES_POPULAR_3_ETF,
    "djia today": DOW_JONES_POPULAR_3_ETF,
    "don jones index": DOW_JONES_POPULAR_3_ETF,
    "dow and jones index": DOW_JONES_POPULAR_3_ETF,
    "dow average today": DOW_JONES_POPULAR_3_ETF,
    "dow futures": DOW_JONES_POPULAR_3_ETF,
    "dow futures now": DOW_JONES_POPULAR_3_ETF,
    "dow graph": DOW_JONES_POPULAR_3_ETF,
    "dow index today": DOW_JONES_POPULAR_3_ETF,
    "dow industrial live": DOW_JONES_POPULAR_3_ETF,
    "dow jones": DOW_JONES_POPULAR_3_ETF,
    "dow jones average": DOW_JONES_POPULAR_3_ETF,
    "dow jones chart": DOW_JONES_POPULAR_3_ETF,
    "dow jones futures": DOW_JONES_POPULAR_3_ETF,
    "dow jones index": DOW_JONES_POPULAR_3_ETF,
    "dow jones index chart": DOW_JONES_POPULAR_3_ETF,
    "dow jones index futures": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial average": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial average chart": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial average futures": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial average index": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial average live": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial average today": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial futures": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial index": DOW_JONES_POPULAR_3_ETF,
    "dow jones industrial live": DOW_JONES_POPULAR_3_ETF,
    "dow jones live": DOW_JONES_POPULAR_3_ETF,
    "dow jones stock markets": DOW_JONES_POPULAR_3_ETF,
    "dow jones stock markets futures": DOW_JONES_POPULAR_3_ETF,
    "dow jones stocks": DOW_JONES_POPULAR_3_ETF,
    "dow jones today": DOW_JONES_POPULAR_3_ETF,
    "dow today": DOW_JONES_POPULAR_3_ETF,
    "dowjones index live": DOW_JONES_POPULAR_3_ETF,
    "etf": NASDAQ_POPULAR_3_ETF,
    "etf s": NASDAQ_POPULAR_3_ETF,
    "etfs": NASDAQ_POPULAR_3_ETF,
    "financial advisor": NASDAQ_POPULAR_3_ETF,
    "futures cnbc": NASDAQ_POPULAR_3_ETF,
    "hkex index": HSI_POPULAR_2_ETF,
    "index nasdaq 100": NASDAQ_POPULAR_3_ETF,
    "index nasdaq composite": NASDAQ_POPULAR_3_ETF,
    "indexnasdaq ixic": NASDAQ_POPULAR_3_ETF,
    "investing": NASDAQ_POPULAR_3_ETF,
    "nasdaq": NASDAQ_POPULAR_3_ETF,
    "nasdaq 100": NASDAQ_POPULAR_3_ETF,
    "nasdaq 100 companies": NASDAQ_POPULAR_3_ETF,
    "nasdaq comp index": NASDAQ_POPULAR_3_ETF,
    "nasdaq compo": NASDAQ_POPULAR_3_ETF,
    "nasdaq composite": NASDAQ_POPULAR_3_ETF,
    "nasdaq composite ixic": NASDAQ_POPULAR_3_ETF,
    "nasdaq composite stock index": NASDAQ_POPULAR_3_ETF,
    "nasdaq futures": NASDAQ_POPULAR_3_ETF,
    "nasdaq index": NASDAQ_POPULAR_3_ETF,
    "nasdaq ixic": NASDAQ_POPULAR_3_ETF,
    "nasdaq market index": NASDAQ_POPULAR_3_ETF,
    "nasdaq ndaq": NASDAQ_POPULAR_3_ETF,
    "nasdaq stock market today": NASDAQ_POPULAR_3_ETF,
    "nasdaq today": NASDAQ_POPULAR_3_ETF,
    "nikkei 225": NI225_POPULAR_3_ETF,
    "ny stock exchange": NASDAQ_POPULAR_3_ETF,
    "premarket": NASDAQ_POPULAR_3_ETF,
    "reddit stocks": ["RDDT"],
    "russell 2000": RUSSELL2000_POPULAR_3_ETF,
    "s and p": SP500_POPULAR_3_ETF,
    "s and p 500": SP500_POPULAR_3_ETF,
    "s and p 500 futures": SP500_POPULAR_3_ETF,
    "s and p 500 index fund": SP500_POPULAR_3_ETF,
    "s and p 500 today": SP500_POPULAR_3_ETF,
    "s and p futures": SP500_POPULAR_3_ETF,
    "s p 100": SP100_POPULAR_3_ETF,
    "s p 500": SP500_POPULAR_3_ETF,
    "s&0 500": SP500_POPULAR_3_ETF,
    "s&5 500": SP500_POPULAR_3_ETF,
    "s&500 index": SP500_POPULAR_3_ETF,
    "s&p": SP500_POPULAR_3_ETF,
    "s&p 100": SP100_POPULAR_3_ETF,
    "s&p 500": SP500_POPULAR_3_ETF,
    "s&p 500 fund": SP500_POPULAR_3_ETF,
    "s&p 500 futures": SP500_POPULAR_3_ETF,
    "s&p 500 index": SP500_POPULAR_3_ETF,
    "s&p 500 index spx": SP500_POPULAR_3_ETF,
    "s&p 500 today": SP500_POPULAR_3_ETF,
    "s&p futures": SP500_POPULAR_3_ETF,
    "s&p stock market today": SP500_POPULAR_3_ETF,
    "s&poors 500": SP500_POPULAR_3_ETF,
    "sand p500": SP500_POPULAR_3_ETF,
    "sandp": SP500_POPULAR_3_ETF,
    "sandp500": SP500_POPULAR_3_ETF,
    "shares": NASDAQ_POPULAR_3_ETF,
    "snp500 futures": SP500_POPULAR_3_ETF,
    "sp 100": SP100_POPULAR_3_ETF,
    "sp 500": SP500_POPULAR_3_ETF,
    "spx": SP500_POPULAR_3_ETF,
    "spx 500 futures": SP500_POPULAR_3_ETF,
    "spx futures": SP500_POPULAR_3_ETF,
    "spx index futures": SP500_POPULAR_3_ETF,
    "spx stock": SP500_POPULAR_3_ETF,
    "standard & poor's 500": SP500_POPULAR_3_ETF,
    "standard & poor's 500 index": SP500_POPULAR_3_ETF,
    "standard and poor's 500 futures": SP500_POPULAR_3_ETF,
    "stock futures": NASDAQ_POPULAR_3_ETF,
    "stock index": NASDAQ_POPULAR_3_ETF,
    "stock indices": NASDAQ_POPULAR_3_ETF,
    "stock market": NASDAQ_POPULAR_3_ETF,
    "stock market futures": NASDAQ_POPULAR_3_ETF,
    "stock market news": NASDAQ_POPULAR_3_ETF,
    "stock market stocks": NASDAQ_POPULAR_3_ETF,
    "stock market today": NASDAQ_POPULAR_3_ETF,
    "stock prices": NASDAQ_POPULAR_3_ETF,
    "stocks": NASDAQ_POPULAR_3_ETF,
    "venture capital": NASDAQ_POPULAR_3_ETF,
    "us stock market": NASDAQ_POPULAR_3_ETF,
    "us stock market today": NASDAQ_POPULAR_3_ETF,
}
