name: Set Up to Run Merino
inputs:
  workspace-path:
    description: "The directory path to store test results"
    required: true
    default: "workspace"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Install uv
      run: pipx install uv
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Create Workspace
      run: mkdir -p ${{ inputs.workspace-path }}
      shell: bash
