"""Utility functions for parsing and validating Particle data."""

import hashlib
import logging
import os
import requests
import sentry_sdk

from enum import StrEnum
from jsonschema import exceptions, validate
from pydantic import Json

from merino.providers.games.particle.backends.errors import (
    ParticleManifestValidationError,
    ParticleRemoteFileProcessError,
)


logger = logging.getLogger(__name__)


class RemoteChannelEnum(StrEnum):
    """Available channels (file sets) from remote Particle manifest JSON."""

    # the puzzle's runtime files
    RUNTIME = "runtime"
    # the daily puzzle files
    PUZZLE = "daily"


class GameFile:
    """Represents a particle game file to be processed - downloaded, SHA verified, and uploaded to GCS."""

    # the name of the file, e.g. style.css - pulled from remote_url
    name: str
    # the content-type of the file
    content_type: str
    # the name of the file when staged in GCS
    gcs_staging_name: str
    # the local filesystem location of the file after it was downloaded
    local_path: str
    # set to True only after the file has been uploaded to GCS
    uploaded: bool = False
    # the remote path to the file, e.g. https://url.com/daily_files/ - pulled from remote_url
    remote_path: str
    # the full remote url to the file, e.g. https://url.com/daily_files/style.css
    remote_url: str

    # SHA generated by compute_sha below - performed after downloading the file
    sha_computed: str
    # pre-computed SHA provided by the manifest - we will match our own SHA against this value
    sha_target: str
    # set to True only after verifying SHA from downloaded file matches sha_target
    sha_verified: bool = False

    def __init__(self, url: str, sha: str, content_type: str):
        """Initialize the instance by splitting up the remote file path into
        path and file name
        """
        self.content_type = content_type
        self.remote_url = url
        self.sha_target = sha
        # get just the file name for the remote file. we store the file in
        # GCS under the same name.
        self.name = os.path.basename(self.remote_url)
        # note - dirname strips the trailing "/"
        self.remote_path = os.path.dirname(self.remote_url)

    @staticmethod
    def compute_sha(local_path) -> str:  # pragma: no cover
        """Get the SHA256 value of the given file."""
        try:
            with open(local_path, "rb", buffering=0) as file:
                return hashlib.file_digest(file, "sha256").hexdigest()
        except Exception as ex:
            sentry_sdk.capture_exception(ParticleRemoteFileProcessError(str(ex)))
            return ""


def validate_manifest_schema_version(manifest_json: Json, manifest_schema_version: int) -> None:
    """Validate schema version exists in the JSON and is of the expected value."""
    try:
        schema_version = manifest_json["schemaVersion"]
    except KeyError:
        logger.error("JSON key error retrieving 'schemaVersion' from manifest JSON.")
        schema_version = None
    except Exception:
        logger.error("JSON error retrieving 'schemaVersion' from manifest JSON.")
        schema_version = None

    if schema_version != manifest_schema_version:
        error_msg = f"Error validating Particle manifest schema version. Received {schema_version}, expected {manifest_schema_version}."

        logger.error(error_msg)

        ex = ParticleManifestValidationError(error_msg)

        raise ex


def validate_manifest_against_schema(manifest_json: Json, manifest_schema: Json) -> None:
    """Validate the returned manifest JSON conforms to the expected schema."""
    try:
        # if this fails, it should raise a ValidationError
        validate(instance=manifest_json, schema=manifest_schema)
    except exceptions.ValidationError as ex:
        logger.error(f"Schema validation failed for manifest JSON: {ex}")

        raise ParticleManifestValidationError(str(ex)) from ex


def remote_manifest_channel_is_updated(
    manifest_remote: Json, manifest_gcs: Json | None, channel: RemoteChannelEnum
) -> bool:
    """Determine if the JSON manifest from Particle has newer files for the given channel than the manifest we have stored in GCS."""
    # if there is no manifest in GCS (cold start), channel needs to be updated
    if manifest_gcs is None:
        return True

    remote = manifest_remote["channels"][channel]["version"]
    gcs = manifest_gcs["channels"][channel]["version"]

    return bool(remote != gcs)


def get_remote_files_and_shas_for_channel(
    manifest_remote: Json, channel: RemoteChannelEnum
) -> list[GameFile]:
    """Get a list of all files associated with the given channel from the remote manifest."""
    game_files = []

    try:
        files = manifest_remote["channels"][channel]["files"]
    except KeyError as ex:
        files = []

        sentry_sdk.capture_exception(ParticleManifestValidationError(str(ex)))

    for file in files:
        game_files.append(
            GameFile(url=file["url"], sha=file["sha256"], content_type=file["contentType"])
        )

    return game_files


def download_remote_file(url: str, destination_path: str) -> None:
    """Download a remote Particle file."""
    response = requests.get(url)  # nosec

    response.raise_for_status()

    with open(destination_path, "wb") as f:
        f.write(response.content)
