apiVersion: apps/v1
kind: Deployment
metadata:
  name: merino-deployment
spec:
  template:
    spec:
      containers:
        - name: merino
          imagePullPolicy: Never
        - name: ohttp-gateway
          imagePullPolicy: Never
