name: build-gar-image-fleece

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          filter: blob:none
      - uses: ./.github/actions/build-project-image
        with:
          project: fleece
          image: app-fleece:build
          artifact-name: merino-fleece
