name: build-dockerhub-locust-image

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
    secrets:
      DOCKERHUB_MERINO_LOCUST_REPO:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build locust image
        run: docker build -t merino-locust -f ./tests/load/Dockerfile .
      - name: Tag image
        run: docker tag merino-locust ${{ secrets.DOCKERHUB_MERINO_LOCUST_REPO }}:${{ inputs.image_tag }}
      - name: Save image
        run: docker save ${{ secrets.DOCKERHUB_MERINO_LOCUST_REPO }}:${{ inputs.image_tag }} | gzip > merino-locust.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: merino-locust-image
          path: merino-locust.tar.gz
