name: build-gar-image-locust

on:
  workflow_call:

jobs:
  build-locust:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          filter: blob:none
      - uses: ./.github/actions/build-project-image
        with:
          project: load-tests
          image: merino-locust:build
          artifact-name: locust-image
