name: build-dockerhub-app-image

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
    secrets:
      DOCKERHUB_REPO:
        required: true

jobs:
  build:
    environment: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Merino app image
        run: make docker-build
      - name: Tag image for Docker Hub
        run: docker tag app:build ${{ secrets.DOCKERHUB_REPO }}:${{ inputs.image_tag }}
      - name: Save image artifact
        run: docker save ${{ secrets.DOCKERHUB_REPO }}:${{ inputs.image_tag }} | gzip > merino-app.tar.gz
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: merino-app-image
          path: merino-app.tar.gz
