name: build-docker-image

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
    secrets:
      DOCKER_IMAGE_PATH:
        required: true

jobs:
  build:
    environment: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get info
        run: |
          uname -v
          docker info
      - name: Create version.json
        run: |
          printf '{"commit":"%s","version":"%s","source":"%s","build":"%s"}\n' \
          "$GITHUB_SHA" \
          "$GITHUB_REF_NAME" \
          "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
          "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" > version.json
      - name: Output version.json
        run: cat version.json
      - name: Build docker image
        run: make docker-build
      - name: Save app:build image
        run: docker save app:build | gzip > image.tar.gz
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: merino
          path: image.tar.gz
