name: build-gar-image-locust

on:
  workflow_call:

jobs:
  build-locust:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Build Locust Docker image
        run: docker build -t merino-locust:build -f ./tests/load/Dockerfile .
      - name: Save image
        run: docker save merino-locust:build | gzip > locust-image.tar.gz
      - name: Upload image artifact
        uses: actions/upload-artifact@v6
        with:
          name: locust-image
          path: locust-image.tar.gz
