name: checks

on:
  workflow_call:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Lint GitHub Actions workflows
        uses: docker://rhysd/actionlint:1.7.12
        with:
          args: -color
      - name: Set up to run
        uses: ./.github/actions/weave
      - name: Run Code Linting
        run: make -k lint
