name: pr-workflow

on: pull_request

permissions:
  contents: read

jobs:
  detect-images:
    uses: ./.github/workflows/detect-image-changes.yaml
  run-checks:
    uses: ./.github/workflows/checks.yaml
  run-tests:
    uses: ./.github/workflows/tests.yaml
  run-docs-build:
    uses: ./.github/workflows/docs-build.yaml
  run-build-gar-image:
    needs: detect-images
    if: needs.detect-images.outputs.merino == 'true'
    uses: ./.github/workflows/build-gar-image.yaml
  run-build-gar-image-fleece:
    needs: detect-images
    if: needs.detect-images.outputs.fleece == 'true'
    uses: ./.github/workflows/build-gar-image-fleece.yaml
  run-build-gar-image-locust:
    needs: detect-images
    if: needs.detect-images.outputs.load_tests == 'true'
    uses: ./.github/workflows/build-gar-image-locust.yaml
