name: publish-dockerhub-locust-image

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
    secrets:
      DOCKERHUB_MERINO_LOCUST_REPO:
        required: true
      DOCKER_USER:
        required: true
      DOCKERHUB_ACCESS_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for [load test skip]
        run: |
          msg=$(git log -1 --pretty=%B)
          echo "Commit message: $msg"
          if echo "$msg" | grep -qi '\[load test: skip\]'; then
            echo "Skipping locust image publish"
            exit 0
          fi
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: merino-locust-image
          path: .
      - name: Load image
        run: gunzip -c merino-locust.tar.gz | docker load
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Tag and push
        run: |
          # Tag loaded image as 'latest'
          docker tag ${{ secrets.DOCKERHUB_MERINO_LOCUST_REPO }}:${{ inputs.image_tag }} ${{ secrets.DOCKERHUB_MERINO_LOCUST_REPO }}:latest

          # Push both tags
          docker push ${{ secrets.DOCKERHUB_MERINO_LOCUST_REPO }}:${{ inputs.image_tag }}
          docker push ${{ secrets.DOCKERHUB_MERINO_LOCUST_REPO }}:latest
