"""Mapping of source files to their test files (both direct and indirect).

This module provides a comprehensive mapping between source files in merino/
and their corresponding test files in tests/unit/ and tests/integration/.

Test Types:
- Direct tests: Test files that directly correspond to the source file by path
  (e.g., merino/middleware/logging.py -> tests/unit/middleware/test_logging.py)
- Indirect tests: Test files that import and use the source module but aren't
  direct path matches (e.g., API integration tests that use providers)

Generated by LLM, verified and modified by Merino devs.
"""

# Mapping from source to direct and indirect test file paths.
SOURCE_TEST_MAPPING_DETAILED: dict[str, dict[str, list[str]]] = {
    "merino/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/cache/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/cache/none.py": {
        "direct": [],
        "indirect": ["tests/unit/providers/suggest/flightaware/backend/test_flightaware.py"],
    },
    "merino/cache/protocol.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/cache/redis.py": {
        "direct": ["tests/unit/utils/test_cache_redis.py"],
        "indirect": [
            "tests/integration/providers/suggest/finance/backends/test_polygon.py",
            "tests/integration/providers/suggest/weather/backends/test_accuweather.py",
            "tests/integration/providers/suggest/yelp/backends/test_yelp.py",
            "tests/unit/providers/suggest/finance/backends/test_polygon.py",
            "tests/unit/providers/suggest/weather/backends/test_accuweather.py",
            "tests/unit/providers/suggest/yelp/backends/test_yelp.py",
        ],
    },
    "merino/configs/__init__.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_engagement.py",
            "tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_prior.py",
            "tests/integration/api/v1/curated_recommendations/ml_backends/test_gcs_local_model.py",
            "tests/integration/api/v1/curated_recommendations/ml_backends/test_gcs_ml_contextual.py",
            "tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py",
            "tests/integration/api/v1/suggest/test_suggest.py",
            "tests/integration/api/v1/suggest/test_suggest_flightaware.py",
            "tests/integration/api/v1/suggest/test_suggest_top_picks.py",
            "tests/integration/api/v1/suggest/test_suggest_weather.py",
            "tests/integration/api/v1/suggest/test_suggest_wikipedia.py",
            "tests/integration/providers/suggest/adm/backends/test_remotesettings_icon.py",
            "tests/integration/providers/suggest/finance/backends/test_polygon.py",
            "tests/integration/providers/suggest/sports/backends/test_sportsdata.py",
            "tests/integration/test_setup.py",
            "tests/unit/jobs/sports/test_sportsdata.py",
            "tests/unit/providers/suggest/finance/backends/test_polygon.py",
            "tests/unit/providers/suggest/flightaware/backend/test_flightaware.py",
            "tests/unit/providers/suggest/sports/backends/common/test_data.py",
            "tests/unit/providers/suggest/sports/backends/common/test_elastic.py",
            "tests/unit/providers/suggest/sports/backends/common/test_sports.py",
            "tests/unit/providers/suggest/sports/backends/test_sports_backend.py",
            "tests/unit/providers/suggest/test_init_providers.py",
            "tests/unit/providers/suggest/top_picks/backends/test_filemanager.py",
            "tests/unit/providers/suggest/top_picks/backends/test_top_picks.py",
            "tests/unit/providers/suggest/top_picks/test_provider.py",
            "tests/unit/providers/suggest/weather/test_provider.py",
            "tests/unit/providers/suggest/wikipedia/backends/test_elastic.py",
            "tests/unit/providers/suggest/wikipedia/test_provider.py",
            "tests/unit/providers/suggest/yelp/backends/test_yelp.py",
            "tests/unit/test_config_logging.py",
            "tests/unit/utils/test_icon_processor.py",
        ],
    },
    "merino/configs/app_configs/config_logging.py": {
        "direct": ["tests/unit/test_config_logging.py"],
        "indirect": [],
    },
    "merino/configs/app_configs/config_sentry.py": {
        "direct": ["tests/unit/test_config_sentry.py"],
        "indirect": [],
    },
    "merino/curated_recommendations/__init__.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/corpus_backends/test_sections_backend.py",
            "tests/integration/api/v1/curated_recommendations/ml_backends/test_gcs_local_model.py",
            "tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py",
            "tests/unit/curated_recommendations/test_rankers.py",
        ],
    },
    "merino/curated_recommendations/article_balancer.py": {
        "direct": [],
        "indirect": ["tests/unit/curated_recommendations/test_rankers.py"],
    },
    "merino/curated_recommendations/corpus_backends/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/curated_recommendations/corpus_backends/caching.py": {
        "direct": ["tests/unit/curated_recommendations/corpus_backends/test_caching.py"],
        "indirect": [],
    },
    "merino/curated_recommendations/corpus_backends/protocol.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/corpus_backends/test_scheduled_surface_backend.py",
            "tests/integration/api/v1/curated_recommendations/corpus_backends/test_sections_backend.py",
            "tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py",
            "tests/unit/curated_recommendations/corpus_backends/test_scheduled_corpus_backend.py",
            "tests/unit/curated_recommendations/corpus_backends/test_utils.py",
            "tests/unit/curated_recommendations/ml_backends/test_static_local_model.py",
            "tests/unit/curated_recommendations/test_localization.py",
            "tests/unit/curated_recommendations/test_provider.py",
            "tests/unit/curated_recommendations/test_rankers.py",
            "tests/unit/curated_recommendations/test_sections.py",
            "tests/unit/curated_recommendations/test_utils.py",
            "tests/unit/prior_backends/test_engagement_rescaler.py",
        ],
    },
    "merino/curated_recommendations/corpus_backends/scheduled_surface_backend.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/corpus_backends/test_scheduled_surface_backend.py",
            "tests/unit/curated_recommendations/corpus_backends/test_scheduled_corpus_backend.py",
        ],
    },
    "merino/curated_recommendations/corpus_backends/sections_backend.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/curated_recommendations/corpus_backends/utils.py": {
        "direct": ["tests/unit/curated_recommendations/corpus_backends/test_utils.py"],
        "indirect": [],
    },
    "merino/curated_recommendations/engagement_backends/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/curated_recommendations/engagement_backends/fake_engagement.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/curated_recommendations/engagement_backends/gcs_engagement.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_engagement.py"
        ],
    },
    "merino/curated_recommendations/engagement_backends/protocol.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_engagement.py",
            "tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py",
            "tests/unit/curated_recommendations/test_rankers.py",
            "tests/unit/curated_recommendations/test_sections.py",
        ],
    },
    "merino/curated_recommendations/interest_picker.py": {
        "direct": ["tests/unit/curated_recommendations/test_interest_picker.py"],
        "indirect": [],
    },
    "merino/curated_recommendations/layouts.py": {
        "direct": [],
        "indirect": [
            "tests/unit/curated_recommendations/legacy/test_sections_adapter.py",
            "tests/unit/curated_recommendations/test_interest_picker.py",
            "tests/unit/curated_recommendations/test_rankers.py",
            "tests/unit/curated_recommendations/test_sections.py",
        ],
    },
    "merino/curated_recommendations/legacy/protocol.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/curated_recommendations/legacy/provider.py": {
        "direct": ["tests/unit/curated_recommendations/legacy/test_provider.py"],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py"
        ],
    },
    "merino/curated_recommendations/legacy/sections_adapter.py": {
        "direct": ["tests/unit/curated_recommendations/legacy/test_sections_adapter.py"],
        "indirect": [],
    },
    "merino/curated_recommendations/localization.py": {
        "direct": ["tests/unit/curated_recommendations/test_localization.py"],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py"
        ],
    },
    "merino/curated_recommendations/ml_backends/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/curated_recommendations/ml_backends/empty_ml_recs.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/curated_recommendations/ml_backends/gcs_local_model.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/curated_recommendations/ml_backends/gcs_ml_recs.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/ml_backends/test_gcs_ml_contextual.py"
        ],
    },
    "merino/curated_recommendations/ml_backends/protocol.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/ml_backends/test_gcs_local_model.py",
            "tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py",
            "tests/unit/curated_recommendations/ml_backends/test_static_local_model.py",
        ],
    },
    "merino/curated_recommendations/ml_backends/static_local_model.py": {
        "direct": ["tests/unit/curated_recommendations/ml_backends/test_static_local_model.py"],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py"
        ],
    },
    "merino/curated_recommendations/prior_backends/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/curated_recommendations/prior_backends/constant_prior.py": {
        "direct": [],
        "indirect": ["tests/unit/curated_recommendations/test_sections.py"],
    },
    "merino/curated_recommendations/prior_backends/engagment_rescaler.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py",
            "tests/unit/curated_recommendations/test_rankers.py",
            "tests/unit/curated_recommendations/test_sections.py",
            "tests/unit/prior_backends/test_engagement_rescaler.py",
        ],
    },
    "merino/curated_recommendations/prior_backends/gcs_prior.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_prior.py"
        ],
    },
    "merino/curated_recommendations/prior_backends/protocol.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_prior.py",
            "tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py",
            "tests/unit/curated_recommendations/test_rankers.py",
        ],
    },
    "merino/curated_recommendations/protocol.py": {
        "direct": ["tests/unit/curated_recommendations/test_protocol.py"],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py",
            "tests/unit/curated_recommendations/legacy/test_sections_adapter.py",
            "tests/unit/curated_recommendations/ml_backends/test_static_local_model.py",
            "tests/unit/curated_recommendations/test_interest_picker.py",
            "tests/unit/curated_recommendations/test_provider.py",
            "tests/unit/curated_recommendations/test_rankers.py",
            "tests/unit/curated_recommendations/test_sections.py",
            "tests/unit/curated_recommendations/test_utils.py",
            "tests/unit/prior_backends/test_engagement_rescaler.py",
        ],
    },
    "merino/curated_recommendations/provider.py": {
        "direct": ["tests/unit/curated_recommendations/test_provider.py"],
        "indirect": ["tests/unit/curated_recommendations/ml_backends/test_static_local_model.py"],
    },
    "merino/curated_recommendations/rankers/__init__.py": {
        "direct": [],
        "indirect": [
            "tests/unit/curated_recommendations/test_rankers.py",
            "tests/unit/curated_recommendations/test_sections.py",
        ],
    },
    "merino/curated_recommendations/rankers/contextual_ranker.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/curated_recommendations/rankers/ranker.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/curated_recommendations/rankers/t_sampling.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/curated_recommendations/rankers/utils.py": {
        "direct": [],
        "indirect": ["tests/unit/curated_recommendations/test_rankers.py"],
    },
    "merino/curated_recommendations/sections.py": {
        "direct": ["tests/unit/curated_recommendations/test_sections.py"],
        "indirect": [],
    },
    "merino/curated_recommendations/utils.py": {
        "direct": ["tests/unit/curated_recommendations/test_utils.py"],
        "indirect": [],
    },
    "merino/exceptions.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_weather.py",
            "tests/integration/providers/suggest/finance/backends/test_polygon.py",
            "tests/integration/providers/suggest/weather/backends/test_accuweather.py",
            "tests/integration/providers/suggest/yelp/backends/test_yelp.py",
            "tests/integration/test_setup.py",
            "tests/unit/providers/suggest/adm/backends/test_remotesettings.py",
            "tests/unit/providers/suggest/flightaware/backend/test_cache.py",
            "tests/unit/providers/suggest/flightaware/backend/test_errors.py",
            "tests/unit/providers/suggest/sports/backends/common/test_elastic.py",
            "tests/unit/providers/suggest/test_init_providers.py",
            "tests/unit/providers/suggest/top_picks/test_provider.py",
            "tests/unit/providers/suggest/weather/backends/test_accuweather.py",
            "tests/unit/providers/suggest/wikipedia/backends/test_elastic.py",
            "tests/unit/providers/suggest/wikipedia/test_provider.py",
        ],
    },
    "merino/governance/__init__.py": {
        "direct": ["tests/unit/governance/test_service_governing.py"],
        "indirect": [],
    },
    "merino/governance/circuitbreakers.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_flightaware.py",
            "tests/integration/api/v1/suggest/test_suggest_weather.py",
        ],
    },
    "merino/jobs/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/amo_rs_uploader/__init__.py": {
        "direct": [],
        "indirect": ["tests/unit/jobs/amo_rs_uploader/test_amo_rs_uploader.py"],
    },
    "merino/jobs/cli.py": {
        "direct": ["tests/integration/jobs/test_cli.py"],
        "indirect": [],
    },
    "merino/jobs/csv_rs_uploader/__init__.py": {
        "direct": [],
        "indirect": [
            "tests/unit/jobs/csv_rs_uploader/test_csv_rs_uploader.py",
            "tests/unit/jobs/csv_rs_uploader/test_fakespot.py",
            "tests/unit/jobs/csv_rs_uploader/test_mdn.py",
            "tests/unit/jobs/csv_rs_uploader/test_pocket.py",
            "tests/unit/jobs/relevancy_uploader/test_relevancy_csv_uploader.py",
            "tests/unit/jobs/utils/test_chunked_rs_uploader.py",
        ],
    },
    "merino/jobs/csv_rs_uploader/base.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/csv_rs_uploader/chunked_rs_uploader.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/csv_rs_uploader/fakespot.py": {
        "direct": ["tests/unit/jobs/csv_rs_uploader/test_fakespot.py"],
        "indirect": [],
    },
    "merino/jobs/csv_rs_uploader/mdn.py": {
        "direct": ["tests/unit/jobs/csv_rs_uploader/test_mdn.py"],
        "indirect": [],
    },
    "merino/jobs/csv_rs_uploader/pocket.py": {
        "direct": ["tests/unit/jobs/csv_rs_uploader/test_pocket.py"],
        "indirect": [],
    },
    "merino/jobs/csv_rs_uploader/row_major_base.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/csv_rs_uploader/yelp.py": {
        "direct": ["tests/unit/jobs/csv_rs_uploader/test_yelp.py"],
        "indirect": [],
    },
    "merino/jobs/flightaware/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/flightaware/fetch_schedules.py": {
        "direct": [
            "tests/integration/jobs/flightaware/test_fetch_schedules.py",
            "tests/unit/jobs/flightaware/test_fetch_schedules.py",
        ],
        "indirect": [],
    },
    "merino/jobs/geonames_uploader/__init__.py": {
        "direct": [],
        "indirect": ["tests/unit/jobs/geonames_uploader/test_upload.py"],
    },
    "merino/jobs/geonames_uploader/alternates.py": {
        "direct": [],
        "indirect": [
            "tests/unit/jobs/geonames_uploader/test_upload.py",
            "tests/unit/jobs/geonames_uploader/test_upload_alternates.py",
        ],
    },
    "merino/jobs/geonames_uploader/downloader.py": {
        "direct": ["tests/unit/jobs/geonames_uploader/test_downloader.py"],
        "indirect": ["tests/unit/jobs/geonames_uploader/test_upload_alternates.py"],
    },
    "merino/jobs/geonames_uploader/geonames.py": {
        "direct": [],
        "indirect": [
            "tests/unit/jobs/geonames_uploader/test_upload.py",
            "tests/unit/jobs/geonames_uploader/test_upload_alternates.py",
            "tests/unit/jobs/geonames_uploader/test_upload_geonames.py",
        ],
    },
    "merino/jobs/geonames_uploader/tempzipfile.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/navigational_suggestions/__init__.py": {
        "direct": [
            "tests/integration/jobs/navigational_suggestions/test_init.py",
            "tests/unit/jobs/navigational_suggestions/test_init.py",
        ],
        "indirect": ["tests/unit/jobs/navigational_suggestions/test_navigational_suggestions.py"],
    },
    "merino/jobs/navigational_suggestions/constants.py": {
        "direct": [],
        "indirect": [
            "tests/unit/jobs/navigational_suggestions/test_navigational_suggestions_utils.py"
        ],
    },
    "merino/jobs/navigational_suggestions/enrichments/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/navigational_suggestions/enrichments/custom_domains.py": {
        "direct": [],
        "indirect": ["tests/integration/jobs/navigational_suggestions/test_local_mode.py"],
    },
    "merino/jobs/navigational_suggestions/enrichments/custom_favicons.py": {
        "direct": [],
        "indirect": ["tests/unit/jobs/navigational_suggestions/test_custom_favicons.py"],
    },
    "merino/jobs/navigational_suggestions/enrichments/partner_favicons.py": {
        "direct": [],
        "indirect": ["tests/unit/jobs/navigational_suggestions/test_init.py"],
    },
    "merino/jobs/navigational_suggestions/favicon/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/navigational_suggestions/favicon/favicon_extractor.py": {
        "direct": [],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_domain_processing_integration.py",
            "tests/integration/jobs/navigational_suggestions/test_favicon_pipeline_integration.py",
            "tests/unit/jobs/navigational_suggestions/test_favicon_extractor.py",
        ],
    },
    "merino/jobs/navigational_suggestions/favicon/favicon_processor.py": {
        "direct": [],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_domain_processing_integration.py",
            "tests/integration/jobs/navigational_suggestions/test_favicon_pipeline_integration.py",
            "tests/unit/jobs/navigational_suggestions/test_favicon_processor.py",
        ],
    },
    "merino/jobs/navigational_suggestions/favicon/favicon_selector.py": {
        "direct": [],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_favicon_pipeline_integration.py",
            "tests/unit/jobs/navigational_suggestions/test_favicon_selector.py",
        ],
    },
    "merino/jobs/navigational_suggestions/io/__init__.py": {
        "direct": [],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_init.py",
            "tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader.py",
            "tests/unit/jobs/navigational_suggestions/test_favicon_processor.py",
            "tests/unit/jobs/navigational_suggestions/test_navigational_suggestions_utils.py",
        ],
    },
    "merino/jobs/navigational_suggestions/io/async_favicon_downloader.py": {
        "direct": [],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_async_favicon_integration.py",
            "tests/integration/jobs/navigational_suggestions/test_domain_processing_integration.py",
            "tests/integration/jobs/navigational_suggestions/test_favicon_pipeline_integration.py",
        ],
    },
    "merino/jobs/navigational_suggestions/io/domain_data_downloader.py": {
        "direct": [],
        "indirect": ["tests/unit/jobs/navigational_suggestions/test_domain_data_downloader.py"],
    },
    "merino/jobs/navigational_suggestions/io/domain_metadata_diff.py": {
        "direct": [],
        "indirect": ["tests/unit/jobs/navigational_suggestions/test_domain_metadata_diff.py"],
    },
    "merino/jobs/navigational_suggestions/io/domain_metadata_uploader.py": {
        "direct": [],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_async_favicon_integration.py",
            "tests/integration/jobs/navigational_suggestions/test_domain_metadata_uploader.py",
            "tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader.py",
            "tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader_error.py",
        ],
    },
    "merino/jobs/navigational_suggestions/models.py": {
        "direct": [],
        "indirect": [
            "tests/unit/jobs/navigational_suggestions/test_favicon_extractor.py",
            "tests/unit/jobs/navigational_suggestions/test_favicon_scraper.py",
        ],
    },
    "merino/jobs/navigational_suggestions/modes/__init__.py": {
        "direct": [],
        "indirect": ["tests/integration/jobs/navigational_suggestions/test_init.py"],
    },
    "merino/jobs/navigational_suggestions/modes/local_mode_helpers.py": {
        "direct": [],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_local_mode.py",
            "tests/unit/jobs/navigational_suggestions/test_local_mode.py",
        ],
    },
    "merino/jobs/navigational_suggestions/modes/local_mode_runner.py": {
        "direct": [],
        "indirect": [
            "tests/unit/jobs/navigational_suggestions/test_init.py",
            "tests/unit/jobs/navigational_suggestions/test_local_mode_runner.py",
        ],
    },
    "merino/jobs/navigational_suggestions/modes/normal_mode.py": {
        "direct": [],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_init.py",
            "tests/unit/jobs/navigational_suggestions/test_init.py",
            "tests/unit/jobs/navigational_suggestions/test_navigational_suggestions.py",
        ],
    },
    "merino/jobs/navigational_suggestions/processing/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/navigational_suggestions/processing/domain_processor.py": {
        "direct": [],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_domain_processing_integration.py",
            "tests/unit/jobs/navigational_suggestions/test_domain_processor.py",
        ],
    },
    "merino/jobs/navigational_suggestions/processing/manifest_builder.py": {
        "direct": [],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_init.py",
            "tests/unit/jobs/navigational_suggestions/test_get_serp_categories.py",
            "tests/unit/jobs/navigational_suggestions/test_init.py",
            "tests/unit/jobs/navigational_suggestions/test_navigational_suggestions.py",
        ],
    },
    "merino/jobs/navigational_suggestions/scrapers/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/navigational_suggestions/scrapers/favicon_scraper.py": {
        "direct": [],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_domain_processing_integration.py",
            "tests/integration/jobs/navigational_suggestions/test_favicon_pipeline_integration.py",
            "tests/unit/jobs/navigational_suggestions/test_favicon_extractor.py",
            "tests/unit/jobs/navigational_suggestions/test_favicon_scraper.py",
        ],
    },
    "merino/jobs/navigational_suggestions/scrapers/web_scraper.py": {
        "direct": [],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_domain_processing_integration.py",
            "tests/integration/jobs/navigational_suggestions/test_web_scraping_integration.py",
            "tests/unit/jobs/navigational_suggestions/test_web_scraper.py",
        ],
    },
    "merino/jobs/navigational_suggestions/utils.py": {
        "direct": [],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_domain_processing_integration.py",
            "tests/integration/jobs/navigational_suggestions/test_web_scraping_integration.py",
            "tests/unit/jobs/navigational_suggestions/test_url_utils.py",
            "tests/unit/jobs/navigational_suggestions/test_validators.py",
        ],
    },
    "merino/jobs/navigational_suggestions/validators.py": {
        "direct": ["tests/unit/jobs/navigational_suggestions/test_validators.py"],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_domain_processing_integration.py",
            "tests/integration/jobs/navigational_suggestions/test_web_scraping_integration.py",
        ],
    },
    "merino/jobs/polygon/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/polygon/polygon_ingestion.py": {
        "direct": ["tests/integration/jobs/polygon/test_polygon_ingestion.py"],
        "indirect": [],
    },
    "merino/jobs/relevancy_uploader/__init__.py": {
        "direct": [],
        "indirect": ["tests/unit/jobs/relevancy_uploader/test_chunked_relevancy_rs_uploader.py"],
    },
    "merino/jobs/relevancy_uploader/chunked_rs_uploader.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/sportsdata_jobs/__init__.py": {
        "direct": [],
        "indirect": ["tests/unit/jobs/sports/test_sportsdata.py"],
    },
    "merino/jobs/utils/__init__.py": {
        "direct": [],
        "indirect": ["tests/unit/jobs/utils/test_utils.py"],
    },
    "merino/jobs/utils/chunked_rs_uploader.py": {
        "direct": ["tests/unit/jobs/utils/test_chunked_rs_uploader.py"],
        "indirect": [],
    },
    "merino/jobs/utils/domain_tester.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/utils/rs_client.py": {
        "direct": ["tests/unit/jobs/utils/test_rs_client.py"],
        "indirect": [
            "tests/unit/jobs/geonames_uploader/test_upload_alternates.py",
            "tests/unit/jobs/geonames_uploader/test_upload_geonames.py",
        ],
    },
    "merino/jobs/utils/system_monitor.py": {
        "direct": [],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_domain_processing_integration.py",
            "tests/integration/jobs/navigational_suggestions/test_init.py",
        ],
    },
    "merino/jobs/wikipedia_indexer/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/wikipedia_indexer/filemanager.py": {
        "direct": [
            "tests/integration/jobs/wikipedia_indexer/test_filemanager.py",
            "tests/unit/jobs/wikipedia_indexer/test_filemanager.py",
        ],
        "indirect": [],
    },
    "merino/jobs/wikipedia_indexer/indexer.py": {
        "direct": ["tests/integration/jobs/wikipedia_indexer/test_indexer.py"],
        "indirect": [],
    },
    "merino/jobs/wikipedia_indexer/settings/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/wikipedia_indexer/settings/v1.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/wikipedia_indexer/suggestion.py": {
        "direct": ["tests/unit/jobs/wikipedia_indexer/test_suggestion.py"],
        "indirect": [],
    },
    "merino/jobs/wikipedia_indexer/utils.py": {
        "direct": ["tests/unit/jobs/wikipedia_indexer/test_utils.py"],
        "indirect": [],
    },
    "merino/jobs/wikipedia_offline_uploader/__init__.py": {
        "direct": [],
        "indirect": [
            "tests/unit/jobs/wikipedia_offline_uploader/test_make_suggestions.py",
            "tests/unit/jobs/wikipedia_offline_uploader/test_wikipedia_offline_uploader.py",
        ],
    },
    "merino/jobs/wikipedia_offline_uploader/downloader.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/wikipedia_offline_uploader/make_suggestions.py": {
        "direct": ["tests/unit/jobs/wikipedia_offline_uploader/test_make_suggestions.py"],
        "indirect": [],
    },
    "merino/jobs/wikipedia_offline_uploader/top_n_by_frequency.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/jobs/wikipedia_offline_uploader/top_n_by_recency.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/main.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/middleware/__init__.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_weather.py",
            "tests/unit/middleware/test_geolocation.py",
            "tests/unit/middleware/test_user_agent.py",
            "tests/unit/utils/api/test_query_params.py",
            "tests/unit/utils/test_log_data_creator.py",
        ],
    },
    "merino/middleware/featureflags.py": {
        "direct": ["tests/unit/middleware/test_featureflags.py"],
        "indirect": [],
    },
    "merino/middleware/geolocation.py": {
        "direct": ["tests/unit/middleware/test_geolocation.py"],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_weather.py",
            "tests/integration/providers/suggest/weather/backends/test_accuweather.py",
            "tests/unit/providers/suggest/adm/test_provider.py",
            "tests/unit/providers/suggest/amo/test_provider.py",
            "tests/unit/providers/suggest/finance/test_provider.py",
            "tests/unit/providers/suggest/flightaware/test_provider.py",
            "tests/unit/providers/suggest/geolocation/test_provider.py",
            "tests/unit/providers/suggest/sports/test_sports_provider.py",
            "tests/unit/providers/suggest/weather/backends/test_accuweather.py",
            "tests/unit/providers/suggest/weather/backends/test_pathfinder.py",
            "tests/unit/providers/suggest/weather/test_provider.py",
            "tests/unit/providers/suggest/yelp/backends/test_yelp.py",
            "tests/unit/providers/suggest/yelp/test_provider.py",
            "tests/unit/utils/api/test_query_params.py",
            "tests/unit/utils/test_log_data_creator.py",
        ],
    },
    "merino/middleware/logging.py": {
        "direct": ["tests/unit/middleware/test_logging.py"],
        "indirect": [],
    },
    "merino/middleware/metrics.py": {
        "direct": ["tests/unit/middleware/test_metrics.py"],
        "indirect": [],
    },
    "merino/middleware/user_agent.py": {
        "direct": ["tests/unit/middleware/test_user_agent.py"],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_weather.py",
            "tests/unit/providers/suggest/adm/test_provider.py",
            "tests/unit/utils/test_log_data_creator.py",
        ],
    },
    "merino/providers/manifest/__init__.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py",
            "tests/integration/api/v1/manifest/test_manifest.py",
            "tests/unit/curated_recommendations/corpus_backends/test_utils.py",
            "tests/unit/providers/manifest/test_init_provider.py",
        ],
    },
    "merino/providers/manifest/backends/filemanager.py": {
        "direct": ["tests/unit/providers/manifest/backends/test_filemanager.py"],
        "indirect": [],
    },
    "merino/providers/manifest/backends/manifest.py": {
        "direct": ["tests/unit/providers/manifest/backends/test_manifest.py"],
        "indirect": ["tests/unit/providers/manifest/test_provider.py"],
    },
    "merino/providers/manifest/backends/protocol.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py",
            "tests/integration/api/v1/manifest/test_manifest.py",
            "tests/unit/providers/manifest/backends/test_filemanager.py",
            "tests/unit/providers/manifest/backends/test_manifest.py",
            "tests/unit/providers/manifest/test_get_icon_url.py",
            "tests/unit/providers/manifest/test_provider.py",
        ],
    },
    "merino/providers/manifest/provider.py": {
        "direct": ["tests/unit/providers/manifest/test_provider.py"],
        "indirect": [
            "tests/integration/api/v1/manifest/test_manifest.py",
            "tests/unit/providers/manifest/test_get_icon_url.py",
        ],
    },
    "merino/providers/suggest/__init__.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/suggest/test_providers.py",
            "tests/unit/providers/suggest/test_init_providers.py",
        ],
    },
    "merino/providers/suggest/adm/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/adm/backends/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/adm/backends/fake_backends.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/adm/backends/protocol.py": {
        "direct": [],
        "indirect": [
            "tests/integration/providers/suggest/adm/backends/test_remotesettings_icon.py",
            "tests/unit/providers/suggest/adm/backends/test_remotesettings.py",
        ],
    },
    "merino/providers/suggest/adm/backends/remotesettings.py": {
        "direct": ["tests/unit/providers/suggest/adm/backends/test_remotesettings.py"],
        "indirect": [
            "tests/integration/providers/suggest/adm/backends/test_remotesettings_icon.py",
            "tests/unit/providers/suggest/adm/test_provider.py",
            "tests/unit/utils/test_icon_processor.py",
        ],
    },
    "merino/providers/suggest/adm/provider.py": {
        "direct": ["tests/unit/providers/suggest/adm/test_provider.py"],
        "indirect": [],
    },
    "merino/providers/suggest/amo/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/amo/addons_data.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_amo.py",
            "tests/unit/providers/suggest/amo/backends/test_dynamic.py",
            "tests/unit/providers/suggest/amo/backends/test_static.py",
            "tests/unit/providers/suggest/amo/test_provider.py",
        ],
    },
    "merino/providers/suggest/amo/backends/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/amo/backends/dynamic.py": {
        "direct": ["tests/unit/providers/suggest/amo/backends/test_dynamic.py"],
        "indirect": [],
    },
    "merino/providers/suggest/amo/backends/protocol.py": {
        "direct": [],
        "indirect": [
            "tests/unit/providers/suggest/amo/backends/test_dynamic.py",
            "tests/unit/providers/suggest/amo/backends/test_static.py",
            "tests/unit/providers/suggest/amo/test_provider.py",
        ],
    },
    "merino/providers/suggest/amo/backends/static.py": {
        "direct": ["tests/unit/providers/suggest/amo/backends/test_static.py"],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_amo.py",
            "tests/unit/providers/suggest/amo/test_provider.py",
        ],
    },
    "merino/providers/suggest/amo/provider.py": {
        "direct": ["tests/unit/providers/suggest/amo/test_provider.py"],
        "indirect": ["tests/integration/api/v1/suggest/test_suggest_amo.py"],
    },
    "merino/providers/suggest/base.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_flightaware.py",
            "tests/integration/api/v1/suggest/test_suggest_weather.py",
            "tests/unit/providers/suggest/amo/test_provider.py",
            "tests/unit/providers/suggest/flightaware/test_provider.py",
            "tests/unit/providers/suggest/geolocation/test_provider.py",
            "tests/unit/providers/suggest/sports/test_sports_provider.py",
            "tests/unit/providers/suggest/top_picks/test_provider.py",
            "tests/unit/providers/suggest/weather/test_provider.py",
            "tests/unit/providers/suggest/yelp/test_provider.py",
        ],
    },
    "merino/providers/suggest/custom_details.py": {
        "direct": [],
        "indirect": [
            "tests/unit/providers/suggest/amo/test_provider.py",
            "tests/unit/providers/suggest/finance/test_provider.py",
            "tests/unit/providers/suggest/flightaware/test_provider.py",
            "tests/unit/providers/suggest/geolocation/test_provider.py",
            "tests/unit/providers/suggest/sports/test_sports_provider.py",
            "tests/unit/providers/suggest/weather/test_provider.py",
            "tests/unit/providers/suggest/yelp/test_provider.py",
        ],
    },
    "merino/providers/suggest/finance/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/finance/backends/__init__.py": {
        "direct": [],
        "indirect": ["tests/integration/api/v1/suggest/test_suggest_finance.py"],
    },
    "merino/providers/suggest/finance/backends/polygon/__init__.py": {
        "direct": [],
        "indirect": ["tests/integration/providers/suggest/finance/backends/test_polygon.py"],
    },
    "merino/providers/suggest/finance/backends/polygon/backend.py": {
        "direct": [],
        "indirect": ["tests/unit/providers/suggest/finance/backends/test_polygon.py"],
    },
    "merino/providers/suggest/finance/backends/polygon/errors.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/finance/backends/polygon/etf_ticker_company_mapping.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/finance/backends/polygon/filemanager.py": {
        "direct": [],
        "indirect": ["tests/unit/providers/suggest/finance/backends/test_filemanager.py"],
    },
    "merino/providers/suggest/finance/backends/polygon/keyword_ticker_mapping.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/finance/backends/polygon/stock_ticker_company_mapping.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/finance/backends/polygon/utils.py": {
        "direct": [],
        "indirect": ["tests/unit/providers/suggest/finance/backends/test_utils.py"],
    },
    "merino/providers/suggest/finance/backends/protocol.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_finance.py",
            "tests/integration/providers/suggest/finance/backends/test_polygon.py",
            "tests/unit/providers/suggest/finance/backends/test_filemanager.py",
            "tests/unit/providers/suggest/finance/backends/test_polygon.py",
            "tests/unit/providers/suggest/finance/backends/test_utils.py",
            "tests/unit/providers/suggest/finance/test_provider.py",
        ],
    },
    "merino/providers/suggest/finance/provider.py": {
        "direct": ["tests/unit/providers/suggest/finance/test_provider.py"],
        "indirect": ["tests/integration/api/v1/suggest/test_suggest_finance.py"],
    },
    "merino/providers/suggest/flightaware/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/flightaware/backends/airline_mappings.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/flightaware/backends/cache.py": {
        "direct": [],
        "indirect": ["tests/unit/providers/suggest/flightaware/backend/test_cache.py"],
    },
    "merino/providers/suggest/flightaware/backends/errors.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_flightaware.py",
            "tests/unit/providers/suggest/flightaware/backend/test_cache.py",
            "tests/unit/providers/suggest/flightaware/backend/test_errors.py",
            "tests/unit/providers/suggest/flightaware/backend/test_flightaware.py",
            "tests/unit/providers/suggest/flightaware/test_provider.py",
        ],
    },
    "merino/providers/suggest/flightaware/backends/filemanager.py": {
        "direct": [],
        "indirect": ["tests/unit/providers/suggest/flightaware/backend/test_filemanager.py"],
    },
    "merino/providers/suggest/flightaware/backends/flightaware.py": {
        "direct": ["tests/unit/providers/suggest/flightaware/backend/test_flightaware.py"],
        "indirect": [],
    },
    "merino/providers/suggest/flightaware/backends/protocol.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_flightaware.py",
            "tests/unit/providers/suggest/flightaware/backend/test_cache.py",
            "tests/unit/providers/suggest/flightaware/backend/test_filemanager.py",
            "tests/unit/providers/suggest/flightaware/backend/test_flightaware.py",
            "tests/unit/providers/suggest/flightaware/backend/test_utils.py",
            "tests/unit/providers/suggest/flightaware/test_provider.py",
        ],
    },
    "merino/providers/suggest/flightaware/backends/utils.py": {
        "direct": ["tests/unit/providers/suggest/flightaware/backend/test_utils.py"],
        "indirect": [],
    },
    "merino/providers/suggest/flightaware/provider.py": {
        "direct": ["tests/unit/providers/suggest/flightaware/test_provider.py"],
        "indirect": ["tests/integration/api/v1/suggest/test_suggest_flightaware.py"],
    },
    "merino/providers/suggest/geolocation/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/geolocation/provider.py": {
        "direct": ["tests/unit/providers/suggest/geolocation/test_provider.py"],
        "indirect": [],
    },
    "merino/providers/suggest/manager.py": {
        "direct": [],
        "indirect": ["tests/unit/providers/suggest/test_init_providers.py"],
    },
    "merino/providers/suggest/sports/__init__.py": {
        "direct": [],
        "indirect": ["tests/unit/providers/suggest/sports/test_sports_provider.py"],
    },
    "merino/providers/suggest/sports/__main__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/sports/backends/__init__.py": {
        "direct": [],
        "indirect": ["tests/unit/providers/suggest/sports/backends/test_sports_backend.py"],
    },
    "merino/providers/suggest/sports/backends/sportsdata/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/sports/backends/sportsdata/backend.py": {
        "direct": [],
        "indirect": [
            "tests/integration/providers/suggest/sports/backends/test_sportsdata.py",
            "tests/unit/providers/suggest/sports/backends/test_sports_backend.py",
            "tests/unit/providers/suggest/sports/test_sports_provider.py",
        ],
    },
    "merino/providers/suggest/sports/backends/sportsdata/common/__init__.py": {
        "direct": [],
        "indirect": [
            "tests/integration/providers/suggest/sports/backends/test_sportsdata.py",
            "tests/unit/jobs/sports/test_sportsdata.py",
            "tests/unit/providers/suggest/sports/backends/common/test_data.py",
            "tests/unit/providers/suggest/sports/backends/common/test_elastic.py",
            "tests/unit/providers/suggest/sports/backends/common/test_sports.py",
            "tests/unit/providers/suggest/sports/backends/test_sports_backend.py",
        ],
    },
    "merino/providers/suggest/sports/backends/sportsdata/common/data.py": {
        "direct": [],
        "indirect": [
            "tests/integration/providers/suggest/sports/backends/test_sportsdata.py",
            "tests/unit/jobs/sports/test_sportsdata.py",
            "tests/unit/providers/suggest/sports/backends/common/test_data.py",
            "tests/unit/providers/suggest/sports/backends/common/test_elastic.py",
            "tests/unit/providers/suggest/sports/backends/common/test_sports.py",
            "tests/unit/providers/suggest/sports/backends/test_sports_backend.py",
        ],
    },
    "merino/providers/suggest/sports/backends/sportsdata/common/elastic.py": {
        "direct": [],
        "indirect": [
            "tests/integration/providers/suggest/sports/backends/test_sportsdata.py",
            "tests/unit/jobs/sports/test_sportsdata.py",
            "tests/unit/providers/suggest/sports/backends/common/test_elastic.py",
            "tests/unit/providers/suggest/sports/backends/test_sports_backend.py",
        ],
    },
    "merino/providers/suggest/sports/backends/sportsdata/common/error.py": {
        "direct": [],
        "indirect": [
            "tests/unit/providers/suggest/sports/backends/common/test_elastic.py",
            "tests/unit/providers/suggest/sports/backends/common/test_sports.py",
        ],
    },
    "merino/providers/suggest/sports/backends/sportsdata/common/sports.py": {
        "direct": [],
        "indirect": [
            "tests/integration/providers/suggest/sports/backends/test_sportsdata.py",
            "tests/unit/providers/suggest/sports/backends/common/test_data.py",
            "tests/unit/providers/suggest/sports/backends/common/test_elastic.py",
            "tests/unit/providers/suggest/sports/backends/common/test_sports.py",
        ],
    },
    "merino/providers/suggest/sports/backends/sportsdata/protocol.py": {
        "direct": [],
        "indirect": [
            "tests/integration/providers/suggest/sports/backends/test_sportsdata.py",
            "tests/unit/providers/suggest/sports/test_sports_provider.py",
        ],
    },
    "merino/providers/suggest/sports/provider.py": {
        "direct": ["tests/unit/providers/suggest/sports/test_sports_provider.py"],
        "indirect": [],
    },
    "merino/providers/suggest/top_picks/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/top_picks/backends/filemanager.py": {
        "direct": ["tests/unit/providers/suggest/top_picks/backends/test_filemanager.py"],
        "indirect": [
            "tests/unit/providers/suggest/top_picks/backends/test_top_picks.py",
            "tests/unit/providers/suggest/top_picks/test_provider.py",
        ],
    },
    "merino/providers/suggest/top_picks/backends/protocol.py": {
        "direct": [],
        "indirect": [
            "tests/unit/providers/suggest/top_picks/backends/test_top_picks.py",
            "tests/unit/providers/suggest/top_picks/test_provider.py",
        ],
    },
    "merino/providers/suggest/top_picks/backends/top_picks.py": {
        "direct": ["tests/unit/providers/suggest/top_picks/backends/test_top_picks.py"],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_top_picks.py",
            "tests/unit/providers/suggest/top_picks/test_provider.py",
        ],
    },
    "merino/providers/suggest/top_picks/provider.py": {
        "direct": ["tests/unit/providers/suggest/top_picks/test_provider.py"],
        "indirect": ["tests/integration/api/v1/suggest/test_suggest_top_picks.py"],
    },
    "merino/providers/suggest/weather/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/weather/backends/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/weather/backends/accuweather/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/weather/backends/accuweather/backend.py": {
        "direct": [],
        "indirect": [
            "tests/integration/providers/suggest/weather/backends/test_accuweather.py",
            "tests/unit/providers/suggest/weather/backends/test_accuweather.py",
        ],
    },
    "merino/providers/suggest/weather/backends/accuweather/errors.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_weather.py",
            "tests/integration/providers/suggest/weather/backends/test_accuweather.py",
            "tests/unit/providers/suggest/weather/backends/test_accuweather.py",
            "tests/unit/providers/suggest/weather/test_provider.py",
        ],
    },
    "merino/providers/suggest/weather/backends/accuweather/pathfinder.py": {
        "direct": ["tests/unit/providers/suggest/weather/backends/test_pathfinder.py"],
        "indirect": [
            "tests/unit/providers/suggest/weather/backends/test_accuweather.py",
            "tests/unit/providers/suggest/weather/test_provider.py",
        ],
    },
    "merino/providers/suggest/weather/backends/accuweather/utils.py": {
        "direct": [],
        "indirect": ["tests/unit/providers/suggest/weather/backends/test_accuweather.py"],
    },
    "merino/providers/suggest/weather/backends/fake_backends.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/weather/backends/protocol.py": {
        "direct": ["tests/unit/providers/suggest/weather/backends/test_protocol.py"],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_weather.py",
            "tests/integration/providers/suggest/weather/backends/test_accuweather.py",
            "tests/unit/providers/suggest/weather/backends/test_accuweather.py",
            "tests/unit/providers/suggest/weather/backends/test_pathfinder.py",
            "tests/unit/providers/suggest/weather/test_provider.py",
        ],
    },
    "merino/providers/suggest/weather/provider.py": {
        "direct": [
            "tests/unit/providers/suggest/weather/test_provider.py",
            "tests/integration/api/v1/suggest/test_suggest_weather.py",
        ],
        "indirect": [],
    },
    "merino/providers/suggest/wikipedia/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/wikipedia/backends/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/wikipedia/backends/elastic.py": {
        "direct": ["tests/unit/providers/suggest/wikipedia/backends/test_elastic.py"],
        "indirect": [],
    },
    "merino/providers/suggest/wikipedia/backends/fake_backends.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_wikipedia.py",
            "tests/unit/providers/suggest/wikipedia/test_provider.py",
        ],
    },
    "merino/providers/suggest/wikipedia/backends/protocol.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/wikipedia/backends/utils.py": {
        "direct": ["tests/unit/providers/suggest/wikipedia/backends/test_utils.py"],
        "indirect": [],
    },
    "merino/providers/suggest/wikipedia/provider.py": {
        "direct": [
            "tests/unit/providers/suggest/wikipedia/test_provider.py",
            "tests/integration/api/v1/suggest/test_suggest_wikipedia.py",
        ],
        "indirect": [],
    },
    "merino/providers/suggest/yelp/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/yelp/backends/keyword_mapping.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/providers/suggest/yelp/backends/protocol.py": {
        "direct": [],
        "indirect": ["tests/unit/providers/suggest/yelp/test_provider.py"],
    },
    "merino/providers/suggest/yelp/backends/yelp.py": {
        "direct": [
            "tests/integration/providers/suggest/yelp/backends/test_yelp.py",
            "tests/unit/providers/suggest/yelp/backends/test_yelp.py",
        ],
        "indirect": ["tests/unit/providers/suggest/yelp/test_provider.py"],
    },
    "merino/providers/suggest/yelp/provider.py": {
        "direct": ["tests/unit/providers/suggest/yelp/test_provider.py"],
        "indirect": [],
    },
    "merino/utils/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/utils/api/cache_control.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/utils/api/metrics.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/utils/api/query_params.py": {
        "direct": ["tests/unit/utils/api/test_query_params.py"],
        "indirect": [],
    },
    "merino/utils/blocklists.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/utils/cron.py": {
        "direct": ["tests/unit/utils/test_cron.py"],
        "indirect": [],
    },
    "merino/utils/domain_categories/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/utils/domain_categories/domain_category_mapping.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/utils/domain_categories/models.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest_top_picks.py",
            "tests/integration/jobs/navigational_suggestions/test_init.py",
            "tests/unit/jobs/navigational_suggestions/test_get_serp_categories.py",
            "tests/unit/jobs/navigational_suggestions/test_init.py",
            "tests/unit/jobs/navigational_suggestions/test_navigational_suggestions.py",
            "tests/unit/providers/suggest/sports/test_sports_provider.py",
            "tests/unit/providers/suggest/top_picks/test_provider.py",
            "tests/unit/providers/suggest/wikipedia/test_provider.py",
        ],
    },
    "merino/utils/featureflags.py": {
        "direct": ["tests/unit/utils/test_featureflags.py"],
        "indirect": ["tests/unit/middleware/test_featureflags.py"],
    },
    "merino/utils/gcs/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/utils/gcs/gcs_uploader.py": {
        "direct": ["tests/unit/content_handler/test_gcp_uploader.py"],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_async_favicon_integration.py",
            "tests/integration/jobs/navigational_suggestions/test_domain_metadata_uploader.py",
            "tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader.py",
            "tests/unit/providers/suggest/finance/backends/test_polygon.py",
        ],
    },
    "merino/utils/gcs/models.py": {
        "direct": ["tests/unit/utils/test_gcs_models.py"],
        "indirect": [
            "tests/integration/jobs/navigational_suggestions/test_async_favicon_integration.py",
            "tests/integration/jobs/navigational_suggestions/test_domain_metadata_uploader.py",
            "tests/integration/jobs/navigational_suggestions/test_domain_processing_integration.py",
            "tests/integration/jobs/navigational_suggestions/test_favicon_pipeline_integration.py",
            "tests/integration/providers/suggest/adm/backends/test_remotesettings_icon.py",
            "tests/unit/content_handler/test_gcp_uploader.py",
            "tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader.py",
            "tests/unit/jobs/navigational_suggestions/test_domain_metadata_uploader_error.py",
            "tests/unit/jobs/navigational_suggestions/test_favicon_processor.py",
            "tests/unit/jobs/navigational_suggestions/test_navigational_suggestions_utils.py",
            "tests/unit/providers/suggest/finance/backends/test_polygon.py",
            "tests/unit/utils/test_icon_processor.py",
        ],
    },
    "merino/utils/http_client.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/utils/icon_processor.py": {
        "direct": ["tests/unit/utils/test_icon_processor.py"],
        "indirect": [
            "tests/integration/providers/suggest/adm/backends/test_remotesettings_icon.py",
            "tests/unit/providers/suggest/adm/backends/test_remotesettings.py",
        ],
    },
    "merino/utils/log_data_creators.py": {
        "direct": ["tests/unit/utils/test_log_data_creator.py"],
        "indirect": [
            "tests/integration/api/v1/suggest/test_suggest.py",
        ],
    },
    "merino/utils/metrics.py": {
        "direct": [],
        "indirect": ["tests/unit/providers/suggest/sports/test_sports_provider.py"],
    },
    "merino/utils/synced_gcs_blob.py": {
        "direct": [],
        "indirect": [
            "tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_engagement.py",
            "tests/integration/api/v1/curated_recommendations/engagement_backends/test_gcs_prior.py",
            "tests/integration/api/v1/curated_recommendations/ml_backends/test_gcs_local_model.py",
            "tests/integration/api/v1/curated_recommendations/ml_backends/test_gcs_ml_contextual.py",
        ],
    },
    "merino/utils/task_runner.py": {
        "direct": ["tests/unit/utils/test_task_runner.py"],
        "indirect": [],
    },
    "merino/utils/user_agent_parsing.py": {
        "direct": ["tests/unit/utils/test_user_agent_parsing.py"],
        "indirect": [],
    },
    "merino/utils/version.py": {
        "direct": ["tests/unit/utils/test_version.py"],
        "indirect": [],
    },
    "merino/web/__init__.py": {
        "direct": [],
        "indirect": [],
    },
    "merino/web/api_v1.py": {
        "direct": ["tests/integration/api/v1/"],
        "indirect": [],
    },
    "merino/web/dockerflow.py": {
        "direct": [
            "tests/integration/test_error.py",
            "tests/integration/test_heartbeat.py",
            "tests/integration/test_version.py",
        ],
        "indirect": [],
    },
    "merino/web/models_v1.py": {
        "direct": [],
        "indirect": ["tests/integration/api/v1/"],
    },
}


def get_tests_for_source(source_path: str, include_indirect: bool = True) -> list[str]:
    """Get test files for a given source file.

    Args:
        source_path: Path to the source file (e.g., "merino/middleware/logging.py")
        include_indirect: If True, include tests that import the module.
                         If False, only return direct tests.

    Returns:
        List of test file paths. Empty list if no tests found.

    Example:
        >>> get_tests_for_source("merino/middleware/logging.py")
        ['tests/unit/middleware/test_logging.py', ...]

        >>> get_tests_for_source("merino/middleware/logging.py", include_indirect=False)
        ['tests/unit/middleware/test_logging.py']
    """
    tests = get_direct_tests(source_path)
    if include_indirect:
        tests.extend(get_indirect_tests(source_path))

    return tests


def get_direct_tests(source_path: str) -> list[str]:
    """Get only direct test files for a source file.

    Direct tests are those that follow the naming convention:
    merino/X/Y.py -> tests/unit/X/test_Y.py or tests/integration/X/test_Y.py

    Args:
        source_path: Path to the source file

    Returns:
        List of direct test file paths
    """
    details = SOURCE_TEST_MAPPING_DETAILED.get(source_path, {})
    return details.get("direct", [])


def get_indirect_tests(source_path: str) -> list[str]:
    """Get only indirect test files for a source file.

    Indirect tests are those that import the module but don't follow
    the direct naming convention.

    Args:
        source_path: Path to the source file

    Returns:
        List of indirect test file paths
    """
    details = SOURCE_TEST_MAPPING_DETAILED.get(source_path, {})
    return details.get("indirect", [])
